### PR TITLE
[heos ]Fixed an issue with the commons-net library

### PR DESCRIPTION
**Pull request by Wire82**
**[heos] Fix an dependency issue**

This pull request fixes a issue with the dependency of the commons-net library which prevents the binding to start.
Also a possible null pointer is fixed which may occur during scan for player and groups if the connection is not established at this point.
This pull request fixes the issues mentioned in the discussion here:
https://community.openhab.org/t/heos-denon-support/3449/231

An build can be found here
https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/

### CODE REVIEW

**Comment by Wire82** [comment]
@martinvw 

For your information. As discussed I fixed the dependency to the commons-net library so that the binding is starting again. I also made to small changes I noticed to improve the current version.

Cheers,
Wire82

**Comment by martinvw** [comment]
@Wire82 I fear that there is an incompatibility with the older version, I fear that it will not work without setting, readerThread to true

So in the method [startInputListener](https://github.com/openhab/openhab2-addons/blob/30fbcfbd50db7d8e8f31ae5b33ade2ea3ddef874/bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/resources/Telnet.java#L243) we need a call:

```
        client.setReaderThread(true);
```
 before setting the input listener, it fixes the problems in my local branch which occurred after downgrading

**Comment by Wire82** [comment]
@martinvw what is the problem you are facing if this is not set?
On my side everything works also without using the 
`client.setReaderThread(true);`

**Comment by martinvw** [comment]
I receive no upodates at all anymore, so no updated titles after skipping to the next song and not progress of the song.  Note also the documentation of registerInputListener:

```
 /***
     * Register a listener to be notified when new incoming data is
     * available to be read on the {@link #getInputStream input stream}.
     * Only one listener is supported at a time.
     *
     * <p>
     * More precisely, notifications are issued whenever the number of
     * bytes available for immediate reading (i.e., the value returned
     * by {@link InputStream#available}) transitions from zero to non-zero.
     * Note that (in general) multiple reads may be required to empty the
     * buffer and reset this notification, because incoming bytes are being
     * added to the internal buffer asynchronously.
     * </p>
     *
     * <p>
     * Notifications are only supported when a {@link #setReaderThread
     * reader thread} is enabled for the connection.
     * </p>
     *
     * @param listener listener to be registered; replaces any previous
     * @since 3.0
     ***/
    public synchronized void registerInputListener(TelnetInputListener listener)
    {
        this.inputListener = listener;
    }
```

**Comment by martinvw** [comment]
Maybe you should check which version of commons net you are using on your environment maybe 3.6 is still present somehow?

**Comment by Wire82** [comment]
Hmm I checked with the development environment and it is 3.3 from the core. Also deleted the 3.6 version to make sure that it is not used anymore.
But of course it is not an issue to add this line if it improves the compatibility.

**Pull request merged**
