### PR TITLE
[exec] Migrate to bnd build

### PR DESCRIPTION
**Pull request by Hilbrand**
Automigrated with https://gist.github.com/Hilbrand/a7127d0fb7afd36124a78a248453ff03

### CODE REVIEW

**Comment by martinvw** [comment]
@wborn @J-N-K @davidgraeff wdyt?

**Comment by davidgraeff** [comment]
That's quite a task to finish that PR, as it is a takeover, and need review again.
I'm for migrating first to get a bnd-only distro out soon.

**Comment by martinvw** [comment]
@Hilbrand given your both the creator of this PR and the volunteer for the other one, wdyt?

**Comment by Hilbrand** [comment]
PR #2012 needs rebasing. So needs work before it can be merged, and that since there isn't a lot of activity that seems to indicate the pr is going to be finished soon I would suggest to merge this migration pr first and handle PR #2012 later.

**Pull request merged**
