### PR TITLE
[netatmo] Recompute VPN URL

### LINKED ISSUE #5250: [netatmo] Live picture and live stream URLs update
## Expected Behavior

The Netatmo documentation says : “The vpn_url expire after 3 hours and if the camera reboots” (cf https://dev.netatmo.com/resources/technical/reference/security/live 

The Netatmo binding should update the Live Stream URL and Live Picture URL as soon as the vpn_url changes, since these URLs are built using the vpn_url.

## Current Behavior

I noticed that the netatmo binding does not update the Live Picture URL nor the Live Stream URL. After a while these URLs are not valid anymore and I need to stop and restart the netatmo binding to get new valid URLs.

## Possible Solution

I think that the problem is in the NAWelcomeCameraHander.java which does not take into account changes of vpn_url of the cameras.

1 - The getVpnUrl() method should always return the value obtained by calling module.getVpnUrl() since this value may change every 3 hours. It does not do so if the vpnUrl attribute has already been set by the first call to getVpnUrl().

2 - The getLivePictureURL() method should always rebuild the live picture URL by calling getVpnUrl(). It does not do so if the livePictureURL attribute has already been set by the first call to getLivePictureURL()

3 - getLiveStreamURL() method should always rebuild the live stream URL by calling getVpnUrl(). It does not do so if the liveStreamURL attribute has already been set by the first call to getLiveStreamURL().

## Your Environment

The bug can be reproduced wth the last version of openhab (2.5 on windows 10)

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #5250

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@jlchevet : here is a jar for testing the fix: [org.openhab.binding.netatmo-2.5.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/3365464/org.openhab.binding.netatmo-2.5.0-SNAPSHOT.zip)

**Comment by martinvw** [comment]
Should we wait for @jlchevet?

**Comment by lolodomo** [comment]
I have not yet tested my fix as the only solution to test it is to deploy it in my production environment. 
Even of I have no doubt,  that would be better if someone do a test.  I can do it in the next days.

**Comment by lolodomo** [comment]
Unfortunately, testing with the jar pushed in the addons folder is no more possible, I suppose due to the new way to handle binding dependencies. 
```
11:05:06.834 [WARN ] [org.apache.felix.fileinstall         ] - Error while starting bundle: file:/home/pi/openhab/addons/org.openhab.binding.netatmo-2.5.0-SNAPSHOT.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.netatmo [278]
  Unresolved requirement: Import-Package: io.swagger.annotations; version="[1.5.0,2.0.0)"; resolution:="optional"
  Unresolved requirement: Import-Package: com.squareup.okhttp; version="[2.3.0,3.0.0)"

        at org.eclipse.osgi.container.Module.start(Module.java:444) ~[?:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) ~[?:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [10:org.apache.felix.fileinstall:3.6.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [10:org.apache.felix.fileinstall:3.6.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) [10:org.apache.felix.fileinstall:3.6.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [10:org.apache.felix.fileinstall:3.6.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [10:org.apache.felix.fileinstall:3.6.4]
```
So I am sorry but I forgive the testing.

Let's go for a merge, I am confident in my few little changes.

**Comment by J-N-K** [comment]
@lolodomo, you can install the binding the normal way, and then update only the binbding-bundle with `bundle:update <number> <URL>`, then only the bundle is replaced and all dependencies are still there.

**Comment by lolodomo** [comment]
The URL can be a local file on the server ?
What is expected as content in the URL ? Is it the binding jar ?
If I use bundle:update to update the bundle, what is then the command to restore the original bundle ?

**Comment by J-N-K** [comment]
Can be a local file (`file://absolute_path`) or something Remote (`https://...`), it should be the jar but I think the extension is not important. Going back is the same, just update to the original bundle.

**Comment by lolodomo** [comment]
Using bundle:update, I get a similar result:
```
12:52:46.961 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'netatmo:netatmoapi:maison' changed from UNINITIALIZED to UNINITIALIZED (HANDLER_MISSING_ERROR)
12:52:47.091 [ERROR] [org.openhab.binding.netatmo          ] - FrameworkEvent ERROR - org.openhab.binding.netatmo
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.netatmo [288]
  Unresolved requirement: Import-Package: io.swagger.annotations; version="[1.5.0,2.0.0)"; resolution:="optional"
  Unresolved requirement: Import-Package: com.squareup.okhttp; version="[2.3.0,3.0.0)"

        at org.eclipse.osgi.container.Module.start(Module.java:444) ~[?:?]
        at org.eclipse.osgi.container.ModuleContainer.update(ModuleContainer.java:374) ~[?:?]
        at org.eclipse.osgi.storage.Storage.update(Storage.java:741) ~[?:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.update(EquinoxBundle.java:429) ~[?:?]
        at org.apache.karaf.bundle.command.Update.update(Update.java:74) ~[?:?]
        at org.apache.karaf.bundle.command.Update.doExecute(Update.java:51) ~[?:?]
        at org.apache.karaf.bundle.command.BundleCommand.execute(BundleCommand.java:49) ~[?:?]
        at org.apache.karaf.shell.impl.action.command.ActionCommand.execute(ActionCommand.java:84) ~[?:?]
        at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:68) ~[?:?]
        at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:86) ~[?:?]
        at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:599) ~[?:?]
        at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:526) ~[?:?]
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:415) ~[?:?]
        at org.apache.felix.gogo.runtime.Pipe.doCall(Pipe.java:416) ~[?:?]
        at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:229) ~[?:?]
        at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:59) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:?]
        at java.lang.Thread.run(Thread.java:748) ~[?:?]
```

**Comment by J-N-K** [comment]
Which version are you running? Latest (or at least a recent) snapshot? M1 and before is probably difficult.

**Comment by lolodomo** [comment]
Uninstalling and reinstalling the binding with Paper UI allows hopefully to restore the binding version from the distribution.

**Comment by lolodomo** [comment]
A version from around one week. Snapshot 1621.

**Comment by J-N-K** [comment]
That‘s strange. I‘ll see if I can find time this evening to check that. It should work.

**Comment by J-N-K** [comment]
I just tried with S1638 which is running on my Test-System (RPi 3).

- added 'netatmo'  to the addons.cfg
- waited until the binding is installed
- 'bundle:list | grep -i netatmo' => bundle number is 223
- 'bundle:update 223 https://janessa.me/esh/org.openhab.binding.netatmo-2.5.0-SNAPSHOT.jar' => no error
- 'bundle:restart 223' => no error

I can't test the changes though, I don't own Netatmo devices.

**Comment by lolodomo** [comment]
I tried again using this time the jar from the ZIP file and it does definitively not work for me.

```
openhab> bundle:update 293 file:///home/pi/openhab/netatmo2.jar
openhab> bundle:list | grep etatmo
293 x Installed x  80 x 2.5.0.201907070948    x openHAB Add-ons :: Bundles :: Netatmo Binding
openhab> bundle:restart 293
Error executing command: Error restarting bundles:
        Unable to start bundle 293: Could not resolve module: org.openhab.binding.netatmo [293]
  Unresolved requirement: Import-Package: io.swagger.annotations; version="[1.5.0,2.0.0)"; resolution:="optional"
  Unresolved requirement: Import-Package: com.squareup.okhttp; version="[2.3.0,3.0.0)"
```

**Comment by lolodomo** [comment]
Before the bundle update:
```
294 │ Active │  80 │ 2.3.0                 │ OkHttp
295 │ Active │  80 │ 1.9.0                 │ Retrofit
296 │ Active │  80 │ 1.0.0                 │ org.apache.oltu.oauth2.client
297 │ Active │  80 │ 1.0.0                 │ org.apache.oltu.oauth2.common
298 │ Active │  80 │ 2.5.0.201906222158    │ openHAB Add-ons :: Bundles :: Netatmo Binding
```
After the bundle update:
```
294 │ Active    │  80 │ 2.3.0                 │ OkHttp
295 │ Active    │  80 │ 1.9.0                 │ Retrofit
296 │ Active    │  80 │ 1.0.0                 │ org.apache.oltu.oauth2.client
297 │ Active    │  80 │ 1.0.0                 │ org.apache.oltu.oauth2.common
298 │ Installed │  80 │ 2.5.0.201907070948    │ openHAB Add-ons :: Bundles :: Netatmo Binding
```
And then bundle  restart:
```
 bundle:restart 298
Error executing command: Error restarting bundles:
        Unable to start bundle 298: Could not resolve module: org.openhab.binding.netatmo [298]
  Unresolved requirement: Import-Package: io.swagger.annotations; version="[1.5.0,2.0.0)"; resolution:="optional"
  Unresolved requirement: Import-Package: com.squareup.okhttp; version="[2.3.0,3.0.0)"
```
What is strange is that okhttp bundle seems to already active.

**Comment by J-N-K** [comment]
Can you try `bundle:resolve 298`?

**Comment by lolodomo** [comment]
```
303 │ Active │  80 │ 2.5.0.201906222158    │ openHAB Add-ons :: Bundles :: Netatmo Binding
openhab> bundle:update 303 file:///home/pi/openhab/netatmo2.jar
openhab> bundle:list | grep etat
303 x Installed x  80 x 2.5.0.201907070948    x openHAB Add-ons :: Bundles :: Netatmo Binding
openhab> bundle:resolve 303
openhab> bundle:restart 303
Error executing command: Error restarting bundles:
        Unable to start bundle 303: Could not resolve module: org.openhab.binding.netatmo [303]
  Unresolved requirement: Import-Package: io.swagger.annotations; version="[1.5.0,2.0.0)"; resolution:="optional"
  Unresolved requirement: Import-Package: com.squareup.okhttp; version="[2.3.0,3.0.0)"

openhab> bundle:resolve 303
openhab> bundle:restart 303
Error executing command: Error restarting bundles:
        Unable to start bundle 303: Could not resolve module: org.openhab.binding.netatmo [303]
  Unresolved requirement: Import-Package: io.swagger.annotations; version="[1.5.0,2.0.0)"; resolution:="optional"
  Unresolved requirement: Import-Package: com.squareup.okhttp; version="[2.3.0,3.0.0)"

openhab>
```

**Comment by lolodomo** [comment]
Why did you close the PR ?

**Comment by lolodomo** [comment]
I reopen it.

**Comment by J-N-K** [comment]
Thick fingers on mobile screen... sorry. I have no idea. Was your Snapshot created before the osgiify-change was merged? Maybe that’s why.

**Comment by lolodomo** [comment]
The snapshot was built the 22th of June I think. Is it too much old ?

**Comment by lolodomo** [comment]
I will move to the last snapshot during the weekend and try again.

**Comment by lolodomo** [comment]
Ok, with the snapshot 1638, I am now able to restart the bundle.

**Comment by lolodomo** [comment]
Ok, after the update of the bundle one day ago, I tried.

It looks good even if the video are no more playable. I don't think that it is relative to this change. The video URL is a m3u8 file which contains several size videos. I have in mind we chose in the past the URL of a particular resolution. Don't know if this is something that was changed. I just had in mind that the video was playable in at least one app but I don't remember which one. Now it is not playable neither in Firefox, nor in Edge, nor in Android app.

Regarding the event picture URL and the live picture URL, they are correctly displayed but with a delay of several minutes. I think it is normal because I have not set the forward URL in netatmo and so the OH server can't receive any event update. In this case, if I correctly remember, the data are refreshed every X minutes.

**So, I can at least confirm that this change is OK for pictures.**

**Comment by lolodomo** [comment]
Vidéo are apparently playable in Chrome.
So everything is good I think.

**Comment by J-N-K** [comment]
Thanks, @lolodomo

**Pull request merged**
