### PR TITLE
[jsonpath] Fixed wrong feature file

### PR DESCRIPTION
**Pull request by cweitkamp**
- Fixed wrong feature file

See https://community.openhab.org/t/snapshots-1715-1716-1717-1718-1719-1720-1721-restdocs-rest-api-errors/83371/19 and https://github.com/openhab/openhab2-addons/commit/b00c8cc5c3b7811bef1e9e268c2b228bdd69ed11#r35480350

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by J-N-K** [comment]
IMO wring Solution for another problem. The core of the problem is the swagger feature which requires Jackson 2.4.5 while the feature provides 2.9.9. Since the feature does not install all Jackson bundles this gets messed up.

**Comment by cweitkamp** [comment]
For now it messed up the build completely :frowning: (see https://travis-ci.org/openhab/openhab2-addons/builds/597354199). But according to the [docs](https://github.com/json-path/JsonPath#jsonprovider-spi) Jackson is not mandatory for JsonPath and we are not using it. We are using the default `JsonProvider`.

I agree with you on the Jackson version used in OHC.

**Comment by J-N-K** [comment]
As I said: if you want to remove the hard dependency on jackson, you have to add `com.fasterxml.jackson.*;resolution:="optional"` to `bnd.importpackage`. The reason is that the optional information is lost for embedded bundles and needs to be set explicitly.

**Comment by kaikreuzer** [comment]
Hm, so you are saying that this PR will actually leave the jsonpath bundle unresolved?
Then I fully agree, we should manually set the dependency to be optional in the bnd config!
Could you prepare such a PR? Would be great!

**Comment by cweitkamp** [comment]
Yes, it does. Let's revert this. I will test another solution based on Gson. Otherwise I will change the dependency on Jackson to optional like suggested.

**Comment by kaikreuzer** [comment]
Why revert it if we all agree that we do not want a dependency on the Jackson from the TP (or rather not at all)?

**Comment by cweitkamp** [comment]
Because adding the other bundles in the feature file was wrong. They have to be removed anyways independently from the changes we want to make on the Jackson dependency.

**Comment by kaikreuzer** [comment]
ok, so let's remove the tp jackson dependency as soon there's a PR for making the dependency in the bundle optional (or to remove it completely, isn't that also an option @J-N-K?).

**Comment by J-N-K** [comment]
Of course. I did that with a lot of packages. Add `!com.fasterxml.jackson.*`.

**Comment by kaikreuzer** [comment]
Like https://github.com/openhab/openhab2-addons/pull/6220?

**Pull request merged**
