### PR TITLE
[cbus] CBus Binding initial contribution

### PR DESCRIPTION
**Pull request by jpharvey**
Signed-off-by: John Harvey <john.p.harvey@btinternet.com>

[cbus] Initial contribution of binding to control Clipsal C-Bus automation system. 

This is an new PR to replace https://github.com/openhab/openhab2-addons/pull/776. It fixes several problems found with that version and should address the review comments. A built jar of the latest version is available for testing in the old PR.
This allows OpenHab to interact with devices on the Clipsal CBus network via their CGate Interface. 
At this stage there is no support for triggers and groups but basic operations should work.

### CODE REVIEW

**Comment by martinvw** [comment]
Thanks for continue the work on this PR! 

Please include the build in the parent `pom.xml` in that case it will already be tested and analysed by travis. And it will become available in [jfrog builds list](https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/).

Please also check:

http://docs.openhab.org/developers/development/bindings.html
http://docs.openhab.org/developers/development/guidelines.html

Please also review the report of [the Static code analysis](https://docs.openhab.org/developers/development/bindings.html#static-code-analysis), this also saves me some time while reviewing.

Some things which I quickly notes was that some variables do not follow the java coding standards, they should be camelcase and I believe I saw some empty catch-clauses.

**Comment by neohusky** [comment]
Hey all

I thought I’d repost this as we are continuing discussions on the new PR here. 

Hi guys

I haven’t had a chance to update my version yet. Hopefully I get a chance today.

When trying to get my head around scenes and triggers ago I found this forum post/tutorial helpful: https://www.cbusforums.com/resources/what-are-c-bus-scenes.1/

That forum has a wealth of invaluable information on cbus that pertains to installation/setup rather than end user.

I’ll report back my experiences with the triggers soon.

**Comment by neohusky** [comment]
Scenes are working!  Great work!

I can set an action selector value of a Trigger group and the scene is set.  I can also read the value of the trigger group to show status.

I've had a few minutes to play with it but this is what I have on a sample habpanel dashboard.  This is a few example of how to do it.  I ended up using a modded custom widget to simplify things.
screen shot 2017-12-18 at 7 46 21 pm
screen shot 2017-12-18 at 7 53 24 pm



I think the only improvement for the time being is to somehow read or determin the scene is killed or brokenso that maybe we can set the trigger value to null.eg if in my cooking scene an individual group is changed then the scene is broken and therefore the status indicator should be off similar to a DLT switch.

**Comment by jpharvey** [comment]
@neohusky  Thanks for the feedback. Unfortunately cgate doesnt seem to send anything out when a device pushes the "IndicatorKill" message on the network. I've posted a message on the cbus forum but without being able to receive that event i cant do anything about clearing the state. Lets see what comes back. 
There is a mechanism for sending it back which i guess we could use if we implement something in cbus to react to trigger events. (ie press button on switch and trigger some non-cbus change. Then if that is changed manually push back to kill the trigger. Not planning to do that yet but it seems like it will be possible.

**Comment by neohusky** [comment]
@jpharvey 

cool. lets wait and see if one to the resident experts gets back to you on the forum.  In the meantime I found this document: http://training.clipsal.com/downloads/OpenCBus/Trigger%20Control%20Application.pdf

I haven't had time to fully explore this document but, theres info in here regarding the kill indicator message sent out by the unit. I'll take a look at this along with my event log a little later to try and help solve this.

This is not really important, but, would be a nice touch.

**Comment by jpharvey** [comment]
@martinvw Looks like i have done something wrong but not sure what? I added this to the top level pom.xml but now the jenkins build errors at the start but i have no idea why. Any idea what i have messed up?

**Comment by martinvw** [comment]
Ideally you should rebase on the current master and update any references to the 2.3.0-SNAPSHOT

I think that it might be caused by the fact that our parent pom version 2.2.0-SNAPSHOT does not seem to be published anymore. But we know that for sure if this resolves the problem.

**Comment by jpharvey** [comment]
@martinvw Thanks that fixed jenkins, Now for the static code analysis problems. The biggest set of problems left is the inernal/cgate subdirectory. This was a modified version of href="https://github.com/cnery/cgateinterface.
Dave updated the copyright on that to suit our use which is what is now in those files but that fails the static analysis test along with other coding things. 
The code in the original pull request was modified to use ESH features (logging/threadpool) instead of ones coming from a different external dependency. I havent changed that but have added 1 small feature and fixed a bug. Given this is derived work i dont think i should modify the copyright to OpenHabs and i dont want to change the code more than necessary to fix the static analysis rules (other than to fix real bugs). 
Any advice how to proceeed with this?

Thanks

**Comment by martinvw** [comment]
Yves the proper solution is to clone the other GitHub repo and make the changes there, then create a jar from that source I believe there was some naming suggestion of how to name it, maybe @wborn remembers. And then you can put that jar in the lib folder.

**Comment by wborn** [comment]
For the Karaf bugfix one line of code was changed and we appended `-sp1` to the version. The best way is ofcourse to get all your features and bugfixes merged upstream.

**Comment by jpharvey** [comment]
Will see what i can do about using the original version and then getting the fixes in. Biggest change was to replace some other logging mechanism with that from OpenHab & the same for threadpool. I cant see those getting taken upstream, But maybe it will work ok without that. There was a dependency issue which we can work around in the pom.xml file but Dave said it would take some time just to get it rebuilt to depend on a version that is still available so getting other changes in may be slow. If so i guess i'll clone it and try to create a jar. Can i include the jar in this submission ok or do we want to reference them from an external maven repository if i need to do that?

**Comment by martinvw** [comment]
> Can i include the jar in this submission ok or do we want to reference them from an external maven repository if i need to do that?

You should include it in the lib folder

**Comment by wborn** [comment]
> Will see what i can do about using the original version and then getting the fixes in. Biggest change was to replace some other logging mechanism with that from OpenHab & the same for threadpool.

It looks like the original library uses commons logging. Using [SLF4J](https://www.slf4j.org/) in the library will make it more reusable and will still allow commons logging to be used. See also [Bridging legacy APIs](https://www.slf4j.org/legacy.html). Introducing some sort of thread factory in the library could help with reusing the correct threadpool.

**Comment by jpharvey** [comment]
Thanks. Will try to tidy it up over the next week or two. Will fork the original library update it and then see if we can eventually taken upstream but put a jar file in for now.

**Comment by npdsomerhayes** [comment]
I started a clean OpenHab install using the hassle free image for a raspberry pi

I have Cgate working and tested using toolkit, My project is loaded in the tags folder

I have added the latest version of the binding I could find (org.openhab.binding.cbus-2.2.0-SNAPSHOT.jar) to the /usr/share/openhab2/addons folder

but from hear I cannot really work out how I got it to show in the Paper UI

does anyone have any suggestions?

**Comment by neohusky** [comment]
Hi npdsomerhayes

I just saw your post. Have you figured this out yet?

**Comment by shovelhead66** [comment]
Hi, can I ask if there are any known issues getting this to work with Openhab on a Windows 10.
Also my CBus Toolkit project connection is via a CNI, therefore not serial, could this be an issue?
I'm able to get openhab to open communication to the CGate Connection "Online", just unable to get it to open the network bridge, "Initialising". I know I have the correct Network ID and Project name.
Spent 2 days attempting to get this to work, can anyone shed any light on this.
Everything I'm reading up on appears to be done via a Pi, am I best investing in one of these ?

Appreciate any support that can be offered

**Comment by neohusky** [comment]
Hi @shovelhead66

I don't believe there should be any issue with operating system used. Nor am I aware of issues with the addon. It's been working flawlessly for me for many months now. 

Two thing you should check:

1. OpenHAB- that the Cbus network thing is configured correctly. Namely network id and project name. 
2. Cgate server - the Cbus server and project has been setup correctly eg.  reference your CNI in the project and also set the default project and project start lines in the cgate server (/cgate/config/access.txt) file. 

This is the guide to turn a Pi into a CNI when used in conjunction with a Cbus PCinterface also running cgate server. http://addictedtopi.tumblr.com/post/96351714013/installing-c-gate-on-a-raspberry-pi

Look at the bottom part of the guide. In your case you have a CNI. Ensure your project references this. In your example your running the toolkit and thus the cgate server on a Windows 10 machine. Just like openHAB. Cgate server will need to be always running with your project open while you are using it with openHAB. 
It may or may not be more practical/cheaper to run cgate and openHAB on a Pi that is always running. I haven't run into any performance issues.

**Comment by neohusky** [comment]
@npdsomerhayes

Have you followed a guide similar to this to setup your Pi and cgate server?

http://addictedtopi.tumblr.com/post/96351714013/installing-c-gate-on-a-raspberry-pi

When cgate server and your project is setup correctly iI IS simply a matter of of adding a new item from the PaperUI inbox for example. Cbus Binding --> cgate connection

Scanning for or manually adding the network would be the next step in PaperUI

This was the original Cbus binding thread that had some useful information: https://community.openhab.org/t/new-clipsal-c-bus-binding/9208

**Comment by jpharvey** [comment]
@shovelhead66  It really shouldn't matter where cgate runs and a CNI works as well since that is what I am using.
When openhab connects to cbus you should see messages in both the cbus console output & the openhab logs. For openhab increasing the logging to debug for cbus will help. Those might show something obvious if not post them here and I can take a look.

**Comment by jpharvey** [comment]
As for fixing the issues with the patch I am part way through it but have run out of time. Hopefully will get back to it in April.

**Comment by neohusky** [comment]
Thanks @jpharvey

**Comment by shovelhead66** [comment]
@jpharvey @neohusky 

Cheers, bit of tinkering then it fired up.

**Comment by neohusky** [comment]
Glad to hear @shovelhead66

**Comment by saintjerome7** [comment]
Hi all - being new to GitHub, I cannot find where to grab the .jar file(s) from for this binding. Apologies for appearing stupid...

**Comment by neohusky** [comment]
hey @saintjerome7 

I haven't been around in a while and just saw your post.  If you haven't found the jar file already it's in the original PR.. See [here](https://github.com/openhab/openhab2-addons/pull/776)

**Comment by stavlocker** [comment]
Hi guys, any progress on this? How can I test this myself?

**Comment by martinvw** [comment]
Hello @jpharvey,

Thanks for your contribution and sorry to keep you waiting. Because we are better staffed now we hope to wrap up a bunch of our old pending pull requests.

Our first important question is, are you still interested in finishing your binding and if so, can we get >your commitment to process the review comments in approximately 2-4 weeks.

What do we commit to, we will review your binding in the upcoming 1-2 week(s) and with a quick response from your side the binding should be merged in 2-4 weeks.

We aim to review your PR in two rounds, first we will focus in the architecture of the binding and correct abstraction level of the channels. In the second review we will focus more on the code style etc.

So the main question, are you able to commit to processing review comments of this PR in 2-4 weeks:

* Yes, I’m going to process the comments in the next weeks.
* Yes, but I’d like to get some help, (for example with my git branch and/or changes that have been made to openHAB that affect my contribution)
* No, I have no time in the coming weeks. But please review it I will pick it up within 3 months.
* No, I have other priorities or are not able to finish the work. I would welcome someone to takeover this PR (and [I thus confirm the origin of my work](https://www.openhab.org/docs/developer/contributing/contributing.html#sign-your-work) )
* No, this pr can be closed for reason: … (please specify. For example the service it connects to has been discontinued).

If you did not yet publish your binding on the marketplace and or announce it on the community forum that would be great thing to do as well:

See [Distributing bindings through the IoT Marketplace](https://community.openhab.org/t/distributing-bindings-through-the-iot-marketplace/24491)

Thanks for your support,

Best regards,

The openhab2-maintainers

@wborn
@cweitkamp
@Hilbrand
@kaikreuzer
@martinvw

**Comment by jpharvey** [comment]
@martinvw Thankyou for the message. There is work to do from the previous review which i still need to do. I wont get to these completed in the next 2-4 weeks but i do intend starting to work on it in that timeframe. 
So if you do another review in the next 1-2 weeks i would expect to pick them up and resolve them within 3 months.

John

**Comment by davidgraeff** [comment]
I have added the work in progress flag. If you are done please request to remove it so that other maintainers now when it is time for a review.

**Comment by neohusky** [comment]
Hey @jpharvey

I am so excited to hear that you’ve found time to work on this and appreciate your work this far. I look forward to see a more stable and compatible addon. 

Do you by any chance have a compiled jar to test with your work so far?

**Comment by jpharvey** [comment]
@neohusky I have some more changes to push in that fix the trigger group/indicatorkill. That is working now with the latest release of cgate. I'll push them in tonight i hope and i will test the jar that is produced by the Jenkins build and assuming it is ok i will send a link to it.
I am hoping the code is almost in a state that can be accepted but some of the static analysis is not working after the reorganization in the openhab source tree and i want to try to get all that sorted out before requesting a review from the developers.

**Comment by neohusky** [comment]
Sounds like a plan. Let us know if you need any help testing when ready.

**Comment by davidgraeff** [comment]
What's happening?

**Comment by jpharvey** [comment]
@davidgraeff My branch had become a mess and all my attempts to clean it were failing and making things worse. So i am re-creating a new branch with all the commits squashed. Hope that makes sense. I think i will be able to reopen this with the new branch or we could create a new Pull Request. I dont mind which?

**Comment by davidgraeff** [comment]
whatever you prefer

**Comment by jpharvey** [comment]
I couldnt reopen this pull request so have created a new one #5648

**Pull request closed without merging**
