### PR TITLE
Fixed wrong port range

### PR DESCRIPTION
**Pull request by cweitkamp**
- Fixed wrong port range

A port number is a 16-bit unsigned integer, thus ranging from 0 to 65535. Some configurations use `min="1"` which by definition is wrong too. Shall we update it too?

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by marcelrv** [comment]
I don't think TCP port 0 is possible, 1 seems to me the valid first port

A port number is a 16-bit unsigned integer, thus ranging from 0 to 65535. For TCP, port number 0 is reserved and cannot be used, while for UDP, the source port is optional and a value of zero means no port

https://en.wikipedia.org/wiki/Port_(computer_networking)

**Comment by cweitkamp** [comment]
Good point. I changed minimum value for ports to "1" (where possible).

**Comment by cweitkamp** [comment]
@lolodomo Thanks for the hint. And there are many more. But most of them do not define `min` and `max` values at all. My intention was not to align all port configurations but to fix the wrong existing ones. Maybe you are interested in fixing the rest :wink:.

**Comment by martinvw** [comment]
@cweitkamp can you rebase?

**Comment by cweitkamp** [comment]
@martinvw I did.

**Pull request merged**
