### PR TITLE
Further evolution of travis build script

### PR DESCRIPTION
**Pull request by martinvw**
Use the commit range given by travis to calculate the changed files (not only new files) and make sure we return the correct exit code

### CODE REVIEW

**Comment by J-N-K** [comment]
Can you make the build fail (so we see that indeed the errorstatus is correctly picked up)? Otherwise LGTM.

**Comment by martinvw** [comment]
@davidgraeff do you have any ideas why `this logfile` does not work anymore?

**Comment by martinvw** [comment]
@J-N-K looks great, let me know when you saw it, then I will remove the commit

**Comment by davidgraeff** [comment]
No I don't have an idea. Maybe we are discarding the log in the travis job? But why do you want the log for happy messages? For showing the SAT findings?

**Comment by martinvw** [comment]
> No I don't have an idea. Maybe we are discarding the log in the travis job? But why do you want the log for happy messages? For showing the SAT findings?

I don't know you already bootstrapped that ;-)

**Comment by davidgraeff** [comment]
Hm. Might be that I just wanted TravisBuddy to report *something* on success and that I understood `successBuildLog` as a requirement.

But I'm not entire sold on this tbh. Maybe TravisBuddy should just report failures.

**Pull request merged**
