### PR TITLE
 [mcp23017] Migrate to bnd build 

### PR DESCRIPTION
**Pull request by Hilbrand**
Consists of 2 commits:

1) Automigrated with https://gist.github.com/Hilbrand/a7127d0fb7afd36124a78a248453ff03
2) Migrated pi4j library to bnd

### CODE REVIEW

**Comment by zolee28** [comment]
Hi guys, the addon does not work with OH 2.5-M3.

**Comment by Hilbrand** [comment]
@zolee28 "it does not work" is kind of vague. Please either post on the forum or open a new issue with details.

**Comment by zolee28** [comment]
Yes, sorry - that was just stupid of me.

So, below is the log what I got, after startup.

```2019-09-18 22:28:06.573 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.dispose()' on 'org.openhab.binding.mcp23017.internal.handler.Mcp23017Handler@bdf7ba': null
java.lang.NullPointerException: null
	at org.openhab.binding.mcp23017.internal.handler.Mcp23017Handler.dispose(Mcp23017Handler.java:186) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [133:org.openhab.core:2.5.0.M3]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [133:org.openhab.core:2.5.0.M3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
2019-09-18 22:28:06.579 [ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred while disposing handler of thing 'mcp23017:mcp23017:27599645': null
java.lang.NullPointerException: null
	at org.openhab.binding.mcp23017.internal.handler.Mcp23017Handler.dispose(Mcp23017Handler.java:186) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [133:org.openhab.core:2.5.0.M3]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [133:org.openhab.core:2.5.0.M3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?] ```

**Comment by Hilbrand** [comment]
`java.lang.NullPointerException`  This is a bug unrelated to the changes in this pull request. Please report as a new issue.

**Pull request merged**
