### PR TITLE
Fix for WiFi LED controller Binding (see #496) 

### PR DESCRIPTION
**Pull request by PH89**
This makes WifiLEDBinding working again and resolves conflicts in #496.
It also improves the binding by introducing a new channel "power", that makes it possible to switch the LED off / on with leaving the brightness value untouched.
It also contains a few fixes with warm white LED channel.
Tested with a Magic UFO (a LD382A device)

It seems like that @xylo with #755 and I were fixing this binding at the same time.... :smile: 
How ever I still want hand my changes in, since its my first contributing ever :tada:

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Ok, I am a bit lost now, which PR should be taken into account.
@PH89 and @xylo, could you please clarify which PR should be closed and which one to be reviewed/merged? Did you do identical changes or would you be able to reconcile both versions into a common PR?

**Comment by xylo** [comment]
@kaikreuzer 
Both pull requests are fixing the compilation issues of the original plugin and both add a power channel.
However, my version adds also the functionality to fade smoothly over from one LED state to another.  So, from the perspective of functionality I would suggest to use my version.

**Comment by PH89** [comment]
@kaikreuzer 
I looked also both pull requests and I agree with xylo, so you can merge his PR.

**Comment by cheese68** [comment]
It woud be great if someone could publish a link (or two) to the .jar file of WifiLEDBinding. I have an RasPi2 with an OpenHab2 and my LD382A is waiting for commands :-)

**Comment by thatstheplace** [comment]
@cheese68 I would appreciate that too.

Maybe this thread is interesting for you: https://github.com/openhab/openhab2-addons/pull/755

xylo didn't just fix this binding but added a fade function too.

Like you will see in the thread, the binding isn't running for me, i think something went wrong with my compile process. I had to do it myself because I couldn't find a .jar file too.

Unfortunately I still don't have a solution for my problem.

I'm hoping kaikreuzer will merge the binding to a coming release, now where it is clarified what the differences between xylos and PH89s releases are.

**Comment by xylo** [comment]
@thatstheplace 
Sorry that I didn't solve the problem yet.  I will upload a precompiled jar file in around 10 hours.
On Sunday I wanted to test the add-on with the latest openhab2 snapshot version but could not get this openhab2 version to work.  Seems I have to look for another version (maybe beta).

**Comment by thatstheplace** [comment]
@xylo No cause for a apologize, I think you got a job or something you have enough to do with and I'm grateful for your work allthough.
It would be awesome if you could upload this in the evening! Then we can exclude the possibility that my compile process failed.

**Comment by xylo** [comment]
@thatstheplace [Here](http://stefan.endrullis.de/openhab2/org.openhab.binding.wifiled-2.0.0-SNAPSHOT.jar) is the compiled version of the add-on.  I hope it is working for you.

**Comment by cheese68** [comment]
@xylo THX! 
A HF-LPB100-ZJ200 was detected (L382A) 
Tomorrow I will check if I control my rgbw stribes.

**Comment by thatstheplace** [comment]
@xylo Thanks to you! First it didn't run allthough. I had the same UNINITIALIZED state for the thing. Because it worked for cheese68 I wanted to try it from the start, so I downloaded the openhab snapshot from the openhab website again and just installed the wifiled binding and now it runs!!! I don't know what the problem was but my previous build was "#444" and now its "#547".

Until now the binding seems to be a bit buggy but that is comprehensible because its a BETA.

I will now install all my previous bindings and configure my items to test my complete configuration and then test the wifiled binding in everyday life.

I will give you feedback in a few days.

Thanks again!

**Comment by cheese68** [comment]
Nice
It's working! Both drivers, "Classic" and "Fading" are able to control my L382A. Autodetect is working to. 
I had some issues. Maybee because of conflicts with old openhab bindings like pilight and wifilight, but I can not reproduce it. I removed some old binding i do not use anymore (not pilight!) and now its fine.
THX

**Pull request closed without merging**
