### PR TITLE
Added gzip support to feed binding

### PR DESCRIPTION
**Pull request by meisterfuu**
Added gzip support to the feed binding.
https://github.com/openhab/openhab2-addons/issues/2160

### CODE REVIEW

**Comment by meisterfuu** [comment]
Thanks. I added the request property.

**Comment by martinvw** [comment]
Can you squash your commits and change commit message to include a `Signed-off-by` (to certify that you wrote it or otherwise have the right to pass it on as an open-source), see http://docs.openhab.org/developers/contributing/contributing.html#sign-your-work

For squashing / rebasing see:
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by martinvw** [comment]
@meisterfuu it would be great if you could do the sign-off then everything should be ready to merge.

If you are having problems doing this, please let us know.

**Comment by meisterfuu** [comment]
Sorry for taking so long to respond! I am on it right now.

**Comment by meisterfuu** [comment]
Ok, I think I got everything now?

**Pull request merged**
