### PR TITLE
Bosesoundtouch initial PR

### PR DESCRIPTION
**Pull request by tratho**
New Binding for Bose devices

Signed-off-by: Thomas Traunbauer <thomas.traunbauer@gmail.com> (github: tratho)

### CODE REVIEW

**Comment by martinvw** [comment]
We already have this binding pending in the queue, how do they compare?\

https://github.com/openhab/openhab2-addons/pull/1846

**Comment by tratho** [comment]
Yes i know. But this one has much more features. Sadly we were not able to merge our work.
I know this is bad. But i don't think this should be, First come first serve, but check which one is the better one.

**Comment by kaikreuzer** [comment]
> Sadly we were not able to merge our work.

It seems you guys [had a call to discuss this matter](https://community.openhab.org/t/bose-soundtouch-binding/5678/83?u=kai) a while ago.
I cannot find any documented outcome of your call, though - it would be nice to know, what were your conclusions/agreements after it.

> First come first serve, but check which one is the better one.

This is not how it works. openHAB is driven by the community and we (maintainers) won't judge one contribution over the other. Yes, you are right in general, a contribution that comes first will be in first. But if the community (possibly including the author of the first contribution) agrees that a total rewrite makes sense and will be the better choice on the long run, this is totally fair. But this is not up to us (the maintainers), but it should be the contributors (you and Christian and all the others who already helped reviewing/testing the bindings) to find a solution and suggestion on how to proceed. Do you agree?

**Comment by tratho** [comment]
You will find nothing official. There were only personal emails. What should i say, we tried, but did not find together.
We knew this will lead to some problems but we decided to create the PR because of serveral reasons.
-This binding is tested by several persons over more than one year, see the 100post community thread
-We stand in contact with someone, who works for Bose.
-The Binding is definitly tested with BST10/20/30/300/wireless link adapter.
-The binding supports not only the official API but also includes knowledg from reverse engeneer. This leads to more functionallity

**Comment by kaikreuzer** [comment]
> we decided to create the PR

Whom do you refer to as "we"? As I said, it is perfectly valid to decide to withdraw a PR in favor of another. But my hope would be that such a decision is taken in full agreement of everyone involved - especially @xianlukas. I do not want to be a judge here; what I ask for is that you better sort it out yourselves, this is imho the only fair way forward.

**Comment by tratho** [comment]
We means @marvkis and me.
No as i mentioned, we tried to find a way to work together with @xianlukas but we didn't.

So if you maintainers won't judge in any case, you can close this PR. (judge is very hard, but your words. Better would be have a review and decide which is better, based on the code)

**Comment by martinvw** [comment]
@xianlukas what is your view about this.

@tratho @xianlukas @marvkis which of the bindings is community tested, none, one, both?

**Comment by tratho** [comment]
@martinvw 
this one is community tested. See https://community.openhab.org/t/bose-soundtouch-binding/5678
i do not know if @xianlukas is tested

**Comment by kaikreuzer** [comment]
> judge is very hard, but your words. Better would be have a review and decide which is better, based on the code

I didn't mean judging as "rolling the dice", but as looking at the code and say "this one is good" and "this one is bad". In general, every contribution is welcome and I will never say that something looks bad and thus won't be accepted - we will rather help the author to improve it, so that it becomes mergeable. And this is also what I expect from the community; not to compete, but to collaborate. That's why I am asking for @xianlukas (and other actively interested developers') consent.

**Comment by kaikreuzer** [comment]
@xianlukas I am specifically interested in your opinion - if you say that we should move forward with this PR, there is no need for any further discussion.

**Comment by xianlukas** [comment]
Hi @all,
the major difference about both bindings is how the communication with the device works.
This binding here does not support the official API from Bose.

In my opinion a first version should support the official API even if that means it would have some channels less. In a second step the bindings could be merged to support also the reversed engineered way.
The question here is what the community desires.

In general it would be nice to know if it is possible to have more than one binding for a specific device (set)/service on Eclipse IoT Marketplace, because that might also solve this situation.

**Comment by tratho** [comment]
@xianlukas
This bindings supports the whole official API. Perhaps in a reverse engeneer way, but it does!
The other binding does not even support the whole API. Major things are missing. Such as zone control. So this argument does not count, in my point of view.

Of course you are totally right. A new binding  has not to bring full functionality, but if there is a tested binding which has much more functionality, i do not understand why to prefer the one with the fewer features.

**Comment by marvkis** [comment]
Hi @all,

I'm the 'other' developer and initially started developing this plugin in Dec. 15. I'm standing also behind the decision to start this PR and of course you also have my

Signed-off-by: Christian Niessner <github-marvkis@christian-niessner.de> (github: marvkis)

for the plugin. 

To the situation having two different PR for the same "device" - it was not in our intension to start a PR 'war' here. We tried to sort this out via personal mails but we didn't come up with a con sense. Our intention is to show that there is an other plugin developing within the community for over a year. The PR was not on our prio list but I think it would confuse users if there suddenly will be an other plugin deployed with openHAB only providing some basic functionality instead of the known features provided by the previously used plugin.

@xianlukas - as already stated out in our PM's - we are open for discussion, and we asked you several times to provide some facts to prove your statements.

**Comment by FrankZimmer** [comment]
I'm wondering using not the official API, but I checked this version of the BOSE SoundTouch Binding. Running on latest MASTER Branch OpenHAB2. I did several test but get it not running. The thing ends every time in UNINITIALIZED state. I'm using SountTouch 10 via wifi. Any known issuse here?

**Comment by tratho** [comment]
This is because of the license conditions. You can read about it in the posted thread of the community forum.
To your problem itself. I just tested with the latest snapshot downloaded from
https://openhab.ci.cloudbees.com/job/openHAB-Distribution/
and it works fine for me.

Without any logs, we wil not be able to solve the problem

**Comment by kaikreuzer** [comment]
All, it has become very quiet here, I hope you are still around and happily using this binding :-)

The good news is: I now also have a Bose Soundtouch 20 for testing and review the PR.
I tried to read through the community thread and it seems as if this is the PR that people are using and testing, probably due to the more functional completeness. I would hencesuggest to continue on it in favor of #1846.

In my first initial tests, I came across quite a number of warnings and exceptions in my log, so it seems as if there is still a bit to do.

I have also talked to some people that would love to contribute notification and audio sink support to this binding and for this it would actually be cool, if we could move it over to ESH.

@tratho & @marvkis, would you be fine with that move? If so, would you want to refactor the namespace yourself and create a PR against https://github.com/eclipse/smarthome or would you prefer me to do so? I would use this opportunity to address some review comments myself, instead of leaving the work to you. Let me know, what you think! Looking forward to driving this towards a merge together with you!

**Comment by tratho** [comment]
hi @kaikreuzer 
Nice to hear, that had a look on the binding
i haven't heard from @marvkis for a long time. For me it would be ok, if you move it to ESH.
The main problem working on this binding was propably the uncertainty. This problem seams to be solved now.
Nevertheless there was also the problem, that neither me nor @marvkis found the time to finish the binding, that it is mergeable. So for me it would be greate to see this plugin become official. Especially if you or someone other would contribute.

**Comment by kaikreuzer** [comment]
Ok, perfect! I'll then try to prepare a PR against ESH with your code next week (and might leave some unfinished parts out for the start) - this can then be a good basis for further collaboration and adding more advanced features step by step. I'll comment here once the PR is available.

**Comment by marvkis** [comment]
Hi @kaikreuzer ,

just a ping back - I'm also happy to hear this and I'm also completely fine moving / contributing everything to the ESH project. I'll try to find some time this evening to sign the Eclipse ECA.
Just for completeness if not already noticed: Our latest source / working tree is https://github.com/marvkis/openhab2-addons/tree/bosesoundtouch-devel-master - @tratho  and me did some updates some time ago to have it working with the latest (okay, 2 weeks ago i did the last patches) OH 2.3 beta version. So if might be good to continue with this tree. Shall we update this PR with our latest version?

**Comment by kaikreuzer** [comment]
Great to hear, thanks @marvkis! No need to update this PR, I will directly take the code from your fork then, thanks for the hint.

**Comment by tratho** [comment]
@kaikreuzer 
probably i will update the branch. Today, or tomorrow. I think i have some uncommited changes on my disk. But you don't want to start before next week anyway, so that should not be a problem

**Comment by marvkis** [comment]
Okay, I've read & signed the ECA. I've created a new eclipse account with the same mail address used in my sign-off's. Hope that's okay this way ;)

@kaikreuzer - when you have any questions regarding the implementation don't hesitate to ask ;). It seems the state machine used to parse the XML messages seems to be a bit hard to understand...

**Comment by kaikreuzer** [comment]
Ok, here we go: https://github.com/eclipse/smarthome/pull/5397.
Let's continue on that PR and close this one here.

**Pull request closed without merging**
