### PR TITLE
[modbus] update time-of-last-update

### PR DESCRIPTION
**Pull request by ssalonen**
Fixes sloppy modification based on [code review comment](https://github.com/openhab/openhab2-addons/pull/4701#discussion_r251032820) (which was valid on its own) from a maintainer, which lead to [situation that "time of last update" was not kept up-to-date](https://github.com/openhab/openhab2-addons/pull/4701/commits/e13e893af3b30d89c66856dc21b3dda72fb440fd).

cc @martinvw 

Signed-off-by: Sami Salonen <ssalonen@gmail.com>

### CODE REVIEW

**Comment by ssalonen** [comment]
@cweitkamp thanks -- and I thought I could update single line without full IDE :)  Will make sure the tests pass and the report back.

**Comment by ssalonen** [comment]
CI issues, from https://ci.openhab.org/job/PR-openHAB2-Addons/12352/console

```
Downloaded artifact https://ci.openhab.org/artifactory/libs-snapshot/org/openhab/pom-tycho/2.5.0-SNAPSHOT/maven-metadata.xml
Downloaded artifact https://ci.openhab.org/artifactory/libs-snapshot/org/openhab/pom-tycho/2.5.0-SNAPSHOT/maven-metadata.xml
ERROR: Failed to parse POMs
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.eclipse.smarthome.model:org.eclipse.smarthome.model.sitemap:jar must be a valid version but is '${esh.version}'. @ line 30, column 16
[ERROR] 'dependencies.dependency.version' for org.eclipse.smarthome.ui:org.eclipse.smarthome.ui:jar must be a valid version but is '${esh.version}'. @ line 35, column 16
[ERROR] 'dependencies.dependency.version' for org.eclipse.smarthome.ui:org.eclipse.smarthome.ui.icon:jar must be a valid version but is '${esh.version}'. @ line 40, column 16
[ERROR] 'dependencies.dependency.version' for org.eclipse.smarthome.model:org.eclipse.smarthome.model.sitemap:jar must be a valid version but is '${esh.version}'. @ line 35, column 16
[ERROR] 'dependencies.dependency.version' for org.eclipse.smarthome.ui:org.eclipse.smarthome.ui:jar must be a valid version but is '${esh.version}'. @ line 40, column 16
[ERROR] 'dependencies.dependency.version' for org.eclipse.smarthome.ui:org.eclipse.smarthome.ui.icon:jar must be a valid version but is '${esh.version}'. @ line 45, column 16
[ERROR] 'dependencies.dependency.version' for org.eclipse.smarthome:esh-core:xml:features must be a valid version but is '${esh.version}'. @ line 28, column 16
[ERROR] 'dependencies.dependency.version' for org.eclipse.smarthome:esh-tp:xml:features must be a valid version but is '${esh.version}'. @ line 35, column 16
[ERROR] 'dependencies.dependency.version' for org.eclipse.smarthome:esh-ext:xml:features must be a valid version but is '${esh.version}'. @ line 42, column 16

	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:364)
	at org.jfrog.build.extractor.maven.ArtifactoryProjectBuilder.build(ArtifactoryProjectBuilder.java:31)
	at hudson.maven.MavenEmbedder.buildProjects(MavenEmbedder.java:361)
	at hudson.maven.MavenEmbedder.readProjects(MavenEmbedder.java:331)
	at hudson.maven.MavenModuleSetBuild$PomParser.invoke(MavenModuleSetBuild.java:1328)
	at hudson.maven.MavenModuleSetBuild$PomParser.invoke(MavenModuleSetBuild.java:1125)
	at hudson.FilePath.act(FilePath.java:1078)
	at hudson.FilePath.act(FilePath.java:1061)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.parsePoms(MavenModuleSetBuild.java:986)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:691)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1810)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```

**Comment by ssalonen** [comment]
CI issues: https://ci.openhab.org/job/PR-openHAB2-Addons/12353/console

```
Downloaded artifact https://ci.openhab.org/artifactory/libs-snapshot/org/openhab/pom-tycho/2.5.0-SNAPSHOT/maven-metadata.xml
Downloaded artifact https://ci.openhab.org/artifactory/libs-snapshot/org/openhab/pom-tycho/2.5.0-SNAPSHOT/maven-metadata.xml
ERROR: Failed to parse POMs
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.eclipse.smarthome.model:org.eclipse.smarthome.model.sitemap:jar must be a valid version but is '${esh.version}'. @ line 30, column 16
[ERROR] 'dependencies.dependency.version' for org.eclipse.smarthome.ui:org.eclipse.smarthome.ui:jar must be a valid version but is '${esh.version}'. @ line 35, column 16
[ERROR] 'dependencies.dependency.version' for org.eclipse.smarthome.ui:org.eclipse.smarthome.ui.icon:jar must be a valid version but is '${esh.version}'. @ line 40, column 16
[ERROR] 'dependencies.dependency.version' for org.eclipse.smarthome.model:org.eclipse.smarthome.model.sitemap:jar must be a valid version but is '${esh.version}'. @ line 35, column 16
[ERROR] 'dependencies.dependency.version' for org.eclipse.smarthome.ui:org.eclipse.smarthome.ui:jar must be a valid version but is '${esh.version}'. @ line 40, column 16
[ERROR] 'dependencies.dependency.version' for org.eclipse.smarthome.ui:org.eclipse.smarthome.ui.icon:jar must be a valid version but is '${esh.version}'. @ line 45, column 16
[ERROR] 'dependencies.dependency.version' for org.eclipse.smarthome:esh-core:xml:features must be a valid version but is '${esh.version}'. @ line 28, column 16
[ERROR] 'dependencies.dependency.version' for org.eclipse.smarthome:esh-tp:xml:features must be a valid version but is '${esh.version}'. @ line 35, column 16
[ERROR] 'dependencies.dependency.version' for org.eclipse.smarthome:esh-ext:xml:features must be a valid version but is '${esh.version}'. @ line 42, column 16

	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:364)
	at org.jfrog.build.extractor.maven.ArtifactoryProjectBuilder.build(ArtifactoryProjectBuilder.java:31)
	at hudson.maven.MavenEmbedder.buildProjects(MavenEmbedder.java:361)
	at hudson.maven.MavenEmbedder.readProjects(MavenEmbedder.java:331)
	at hudson.maven.MavenModuleSetBuild$PomParser.invoke(MavenModuleSetBuild.java:1328)
	at hudson.maven.MavenModuleSetBuild$PomParser.invoke(MavenModuleSetBuild.java:1125)
	at hudson.FilePath.act(FilePath.java:1078)
	at hudson.FilePath.act(FilePath.java:1061)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.parsePoms(MavenModuleSetBuild.java:986)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:691)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1810)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level /var/jenkins_home/workspace/PR-openHAB2-Addons/target to /var/jenkins_home/jobs/PR-openHAB2-Addons/builds/12353/htmlreports/Static_20Code_20Analysis_20Report
Finished: FAILURE
```

**Comment by ssalonen** [comment]
Dependency issues still:
```
1) org.eclipse.smarthome.ui:org.eclipse.smarthome.ui:jar:${esh.version}

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.eclipse.smarthome.ui -DartifactId=org.eclipse.smarthome.ui -Dversion=${esh.version} -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.eclipse.smarthome.ui -DartifactId=org.eclipse.smarthome.ui -Dversion=${esh.version} -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
  	1) org.openhab.binding:org.openhab.binding.modbus:pom:2.5.0-SNAPSHOT
  	2) org.openhab.io:org.openhab.io.transport.modbus:jar:2.5.0-SNAPSHOT
  	3) org.openhab.core:org.openhab.core:jar:2.5.0-SNAPSHOT
  	4) org.eclipse.smarthome.ui:org.eclipse.smarthome.ui:jar:${esh.version}
```

**Comment by martinvw** [comment]
Travis being green is good enough for now 👍

**Comment by martinvw** [comment]
Thanks!

**Pull request merged**
