### PR TITLE
POM Code Convention

### PR DESCRIPTION
**Pull request by wborn**
Reformats the POM files using the "recommended_2008_06" profile.

Command that has been executed:

```
mvn \
  com.github.ekryd.sortpom:sortpom-maven-plugin:sort \
  -Dsort.createBackupFile=false \
  -Dsort.keepBlankLines=true \
  -Dsort.predefinedSortOrder="recommended_2008_06"
```

### CODE REVIEW

**Comment by davidgraeff** [comment]
Can this be part of the official ESH.xml Eclipse formatting file please?

**Comment by J-N-K** [comment]
I don‘t think you can have different formatters for the same extension.

**Comment by wborn** [comment]
I also think it's currently not possible. :disappointed:

**Comment by davidgraeff** [comment]
So that means we have a problem if people use Eclipse for auto-formatting the entire project :/
Maybe we adapt our guidelines of our own xml files?

**Comment by wborn** [comment]
I'd just use 4 spaces in every XML file which works well for me in other projects. :smile: That way tooling can handle it and it always looks the same in each and every editor. The biggest downside is that you have to press more keys (arrow/space/del) so it can cause more RSI.

When tabs were enforced there was not really a rationale given in https://github.com/openhab/static-code-analysis/issues/223. Maybe other @openhab/core-maintainers or @openhab/sat-maintainers now the reason for this? It does get tedious to keep switching all files in each repo from one indentation style to another.

I also read [people using spaces instead of tabs make more money](https://stackoverflow.blog/2017/06/15/developers-use-spaces-make-money-use-tabs/). :wink:

**Comment by kaikreuzer** [comment]
> Maybe other @openhab/core-maintainers or @openhab/sat-maintainers know the reason for this?

This was a long discussion at ESH at the time. The outcome was that we decided for using tabs in XMLs that end up in bundles in order to not unnecessarily increase their size as the XMLs make up quite some content, especially for bindings and processing them also was a significant part of the startup time.

**Pull request merged**
