### PR TITLE
Replace spaces with tabs in XML and update checkstyle.properties

### PR DESCRIPTION
**Pull request by wborn**
* Replace spaces with tabs in XML files because SAT will consider these as errors (https://github.com/openhab/static-code-analysis/pull/268)
* Use default file name for generated OwHandlerFactory component XML so it can contain spaces
* Add com.google.common.collect to forbidden packages (see also https://github.com/openhab/openhab-core/pull/407)

Resolves most of the issues with SAT 0.6.0-SNAPSHOT.

### CODE REVIEW

**Comment by martinvw** [comment]
@openhab/2-x-add-ons-maintainers is this new and desired?

> Merging can be performed automatically with 2 approving reviews.

**Comment by cweitkamp** [comment]
> @openhab/2-x-add-ons-maintainers is this new and desired?
>
> > Merging can be performed automatically with 2 approving reviews.

Yes, it looks new to me. Maybe related to the CODEOWNER features. Lets see what happens if one of @cschneider , @davidgraeff , @fruggy83 or @kaikreuzer will approve this PR.

**Comment by kaikreuzer** [comment]
Yes, I changed it to two reviews, so that in the normal case a code owner and a repo maintainer have to approve before a merge. But repo maintainers should always feel free to overrule this, please! It is just a safety measure for preventing code owners to merge stuff (as they now have write access as well).

**Comment by kaikreuzer** [comment]
Yes, I changed it to two reviews, so that in the normal case a code owner and a repo maintainer have to approve before a merge. But repo maintainers should always feel free to overrule this, please! It is just a safety measure for preventing code owners to merge stuff (as they now have write access as well).

But what is weird is that we now have 3 approvals, but Github still complains...

**Comment by cweitkamp** [comment]
It looks like the CODEOWNER feature overrules the PullApprove add-on. 

Btw: They released [version 3](https://medium.com/dropseed/introducing-pullapprove-version-3-4da68e14a623). Maybe it helps if we upgrade our add-on to that version.

**Comment by kaikreuzer** [comment]
> It looks like the CODEOWNER feature overrules the PullApprove add-on.

No, it actually expects approval from all CODEOWNERS of code that is touched and this PR simply goes across multiple add-ons, i.e. many CODEOWNERS.

**Pull request merged**
