### PR TITLE
[passthru] Passthru Binding initial contribution

### PR DESCRIPTION
**Pull request by jogeyer**
New passthru binding for simple Raspberry Pi GPIO remote control

### CODE REVIEW

**Comment by sja** [comment]
Cool! But what if I want to contribute "passthrough" for ESP8266? RaspberryGpioPassthrough would be a long, but better name.

**Comment by sja** [comment]
Oh, Im sorry. Its already designed to be hardware agnostic.

**Comment by jogeyer** [comment]
In fact this a openhab 1 or 2 to openhab 1 or 2 connection. It may be used on any hardware platform which supports openhab but is restricted to commands similar to use GPIO control.

**Comment by jogeyer** [comment]
Sorry in this case this is a openhab 2 to openhab 1/2 connection. There is also a version for openhab 1 existent.

**Comment by martinvw** [comment]
@jogeyer it has been an incredible long time, is this binding still relevant and are you still active?

If so I can do a review and we could go towards merging it, please let me know.

**Comment by davidgraeff** [comment]
Hm. I think this should be closed.

When I read the description I expected a GPIO interaction binding. But instead it connects to another openHAB instance by watching the classicUI REST api (via polling, not even server-send-events).

**Comment by kaikreuzer** [comment]
@davidgraeff I fully agree with you - this is something very different than a binding and should not be treated as such, so let's close it.

**Pull request closed without merging**
