### PR TITLE
[modbus] avoid calling expensive isLinked and react to channel(Un)Linked

### PR DESCRIPTION
**Pull request by ssalonen**
Performance optimization for modbus binding based on CPU profiling with mbs38 in the community forums (See e.g. [this post](https://community.openhab.org/t/many-100-modbus-pollers-is-it-slowing-down-the-binding/53496/8?u=ssalonen)).

Turns out `isLinked(String)` is quite a heavy operation, and it can be optimized away by listening for `channelLinked` and `channelUnlinked` and keeping a list of list of linked channels.

Signed-off-by: Sami Salonen <ssalonen@gmail.com>

### CODE REVIEW

**Comment by wborn** [comment]
Can you fix the broken tests @ssalonen?

```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:1.2.0:compile (default-compile) on project org.openhab.binding.modbus.test: Compilation failure: Compilation failure: 
[ERROR] /home/travis/build/openhab/openhab2-addons/addons/binding/org.openhab.binding.modbus.test/src/test/java/org/openhab/binding/modbus/internal/ModbusDataHandlerTest.java:[223] 
[ERROR] 	public boolean addTag(String itemName, String tag) {
[ERROR] 	               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The method addTag(String, String) of type ModbusDataHandlerTest.ItemRegisteryTestImpl must override or implement a supertype method
[ERROR] /home/travis/build/openhab/openhab2-addons/addons/binding/org.openhab.binding.modbus.test/src/test/java/org/openhab/binding/modbus/internal/ModbusDataHandlerTest.java:[229] 
[ERROR] 	public boolean addTags(String itemName, Collection<String> tags) {
[ERROR] 	               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The method addTags(String, Collection<String>) of type ModbusDataHandlerTest.ItemRegisteryTestImpl must override or implement a supertype method
[ERROR] /home/travis/build/openhab/openhab2-addons/addons/binding/org.openhab.binding.modbus.test/src/test/java/org/openhab/binding/modbus/internal/ModbusDataHandlerTest.java:[235] 
[ERROR] 	public boolean removeTag(String itemName, String tag) {
[ERROR] 	               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The method removeTag(String, String) of type ModbusDataHandlerTest.ItemRegisteryTestImpl must override or implement a supertype method
[ERROR] /home/travis/build/openhab/openhab2-addons/addons/binding/org.openhab.binding.modbus.test/src/test/java/org/openhab/binding/modbus/internal/ModbusDataHandlerTest.java:[241] 
[ERROR] 	public boolean removeTags(String itemName, Collection<String> tags) {
[ERROR] 	               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The method removeTags(String, Collection<String>) of type ModbusDataHandlerTest.ItemRegisteryTestImpl must override or implement a supertype method
[ERROR] /home/travis/build/openhab/openhab2-addons/addons/binding/org.openhab.binding.modbus.test/src/test/java/org/openhab/binding/modbus/internal/ModbusDataHandlerTest.java:[247] 
[ERROR] 	public boolean removeTags(String itemName) {
[ERROR] 	               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The method removeTags(String) of type ModbusDataHandlerTest.ItemRegisteryTestImpl must override or implement a supertype method
```

**Comment by martinvw** [comment]
@wborn looks fine to me, any further remarks?

**Comment by ssalonen** [comment]
Fixed... My local checkout of smarthome was out of date.

**Comment by wborn** [comment]
Besides the compiliation issues the code looks good!

Since I ran into these performance issues myself with the Nest Binding (https://github.com/openhab/openhab2-addons/pull/3695), I think it would be better if they are fixed in ESH. That way binding code stays clean and each binding can benefit from them. WDYT @kaikreuzer, @htreu?

**Comment by kaikreuzer** [comment]
>  I think it would be better if they are fixed in ESH

Definitely so! I wasn't aware at all that this is a heavy operation (its name does not suggest this indeed). Could you enter an issue at ESH for that, please?

**Comment by wborn** [comment]
> Could you enter an issue at ESH for that, please?

I've created https://github.com/eclipse/smarthome/issues/6416 for this.

**Comment by htreu** [comment]
Hi all, I suggest closing this PR since the performance issues are now fixed inside the framework. No need to hold your own cache of linked channels.

wdyt @ssalonen, @wborn, @martinvw?

**Comment by wborn** [comment]
The performance improvements should be available in the latest openHAB 2.4.0-SNAPSHOT # 1413 build.

Are the changes in the `ModbusDataHandlerTest` in this PR solving some other issue @ssalonen?

**Comment by ssalonen** [comment]
I agree with closing the PR -- it will be cleaner code when framework is fixed.

@wborn good point regarding the ModbusDataHandlerTest. Indeed there was one commit to fix eclipse null checks:
https://github.com/openhab/openhab2-addons/pull/4159/commits/8489b30635594818889fabf52125b9305501cbf3

Does the CI checks these? Perhaps it was issue with my IDE setup?

**Comment by wborn** [comment]
> Does the CI checks these? Perhaps it was issue with my IDE setup?

The build will not fail on the null annotations errors. I also see the following error in Eclipse.

`Null type mismatch (type annotations): required '@NonNull Item' but this expression has type '@Nullable Item'`

So it would be nice to see it fixed.

The `org.openhab.binding.modbus.test` Eclipse JUnit plugin test configuration also fails validation because some Jetty bundles are missing from it.

**Comment by ssalonen** [comment]
Thanks for testing that out. I can introduce separate pr for the null fix.

I am not sure what the latter issue means, I am not sure if jetty bundles are even needed in these tests...

**Comment by wborn** [comment]
>  I can introduce separate pr for the null fix.

Great! Then I'll close this PR.

> I am not sure what the latter issue means

Whenever you run the `org.openhab.binding.modbus.test` tests in Eclipse it validates if all required bundles are available. Some transitive dependency will probably require these Jetty bundles.

**Pull request closed without merging**
