### PR TITLE
migrate nibeheatpump to bnd

### PR DESCRIPTION
**Pull request by J-N-K**
This binding includes some files that are not used for building the jar. They are located directly in the project directory. Shall we define a place for such files,like `<projecthome>\contrib`?

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by wborn** [comment]
Can you resolve the merge conflicts @J-N-K ?

**Comment by J-N-K** [comment]
What about my other comment regarding the additional files? I can do both in one shot.

**Comment by wborn** [comment]
I'm fine with moving such content to a `contrib` dir.
It's also commonly used in other projects (e.g. [git/contrib](https://github.com/git/git/tree/master/contrib)).

**Comment by J-N-K** [comment]
done

**Comment by wborn** [comment]
Can you resolve the merge conflicts again @J-N-K ?

**Comment by J-N-K** [comment]
done

**Pull request merged**
