### PR TITLE
Updated binding XML schema locations to openhab

### PR DESCRIPTION
**Pull request by cweitkamp**
- Updated binding XML schema locations to openhab

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by martinvw** [comment]
Thanks, I feer that it does create a conflict with my open fix-sat findings PR in rfxcom :-(

**Comment by cweitkamp** [comment]
@martinvw Shall I exclude the changes in the rfxcom bundle from this PR?

**Comment by martinvw** [comment]
No I have to fix some other comments and can there rebase 👍

**Comment by wborn** [comment]
There doesn't seem to be a merge conflict now in https://github.com/openhab/openhab2-addons/pull/2980 @martinvw. :-)

**Comment by martinvw** [comment]
Great :-)

**Pull request merged**
