### PR TITLE
removed specific thread pool and renamed discovery class to match its function

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by digitaldan** [comment]
LGTM, but should we combine the 2 discovery classes classes together?  Since we removed the discovery dependency from the thing handler, I don't see why it can't be the same class.  I'm good either way, but I would volunteer to combine them if thats the preference.

**Comment by kaikreuzer** [comment]
Yes, I thought the same, but didn't want to do too many changes at once there, especially as I currently cannot test the code. But happy, if you want to refactor it accordingly.

**Comment by digitaldan** [comment]
Since I'm back in this codebase I will go ahead merge the two classes.

**Comment by kaikreuzer** [comment]
Superseded by #2077.

**Pull request closed without merging**
