### PR TITLE
Fixes issue with reconnects to Harmony Hubs

### PR DESCRIPTION
**Pull request by digitaldan**
Signed-off-by: Dan Cunningham <dan@digitaldan.com>

### CODE REVIEW

**Comment by digitaldan** [comment]
@wborn this looks to fix reconnects on my system.

**Comment by wborn** [comment]
This also fixes the reconnect issue with my hub @digitaldan. Thanks a lot! The code also LGTM. Hopefully we've squashed the last pesky Harmony bug with this. :-)

**Comment by felixloesch** [comment]
I just tried this on the latest build #893 of OH2. Now the situation is as follows. The binding tries to reconnect when the Hub becomes available again but this still results in an "InterruptedException". Here is the stack trace:

2017-04-25 22:44:34.750 [WARN ] [harmonyhub.handler.HarmonyHubHandler] - heartbeat failed
java.lang.RuntimeException: Failed communicating with Harmony Hub
        at net.whistlingfish.harmony.HarmonyClient.sendOAStanza(HarmonyClient.java:275)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at net.whistlingfish.harmony.HarmonyClient.sendOAStanza(HarmonyClient.java:264)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at net.whistlingfish.harmony.HarmonyClient.sendPing(HarmonyClient.java:333)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.openhab.binding.harmonyhub.handler.HarmonyHubHandler$2.run(HarmonyHubHandler.java:213)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_121]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)[:1.8.0_121]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)[:1.8.0_121]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)[:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
Caused by: org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 5000ms (~5s). Waited for response using: net.whistlingfish.harmony.protocol.OAReplyFilter@3657f7.
        at org.jivesoftware.smack.SmackException$NoResponseException.newWith(SmackException.java:110)
        at org.jivesoftware.smack.SmackException$NoResponseException.newWith(SmackException.java:97)
        at net.whistlingfish.harmony.HarmonyClient.getNextStanzaSkipContinues(HarmonyClient.java:287)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at net.whistlingfish.harmony.HarmonyClient.sendOAStanza(HarmonyClient.java:273)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        ... 10 more
2017-04-25 22:44:39.833 [DEBUG] [harmonyhub.handler.HarmonyHubHandler] - Updating listeners with status OFFLINE
2017-04-25 22:45:04.750 [WARN ] [.whistlingfish.harmony.HarmonyClient] - Send heartbeat failed
java.lang.RuntimeException: Failed communicating with Harmony Hub
        at net.whistlingfish.harmony.HarmonyClient.sendOAStanza(HarmonyClient.java:275)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at net.whistlingfish.harmony.HarmonyClient.sendOAStanza(HarmonyClient.java:264)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at net.whistlingfish.harmony.HarmonyClient.sendPing(HarmonyClient.java:333)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at net.whistlingfish.harmony.HarmonyClient$2.run(HarmonyClient.java:177)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_121]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)[:1.8.0_121]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)[:1.8.0_121]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)[:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
Caused by: org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 5000ms (~5s). Waited for response using: net.whistlingfish.harmony.protocol.OAReplyFilter@afb191.
        at org.jivesoftware.smack.SmackException$NoResponseException.newWith(SmackException.java:110)
        at org.jivesoftware.smack.SmackException$NoResponseException.newWith(SmackException.java:97)
        at net.whistlingfish.harmony.HarmonyClient.getNextStanzaSkipContinues(HarmonyClient.java:287)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at net.whistlingfish.harmony.HarmonyClient.sendOAStanza(HarmonyClient.java:273)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        ... 10 more
2017-04-25 22:45:39.804 [DEBUG] [harmonyhub.handler.HarmonyHubHandler] - Connecting: host 192.168.0.118
2017-04-25 22:45:42.813 [DEBUG] [harmonyhub.handler.HarmonyHubHandler] - Could not connect to HarmonyHub at 192.168.0.118
java.lang.RuntimeException: Failed communicating with Harmony Hub
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:189)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:114)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.openhab.binding.harmonyhub.handler.HarmonyHubHandler.connect(HarmonyHubHandler.java:207)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.openhab.binding.harmonyhub.handler.HarmonyHubHandler.access$4(HarmonyHubHandler.java:178)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.openhab.binding.harmonyhub.handler.HarmonyHubHandler$3.run(HarmonyHubHandler.java:249)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_121]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_121]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
Caused by: org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: '192.168.0.118:5222' failed because: /192.168.0.118 exception: java.net.NoRouteToHostException: No route to host (Host unreachable)
        at org.jivesoftware.smack.SmackException$ConnectionException.from(SmackException.java:277)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:617)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:888)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:377)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:125)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        ... 11 more
2017-04-25 22:45:42.846 [DEBUG] [harmonyhub.handler.HarmonyHubHandler] - Updating listeners with status OFFLINE
2017-04-25 22:46:42.837 [DEBUG] [harmonyhub.handler.HarmonyHubHandler] - Connecting: host 192.168.0.118
2017-04-25 22:46:42.848 [DEBUG] [harmonyhub.handler.HarmonyHubHandler] - Could not connect to HarmonyHub at 192.168.0.118
java.lang.RuntimeException: Failed communicating with Harmony Hub
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:189)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:114)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.openhab.binding.harmonyhub.handler.HarmonyHubHandler.connect(HarmonyHubHandler.java:207)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.openhab.binding.harmonyhub.handler.HarmonyHubHandler.access$4(HarmonyHubHandler.java:178)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.openhab.binding.harmonyhub.handler.HarmonyHubHandler$3.run(HarmonyHubHandler.java:249)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_121]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_121]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
Caused by: java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2067)[:1.8.0_121]
        at org.jivesoftware.smack.SynchronizationPoint.waitForConditionOrTimeout(SynchronizationPoint.java:243)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWait(SynchronizationPoint.java:151)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWaitOrThrow(SynchronizationPoint.java:126)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:380)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:125)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        ... 11 more
2017-04-25 22:46:42.859 [DEBUG] [harmonyhub.handler.HarmonyHubHandler] - Updating listeners with status OFFLINE
2017-04-25 22:47:07.089 [DEBUG] [discovery.HarmonyHubDiscoveryService] - StartScan called
2017-04-25 22:47:07.090 [DEBUG] [discovery.HarmonyHubDiscoveryService] - Creating Harmony server on port 39951
2017-04-25 22:47:42.869 [DEBUG] [harmonyhub.handler.HarmonyHubHandler] - Connecting: host 192.168.0.118
2017-04-25 22:47:42.876 [DEBUG] [harmonyhub.handler.HarmonyHubHandler] - Could not connect to HarmonyHub at 192.168.0.118
java.lang.RuntimeException: Failed communicating with Harmony Hub
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:189)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:114)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.openhab.binding.harmonyhub.handler.HarmonyHubHandler.connect(HarmonyHubHandler.java:207)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.openhab.binding.harmonyhub.handler.HarmonyHubHandler.access$4(HarmonyHubHandler.java:178)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.openhab.binding.harmonyhub.handler.HarmonyHubHandler$3.run(HarmonyHubHandler.java:249)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_121]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_121]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
Caused by: java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2067)[:1.8.0_121]
        at org.jivesoftware.smack.SynchronizationPoint.waitForConditionOrTimeout(SynchronizationPoint.java:243)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWait(SynchronizationPoint.java:151)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWaitOrThrow(SynchronizationPoint.java:126)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:380)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:125)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        ... 11 more
2017-04-25 22:47:42.889 [DEBUG] [harmonyhub.handler.HarmonyHubHandler] - Updating listeners with status OFFLINE
2017-04-25 22:48:42.891 [DEBUG] [harmonyhub.handler.HarmonyHubHandler] - Connecting: host 192.168.0.118
2017-04-25 22:48:42.896 [DEBUG] [harmonyhub.handler.HarmonyHubHandler] - Could not connect to HarmonyHub at 192.168.0.118
java.lang.RuntimeException: Failed communicating with Harmony Hub
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:189)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:114)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.openhab.binding.harmonyhub.handler.HarmonyHubHandler.connect(HarmonyHubHandler.java:207)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.openhab.binding.harmonyhub.handler.HarmonyHubHandler.access$4(HarmonyHubHandler.java:178)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.openhab.binding.harmonyhub.handler.HarmonyHubHandler$3.run(HarmonyHubHandler.java:249)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_121]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_121]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
Caused by: java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2067)[:1.8.0_121]
        at org.jivesoftware.smack.SynchronizationPoint.waitForConditionOrTimeout(SynchronizationPoint.java:243)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWait(SynchronizationPoint.java:151)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWaitOrThrow(SynchronizationPoint.java:126)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:380)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:125)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        ... 11 more
2017-04-25 22:48:42.902 [DEBUG] [harmonyhub.handler.HarmonyHubHandler] - Updating listeners with status OFFLINE
2017-04-25 22:49:42.909 [DEBUG] [harmonyhub.handler.HarmonyHubHandler] - Connecting: host 192.168.0.118
2017-04-25 22:49:42.920 [DEBUG] [harmonyhub.handler.HarmonyHubHandler] - Could not connect to HarmonyHub at 192.168.0.118
java.lang.RuntimeException: Failed communicating with Harmony Hub
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:189)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:114)
2017-04-25 22:56:43.039 [DEBUG] [harmonyhub.handler.HarmonyHubHandler] - Connecting: host 192.168.0.118
2017-04-25 22:56:43.047 [DEBUG] [harmonyhub.handler.HarmonyHubHandler] - Could not connect to HarmonyHub at 192.168.0.118
java.lang.RuntimeException: Failed communicating with Harmony Hub
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:189)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:114)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.openhab.binding.harmonyhub.handler.HarmonyHubHandler.connect(HarmonyHubHandler.java:207)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.openhab.binding.harmonyhub.handler.HarmonyHubHandler.access$4(HarmonyHubHandler.java:178)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.openhab.binding.harmonyhub.handler.HarmonyHubHandler$3.run(HarmonyHubHandler.java:249)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_121]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_121]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
Caused by: java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2067)[:1.8.0_121]
        at org.jivesoftware.smack.SynchronizationPoint.waitForConditionOrTimeout(SynchronizationPoint.java:243)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWait(SynchronizationPoint.java:151)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWaitOrThrow(SynchronizationPoint.java:126)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:380)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:125)[216:org.openhab.binding.harmonyhub:2.1.0.201704170008]

**Comment by wborn** [comment]
@felixloesch is your binding up to date? According to your logging you are using a version that can not have this fix: org.openhab.binding.harmonyhub:2.1.0.201704170008

**Comment by felixloesch** [comment]
Although the newest 2.1.0-SNAPSHOT KAR file was installed the HarmonyHub Binding was still on 2017-04-17. I upgraded it to 2017-04-25 and it works now like a charm. Thank you very much for the fix!

**Pull request merged**
