### PR TITLE
Snapcast Binding

### PR DESCRIPTION
**Pull request by ssoerensen**
Openhab 2 binding for controlling the multiroom audio server Snapcast:

https://github.com/badaix/snapcast

### CODE REVIEW

**Comment by martinvw** [comment]
@ssoerensen Can you please add your binding to the `pom.xml` that way our build and analysis tools can already do some preliminary checks.

**Comment by rusitschka** [comment]
@ssoerensen This plugin does not work with the latest snapserver 0.11.1, right? I'm getting

`
java.lang.NullPointerException
         at org.openhab.binding.snapcast.internal.protocol.SnapcastController.connect(SnapcastController.java:49)
         at org.openhab.binding.snapcast.handler.SnapserverHandler.initialize(SnapserverHandler.java:70)
         at org.eclipse.smarthome.core.thing.internal.ThingManager$9$1.call(ThingManager.java:713)
         at org.eclipse.smarthome.core.thing.internal.ThingManager$9$1.call(ThingManager.java:1)
         at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:179)
         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
         at java.lang.Thread.run(Thread.java:748)
`

Seems to be due to the new groups feature and the changed JSON response from SnapServer.

**Comment by ssoerensen** [comment]
That is correct, the binding does not work with v 0.11 due to json protocol updates. i am working on a fix before submitting a new pull request

**Comment by ssoerensen** [comment]
@rusitschka I have made some work on the issue. i have posted a update to my thread on community.openhab.org and i would love your feedback: https://community.openhab.org/t/snapcast-binding/25551/7

**Comment by martinvw** [comment]
@ssoerensen something went wrong, you included a lot of commits which should not be here, can you take a look at it. It might be best to store the changes of the last commit somewhere and then revert all the commits that should not be included.

**Comment by fallenicarus** [comment]
@ssoerensen is there an update in this? I am trying to setup snapcast with openhab and wanted to check if the issues with v0.11 were fixed?

**Comment by ssoerensen** [comment]
@fallenicarus i am about to be done with the fixes. I haven't had that much time lately. i had a setback controlling the group concept, because when using the snapcast control app groups get created and deleted dynamically, this means that using a group as a item is not a possibility

**Pull request closed without merging**
