### PR TITLE
[senseBox] Forgot to add binding to addons/binding/pom.xml

### PR DESCRIPTION
**Pull request by hakan42**
Not only forgot to add the binding to feature.xml, also forgot to add to upper level pom.xml.

Signed-off-by: Hakan Tandogan <hakan@tandogan.com>

### CODE REVIEW

**Comment by hakan42** [comment]
For Jenkins, it's the 'package org.openhab.core 0.0.0' which provides the OpenHAB class.

On my system, I needed a re-compile of openhab-core. Interestingly, this package should have been part of OH itself as the Dashboard UI uses it to show the build number in the footer. @kaikreuzer , any idea?

**Comment by kaikreuzer** [comment]
Yes, bindings should not have any dependencies to openHAB core, only to ESH APIs. So removing that dependency would be the simplest solution:-)
If you need to get hold of some version, why not use the bundle version through `FrameworkUtil.getBundle(getClass()).getVersion();`?

**Comment by hakan42** [comment]
I wanted to give the API endpoint as much information as possible in case they want to react to misbehaving binding versions. I will go with the easiest solution and provide only the bundle version, especially as I have that piece of code already in place :)

Independently of this, is there a chance that we could have something similar to the OpenHAB.version() method in the ESH core? If yes, I would open up an issue over there and start a discussion...

**Comment by kaikreuzer** [comment]
No, because it simply is difficult what the "version" should be - ESH is just a set of bundles. For openHAB, you can also install bindings of different versions than the core bundles. So the best version to send out is really the version of the bundle, where your code is in - then you can be sure that you can trace requests back to where they originated from.

**Comment by hakan42** [comment]
@martinvw , Travis and Jenkins are happy again. Could you have another look please?

**Comment by kaikreuzer** [comment]
Perfect, thanks!

**Pull request merged**
