### PR TITLE
[satel] Migrate to bnd build

### PR DESCRIPTION
**Pull request by Hilbrand**
Automigrated with https://gist.github.com/Hilbrand/a7127d0fb7afd36124a78a248453ff03

### CODE REVIEW

**Comment by Hilbrand** [comment]
Is the dependency of `gnu.io` a problem? Or is it something we want preferable be removed? I assume it would still work this binding has been moved to the bnd build and it still uses `gnu.io`?

**Comment by cweitkamp** [comment]
> Is the dependency of gnu.io a problem?

Nevermind. I saw some recent work to suppress its usage (https://github.com/openhab/openhab2-addons/pull/5167 or https://github.com/openhab/org.openhab.binding.zwave/pull/1152) and switch to OHC SerialPort API (https://github.com/eclipse/smarthome/pull/5560). Nothing important for Java 11.

**Comment by druciak** [comment]
>  I saw some recent work to suppress its usage

I will try to switch from gnu.io to the new api once this migration is merged.

**Comment by davidgraeff** [comment]
conflicts

**Pull request merged**
