### PR TITLE
Revert 4685 modbus internal

### PR DESCRIPTION
**Pull request by wborn**
Reverts #4685.

As @mrbig [pointed out](https://github.com/openhab/openhab2-addons/pull/4685#issuecomment-457407781) the exported packages are there so they can be used in https://github.com/openhab/openhab2-addons/pull/4220. Sorry for making them internal again! 

We'd best review/merge https://github.com/openhab/openhab2-addons/pull/4220 so whenever we make them internal it results in build errors. :wink:

### CODE REVIEW

**Comment by martinvw** [comment]
Lets wait for the build :-)

**Comment by kaikreuzer** [comment]
> We'd best review/merge #4220 so whenever we make them internal it results in build errors. 😉

Go for it 😎!

**Comment by kaikreuzer** [comment]
> Lets wait for the build :-)

Travis should be enough, Jenkins has some memory issues atm...

**Comment by mrbig** [comment]
Thank you @wborn for you understanding.
I see that you guys are doing a lot of work, so such things could happen.
Please keep up the good work you do for the community!

**Pull request merged**
