### PR TITLE
Remove org.osgi.service.component.annotations from manifests

### PR DESCRIPTION
**Pull request by wborn**
See https://github.com/openhab/openhab2-addons/pull/2878#issuecomment-346804361

### CODE REVIEW

**Comment by wborn** [comment]
Should these imports also be removed from ESH manifests or does other logic apply there?

**Comment by martinvw** [comment]
Lgtm, Travis happy

**Comment by kaikreuzer** [comment]
Hm, although it didn't make the build fail, removing the import broke the XML generation during the build, see https://community.openhab.org/t/oh2-startup-error-in-latest-build/9082/3.

I have reverted this commit for the moment - we have to figure out why this happens.

**Comment by wborn** [comment]
OK we'll need to add it back to the Wincentrale Binding as well. I currently only have a virtual keyboard at my disposal. ;-)

**Comment by kaikreuzer** [comment]
Done: https://github.com/openhab/openhab2-addons/pull/2884
Will have to trigger a new build with it...

**Comment by wborn** [comment]
Thanks!

**Pull request merged**
