### PR TITLE
[orvibo] fix embedded library

### LINKED ISSUE #5611: [orvibo] the bnd migration broke the binding
## Expected Behavior

Binding works as it did prior to the bnd migration.

## Current Behavior

Binding throws an exception during the discovery.  See stacktrace below:

```
2019-05-17 20:52:43.582 [ERROR] [org.openhab.binding.orvibo          ] - bundle org.openhab.binding.orvibo:2.5.0.201905170420 (275)[org.openhab.binding.orvibo.internal.discovery.SocketDiscoveryService(384)] :  Error during instantiation of the implementation object

java.lang.reflect.InvocationTargetException: null

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]

	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]

	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]

	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:?]

	at org.apache.felix.scr.impl.inject.ComponentConstructor.newInstance(ComponentConstructor.java:309) ~[?:?]

	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:277) ~[?:?]

	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:114) ~[?:?]

	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:982) ~[?:?]

	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:955) ~[?:?]

	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:756) ~[?:?]

	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:666) ~[?:?]

	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:432) ~[?:?]

	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:665) ~[?:?]

	at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:338) ~[?:?]

	at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:382) ~[?:?]

	at org.apache.felix.scr.impl.Activator.access$200(Activator.java:49) ~[?:?]

	at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:264) ~[?:?]

	at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196) ~[?:?]

	at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169) ~[?:?]

	at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49) ~[?:?]

	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:482) ~[?:?]

	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:415) ~[?:?]

	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232) ~[?:?]

	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:444) ~[?:?]

	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:908) ~[?:?]

	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) ~[?:?]

	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) ~[?:?]

	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:213) ~[?:?]

	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:120) ~[?:?]

	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:112) ~[?:?]

	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:168) ~[?:?]

	at org.eclipse.osgi.container.Module.publishEvent(Module.java:476) ~[?:?]

	at org.eclipse.osgi.container.Module.start(Module.java:467) ~[?:?]

	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) ~[?:?]

	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402) ~[?:?]

	at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.startBundle(BundleInstallSupportImpl.java:161) ~[?:?]

	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:1149) ~[?:?]

	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:997) ~[?:?]

	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1058) ~[?:?]

	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:994) ~[?:?]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]

	at java.lang.Thread.run(Thread.java:748) [?:?]

Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature

	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:299) ~[6:org.ops4j.pax.logging.pax-logging-api:1.10.1]

	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:269) ~[6:org.ops4j.pax.logging.pax-logging-api:1.10.1]

	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281) ~[6:org.ops4j.pax.logging.pax-logging-api:1.10.1]

	at org.openhab.binding.orvibo.internal.discovery.SocketDiscoveryService.<init>(SocketDiscoveryService.java:45) ~[?:?]

	... 44 more
```

## Solution
Although I'm the author of the Orvibo binding, unfortunately I don't understand the bnd build system to know what is causing this.

## Steps to Reproduce (for Bugs)

1. Enable Orvibo binding (through addons.cfg)
2. Wait for the automatic discovery to start

## Your Environment

openHAB 2.5.0 Build #1593
Running Raspbian Stretch on a Raspberry Pi 3B+

### PR DESCRIPTION
**Pull request by J-N-K**
Fixes #5611 

The embedded library contained slf4j and commons-collections4 bundles instead of referencing them as dependencies. This lead to exceptions at runtime due to mismatching versions. The modified source is attached. Unfortunately the library is not available online but needs to be embedded.

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by tavalin** [comment]
I'll try and review/test tomorrow evening as I'm not at home tonight, unfortunately. However I'm grateful for your efforts!

**Comment by tavalin** [comment]
Hi @J-N-K

I managed to download the attached binding and no longer get the stacktrace as before.

I didn't get to do any extensive testing as my device wasn't responding to OH command, but I think this is a separate issue.

**Comment by J-N-K** [comment]
I only changed the `scope` of the dependencies and the assembly `descriptor-ref`. If this fixes the reported problem, we should merge it.

**Comment by martinvw** [comment]
@J-N-K feel free to merge

**Comment by J-N-K** [comment]
@martinvw The embedded library was the problem. It contained a version of slf4j that conflicted with our version. Since the library was compiled only for our use anyway I modified it to not embed dependencies but require provided ones. Since slf4j is provided in every case there is no need to decklare it in the binding pom.

**Pull request merged**
