### PR TITLE
Network binding arping fix

### LINKED ISSUE #3539: [Network] Arping exit code 1 on Ubuntu
I get a lot of these:

```
2018-05-03 14:12:21.883 [DEBUG] [ome.core.thing.internal.ThingManager] - Calling initialize handler for thing 'network:pingdevice:server' at 'org.openhab.binding.network.handler.NetworkHandler@11d3427'.
2018-05-03 14:12:21.914 [DEBUG] [lipse.smarthome.io.net.exec.ExecUtil] - executed commandLine 'arping'
2018-05-03 14:12:21.965 [DEBUG] [lipse.smarthome.io.net.exec.ExecUtil] - exit code '1', result 'ARPing 2.19, by Thomas Habets <thomas@habets.se>
usage: arping [ -0aAbdDeFpPqrRuUv ] [ -w <sec> ] [ -W <sec> ] [ -S <host/ip> ]
              [ -T <host/ip ] [ -s <MAC> ] [ -t <MAC> ] [ -c <count> ]
              [ -C <count> ] [ -i <interface> ] [ -m <type> ] [ -g <group> ]
              [ -V <vlan> ] [ -Q <priority> ] <host/ip/MAC | -B>
For complete usage info, use --help or check the manpage.'
```
on a

Linux supermicro 4.13.0-32-generic #35-Ubuntu SMP Thu Jan 25 09:13:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by davidgraeff**
Thomas Habets arping required "-i" instead of "-I", at least in the latest (2017) 2.19 version.

Fixes #3539

### CODE REVIEW

**Comment by martinvw** [comment]
@davidgraeff  could you include a sign-off :-)

**Comment by davidgraeff** [comment]
I cannot edit a commit in the online editor unfortunately, otherwise I'd had done that already :/

**Comment by martinvw** [comment]
If you state it here, then I will update the commit message when merging

**Comment by davidgraeff** [comment]
Signed-off-by: David Gräff <david.graeff@web.de>

**Pull request merged**
