### PR TITLE
Small tweak so this does not conflict with the WeMo binding.

### PR DESCRIPTION
**Pull request by digitaldan**
Signed-off-by: digitaldan <dan@digitaldan.com>

### CODE REVIEW

**Comment by digitaldan** [comment]
Hey @kaikreuzer , this is not a long term fix, but it should prevent the  WeMo binding from not being able to discover devices, all other upnp operations function fine.   The Cling/Jupnp libraries are not very flexible and it might take me a little while to get the long term fix working.

**Comment by kaikreuzer** [comment]
Thanks @digitaldan. Could you briefly comment on WHY this actually fixes the problem? I see that you are now using port 1900 for sending and receiving. But from #698 I understood that the problem is that you are trying to listen on 1900, which jUPnP does as well and thus there is a conflict. Changing the sending port does not sound to be the right answer to this. So was the assumption incorrect then?

**Comment by digitaldan** [comment]
For finding UPNP devices jupnp sends a discovery message TO port 1900 on the multicast from some random port, devices listening will respond back on the port that the UDP message was sent from (random port).  This is why when you added the emulator binding openhab was able to see itself as a Hue bridge.  Because nothing is advertising local devices, upnp does not have to listen on port 1900 for external systems to send a message to.

I realize that we still need a longer term solution, especially if other bindings would like to advertise ESH services on the network, so this is still my intention.  The Cling/UPNP libraries try to abstract away the details of how services are both advertised and also consumed .   Unfortunately for the very basic thing I need it for (advertising) it is lacking a very simple XML field (baseURL) that there does not seem to be any way to add through this abstraction.  I'm not 100% done trying to get it to work with the version we have, but if that doesn't work out, I will need to submit a fix to the upstream jupnp project to support this.

**Comment by kaikreuzer** [comment]
> upnp does not have to listen on port 1900 for external systems to send a message to.

But external systems also send advertisements per multicast that need to be received by jUPnP. Isn't that done on 1900 as well? But I think several applications can listen on the multicast port simultaneously, so this should not be a problem.

But I still have not understood why this PR makes a change on WeMo. Why does WeMo discovery not work anymore, when the hue emulator SENDS on 1901 instead of 1900?

**Comment by digitaldan** [comment]
> But external systems also send advertisements per multicast that need to be received by jUPnP. Isn't that done on 1900 as well? 

You are correct of course, had not thought of that since ESH was finding my devices by sending disco requests .

>  But I think several applications can listen on the multicast port simultaneously, so this should not be a problem.

Did not know that, I don't get to use multicast often ;-)

> But I still have not understood why this PR makes a change on WeMo. Why does WeMo discovery not work anymore, when the hue emulator SENDS on 1901 instead of 1900?

The Wemo was listening on this port, but its looks like on Feb 25th that changed, so that's no longer valid, see https://github.com/eclipse/smarthome/commit/8ca62f8dab486ce0342bd3c5f3661e202ea6d3a3#diff-78e7c0d8511ad314b1ec625cd2b2202eL57

Since the Wemo binding will no longer be in conflict, I'm not sure if this PR is needed. I believe it's still better than what's merged, but not necessary. I did not need to specify a different port and socket for responses, that was leftover code from when I was working through some device specific issues.

**Comment by digitaldan** [comment]
Closing this, i'll continue the discussion back on #698

**Comment by kaikreuzer** [comment]
Hey, I was just ready to merge it as I agree that it is better than the checked in version.
And since you now explained that it indeed does not fix anything, my questions are also answered.
So why did you close it?

**Comment by DigitalBites** [comment]
@digitaldan @kaikreuzer - for what it's worth I created a patch file based on this pull request and tested it today with the latest version of the wemo plugin and they both appear to be working fine.

**Comment by digitaldan** [comment]
@kaikreuzer see https://github.com/openhab/openhab2-addons/issues/698 , I was a little paranoid about sending back on port 1900 and causing a future issue with jupnp, if you don't thinks thats a valid concern, I will re-open this.

**Comment by kaikreuzer** [comment]
I have no clue whether it is a valid concern or not - so let's just leave it as it is to be on the safe side...

**Pull request closed without merging**
