### PR TITLE
Implemented tests for the Astro Binding

### PR DESCRIPTION
**Pull request by petarnv**
There are 101 tests, that mainly test `org.openhab.binding.astro.handler.AstroThingHandler` and `org.openhab.binding.astro.discovery.AstroDiscoveryService`. The tests are behaving exactly the same way on Windows and MAC.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@gerrieg Could you please check if these tests make sense to you?

**Comment by gerrieg** [comment]
Hmmm ... for me, these tests make relatively little sense relating to astro. The real astro calculations in SunCalc, MoonCalc, ... are not covered.

**Comment by petarnv** [comment]
@gerrieg, aren't these calculations done when a job is executed? I have tests, that verify whether the item state is updated, and in order for the item state to be updated properly, a job needs to be executed, and when a job is executed, the calculations are used (in fact, the classes SunCalc and MoonCalc have more than 90% coverage). I agree that there are no specialized tests for the calculations, but I am testing the general mechanism of the astro binding (e.g. whether the jobs are scheduled for execution, whether the item state is updated, whether the thing status is changed properly for different configurations, whether an astro thing is discovered and some other corner cases). A specialized unit tests, that verify whether the logic in the calculations is correct, can be implemented in another PR.

**Comment by svilenvul** [comment]
See https://github.com/eclipse/smarthome/issues/3213

**Comment by sjka** [comment]
As this hasn't been merged yet I'd propose to wait until the astro binding moved to ESH and then update this one, directing towards ESH too (as tests should stay together with their productive code).

**Comment by kaikreuzer** [comment]
Sorry, @svilenvul, I fully forgot that this PR was still open - but it seems @gerrieg forgot about it as well as his response is still yet outstanding...

**Comment by kaikreuzer** [comment]
@petarnv, As https://github.com/eclipse/smarthome/issues/3233 is merged now, could you port this PR to ESH? Thanks and sorry for the inconvenience!

**Pull request closed without merging**
