### PR TITLE
[zoneminder] Use DS annotations, fix static code analysis findings

### PR DESCRIPTION
**Pull request by wborn**
* Use DS annotations
* Fix static code analysis findings

### CODE REVIEW

**Comment by Mr-Eskildsen** [comment]
They seems to be harmless :-) 
I am currently working on a major rework of the Binding. So I guess it would be important for me to try to embed the changes in the reworked code. I think the merge will handle some of it, but I would need to manually go through the code. It might be helpfull for this process if you can tell me how to perform this static code analysis.

**Comment by wborn** [comment]
> I am currently working on a major rework of the Binding.

Thats great news @Mr-Eskildsen! You might want to create a WIP PR for that to increase visibility. So far I have not added DS annotations and fixed static code analysis for bindings that already have pending major rework PRs.

> It might be helpfull for this process if you can tell me how to perform this static code analysis.

When you build the project with Maven (`mvn clean install`) the result of the static code analysis is available as HTML in: `target/code-analysis/report.html`

**Comment by Mr-Eskildsen** [comment]
> When you build the project with Maven (mvn clean install) the result of the static code analysis is available as HTML in: target/code-analysis/report.html

OK, I will look at that as well. My main problem right now, is time, but I hope to get the last things done in the next month or so. It might be easier to postpone the above change? Else it seems quite harmless, so it isn't important :-)

**Comment by wborn** [comment]
FYI, this PR is waiting for #3583 by @Mr-Eskildsen.

**Comment by wborn** [comment]
Merging this before #3583, see https://github.com/openhab/openhab2-addons/pull/3583#issuecomment-457724707.

**Pull request merged**
