### PR TITLE
updated IDE setup to the new one-4-all IDE

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
Shouldn't we add that file to the distro repo?

**Comment by kaikreuzer** [comment]
Yes, but the official Eclipse Installer currently references exactly this location, so it cannot be changed quickly. Will create a copy and ask the Oomph guys to change the reference then.

**Comment by maggu2810** [comment]
You changed the repo name, so the URL has been changed, too.
openhab2 to openhab2-addons

**Comment by kaikreuzer** [comment]
I thought I did that already?

**Comment by kaikreuzer** [comment]
(also note that the "old" urls are all still valid and working, see https://help.github.com/articles/renaming-a-repository/)

**Comment by maggu2810** [comment]
You have renamed the repo and the URL has been changed. So I believe the Eclipse installer setup reference is already broken.

**Comment by maggu2810** [comment]
Ah okay, I did not know that the old one is still working.

**Comment by kaikreuzer** [comment]
Ok to merge then?

**Comment by maggu2810** [comment]
Do you know if it is possible to change the repo selection of an existing installation? Or is it simpler to start a new one?

**Comment by kaikreuzer** [comment]
Probably easier to start with a new one - you can also then simply import the projects of your old repo.

**Comment by lewie** [comment]
When I use Eclipse Installer to now there are:
- openHAB Development
- openHAB 2 Add-ons
- openHAB 1 Add-ons
- Eclipse SmartHome Extensions
- ESH + OH2 Core Bundles

To a new Workspace and want to get all (OH1 + OH2 + ESH) Bundle-Projects into.
Do I need to select all Github-openHAB-Projects, or are there duplications between?

**Comment by kaikreuzer** [comment]
See step 4 in https://github.com/openhab/openhab-distro/blob/master/docs/sources/development/ide.md.

**Comment by lewie** [comment]
For me, Working Sets have a very understandable breakdown and order now.

Together, over 300 Bundles... wow.

Made a quick comparison,
Found missing Bundles:
- org.openhab.action.dscalarm
- org.openhab.binding.sagercaster
- org.openhab.binding.urtsi
- org.openhab.core.init
- org.openhab.feature.dependencies
- org.openhab.feature.runtime
- org.openhab.io.jetty
- org.openhab.persistence.jdbc
- org.openhab.persistence.jpa
- org.openhab.product.runtime
- org.openhab.repo
- targetplatform

**Comment by kaikreuzer** [comment]
- org.openhab.core.init
- org.openhab.feature.dependencies
- org.openhab.feature.runtime
- org.openhab.io.jetty
- org.openhab.product.runtime
- org.openhab.repo
- targetplatform
- distribution

do not exist anymore.

- targetplatform

has been renamed to "launch"

- org.openhab.binding.sagercaster
- org.openhab.binding.urtsi
- org.openhab.persistence.jdbc
- org.openhab.persistence.jpa

do not compile in the workspace due to problems in their code. @teichsta is informed and will keep track of adding them.

- org.openhab.action.dscalarm

has a dependency to org.openhab.binding.dscalarm, but this project already exists as a 2.0 version and thus cannot be imported twice.

**Comment by lewie** [comment]
Thank You very much Kai,

@teichsta, 
*org.openhab.persistence.jdbc* is missing its dependency libraries.
It needs a first maven run to copy its needed jars to lib folder by maven.
To do this it is used *maven-dependency-plugin* over pom.xml.
Compiling in the workspace works then clean.

I think it's generally more clean to pick libraries from Maven, as it redundant to copy to repository.

Alternatively, we have to copy 
*commons-dbutils-1.6.jar*, 
*HikariCP-2.4.2.jar* and 
*yank-3.1.0.jar* 
to *org.openhab.persistence.jdbc/lib* folder.

**Comment by kaikreuzer** [comment]
> I think it's generally more clean to pick libraries from Maven

I agree that it is, but the way how projects are handled with PDE, this is not easily possible.
This is why we chose for all other projects to include the jars in the repo. Knowing that this isn't nice, but having a working workspace easily is imho more important. And as with the new IDE it is not necessary to run any local Maven build beforehand, I would suggest to add the jars to the lib folder.

**Comment by lewie** [comment]
Yes Kai, I go with you here!

Eclipse PDE with Maven is bugging me for a long time in general.
It is a redundancy definition Problem: Once for Build-path other for Maven Build definitions.
Meanwhile I use *maven-dependency-plugin* for most Projects to "solve" this. Searched very intensive, for a (relative simple) beforehand Scripting/Maven/Eclipse solution to this problem (Build AND compile in workspace per PDE), but a integrated generally applicable solution I have not yet found.

Of course, there must be continuous within a System like openHAB, any death must die.
So I will make a PR/diff for *org.openhab.persistence.jdbc*. ;-)

I must say I'm impressed how clean and simple the entire Eclipse oomph OSGI OH1-OH2-ESH project works from scratch now!

**Comment by kaikreuzer** [comment]
> I must say I'm impressed how clean and simple the entire Eclipse oomph OSGI OH1-OH2-ESH project works from scratch now!

Glad to hear!

**Comment by lewie** [comment]
The PR for jdbc Bundle:
[Adding missing dependency libraries](https://github.com/openhab/openhab/pull/3807)

**Pull request merged**
