### PR TITLE
[tradfri] removed explicit Californium dependency to avoid embedding

### PR DESCRIPTION
**Pull request by kaikreuzer**
depends on https://github.com/openhab/openhab-core/pull/1262

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@J-N-K The changes in openHAB-Core were only just deployed in this seconds (see https://ci.openhab.org/job/openHAB-Core/367/), so I'll trigger a PR build once again now.

**Comment by J-N-K** [comment]
Can you try re-resolving the itest?

**Comment by kaikreuzer** [comment]
Hm, maybe they work once https://github.com/openhab/openhab-core/pull/1263 is build as well...?

**Comment by kaikreuzer** [comment]
Hm, I am a complete noob when it comes to itests...
@J-N-K Do you have any hint what needs to be done to make them run again?

**Comment by wborn** [comment]
Just build `org.openhab.binding.tradfri.tests` using `mvn clean install -DwithResolver` and it will update the bndrun file:

```
diff --git a/itests/org.openhab.binding.tradfri.tests/itest.bndrun b/itests/org.openhab.binding.tradfri.tests/itest.bndrun
index 532d91410a..d3cf45c719 100644
--- a/itests/org.openhab.binding.tradfri.tests/itest.bndrun
+++ b/itests/org.openhab.binding.tradfri.tests/itest.bndrun
@@ -61,12 +61,7 @@ Fragment-Host: org.openhab.binding.tradfri
        org.eclipse.jetty.server;version='[9.4.20,9.4.21)',\
        org.eclipse.jetty.servlet;version='[9.4.20,9.4.21)',\
        org.eclipse.jetty.util;version='[9.4.20,9.4.21)',\
-       org.eclipse.californium.core;version='[2.0,3)',\
-       org.eclipse.californium.core.coap;version='[2.0,3)',\
-       org.eclipse.californium.core.network;version='[2.0,3)',\
-       org.eclipse.californium.elements;version='[2.0,3)',\
-       org.eclipse.californium.elements.exception;version='[2.0,3)',\
-       org.eclipse.californium.scandium;version='[2.0,3)',\
-       org.eclipse.californium.scandium.config;version='[2.0,3)',\
-       org.eclipse.californium.scandium.dtls.pskstore;version='[2.0,3)',\
-       slf4j.simple;version='[1.7.21,1.7.22)'
+       ch.qos.logback.classic;version='[1.2.3,1.2.4)',\
+       org.eclipse.californium.core;version='[2.0.0,2.0.1)',\
+       org.eclipse.californium.element-connector;version='[2.0.0,2.0.1)',\
+       org.eclipse.californium.scandium;version='[2.0.0,2.0.1)'
```

You might also want to squash the commits because the Travis build may be flawed because it only build the itests project if that's the only Maven project updated in your commit.

**Comment by kaikreuzer** [comment]
Thanks for the hints @wborn! Unfortunately, Travis is still red :-(

**Comment by wborn** [comment]
> Travis is still red

It builds fine locally when I do a full build.

I can reproduce the Travis issue if I wipe my local Maven repo, clean my workspace and only build the Tradfri bundle and itests project. It works after I also build the BOMs.

So I think we should just ignore Travis opinion about this. :wink:

**Comment by kaikreuzer** [comment]
> So I think we should just ignore Travis opinion about this.

Sounds like a decent strategy ;-)

**Pull request merged**
