### PR TITLE
AVMFRITZ: Added Support for Comet DECT Thermostat

### PR DESCRIPTION
**Pull request by Radioaktivman**
Added 1 Thing for Comet DECT Thermostat.
Added 2 new channels dedicated for controlling the Comet DECT Thermostat.
Added 1 Thermostate model.class
Modifided existing binding components to support Comet DECT Thermostat.

Please be gentle its my first pull request ever!

### CODE REVIEW

**Comment by cweitkamp** [comment]
Thanks for your work. Please note that there is already a PR [#1815](https://github.com/openhab/openhab2-addons/pull/1815) in which this  feature is added.

**Comment by Radioaktivman** [comment]
Christoph , thank you for your reply. 
I took a look into PR #1815. Great work!! 
However, I implmented a switch which allows to turn the thermostat off  (tsoll=253) and restores the last know value of tsoll to restore it whenn shicht is turn off again.. Can you merge this functionallity into your code?
I wanna be able to turn the thermostat of e.g. when openning the windows.

Futhermore, may FritzBox 6490 does not return e.g. the battery info as XML. That feature is also not described in the AVM Home Automation API (https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AHA-HTTP-Interface.pdf). 
Where did you pull this information from? Does your Box support it?


BR,

**Comment by martinvw** [comment]
While this become obsulete if #1815 is merged?

**Comment by martinvw** [comment]
If it's still relevant please reopen.

**Pull request closed without merging**
