### PR TITLE
[enocean] Fix A5-38-08 Dimmer reset to 0

### LINKED ISSUE #5608: [enocean] A5-38-08 Dimmer reset to 0
## Expected Behavior
The internal dimmer state should represent the real state.

## Current Behavior
If the dimmer is set to a value > 0 (by command or externally), the internal state is set to 0 immediately.

## Possible Solution
The problem is in the function convertToStateImpl(), the line
`if (!getBit(0,0))`
will never branch into the else, because getBit(0,0) will be false always.
Replace the line with
`if(!getBit(getDB_0(), 0))`
this fixes it.

## Steps to Reproduce (for Bugs)
Turn on an EnOcean Dimmer (BasicUI,...), the displayed slider will be reset to zero immediately.

## Your Environment
* Version used: openhab 2.4 with current enocean binding master version

I will send a pull request.

### PR DESCRIPTION
**Pull request by henglert**
Fix the getbit parameter 0, so that internal dimmer state resembles the external state.

As described in issue #5608, the getbit function will always return false.

Fixes #5608

### CODE REVIEW

**Comment by henglert** [comment]
I guess the original author wanted to check if Bit 0 of DB0 was set to  0 (Switching Command off) to set the internal value to 0 percent. Your referenced code from the blinds is handling bit 1 (store last value).
Nevertheless a getBit(0,0) will always return false, so it is obviously a bug.

**Comment by henglert** [comment]
Sorry, there's the same bug on line 113 which also has to be replaced.

**Comment by henglert** [comment]
I don't get it. Can you please help me to get this "pullapprove Signed-off-by needed on 1 commit" corrected? Do I have to go back to fdd55c9 and do the git commit --amend -s? And then a git push -f? I can't get rid of the red x in my first commit.

**Comment by J-N-K** [comment]
Manually verified all commits contain sign-off.

**Comment by J-N-K** [comment]
Jenkins fails unrelated with time-out

**Pull request merged**
