### PR TITLE
[Onkyo] Fix various issues

### PR DESCRIPTION
**Pull request by marcelrv**
Fixes various issues for Onkyo binding
* Fix lookup of listening modes & audio sources below #10
* Adds several missing listening modes
* Adds several missing sources
* Fix Exceptions statusUpdateReceived in case of N/A
* Fix issue when looking up sources for zone2

Signed-off-by: Marcel Verpaalen <marcel@verpaalen.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@pail23, Could you please review?

**Comment by hfanieng** [comment]
> Fix Exceptions statusUpdateReceived in case of N/A

Does this mean i can now use the binding even when my receiver is switched to standby without flooding the log?

**Comment by NorbertHD** [comment]
@hfanieng 
No, because the Onkyo sends LMDN/A when in standby and there is a bug in OnkyoHandler.java.
```
                    case LISTEN_MODE_SET: 
                         String listenModeStr = data.substring(3, 5); 
                         // update only when listen mode is supported 
                         if (listenModeStr != "N/") { 
                             int listenMode = Integer.parseInt(listenModeStr, 16); 
                             updateState(CHANNEL_LISTENMODE, new DecimalType(listenMode)); 
                         } 
                         break; 
```
  if (listenModeStr != "N/") 
should be
  if ( ! listenModeStr.contentEquals("N/"))

**Comment by hfanieng** [comment]
> No, because the Onkyo sends LMDN/A when in standby and there is a bug in OnkyoHandler.java.

Thank you for pointing me on that @NorbertHD 👍  If this bug is fixed the Onkyo-Binding is one thing i would like to test whit my hardware and oH2.

**Comment by marcelrv** [comment]
@NorbertHD also included the fix you proposed.

**Comment by pail23** [comment]
@marcelrv Thanks for the fixes! The changes lgtm. From my point of view this ready to be merged.

**Comment by hfanieng** [comment]
@marcelrv Thanks for the quick reaction!

**Comment by kaikreuzer** [comment]
Thank you all!

**Pull request merged**
