### PR TITLE
[lutron] Add support for Palladiom keypads

### PR DESCRIPTION
**Pull request by bobadair**
This PR adds support for Lutron Palladiom keypads used in HomeWorks QS systems. It also contains some minor improvements to code recently added for keypad model discovery in LutronDeviceDiscoveryService.java and KeypadConfig.java.

### CODE REVIEW

**Comment by bobadair** [comment]
Is it possible to get this one merged before the M5 build? I have an upcoming PR which will depend on this that I want to try to get in to 2.5.0.

**Comment by Hilbrand** [comment]
The next release will be the actual release. There are no plans for M5. This can be merged once the jenkins run is finished.

**Comment by bobadair** [comment]
Thanks @Hilbrand! That Jenkins run started 12 days ago, though, so I don't think it's going to finish. Should I try to trigger a rebuild?

**Comment by bobadair** [comment]
Ok. I triggered a rebuild and the Jenkins run succeeded this time.

**Pull request merged**
