### PR TITLE
[RFXCom] Some sub-types were missing from the thing/*.xml files

### PR DESCRIPTION
**Pull request by martinvw**
Some sub-types were missing from the thing/*.xml files, I made them compatible as far as I found inconsistencies.

### CODE REVIEW

**Comment by martinvw** [comment]
@Jamstah a simple one this time, can you read along?

**Comment by Jamstah** [comment]
LGTM, all matches up with the classes.

**Comment by kaikreuzer** [comment]
Many thanks!
@Jamstah FYI: I added you to the team, so you should be able to also use the github review feature from now on (and provide an "official" approval that way on PRs).

**Comment by Jamstah** [comment]
Great, thanks.

**Pull request merged**
