### PR TITLE
Exported the pcap package in the AmazonDashButton binding.

### PR DESCRIPTION
**Pull request by VelinYordanov**
Currently the public API is unusable, because in AmazonDashButtonHandler method onPcapNetworkInterfaceAdded and onPcapNetworkInterfaceRemoved take internal type PcapNetworkInterfaceWrapper as parameter.

See openhab/static-code-analysis#210

Signed-off-by: VelinYordanov <velin.iordanov@gmail.com>

### CODE REVIEW

**Comment by wborn** [comment]
Can you fix the merge conflicts @VelinYordanov? 

If the public API of this binding is unused you could also stop exporting these packages and move them to internal. See https://github.com/eclipse/smarthome/pull/5434.

**Comment by cweitkamp** [comment]
@VelinYordanov are you still around? Would be nice if you can update this PR. Or shall we take care of it?

**Comment by martinvw** [comment]
The comment was not here, but because of this pr we had (on some other pr or issue maybe...?) some discussion whether we should expose more or less.

**Comment by cweitkamp** [comment]
@martinvw IIRC we agreed on no exports anymore if the binding is not meant to be extended by further bundles (see eclipse/smarthome/pull/5434).

**Comment by martinvw** [comment]
Great I agree with hiding more

**Pull request merged**
