### PR TITLE
[amazonechocontrol] Amazon Devices - serial number location

### PR DESCRIPTION
**Pull request by bredmich**
Added an information about where to find the serial number besides the Alexa App.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@mgeramb Could you please review and comment whether this is correct? Is the servlet showing the  serial number as well, so the Alexa app is not needed?

**Comment by bredmich** [comment]
Here´s a screenshot of my website (http://192.168.2.11:8080/amazonechocontrol/Michael) with randomized Serialnumbers.
bildschirmfoto 2018-07-17 um 22 48 12

**Comment by kaikreuzer** [comment]
Thanks, that looks convincing. I'll nonetheless give @mgeramb a chance to comment before merging.

**Comment by mgeramb** [comment]
Yes, its perfect! It was one of my last change to show this overview. @bredmich thanks!

**Pull request merged**
