### PR TITLE
[infrastructure] migrate airquality and airvisualnode to bnd

### PR DESCRIPTION
**Pull request by J-N-K**
Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by J-N-K** [comment]
@3cky, I can't request review from you. Could you have a look? Thanks.

**Comment by 3cky** [comment]
LGTM.

**Comment by cweitkamp** [comment]
@kaikreuzer Can you please add @3cky to the team? Thanks.

**Comment by kaikreuzer** [comment]
> @kaikreuzer Can you please add @3cky to the team? Thanks.

Sure, done.

**Comment by 3cky** [comment]
@kaikreuzer Thank you!

**Pull request merged**
