### PR TITLE
Remove ZWave binding

### PR DESCRIPTION
**Pull request by cdjackson**
Removes the ZWave and ZWave-Test bundles from the repository. Updates the POM and adds instructions on importing the binding into the IDE from the new repository.

Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
So I am the one to push the nuke button to remove 20,000 lines of code here? Ok, let's go!

**Comment by kgoderis** [comment]
Err.... Chris, where is the new repo ?


K

**Comment by cdjackson** [comment]
It’s in openhab/org.openhab.binding.zwave.

**Comment by thopiekar** [comment]
First moment when I saw this: :scream: 
Will the addon still appear in the list of extensions? (So no need to add a separate repo url somewhere? Updating userdata manually, etc?)

**Comment by kaikreuzer** [comment]
Nothing will change for the distro, no worries!

**Comment by cdjackson** [comment]
Nothing will change -:

https://community.openhab.org/t/openhab-2-zwave-repository-has-moved-to-a-new-home/12828 <https://community.openhab.org/t/openhab-2-zwave-repository-has-moved-to-a-new-home/12828>

**Pull request merged**
