### PR TITLE
[sensibosky][WIP] SensiboSky Binding initial contribution

### LINKED ISSUE #2911: Add Sensibo A/C Controller Binding
I'd like to start working on a new binding for the [Sensibo](https://sensibo.com) family of air conditioner controllers.

## Expected Behavior
Allow OpenHAB to control Sensibo systems.

## Current Behavior
Currently using rules-based scripts: https://github.com/michaeldavie/Sensibo-and-Openhab-2

### PR DESCRIPTION
**Pull request by Zodiarc**
A binding for the Sensibo Sky Smart AC Controller has been added. It provides possibilities to read and set A/C states (things like geofencing, scheduling, etc. are not supported yet).

Build URL: https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.sensibosky

Current TODOs that I'm aware of:
- <s>Signing</s> 
- Documentation
- Coding guidelines check
- Dynamic configuration description if possible [up next]
- Code cleanup

Fixes #2911

### CODE REVIEW

**Comment by Zodiarc** [comment]
I noticed that the jenkins build skipped the sensibo binding entirely. It didn't even try. What did I miss?

**Comment by Hilbrand** [comment]
You need to add your project to the main bindings pom (and add your binding to the feature.xml)
Btw. don't use `Float` but `Double` to avoid conversion problems.

**Comment by Zodiarc** [comment]
Sorry for the mass add. i screwed up

**Comment by Hilbrand** [comment]
Don't forget to sign-off your commits

And if the variable name is the same as the json property don't add `SerializedName` annotations.
Also don't log to `error` it's reserved for system wide problems. IOExceptions should probably be logged to debug if it's a temporary problem due to network connections or so.

**Comment by Zodiarc** [comment]
What is wrong with the CI? I finally got the binding to build just for it to fail for no apparent reason.

**Comment by martinvw** [comment]
@Zodiarc is is still WIP or can I queue it in our (unfortunately long) queue for a review.

**Comment by martinvw** [comment]
Closing to trigger the build

**Comment by Zodiarc** [comment]
It's still WIP. I'm currently making no progress because I'm trying to figure out how dynamic state descriptors work

**Comment by Zodiarc** [comment]
I still didn't make any progress on my problem. It is described [here](https://community.openhab.org/t/is-there-a-proper-documentation-on-dynamic-state-options/68985). If anyone reading this could give me a lead would be really helpful since it's becoming really frustrating.

**Comment by Zodiarc** [comment]
I won´t develop this binding further due to lack of time and some features simply not wanting to work although implementation is correct.

**Comment by claell** [comment]
Sad to see this closed in such a rather completed state according to the TODOs from the first post.

If you are not too frustrated now and still have some time, maybe there can be still some way to get it completed with some help?

Ping to @cweitkamp so you are aware of this PR, since you tried to help in the forum thread.

**Comment by Zodiarc** [comment]
Well since the binding is working, but has not dynamic state descriptions, you can still review and merge it if the requirements are met.

**Comment by claell** [comment]
Alright. So what do the others think about this? Reopen?

**Comment by cweitkamp** [comment]
@claell Thanks for the pointer. Of course I am willing to help. Sry for my late reply here.

I did some work on this binding. I migrated it to the new build system, added some annotations stuff, cleaned up the code and made it build again (see my work [here](https://github.com/openhab/openhab2-addons/compare/master...cweitkamp:pr-4931)). I will prepare a new PR once we got a final version.

Two things I cannot do:

1. The documentation. @Zodiarc It would be nice if you can write some words about it.
2. Testing. Who can help?

**Comment by Zodiarc** [comment]
In what form should I provide the documentation?

**Comment by claell** [comment]
Great to hear that, thanks for you work @cweitkamp.

@Zodiarc I guess the main part is the Readme, see the link in the post above. An easy way is probably to create a PR for that linked file.

**Comment by Zodiarc** [comment]
Alright. I'll make the documentation in the next few days

**Comment by cweitkamp** [comment]
@Zodiarc Great. Thank you very much.

**Comment by Zodiarc** [comment]
I added documentation to my fork.

**Comment by cweitkamp** [comment]
@Zodiarc Thank you.

ftr: https://github.com/Zodiarc/openhab2-addons/commit/8760947612ca06fd8574792a96c359a39b562147

**Pull request closed without merging**
