### PR TITLE
[mqtt] Bugfix subscribe after restart / initialisation (#6828)

### PR DESCRIPTION
**Pull request by pavax**
see Issue: https://github.com/eclipse/smarthome/issues/6828

### CODE REVIEW

**Comment by davidgraeff** [comment]
It would be perfect if you could squash your commits into one:
 `git rebase -i HEAD~10` and then follow the instructions. Then sign the one commit with `git commit --amend -s`. Then do a `git push -f` (force).

**Comment by euphi** [comment]
Is this fix already in openhab-distro 2.5.M1 ?

**Comment by davidgraeff** [comment]
Nope

**Comment by euphi** [comment]
Mhm. Current nightly does not start  at all on arm (orangepi) :-(
Is there any way to get a jar file of the MQTT binding for a 2.5.M1 openhab?

**Pull request merged**
