### PR TITLE
Roku Binding

### PR DESCRIPTION
**Pull request by jpete7683**
There is still refactoring to be done but this provides discovery and basic functions of roku streaming boxes within the openhab2 framework.  I will continue to make changes going forward and address issues as they are discovered but this should be a good start to basic actions and information that users would want to to perform on their roku streaming boxes.

Signed-off-by: Jarod Peters jpete7683@users.noreply.github.com

### CODE REVIEW

**Comment by jpete7683** [comment]
@watou was this the correct way of doing it as you had stated in the other PR?

**Comment by watou** [comment]
@jpete7683 The CI build failure wasn't due to your PR, afaik.  You probably want to add your binding to the parent POM so it eventually gets built, but otherwise, looks like you're on the right track!  Now you can update your master branch and rebase your PR branch as needed until it's merged.

**Comment by jpete7683** [comment]
@watou I am not following the parent POM comment.  Where is that POM found so that I can add it?  All I have checked out at the moment is the OH2 add-ons

**Comment by watou** [comment]
> Where is that POM found so that I can add it?

Your PR should modify [this file](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/pom.xml) to add your binding to the build.

**Comment by kaikreuzer** [comment]
Hi @jpete7683,

Some very first comments before I go into a detailed code review:
- Please check your code against [our guidelines](http://docs.openhab.org/developers/development/guidelines.html). I can e.g. see issues regarding A.2, A.3, A.4, A.5 and B.6
- add a README.md as explained [here](https://www.eclipse.org/smarthome/documentation/development/bindings/docs.html)
- remove the file `ESH-INF/i18n/roku_xx_XX.properties`
- You should not implement your own SSDP discovery, but rather [register a UPnPDiscoveryParticipant](https://www.eclipse.org/smarthome/documentation/development/bindings/discovery-services.html#upnp-discovery) instead.
- Also add your binding to https://github.com/openhab/openhab2-addons/blob/master/features/openhab-addons/src/main/feature/feature.xml

Thanks!

**Comment by jpete7683** [comment]
Closing this pull request as I have abandoned roku's in my home and time did not allow for me to put anymore work into this binding.  Someone is more than welcome to take it over and rework the items that @kaikreuzer pointed out.

**Comment by kaikreuzer** [comment]
Pity to hear that, but thanks for letting us know, @jpete7683!

**Comment by sdwilsh** [comment]
@kaikreuzer, I'm interested in picking this up and finishing it up and addressing your review comments.

**Comment by kaikreuzer** [comment]
Hey, @sdwilsh, sounds wonderful! Thanks and have fun :-)

**Comment by sdwilsh** [comment]
Hey @jpete7683, do you sign-off on me using your code as a starting point (I basically want to put the `Signed-off-by: Jarod Peters <support@instruodev.com> (github: jpete7683)` in the commit message of your work.

**Comment by jpete7683** [comment]
@sdwilsh absolutely!  The code is messy and if you want to rework it all that is great.  If there is anything you keep that was of the original work I wouldn't mind keeping my name as a contributor on that code but if you would rather remove my name that is fine too as well!  Glad someone has found the time to push this binding forward.

**Comment by bulletprooffool** [comment]
Hi guys - has anyone managed to compile a working binding? 
Even if it’s just a jar file I can add (old school OH1 style)?

Thanks

**Pull request closed without merging**
