### PR TITLE
Corrected some missing / outdated copyright notices

### PR DESCRIPTION
**Pull request by martinvw**
Signed-off-by: Martin van Wingerden <martinvw@mtin.nl>

### CODE REVIEW

**Comment by martinvw** [comment]
Thanks @mention-bot I think @kaikreuzer would also do ;-)

**Comment by kaikreuzer** [comment]
Interesting, I thought we had already covered them all through an earlier PR...
@svilenvul I had this effect a few times in the past: The SAT failed on stuff that had already passed on earlier occasions (and which clearly shouldn't have passed before). Any idea why this could be the case?

**Comment by martinvw** [comment]
I think that in this case it's caused by PR's being merged containing incorrect headers.

**Comment by davidgraeff** [comment]
Sry for the milight add-on being a big part of this PR. The original milight PR was made in 2016 and only accepted in 2017, so the reviewers had already done the boring checks (like checking the copyright headers) and concentrated on the logic in the later review process I guess.

**Pull request merged**
