### PR TITLE
[gardena] Fixed null state handling

### PR DESCRIPTION
**Pull request by gerrieg**
Signed-off-by: Gerhard Riegler <gerhard.riegler@gmail.com>

### CODE REVIEW

**Comment by gerrieg** [comment]
Sometimes channels have a value and then no value. Currently they have a wrong state, because they don't get updated with null. E.g if the date is not in a valid range (< 02.01.1970), the previous value (valid date) is still in the channel.

**Comment by kaikreuzer** [comment]
> Currently they have a wrong state

Can you give an example? Which date of which channel is for sure wrong?

**Comment by gerrieg** [comment]
mower#timestamp_next_start. If the mower is cutting, the value < 02.01.1970 and therefore the channel should be updated with null.

**Comment by kaikreuzer** [comment]
To cover that case, I would expect an `else` branch in [this line](https://github.com/openhab/openhab2-addons/pull/3548/files#diff-c1d89ee1650a72b0e60638bad0ca310eL165).

Line 171 should definitely not cause any state update being sent as it occurs, if the channel does not exist at all.

For situations, where you want to state that currently there is no state for a channel at all, you should send `UnDefType.NULL` (while `UnDefType.UNDEF` states that the current state cannot be expressed in the item type).

**Comment by gerrieg** [comment]
You are right, line 171 is definitely wrong. Sorry, i overlooked that.

**Pull request merged**
