### PR TITLE
Update harmony-java-client and its dependencies

### LINKED ISSUE #1222: Harmony Hub binding exception
I'm getting the following exception periodicallay; Don't know what the problem is.

``` java
16:17:25.139 [WARN ] [rg.jivesoftware.smack.XMPPConnection] - Connection closed with error
java.io.EOFException: no more data available - expected end tag </stream:stream> to close start tag <stream:stream> from line 1, parser stopped on END_TAG seen ...<![CDATA[result=-1]]></oa></iq>... @1:640
        at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:3035)[197:org.openhab.binding.harmonyhub:2.0.0.201609062002]
        at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)[197:org.openhab.binding.harmonyhub:2.0.0.201609062002]
        at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1144)[197:org.openhab.binding.harmonyhub:2.0.0.201609062002]
        at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)[197:org.openhab.binding.harmonyhub:2.0.0.201609062002]
        at org.jivesoftware.smack.tcp.PacketReader.parsePackets(PacketReader.java:279)[197:org.openhab.binding.harmonyhub:2.0.0.201609062002]
        at org.jivesoftware.smack.tcp.PacketReader.access$000(PacketReader.java:47)[197:org.openhab.binding.harmonyhub:2.0.0.201609062002]
        at org.jivesoftware.smack.tcp.PacketReader$1.run(PacketReader.java:81)[197:org.openhab.binding.harmonyhub:2.0.0.201609062002]
```
##

### PR DESCRIPTION
**Pull request by wborn**
@kaikreuzer this PR fixes #1222 by updating the Harmony Binding to use a harmony-java-client using Smack 4.2.0 for XMPP.

I've sent these changes upstream in https://github.com/tuck182/harmony-java-client/pull/16.

The harmony-java-client JAR in this PR was built with https://github.com/wborn/harmony-java-client/commit/54850a25a9f660aa016ca5248efd40fb8abd1e5d.

When this PR is merged, @digitaldan can proceed with reworking the hub discovery/authentication logic.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks @wborn, I assume that all the new additional jxmpp libs are required by the new version of smack - it doesn't make the dependencies of this binding any better, it is really pretty fat for embedded use... Well, what to do 🙄

**Comment by wborn** [comment]
Thanks for merging this @kaikreuzer .

Yes there are indeed a lot of new libraries. The [JXMPP libs are new](https://github.com/igniterealtime/Smack/wiki/Smack-4.2-Readme-and-Upgrade-Guide#use-jxmpps-jid-types) and required. Smack was also modified so it can be used on Android. This introduced 3 additional Java specific libs.

Most fat is caused by the Guava and Jackson libs (4.1MB of the total 4.9MB).

I did remove the unused RESTY dependency. 

We could perhaps also remove `smack-debug-4.2.0.jar` but I don't know if @digitaldan uses it? It provides a [GUI](https://docs.jivesoftware.com/smack/latest/documentation/debugging.html) when you set `-Dsmack.debugEnabled=true`. Since it was already there I left it in. It's only 69kB. I did use it while upgrading Smack but I don't think it should end up in production.

**Comment by digitaldan** [comment]
I don't use it, I think I assumed the harmony library needed, but if thats not the case I would remove.

**Comment by digitaldan** [comment]
@wborn I am having an issue with the refactor of the underlying library I think, when sending button commands to a device the harmony library times out waiting for a response from the hub.  I have tried multiple hubs and also used just the command line version of the harmony client.  Note that current activity and pings all still work, just button presses do not.

**Comment by wborn** [comment]
@digitaldan After some testing I also see this behavior on my hubs. I'll try to find a fix for this.

**Comment by wborn** [comment]
@digitaldan Maybe you want to help testing the fix with https://github.com/wborn/harmony-java-client/commit/f5161a195de49571f00099c4c56ad0e45ca7908b I just made? It seems to work OK with the command line. Haven't tested it within OH yet. There's a precompiled [harmony-java-client-1.1.1.jar](http://www.maindrain.net/github/harmony-java-client-1.1.1.jar) I'll be testing with OH later.

**Comment by digitaldan** [comment]
@wborn your quick!   The command line version is working for me now, nice job.

**Pull request merged**
