### PR TITLE
[foxtrot] New binding Foxtrot - initial Contribution #3346

### PR DESCRIPTION
**Pull request by radovansninsky**
This is initial version of new binding for Tecomat Foxtrot system.

More about binding is in binding's README file.

The binding has no dependency to external libraries.

### CODE REVIEW

**Comment by radovansninsky** [comment]
Could someone review this PR. I'm waiting for any remarks or suggestions. Or is something else needed from me?

**Comment by martinvw** [comment]
Thanks for your PR! 

As a start you could get your commits sorted out, I think that easiest will be copying your new binding directory somewhere else. Delete (or rename) your local branch (not the remote). Create a new branch with the same name based on the current `master`.

Then add your binding in a single signed off commit (to certify that you wrote it or otherwise have the right to pass it on as an open-source), see http://docs.openhab.org/developers/contributing/contributing.html#sign-your-work

Next time (when working on openHAB) do not `merge `in the master but `rebase` instead.

Please also check:

http://docs.openhab.org/developers/development/bindings.html
http://docs.openhab.org/developers/development/guidelines.html

And it we would be great if you could also review the report of [the Static code analysis](https://docs.openhab.org/developers/development/bindings.html#static-code-analysis), this also saves me some time while reviewing.

**Comment by triller-telekom** [comment]
Thank you for your contribution!

I just had a look at how you modeled the things for your binding.

One question that came to my mind for a better understanding of how the foxtrot device works is: The device itself runs a network service on port 5010 and you are connecting to it directly with no other device involved, right?

You have modeled the device as a `bridge` and then created `things` like `bool`, `text`, `number`, `switch` etc. These are not `things` in the Eclipse SmartHome/openHAB world. Things in the ESH world are physical devices, like your CP-1000 device. This device then offers **functions** which should be provided by `channels`.

So what I would suggest is that you model your `CP-1000` device as a `thing` which is extensible by `channels`.

For a reference how things can be extended by channels, please see our documentation: https://www.eclipse.org/smarthome/documentation/development/bindings/thing-handler.html#updating-the-thing-structure

As an example how this is used there is the [bluetooth binding](https://github.com/eclipse/smarthome/blob/bb57a140d9e1979d3b4f055f8210dada73cd2f3a/extensions/binding/org.eclipse.smarthome.binding.bluetooth/src/main/java/org/eclipse/smarthome/binding/bluetooth/ConnectedBluetoothHandler.java#L233-L237) or a thing definition in our testbinding the [magic binding](https://github.com/eclipse/smarthome/blob/master/bundles/test/org.eclipse.smarthome.magic/ESH-INF/thing/thing-types.xml#L6).

Each channel can have a config-description which then holds your variable name to be controlled on the server side.

Does that makes sense to you? If you have any questions, feel free to ask!

**Comment by triller-telekom** [comment]
@martinvw @kaikreuzer Can you please add an awaiting feedback label on this PR?

**Comment by triller-telekom** [comment]
@radovansninsky May I ask why you have closed this PR and deleted you branch? Are you planing to create a new PR? Would be a pity if we would loose your contribution!

**Comment by radovansninsky** [comment]
@triller-telekom I'm really sorry for mess I produced, but I'm not very familiar with git/github concept, I'm more Subversion guy.  @martinvw wrote that I have to sort out my commits, but I'm really lost in all that master origin upstream branches stuff. So friend of mine advice me to somehow rollback all my changes and start it again. But we didn't realize, that this ends in closing this PR.

So what to do now? It's possible to somehow re-open this PR? Or should I create a new one?

**Comment by triller-telekom** [comment]
@radovansninsky Just a friendly ping :) Do you want to reopen this PR? Are the answers in my previous post helpful? Please give us an update, even if it is "I do not have time for this right now". Thanks.

**Comment by radovansninsky** [comment]
@triller-telekom Hi, I've take a briefly look to your advises regarding how to remodel Tecomat PLC and its whole network of attached actors and sensors. But I don't get it at first look. So I need to make a second and more detailed look, but yes right know I don't have enough time. I hope it will be better soon.

**Comment by triller-telekom** [comment]
@radovansninsky Thanks for the update! We are looking forward to see your contribution once you have time to take care of it.

**Pull request closed without merging**
