### PR TITLE
Updated binding xml schema locations to openhab

### PR DESCRIPTION
**Pull request by Hilbrand**
With changes from esh to openhab schema location should change too.
With website pr https://github.com/openhab/website/pull/157 the schemas are available on the openhab website.

### CODE REVIEW

**Comment by wborn** [comment]
SAT fails according to the [Jenkins logging](https://ci.openhab.org/job/PR-openHAB2-Addons/12780/console) with these changes @Hilbrand :

```
[INFO] --- sat-plugin:0.5.0:report (default) @ org.openhab.binding.airquality ---
[INFO] Individual report appended to summary report.
[ERROR] Code Analysis Tool has found: 
 2 error(s)! 
 0 warning(s) 
 1 info(s)
[ERROR] .binding.airquality/ESH-INF/binding/binding.xml:[5]
Cannot find the declaration of element binding:binding.
[ERROR] .binding.airquality/ESH-INF/thing/thing-types.xml:[4]
Cannot find the declaration of element thing:thing-descriptions.
```

**Comment by Hilbrand** [comment]
Ah. SAT has a check for it. So if this will be merged (or even before) we need a new sat version (would help with the about.html error message also. For the change here I've created a pr in sat:
https://github.com/openhab/static-code-analysis/pull/340

**Comment by kaikreuzer** [comment]
> would help with the about.html error message also

This is already addressed with https://github.com/openhab/static-code-analysis/releases/tag/0.6.0

**Comment by Hilbrand** [comment]
But 0.6 isn't yet enabled for the openhab2-core? I still see it refers to version 0.5.

**Comment by kaikreuzer** [comment]
Correct, I did the release, fell sick and didn't try to update the builds...

**Comment by wborn** [comment]
:exclamation: When merging this PR, it probably needs to be updated so it also updates any new files that were added in PRs that have been merged in the mean time.

**Comment by davidgraeff** [comment]
Because with every buildsystem PR the conflicting files will grow, what is the plan for this PR?

**Comment by Hilbrand** [comment]
I guess we need to set the SAT version to 0.61 first and if that is done than I'll update this pr and coordinate with other maintainers to merge this.

**Comment by wborn** [comment]
There's already a SAT 0.6.1. :smile: I'm using it in https://github.com/openhab/openhab-core/pull/626.

**Comment by kaikreuzer** [comment]
Oh oh, this seems to ask for a rebase...

**Comment by kaikreuzer** [comment]
> With website pr openhab/website#157 the schemas are available on the openhab website.

Are they? I get a 404 when trying to access https://openhab.org/schemas/thing-description/v1.0.0

**Comment by Hilbrand** [comment]
@kaikreuzer You're looking at the namespace that doesn't link to a page, see old links: http://eclipse.org/smarthome/schemas/binding/v1.0.0
Only the xsd links to the real page. For example: https://openhab.org/schemas/binding-1.0.0.xsd

**Comment by kaikreuzer** [comment]
Ah, you're right, sorry!
Then all it needs here is a rebase 😄.

**Comment by kaikreuzer** [comment]
Thanks - now we only have to wait for https://github.com/openhab/openhab-core/pull/626 to be merged, I guess.

**Comment by kaikreuzer** [comment]
https://github.com/openhab/openhab-core/pull/626 has been merged, but it seems @Hilbrand need to rebase once more - just merge it afterwards yourself immediately!

**Comment by wborn** [comment]
Note that the tycho projects use another parent in openhab-core which has its [own sat.version](https://github.com/openhab/openhab-core/blob/master/features/p2/poms/pom.xml#L51).

**Comment by Hilbrand** [comment]
@wborn so we need to update that file too, I presume?

**Comment by wborn** [comment]
Yes that is correct.

**Comment by J-N-K** [comment]
Aside from the merge conflicts: This is ready to be merged, right?

**Comment by Hilbrand** [comment]
@J-N-K  I think it first need an update in core to set the sat to 0.6.1 in order to correctly check the schema's

**Comment by J-N-K** [comment]
https://github.com/openhab/openhab-core/pull/626 is merged, so it should be ok.

**Comment by wborn** [comment]
Please read my comments about also updating the Tycho parent project POM. Because OHC only uses bnd it wasn't required for reenabling SAT there.

**Comment by J-N-K** [comment]
Jenkins fails due to wrong SAT version.

**Comment by davidgraeff** [comment]
That need to be done a few times more with every new-binding PR we accept and migration PR that is still in the queue. But it's a good start.

**Comment by cweitkamp** [comment]
@Hilbrand Did you create a script for these changes too? Or do you have a shell command for it?

**Comment by Hilbrand** [comment]
I used these 2 commands:
```
find . -name "*.xml" -exec sed -i "s|http://eclipse.org/smarthome/schemas|https://openhab.org/schemas|g" {} \;
find . -name "*.awk" -exec sed -i "s|http://eclipse.org/smarthome/schemas|https://openhab.org/schemas|g" {} \;
```
And a check command:
```
grep -r "http://eclipse.org/smarthome"
```

**Comment by cweitkamp** [comment]
:+1: Thanks. That will help.

**Pull request merged**
