### PR TITLE
KNX 2.0 : WIP : Refactored and Rebased for Java 8

### PR DESCRIPTION
**Pull request by kgoderis**
Continuation of https://github.com/openhab/openhab2-addons/pull/1438

Signed-off-by: Karel Goderis <karel.goderis@me.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@kgoderis I would prefer if you'd update the existing PRs instead of closing them and opening new ones - we would keep all discussions at a single place and don't spread it over different locations (and no, Github should not screw up any comments in that case - definitely not the "main" comments which are not on single code lines).

I must admit that I didn't follow every single detail of the discussion in the past weeks, but I have the feeling that not many other people managed to do so either.
I would strongly urge everyone to come back to my suggestion from https://github.com/openhab/openhab2-addons/pull/21#issuecomment-258159717 and really try to reduce the scope to have a viable replacement of the KNX1 binding for a start. Stuff like KNX project imports are way beyond this scope and I think that should be a second step.
Let's use the modularity of OSGi to also design the KNX binding in a modular fashion:
- Have a "basic KNX binding" that supports "meaningful" channel types as we had discussed long ago already. This will imho cover the needs of 95% of our users.
- Have additional "expert KNX" extensions that would bring additional thing types and channel types and the according handler implementations for them; here we could e.g. handle rare use cases and e.g. KNX project imports (assuming that they are lacking the meta-data to do a "good" mapping, so we will end up with "awkwardly modelled" Things here).

Going this path would allow us to get to terms with an initial KNX 2 binding soon and keep our code base clean and separated so that it is better readable and maintainable in future. Would you agree?

**Comment by sjka** [comment]
When reflecting the recent discussions I agree that the is no natural way to get both - feature related ChannelTypes and generic project parsing - under one umbrella to work nicely together in the same handler. 

Therefore I really like the idea of splitting up the binding into a "core" binding which brings the libraries, the Bridge handler and a ThingType with functional ChannelTypes and the corresponding handler.

The "advanced" extension will then bring generic discovery, ETS project parsing and the like. Therefore it will bring its own ThingType with its own ThingHandler and also different ChannelTypes - and hopefully can still use the same BridgeHandler. 

I would actually volunteer to split up the existing PR. I did that for my personal setup prototypically already, so you would not need to spent your time doing it again.

**Comment by lewie** [comment]
Yes, I like the idea! ​​Modularization would simplify some but not only "things" here. :smirk:

A "basic KNX binding" binding, which only address to KNX GAs by simple channels would represent the functionality of the KNX1 binding, that seems important to me.

Karel's ingenious concepts to create virtual devices as *calimero* suggests, could be implemented without so much limitations. In openHAB could be created one or more real devices (actors  channels / sensor channels) from the viewpoint of the KNX bus too. 

Then It would also be able to respond on *groupReadRequest* with a *groupReadResponse* to the KNX bus, what a "normal" openHAB binding for architectural reasons is not allowed. (I've thought about such a KNX2-IO add-on, I already work with a modified  KNX1 binding yet.)

The KNX communication would be fully implemented with *groupReadRequest* support and it would be possible to connect two openHAB Instances to each other, simply via the KNX binding for example.
As you know, the *groupReadResponse* is very dear to me. ;-)

Kai, it raises to me the question, whether you have the "expert KNX" extra not titled with "binding". Did you guess my demand about *groupReadRequest*? ;-)

@kgoderis I hope, you like Kai's Idea too! :grin:

Currently there are the following functional blocks:
 - basic KNX functionality: read and write functionality like KNX1 does.
 - KNX project imports
 - KNX bus/device discovery
 - Virtual KNX devices
 - KNX IO with *groupReadRequest*
Karel, does it make sense to have two Bindings as Kai suggests or does it make sense to ​​modularize into more than two OSGI modules?

**Comment by kaikreuzer** [comment]
> Kai, it raises to me the question, whether you have the "expert KNX" extra not titled with "binding". 

Because it will in the end be one KNX binding - but split into several bundles. And yes, I didn't want to limit it to a single "expert" bundle, but there can be any number of them.

**Comment by kgoderis** [comment]
> @kgoderis I would prefer if you'd update the existing PRs instead of closing them and opening new ones - we would keep all discussions at a single place and don't spread it over different locations (and no, Github should not screw up any comments in that case - definitely not the "main" comments which are not on single code lines).

@kaikreuzer I agree but when force-pushing a rebased commit to the PR, it seems Travis can not handle it. Since it was '00s commits behind and based on a non-Java 8 branch, I did it this way.

**Comment by kgoderis** [comment]
> Therefore I really like the idea of splitting up the binding into a "core" binding which brings the libraries, the Bridge handler and a ThingType with functional ChannelTypes and the corresponding handler.
> 
> The "advanced" extension will then bring generic discovery, ETS project parsing and the like. Therefore it will bring its own ThingType with its own ThingHandler and also different ChannelTypes - and hopefully can still use the same BridgeHandler.
> 
> I would actually volunteer to split up the existing PR. I did that for my personal setup prototypically already, so you would not need to spent your time doing it again.

That sounds ok to me. 

What I had in mind to do - apart from your idea - for the "base" part is to reduce complexity by removing the implicit channel configurations (KNXChannelSelectorProxy in fact) in favour a more user configurable (from DSL point of view) channel definitions. Something in the line of 

`Type someType A: [someGA="<dpt>:<x/y/z>:<flags>:<flag-parameters", ......]`

-  with optionally dpt being the DPT, e.g. 1.001. If not supplied, then a default DPT will be choose based on someType. e.g. a "switchGA" will default to "1.001"
 - with optionally <flags> being something like R, W, T, U with some mapping logic to the RWTU flags on the KNX bus (will not go into detail here on that, because 1 on 1 mapping is not meaningful - it is a question of seeing openHAB as an actor that controls other other actors; in an equivalent KNX ETS configuration it would have the T flag for GAs it writes to, and the W flag for GA's it gets status updates on - I will document this in the code as I mapped that whole thing out based on the KNX specs)
 - with optionally <flag-parameters> being something like "3600", the interval to be used if for example a "R" flag would happen to be specified (R = read out the GA every x seconds)

In doing so the logical difference between "command" GAs and "status" GAs disappears completely

In a later stage I imaged to use the knxproj parser to validate DSL or GUI provided things configurations. For example, if we define in the DSL an actor with IA a.b.c and define a channel with GA x/y/z with a T flag (for example a "switchGA" to send out a Telegram to toggle a switch), then we could issue a warning to the user of if the actor with IA a.b.c does not define a "W" flag for the GA x/y/z *in the KNX configuration*, because sending a Telegram to an an actor that does not defines a W flag on the GA will be ignored anyways by that actor. 

In retrospect what we could think about (maybe *should*) is a tool to export the knxproj data in a DSL compatible text format that can be the base for further editing. With '000s of GAs this would be a welcome help, because you do not want to know about the *hours and hours* I spent editing the DSL files

**Comment by kgoderis** [comment]
> Karel's ingenious concepts to create virtual devices as calimero suggests, could be implemented without so much limitations. In openHAB could be created one or more real devices (actors channels / sensor channels) from the viewpoint of the KNX bus too.

@lewie You still happen to have my code by any chance? I removed it all and it got lost during all the commit squashing :-(

**Comment by lewie** [comment]
>@lewie You still happen to have my code by any chance? I removed it all and it got lost during all the commit squashing :-(

There I can Help I hope! I have many Backups of my BS and there should stay many evolution stages of your code. Although it is something the search in the haystack, but can be found. :-)

**Comment by kaikreuzer** [comment]
> a tool to export the knxproj data in a DSL compatible text format that can be the base for further editing

I agree that this might be the most pragmatic approach, since we cannot bridge the information gap; so generating what is possible as a help to the user to nicely construct his DSLs sounds like a useful feature.

**Comment by B0rner** [comment]
Hey,

I'm not sure, if this is the right place, but I have no idea where to place this question else:
I'm following this "KNX2-binding-creation-process" since months and I hat an JAR file ( org.openhab.binding.knx_2.0.0.201702201740.jar) running since months without any problems.
..until today: I did an Update of my openhab2 installation - coming from the stable repository using `apt-get upgrade`. The update runs without error, but KNX2 Binding is not working anymore.



> Error while starting bundle: file:/usr/share/openhab2/addons/org.openhab.binding.knx_2.0.0.201702201740.jar
> org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.knx [9]
>   Unresolved requirement: Import-Package: gnu.io
>   Unresolved requirement: Import-Package: com.google.common.collect
>     -> Export-Package: com.google.common.collect; bundle-symbolic-name="com.google.guava"; bundle-version="18.0.0"; version="18.0.0"; uses:="com.google.common.base,javax.annotation,com.google.common.primitives,com.google.common.math"
>        com.google.guava [12]
>          Unresolved requirement: Import-Package: javax.annotation; resolution:="optional"
>            -> Export-Package: javax.annotation; bundle-symbolic-name="javax.annotation-api"; bundle-version="1.2.0"; version="1.2.0"
>               javax.annotation-api [16]


Is there a way to get this plugin working again or is there a new jar-file, which runs on the current stable release?

Thank you.
B0rner

**Comment by gitpower2017** [comment]
Hello,

I testing the new KNX-Binden.
I have this Binding "org.openhab.binding.knx_2.0.0.201702181144.jar.zip" with openHAB 2.2
Is this the new Version of the binding?
The automatic import from the .knxproj has no function.

**Pull request closed without merging**
