### PR TITLE
ZWave: add mandatory command classes based on zwave+ device type

### PR DESCRIPTION
**Pull request by jongj**
Fixes a TODO in ZWavePlusCommandClass :smile:  

Signed-off-by: Jorg de Jong <jorg@dejong.info> (github: jongj)

### CODE REVIEW

**Comment by cdjackson** [comment]
Cool - nice addition.

One question - in many ways I'd prefer to use the CommandClass enum rather than the hex values. I suspect this might look less readable, and it's obviously a pain to add in the first place (although it's probably quite quick to do a search/replace), but I do think it would be nicer and more maintainable...

What do you think?

**Comment by jongj** [comment]
So I converted the bytes to enum's. Find /replace where my friend here :smile: . 
As you can see I used a formatting hint to prevent the lines from wrapping.

**Comment by cdjackson** [comment]
Thanks - I think it's clearer, or at least more useful as a developer :)

**Comment by cdjackson** [comment]
There's one last thing I'm fighting with - is it worth also having an enum for the device types?

So, we could have -:

```
enum ZWavePlusDeviceType {
 CENTRAL_CONTROLLER(0x0100),
 DISPLAY_SIMPLE(0x0200),
 etc...
}
```

and then in the list -:
```
  new ZWavePlusInfo(CENTRAL_CONTROLLER, DEVICE_RESET_LOCALLY,...),
  new ZWavePlusInfo(DISPLAY_SIMPLE, DEVICE_RESET_LOCALLY,...),
```

This allows us to uniquely identify the classes with the ```ZWavePlusDeviceType``` and this can be used elsewhere. I'm also personally not bothered about the textual names - they won't be used in the binding. Where they will be used (maybe!) is the UI, but to use them in the UI, they should be used through i18n conversion, and this is done elsewhere (either in ESH outside of the protocol layers but still in the binding, or in the UI). Either way, to perform the internationalisation, we need a unique ID which brings us back to the enum...

What do you think? Personally, I think I would prefer this approach and it would allow it to be used in HABmin as well.

**Comment by jongj** [comment]
Well I was hoping we could avoid the extra enum, but if its useful for other parts like HABmin lets do so.

**Comment by cdjackson** [comment]
Understood -  there’s the other option, and that is to not use the list, but to put it all in the custom enum?

**Comment by jongj** [comment]
What about this one? its all in the enum now.

**Comment by cdjackson** [comment]
Looks good - thanks :)

**Pull request merged**
