### PR TITLE
Updated .pullaprove.yml

### PR DESCRIPTION
**Pull request by martinvw**

### CODE REVIEW

**Comment by kaikreuzer** [comment]
So how can we now merge this...?

**Comment by martinvw** [comment]
🙄

**Comment by martinvw** [comment]
Can we disable pullaprove again (temporarely)?

**Comment by kaikreuzer** [comment]
I have

**Comment by kaikreuzer** [comment]
Probably best if you create a new PR now.

**Comment by martinvw** [comment]
:-(

**Comment by martinvw** [comment]
Did you disable it

**Comment by kaikreuzer** [comment]
Yes. But now I have also revoked access to my acount. Let's try again.

**Pull request closed without merging**
