### PR TITLE
[rfxcom] additional lighting4 support

### PR DESCRIPTION
**Pull request by martinvw**
Added support for 10, 11 and 14

Fixes: #3103

### CODE REVIEW

**Comment by Jamstah** [comment]
The code looks fine, but this is a tricky one as the values have been discovered rather than from a spec.

If 11 is "TAMPER", then is setting it to "ON" really the right option here? Should we have a TAMPER instead?

What does the ON/OFF actually mean, does openhab understand what the ON/OFF is for?

**Comment by martinvw** [comment]
The whole lighting4 implementation is not based on a spec, but its based on some chip which can make some signals which are forwarded by the RFXCOM as is. So we decide to give meaning to it. But essentially there is nothing which can be said about other devices using those chips, we know of motion sensors, switches, multi-channel relays, contacts.

That is why we (or I ;-) ) decided to implement this very loosely because you can even configure it in such a way that ON and OFF are reverted. 

This ENUM is mainly used as help for discovering / configuring the devices, because if it receives a signal with an ON value it will configure the discovered device to respond as it received ON. 

See also https://github.com/openhab/openhab2-addons/pull/2045

**Comment by Jamstah** [comment]
So the only recourse we have is to document ourselves I guess.

Do we have a page on the wiki for listing devices that use this chip that we have coded for, and what values they provide? If not, we probably should. We could link it back to the issues that got raised for adding each one where we can. We could also sprinkle some comments into the code to point to that wiki page, and lightly for each value, to help future developers.

On the code:
As TAMPER is new, I would have said we should make sure that listed as whatever we use for DOOR OPEN, I think its the other way around at the moment (14 and 11 are the same).

**Comment by martinvw** [comment]
I felt that tamper had to be ON, but also that OPEN had to be the opposite of the existing CLOSED. So that is why I ended up like this, its on of the big weaknesses regarding the current implementation.

**Comment by Jamstah** [comment]
I was thinking that if someone sets up notifications for when their door is open, then by default they'd want the same trigger if their device was tampered with. As you say, tamper being ON is also something which seems sensible.

Its all so messy!

**Comment by Jamstah** [comment]
Oh, I see you added to the doc with the latest push as well, even better, thanks Martin :+1:

**Pull request merged**
