### PR TITLE
[gpstracker] Fixes the disablement of accuracy check

### PR DESCRIPTION
**Pull request by kaikreuzer**
Having accuracy set to its default 0, the disablement didn't work for me as the comparison of a double value with 0 is not safe. This PR fixes that.

Note that the code formatting has been also applied by my IDE - I have therefore split the PR into two commits, to make clear what I have actually changed about the code.

### CODE REVIEW

**Comment by wborn** [comment]
Do you approve these changes @gbicskei? :-)

**Comment by gbicskei** [comment]
Sure! :) Sorry for the double handling...

**Comment by gbicskei** [comment]
About formatting: is there a list of expected settings somewhere I should sync my IntelliJ with? I had reviews from both of you @kaikreuzer @wborn  in the past and my feeling was that even you aren't in sync using both Eclipse...

**Comment by wborn** [comment]
Thanks for your for your review @gbicskei .

Eclipse is provisioned using Oomph with files like [EclipseSmartHome.setup](https://github.com/eclipse/smarthome/blob/master/targetplatform/EclipseSmartHome.setup) which contain the settings. 
But I don't think you can use those with IntelliJ. It's possible to export the Eclipse ESH formatter settings ([ESH.xml.txt](https://github.com/openhab/openhab2-addons/files/2751036/ESH.xml.txt), remove .txt) and [import them in IntelliJ](https://stackoverflow.com/questions/27035705/how-import-eclipse-code-style-to-intellij-idea).

You can further prevent unnecessary reformatting if you configure IntelliJ to order imports similar to the Eclipse configuration:

imports

> that even you aren't in sync using both Eclipse

Maybe that is/was due to [ESH 6424](https://github.com/eclipse/smarthome/issues/6424)? :neutral_face:

**Pull request merged**
