### PR TITLE
[Loxone] Fix for dimmer switch off

### PR DESCRIPTION
**Pull request by ppieczul**
Hello @martinvw 
It is a simple fix for handling zero value of dimmer. Please take a look and merge if ok.
We have a different min-max ranges for dimmer state value in OH and Loxone. Regardless of the proper scaling between the ranges, value zero should be passed transparently as it means to switch the dimmer off.
Thanks
Pawel

Signed-off-by: Pawel Pieczul <pieczul@gmail.com> (github: ppieczul)

### CODE REVIEW

**Comment by ppieczul** [comment]
That's right. I was misled by the fact it worked. Corrected.

**Comment by martinvw** [comment]
One last question can it receive null and is this method you use resilient

**Comment by martinvw** [comment]
Checked the docs if a null arrives there it will throw a NPE because the method accepts a double primitive only

**Comment by martinvw** [comment]
@ppieczul did you see my last remark regarding, the null-safety?

> Checked the docs if a null arrives there it will throw a NPE because the method accepts a double primitive only

I'm okay to merge it like this but it will explode if a  `null` is handed to the method

**Comment by ppieczul** [comment]
@martinvw  sorry for not reponding, I was out for a while. Please don't merge, there is a chance it can be null. I will fix it. Thanks.

**Comment by ppieczul** [comment]
@martinvw Hi Martin I am back from nullity, hope the change is going to be ok now. Thanks.

**Comment by martinvw** [comment]
Thanks!

**Pull request merged**
