### PR TITLE
Renamed a package to internal in the milight binding.

### PR DESCRIPTION
**Pull request by VelinYordanov**
See openhab/static-code-analysis#100

Signed-off-by: VelinYordanov <velin.iordanov@gmail.com>

### CODE REVIEW

**Comment by martinvw** [comment]
@davidgraeff please review, thanks!

**Comment by davidgraeff** [comment]
Hm, why is the internal rule forced on test packages. Test packages are never exporting anything and usually tests are within a test directory of the main package. The important point is though that I think it doesn't make sense to have all tests in an internal namespace all the time, does it?

**Comment by martinvw** [comment]
But it's not a test sub-project in this case, so I think it makes sense to follow the rules that since it should not be exported (which is clearly true for those) that it should be in the internal package.

@kaikreuzer wdyt?

**Comment by kaikreuzer** [comment]
In general, tests should be in the same package as the class they are testing - so yes, I agree with @davidgraeff that these can be non-internal packages, but still the fragment itself would not export them.
The rule should hence really only be applied on "real" bundles, not on test fragments.

**Comment by martinvw** [comment]
@kaikreuzer I agree with all of the above, but its not a test-fragment its test code in the main binding.

**Comment by kaikreuzer** [comment]
Oops, you are right. Why is it in there at all?

**Comment by davidgraeff** [comment]
By accident I guess. --edit-- They were part of the verification that the implementation is correct, and to sniff packets from newer app versions that communicate with the simulated bulb bridge to find new undocumented packets.

I have no time at the moment to move those classes to another fragment though :/

**Comment by kaikreuzer** [comment]
Then moving them to internal should be the least thing to do, right?

**Comment by martinvw** [comment]
> So should we just proceed here and move those to an internal package?

I would prefer to, than we can better guard new code which is added by enforcing the rule as an error.

**Comment by martinvw** [comment]
Thanks guys!

**Pull request merged**
