### PR TITLE
[Robonect] Migrated to bnd

### PR DESCRIPTION
**Pull request by JueBag**
Signed-off-by: JueBag <opus42@gmx.de>

### CODE REVIEW

**Comment by davidgraeff** [comment]
conflict

**Comment by JueBag** [comment]
Ups, why didn't this conflict show up in yesterdays conflict report?

**Comment by davidgraeff** [comment]
Whenever we merge another migrated binding, there is a chance for a new conflict

**Comment by JueBag** [comment]
Found the reason by myself also. Because this one wasn't ready to be merged right away, it was overtaken by others. 
Standing by to resolve other conflicts.
Do I need to "squash" (I hope it's the right term) all commits into one?

BTW: It's nice outside, we shouldn't sit in front of a screen.

**Comment by davidgraeff** [comment]
No need to squash. 

> BTW: It's nice outside, we shouldn't sit in front of a screen.

Saying that to an internet audience distributed all over the planet :D

**Comment by JueBag** [comment]
What great info for the start of the (short) Saturday night.

**Pull request merged**
