### PR TITLE
ZWave: [WIP] enable FIBARO_FGRM_222 converter

### PR DESCRIPTION
**Pull request by maggu2810**
This PR should be a base for discussion.

@cdjackson I know that the thing XML files are generated by your database.

The following changes allows me to use the Fibaro FGRM222 proprietary manufacturer specific command class implementation to control the roller shutter.

Using that class (you already know) I can also set the lamella angle and not only the position of the blinds.

PercentType is perhaps not correct for angles of lamellas (they could be negative). But that is the XML and should not matter here.

### CODE REVIEW

**Comment by cdjackson** [comment]
I need to think about how to handle this some more yet. I'd like a cleaner approach than we have and I think this should be possible, although not sure how yet.

Probably I would suggest to use different channel types - I'm not sure if we have any defined for window coverings/shutters/etc - I'd need to check, but we probably should define something and use that?

Give me a few days to think about how to proceed with this.....

Thanks

**Comment by maggu2810** [comment]
I have not used the ESH "channel configuration" till now, but perhaps the inverted stuff could be moved to that place.

**Comment by cdjackson** [comment]
I would prefer to move the invert to a channel configuration rather than in the XML - otherwise it might as well be hard coded? This won't change the code - just the channel XML.

I'll try and look at how to handle these manufacturer classes over the next day or so...

**Comment by maggu2810** [comment]
> I would prefer to move the invert to a channel configuration rather than in the XML - otherwise it might as well be hard coded? This won't change the code - just the channel XML.

Have you seen my comment above? :wink: 

```text
WDYT if the inverted option is a thing configuration.
I think it depends on how the wired motor is connected.
If it is inverted then the lamella position and angle is inverted.
So, the inverted is used for both or for no one.
```

**Comment by cdjackson** [comment]
Yep - I saw the comment. My response was that I would prefer to move it to channel configuration- or is that what you meant by thing configuration?

**Comment by maggu2810** [comment]
I want to move it out from the XML and use the configuration, too.

IIRC we added configuration for channels for a few weeks and there is now a configuration for channels and for the thing. I think we should use the thing configuration instead of the channel configuration. If the position is inverted then the lamella angle is inverted, too (because it depends on the wired connection). The state that one channel is inverted and the other one isn't should not be possible.

**Comment by cdjackson** [comment]
> The state that one channel is inverted and the other one isn't should not be possible.

Ok- if that's always true, then I would agree. However... I still wonder if it might be better to put this in the channel config since logically, the processing of channels is separate in the binding from the thing (channels being processed in the converters), so I'd have to do something to link channel configuration to the thing which might be a little nasty.  I'll take a look - it might be possible / simple without a major kludge to make some sort of global config in the thing that feeds in to the different converters.

**Comment by maggu2810** [comment]
> I'll try and look at how to handle these manufacturer classes over the next day or so...

Have you had any change to think about that?

**Comment by cdjackson** [comment]
I had a look a few days back, but haven't really worked out the best approach. I was looking to see if I could create an abstract manufacturer proprietary class which implemented the getCommandClass method but allowed overriding of the other methods. Ultimately they should all return the same key here.

However, how to do this isn't so obvious, so maybe it needs to be done differently. Also, the same thing would be needed in the converter...

Any thoughts :)

**Comment by maggu2810** [comment]
To integrate the manufacturer proprietary class handling we need modifications in the XML and in the code.
The modification in the XML should be "as final as possible" (correct?) because changes could lead to a need of thing removal and readding. Or do your binding handle a sync between the XML and the thing instance?
The code could change from time to time, it is hidden from the user. He don't care.
Is this correct?

So, can't we enable the handling in the code and do some refactor later if necessary? I think it is more clear how to design the architecture if there are some other implementations of manufactorer prorpietary classes, too.

**Comment by cdjackson** [comment]
> The modification in the XML should be "as final as possible" (correct?) because changes could lead to a need of thing removal and readding.

Yes, but I'm not too bothered about re-adding devices. It's a couple of keypresses so isn't too hard :) Of course I would like to minimise this, but at the moment while things are evolving, I'm not too bothered if it has to change. 

> I think it is more clear how to design the architecture if there are some other implementations of manufactorer prorpietary classes, too.

I'm not sure I follow. Why is this clearer? We should have an extendible architecture on the assumption that there will be more. Actually having more doesn't help make it clearer does it?

They all need to implement a single command class, and somehow this needs to be linked back to the device. This needs to be done for both the converter and the class itself.

I want to avoid using "fake" command classes like FIBARO_FGRM_222 - this will become a major mess. I want to stick to the real classes, and then in that class provide a mapping to the implementation class.

So, the XML for the channel should ideally have -:

```
<property name="binding:*:PercentType">MANUFACTURER_PROPRIETARY;type=lamella,invert=true</property>
```

and we would then provide another configuration property that provides the link to the implementation class.

In the command class, it also needs to return MANUFACTURER_PROPRIETARY for the ```getCommandClass``` method. There should not be additional "fake" command classes in the command class list - we need to map these elsewhere, and my thought was to have something like this -:

```
ZWaveManufacturerPriorietaryCommandClass extends ZWaveCommandClass
{
    public CommandClass getCommandClass() {
        return CommandClass.MANUFACTURER_PROPRIETARY;
    }

    \\ Try and map the device class in here somehow!
    \\ Maybe this can be done in a similar way to how the command classes are mapped already, but keeping it inside this class.
}
```

and then the FGRM222 implementation should extend this. A similar thing would be needed in the converters, although I'm less bothered about the converters as it doesn't tie in to the protocol.

I'm not sure if this can work though - I started to play with this but found a bug that requires a major refactor of the binding so it's not top of my list just at the moment... If you have some ideas, let's discuss more - I'd like to get a nice implementation concept if possible, but I fear ultimately we might end up with something horrible like OH1...

**Comment by kaikreuzer** [comment]
Closing this as it should be moved to https://github.com/openhab/org.openhab.binding.zwave

**Pull request closed without merging**
