### PR TITLE
[synopanalyzer] Migration to bnd

### PR DESCRIPTION
**Pull request by clinique**
Signed-off-by: Gaël L'hopital <gael@lhopital.org>

### CODE REVIEW

**Comment by davidgraeff** [comment]
Is that a migration or also a code change? There are 1000 new lines of code? Maybe you have forgotten to commit the removal of a file?

**Comment by clinique** [comment]
No, I did suppress dependency to a not common jar

**Comment by wborn** [comment]
Maybe you can also try using using the library again with the infra that was added in https://github.com/openhab/openhab2-addons/pull/5190?

**Comment by clinique** [comment]
> Maybe you can also try using using the library again with the infra that was added in #5190?

I thought of it but did not for two reasons : 
=> the jar used before migration was produced by me in a separate project
=> OH only uses a small portion of Jonazz's library (no SQL db, no forms ...) - so I expurged a bit his library

**Comment by wborn** [comment]
OK but AFAIK all code contributed to this project should comply to our [coding guidelines](https://www.openhab.org/docs/developer/development/guidelines.html):

> The following guidelines apply to all (Java) code of the openHAB project.

**Comment by davidgraeff** [comment]
Could you please resolve the conflicts? I'll merge asap after that

**Pull request merged**
