### PR TITLE
[MiHome] fixed Update of magnet sensorStatus from heartbeat's

### PR DESCRIPTION
**Pull request by bloft**
When using the MiHome addon and a Door / Windows Sensors, then when openhab2 is restart the status of the sensors remain empty, until the Door / Windows sensor is triggered.

The status information is available and using be other sensors by parsing the heartbeat data.
I have update the XiaomiSensorMagnetHandler to also parse this data, so the state is update.

### CODE REVIEW

**Comment by martinvw** [comment]
It would be great if you could include a `Signed-off-by` (to certify that you wrote it or otherwise have the right to pass it on as an open-source), see http://docs.openhab.org/developers/contributing/contributing.html#sign-your-work

If running a local git client you can use `git commit --amend --signoff` after that a forced push is required.

**Comment by bloft** [comment]
Hi the commit is now Signed.

**Comment by martinvw** [comment]
@dimalo could you do a review? Or maybe @tavalin?

**Comment by bloft** [comment]
I found and fixed a bug in the update.

**Comment by dimalo** [comment]
On old firmware versions Hearbeat and Read_Ack messages didn't get the right status. Even when the window was closed the Heartbeat showed "open".
Sorry it took me longer, I wanted to make sure this bug was now fixed in the latest gateway firmware.
LGTM! thank you @bloft for your contribution

**Comment by martinvw** [comment]
Thanks @bloft and @dimalo!

**Pull request merged**
