### PR TITLE
Holmes/auto reconnect

### PR DESCRIPTION
**Pull request by holmes**
4 commits in here that handle updating the dependent library and spring cleaning of this binding.

First PR on this project, so let me know if you want any changes.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks @holmes, looks all perfect to me.
Just one remark: The lib had already been updated by https://github.com/openhab/openhab2-addons/pull/2027 - could you possible remove this change from your PR, so that we are sure that no changes from @abedwardsw are lost?

@abedwardsw & @lolodomo Please also feel invited to review and test!

**Comment by holmes** [comment]
@kaikreuzer the jar update in #2027 doesn't have the required updates. The required updates landed in https://github.com/vitalidze/chromecast-java-api-v2/pull/73 and https://github.com/vitalidze/chromecast-java-api-v2/pull/78

**Comment by abedwardsw** [comment]
@kaikreuzer the referenced commit from @holmes  [holmes/chromecast-java-api-v2@300922e](https://github.com/holmes/chromecast-java-api-v2/commit/300922e70fc9a7fa73b01886f5e3820aa0ca11e7)  contains my changes so all appears good, thanks

**Comment by kaikreuzer** [comment]
perfect, thank you both!

**Pull request merged**
