### PR TITLE
[WIP] [miflora] binding initial contribution

### PR DESCRIPTION
**Pull request by hakan42**
Signed-off-by: Hakan Tandogan <hakan@tandogan.com>

WIP - As of this moment, the binding has no real code in it. It is more an "envelope" for the various values that are injected via MQTT.

Mainly a discussion starting point for https://github.com/openhab/openhabian/issues/185#issuecomment-317534266

Built artifact will be downloadable at https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.miflora

### CODE REVIEW

**Comment by martinvw** [comment]
Personally I don't think a binding should just be wrapper around mqtt is this the final intended architecture? Or is the intention to depend on a Bluetooth connection later on? For only mqtt you could better just use / write / follow a tutorial with some copy paste of item definitions.

@kaikreuzer what do you think?

**Comment by hakan42** [comment]
Actually, I am still waiting for BLE to be merged into master.

My intention is to have a binding that supports both BLE and MQTT, and in the case of MQTT multiple topic tree schemata ( @ThomDietrich puts everything into one topic as a JSON string, SeaSide puts each measurement into its own topic ). Also, I want to add discovery to the binding.

**Comment by martinvw** [comment]
Great that sounds more like a binding 😉

**Comment by ThomDietrich** [comment]
@hakan42 great to see this idea evolving!!

I've invested a few more minutes yesterday to further tune my program (it now has a systemd service). For reference: https://github.com/ThomDietrich/miflora-mqtt-daemon

In the binding README I'd actually prefer if you called the project "miflora-mqtt-daemon" instead of "ThomDietrich's script" :smile: 

While I'm still in the process of developing and updating the daemon, do you have any wishes that I should take into consideration? JSON is in my opinion a good solution, how do you see it?

Best!

**Comment by kaikreuzer** [comment]
> My intention is to have a binding that supports both BLE and MQTT

Then you should chose a different architecture. Imho, the "flora" thing type should depend on a bridge, which could then either be a "miflora-mqtt-daemon bridge" or a "BLEBridge" (which will be part of the BLE binding, see [here](https://github.com/eclipse/smarthome/pull/3531#issuecomment-305831722)). Does that make sense?

**Comment by hakan42** [comment]
> While I'm still in the process of developing and updating the daemon, do you have any wishes that I should take into consideration? JSON is in my opinion a good solution, how do you see it?

JSON is fine, and a parser is quickly created.

> With a little bit of additional MQTT publishing I'd be able to support openHAB side auto discovery of plants, including names, MAC address, location etc. Would you like to integrate that?

Sounds nice, but I have no real idea about the syntax or desirable values yet. How about we take this discussion back to the community forums? Maybe on https://community.openhab.org/t/xiaomi-miflora-sensor-integration/17453 ?

**Comment by hakan42** [comment]
> Imho, the "flora" thing type should depend on a bridge, which could then either be a "miflora-mqtt-daemon bridge" or a "BLEBridge"

Architecture-wise, this sounds fine. But for the implementation, I have to read a bit more on the https://github.com/eclipse/smarthome/pull/3633 to understand how things are supposed to work.

**Comment by ThomDietrich** [comment]
I have not yet decided if I want to comment in this community thread or start a new one for my program...

In the meantime I've tuned a few things and added an announcement message. https://github.com/ThomDietrich/miflora-mqtt-daemon/commit/4bef99fc311b97d96f7c507bd18d52b8851edb9f

The current code produces these messages
```json
miflora/$announce {}
miflora/$announce {"Tomatenk\u00fcbel": {"refresh": 30, "location": "", "firmware": "2.6.2", "topic": "miflora/Tomatenk\u00fcbel", "mac": "C4:7C:8D:62:40:39"}, "Goldfruchtpalme": {"refresh": 30, "location": "", "firmware": "2.6.2", "topic": "miflora/Goldfruchtpalme", "mac": "C4:7C:8D:62:3F:CA"}}
miflora/Tomatenkübel {"temperature": 15.5, "conductivity": 250, "battery": 89, "light": 19, "moisture": 33}
miflora/Goldfruchtpalme {"temperature": 21.7, "conductivity": 1077, "battery": 100, "light": 45, "moisture": 32}
```
The announce topic has the retain flag and is reset on program start (TODO on termination).
The term `$announce` and the content of the message were the first pieces that came to mind. The location property is not yet available in the program. I'll have to think of a configuration schema for it. Can you think of anything else?

As all of this is related to MQTT and MQTT conventions, I'm going to mention @davidgraeff, maybe he has some feedback 😃

**Comment by davidgraeff** [comment]
@ThomDietrich: Is the Mqtt Homie convention nothing that can be used here for the mqtt topic structure?  Than you could benefit of the soon to exist Homie binding.
Personally I thing sending json over Mqtt topics is perverting the original idea of mqtt topics in the first place, but I recognize that a lot of people do this nowadays. At least command topics, if there are any, should be plain values though.

**Comment by kaikreuzer** [comment]
> Architecture-wise, this sounds fine. But for the implementation, I have to read a bit more on the eclipse/smarthome#3633 to understand how things are supposed to work.

The main change you need to do for a start is to split your one thing (+handler) into a bridge and a thing. Once BLE becomes available, one can check how to best further refactor it.

**Comment by ThomDietrich** [comment]
@davidgraeff thought so too at first but had to learn the benefits and why this combination is famous with a lot of developers. My script is still making good use of MQTT topics while providing combined data sets in one single MQTT message.
Anyhow I agree, I could add one more [`reporting_mode`](https://github.com/ThomDietrich/miflora-mqtt-daemon/blob/master/config.ini#L8-L12) which follows the homie convention. Being a fan of the homie "vision" that would be a nice tribute.

The `$announce` topic is one topic that benefits from being a single (formatted, i.e. json) message. Being an elementary retained message, a single topic subscription is enough for an instant auto-discovery. The discovery process is not yet clearly covered by Homie: https://github.com/marvinroger/homie/issues/12#issuecomment-278110387

**Comment by davidgraeff** [comment]
I thing the sole or main purpose of those conventions is discovery. If homie 2.0 fails in that regard, the specification should be reviewed once more.

**Comment by ThomDietrich** [comment]
@davidgraeff That's not what I wanted to imply :see_no_evil: I'm still unsure about the topic and it's arguable what is really needed for a good, flexible, and platform independent (memory restrictions of µCs) discovery process.
I've implemented Homie mode last night (first draft!): https://github.com/ThomDietrich/miflora-mqtt-daemon/commit/37e90ec1c9fe6ceb1a86652f96afadc665fec3a4

**Comment by hakan42** [comment]
This needs to be rethought with the MQTT and BLE integration into 2.4 milestone.

**Comment by martinvw** [comment]
Makes sense indeed. Note that I did not find time to continue with it either.

 It did not help that the 3 sensors I have, have major measurement differences for the same plant (0,5 cm apart) they reported 21, 28 and 33% soil moisture, so I kind of gave up on the devices as well.

**Pull request closed without merging**
