### PR TITLE
[chromecast] Added dedicated channel to stop playback

### LINKED ISSUE #1783: [chromecast] Player state not updated when changed outside openHAB
I tried the Chromecast binding. It discovered my Freebox Player Mini 4k (running Android TV).
I can use play and pause commands from the control channel.
When I play or pause a YouTube video from my phone using YouTube application, the state of the channel is not updated accordingly.

### LINKED ISSUE #4794: [chromecast] Add feature to stop playback
It currently isn't possible to disconnect a Chromecast Stream, although the API supports it. I think a switch should be sufficient to accomplish this. For example, we send ON to the switch, then we call the stop method, and then we turn off the switch.

### PR DESCRIPTION
**Pull request by cweitkamp**
- Added dedicated channel to stop playback
- Removed handling of `StopMoveType` from `control` channel

Closes #1783
Closes #4794

Test version:
[org.openhab.binding.chromecast-2.5.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab2-addons/files/2855457/org.openhab.binding.chromecast-2.5.0-SNAPSHOT.jar.zip)

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by wborn** [comment]
I tested this with a local build but when I stop casting (using an App) to a Chromecast the player state isn't updated and the stop channel is still off. Also when I start openHAB and my Chromecast is idle the stop channel also is off. So it doesn't seem to fix #1783 for me.

**Comment by cweitkamp** [comment]
@wborn Thank you for testing and feedback. I did not consider the restart. But it should not be to hard to identify the root cause. I think it can be found in the `updateMediaStatus()` method.

**Comment by cweitkamp** [comment]
@wborn I found the culprit. An unhandled event. Fixed with latest commit. As well as the restart: I am assuming the device is OFF.

```
2019-02-17 18:59:22.230 [DEBUG] [ast.internal.ChromecastEventReceiver] - Unhandled event type: CLOSE
```

**Comment by wborn** [comment]
It does work better now. But still it doesn't properly update the `control` and `stop` channel states if you stop casting (using an App). It does properly update the `appName` and `appId` channels to `-` when you stop casting to a Chromecast.

**Comment by cweitkamp** [comment]
Might I ask for a DEBUG log which is recorded while stopping the cast? Thanks.

**Comment by cweitkamp** [comment]
:+1: Great news. I am glad we got it working now.

[Approved with PullApprove](https://pullapprove.com/openhab/openhab2-addons/pull-request/4860/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=openhab/openhab2-addons)

**Pull request merged**
