### PR TITLE
remove version constraint from manifest

### PR DESCRIPTION
**Pull request by J-N-K**
The old manifests did not contain version constraints for the OpenHAB or ESH bundles. The bnd-generated manifests set constraints that do not allow using newer bundles with older versions of OpenHAB (e.g. Snapshot-Build-Binding/Release-Core). This PR reverts that change.

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by davidgraeff** [comment]
At least the major version need to be considered. A OH3 binding will just not work with OH2.

**Comment by J-N-K** [comment]
Difficult. Because ESH bundles before 2.5 have a version of 0.10 (included in OH 2.4). I tried `version="[0.10,3)"` for `org.eclipse.smarthome.*` and `version="[2.3,3)"` for `org.openhab` but that didn‘t work (i.e. my OH2.4 wasn‘t able to resolve these bundles)

**Comment by maggu2810** [comment]
I am still not sure, why it make sense to remove version constraints in OSGi manifests.
The version constraints state which version a bundle works with and resolution phase.
Without that version constraints it will "crash" at runtime, because of classes are not available or method signature mismatches, ...

WRT your comment in the other thread:
If openHAB Core 2.5 adds a new method to some bundle that is used by a openHAB Add-on, I don't understand how that addon should magically work with 2.4.
Sure, without the version constraints you can make the bundle wiring working, but as soon as the non available method is called an exception is raised.
What's better now?

Normally if you want to provide new function of bugfix for version 2.4.0 you will create a branch 2.4.1-SNAPSHOT and work on that.
Removing version constraints just to use a new bundle in an old runtime seems to be the wrong approach (IMHO).
This does not sound like moving forward and create better OSGi headers.

If we need to make sure that new bundles are working in an old environment we need to ensure that core does not change the API anymore.

I don't think every addon developer ensures that it 2.5 addon is working in 2.4.
If you do, it would make more sense to change the version constraints for your bundle only and not for all.

**Comment by J-N-K** [comment]
In general I agree with you. IMO the problem is our release management: We do not do bugfix-releases.

In most cases (at least in the past) bindings worked without problems (there was a change I believe from 2.2 to 2.3 and bindings using UoM could not be used before that was introduced in the core). 

So what essentially happens is: A bug is found and it is fixed in master. The next stable release is probably six month away, so what we did recommend was: use the latest version of that binding only. If that is not possible any longer, all user would be left with this bug until we do our next release.

The same holds true for new bindings. If they do not use new core features (which seldom occurs), these bindings could be used before they were released. This will not be possible now (or we would require binding developers to have two branches, one for the old release and one for the new snapshot that they need to keep in sync. I guess that will probably drive off those that already struggle with git.

For me this is not so much a problem, now that I found out how that works.

**Comment by maggu2810** [comment]
@J-N-K You are right, it is related to the release management.
If the migration to Maven + Bnd is completed (some time), the releases of openHAB Core and Addons could be splitted. I don't know if you (the openHAB product team) is interested in it at all.
The usage of addons that are hosted in separate repos and use a separate version scheme should also be much simpler.
There should be no requirement to use the same versioning for all addons -- from the technical point of view, from product or maintenance view it could make sense to use one for all. Perhaps, there can be also arguments that the maintenance will be much simpler if addons can release more often stable versions.

**Comment by maggu2810** [comment]
I am aware that I am not an addons or product maintainer and my opinion doesn't carry weight here, but as you requested my review, here my very personal comment:
I don't like the version constraints changes and I would like to keep the default mechanism of Bnd. :wink:

**Comment by kaikreuzer** [comment]
@maggu2810 I didn't mean to overrule you here in any way, but I think for the moment, we should adhere to what has been defined so far.
I am absolutely open to change this in future and once we have proper semver in openhab-core with bnd now, we might be in a position to change this - but that will have to go hand in hand with release management and thus will have a bigger impact that needs to be coordinated.

**Pull request merged**
