### PR TITLE
[harmonyhub] Fixes #2497

### LINKED ISSUE #2497: [harmonyhub] Suggestion for checking for current activity before starting a new activity
## Expected Behavior

When I send PowerOff activity (by name) and hub is already in PowerOff state, it should do nothing.

## Current Behavior

When I send PowerOff activity (by name) and hub is already in PowerOff state, it powers on one of my devices (last one). This is 100% reproducible in my setup. When hub is performing some activity is powers off correctly and does not start that device.

## Possible Solution

Looking at the binding code, it is very likely that this is a bug in whistlingfish library or even more likely in harmony hub, as the original remote controller does not allow for such scenario to happen.

I think it would be nice to add checking for current state to handleCommand and update the hub only if requested activity is different to current one. 

Although this is not a big issue and requires a workaround at upper level (for example in .rules file), from usability perspective, binding could be protected against such scenarios, which should not lead to some random activities.

## Steps to Reproduce (for Bugs)

1. Add harmony hub, do not have to add any devices.
2. Create a rule that on some condition sends PowerOff activity to the hub.
3. In my case when hub was powered off, it started my projector.

## Context

I have been trying to power off by AV system when motion sensor detected nobody in the room for 10 minutes. It resulted in my projector being powered on, when AV system was already down.

## Your Environment

* OH snapshot 20170702112021
* Ubuntu Server 16.04

### PR DESCRIPTION
**Pull request by ppieczul**
Fixes issue #2497.
This issue currently forces me to add checks against current activity in habpanel and rules.

I extended the fix to not sending activity set command to the hub library if the current activity is already that activity. This is exactly how Harmony remote controller works - you can't press a button to start an activity if this is the current activity. 

Additionally fixed what static code analyzer complained about: no EOF in about.html and redundant import.

Signed-off-by: Pawel Pieczul <pieczul@gmail.com> (github: ppieczul)

### CODE REVIEW

**Comment by martinvw** [comment]
@wborn can you review these changes?

**Comment by wborn** [comment]
Maybe it would be better to create a PR to fix this issue in the underlying harmony-java-client library? 

This fix will be of use to non-openHAB library users and it would also close:
* https://github.com/tuck182/harmony-java-client/issues/13
* https://github.com/tuck182/harmony-java-client/issues/19 (by @ppieczul)

The `net.whistlingfish.harmony.HarmonyClient` is also keeping track of the [currentActivity](https://github.com/tuck182/harmony-java-client/blob/master/src/main/java/net/whistlingfish/harmony/HarmonyClient.java#L88).

**Comment by ppieczul** [comment]
Right and I have one more request to the whistlingfish library but it seems
it has not been taken care of for some months now. I don't know if this is
abandoned yet - do you have any contact with the author?

**Comment by wborn** [comment]
> I don't know if this is abandoned yet - do you have any contact with the author?

I've put in a few harmony-java-client PRs earlier this year and these were promptly merged. :-)

**Comment by ppieczul** [comment]
Ok, we'll go this way, I got in touch with the author after some initial silence. Thanks.

**Pull request closed without merging**
