### PR TITLE
removed astro binding as it has moved to the ESH repo

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by martinvw** [comment]
Will this break the binding for existing people or will this work fluently when upgrading?

**Comment by kaikreuzer** [comment]
It should work fluently as the binding id etc. is kept the same - the only thing that changes is the technical namespace of the binding.

**Comment by martinvw** [comment]
Great, maybe we should use this one to test what happens if I say the magic word, if its setup :-)

**Comment by martinvw** [comment]
LGTM

**Comment by martinvw** [comment]
@kaikreuzer it even works with the lgtm :-)

**Pull request merged**
