### PR TITLE
[HDL][WIP] Initial contribution

### PR DESCRIPTION
**Pull request by stigli**
[HDL][WIP] Initial contribution for smart House system HDL binding.

This is a new binding for the smart house system HDL.
There is no issues in the static code analysis.

Readme file has been updated and will be updated when there is question in the forum thread:
https://community.openhab.org/t/new-binding-hdl-automation/67204

Jar file can be found her:
https://github.com/stigli/openhab2-addons/tree/master/addons/binding/org.openhab.binding.hdl/releases

### CODE REVIEW

**Comment by stigli** [comment]
Sorry saw that i need to Squash and merge

**Comment by Hilbrand** [comment]
You don't need close. It's not needed to squash. It will be done when the binding is merged. But you need to add sign off to all commits. If you squash you can still push (force) to your branch and this pr will be updated.

**Comment by Hilbrand** [comment]
No, the comments are not part of the git repository itself but only present here on github. You can update (or squash) the git commits with `git rebase -i HEAD~5` This will open and editor were you can specify the actions to take. Like reword (or squash) the commits and afterward push the commit back to github with: `git push --force-with-lease`

**Comment by stigli** [comment]
OK, thank you for your help, will look into it tomorrow.

**Pull request closed without merging**
