### PR TITLE
Blueiris binding

### PR DESCRIPTION
**Pull request by pinkfish**
A binding that will connect to the blue iris camera software and keep pieces up to date using the json interface.  Sadly there is no push request setup there yet, since blue iris itself does not support this.

### CODE REVIEW

**Comment by kubawolanin** [comment]
Hey @pinkfish, please make sure you squash your commits (`git rebase -i`) and include the following in the commit message:
```
Signed-off-by: Name Surname <your@email> (github: pinkfish)
```

This will result in just one commit in this PR (instead of current 44).
Please do the same on your other pull requests.
Thanks!

**Comment by pinkfish** [comment]
Can I do that after I have uploaded them all?  Not clear on that part of
git...

**Comment by kaikreuzer** [comment]
Yes, all you have to do afterwards is a force (-f) push of your branch!

**Comment by pinkfish** [comment]
Ok, I think I did that...  Not 100% sure :)

**Comment by kubawolanin** [comment]
Nope - there are still 48 commits in the repo.
Maybe [this article will be helpful](https://davidwalsh.name/squash-commits-git) for you.

1. Run `git rebase -i` - you'll see a screen like this;
squash

2. If you're using vim, hit `s` to enable inserting. 
You'll see a list of all your commits. 
You will need to `pick` the first commit from the list (ideally) and `squash` all others, so it looks like this:

```
pick fb554f5 This is commit 1
squash 2bd1903 This is commit 2
squash d987ebf This is commit 3
...
```

**Comment by pinkfish** [comment]
I see the noop bit. When I tried rebase -i master it didn't seem to roll up
the checkins correctly.


From that article though perhaps I should use rebase -i blueiris...

Will give that a whirl.

On Mar 3, 2017 11:57 PM, "Kuba Wolanin" <notifications@github.com> wrote:

Nope - there are still 48 commits in the repo.
Maybe this article will be helpful
<https://davidwalsh.name/squash-commits-git> for you.

   1.

   Run git rebase -i - you'll see a screen like this;
   [image: squash]
   <https://cloud.githubusercontent.com/assets/2270505/23577066/7863bb6e-00b6-11e7-9ba4-a01be134f950.PNG>
   2.

   If you're using vim, hit s to enable inserting.
   You'll see a list of all your commits.
   You will need to pick the first commit from the list (ideally) and squash
   all others, so it looks like this:

pick fb554f5 This is commit 1
squash 2bd1903 This is commit 2
squash d987ebf This is commit 3
...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openhab/openhab2-addons/pull/1983#issuecomment-284135551>,
or mute the thread

**Comment by ryanrdetzel** [comment]
Would love to get this merged!

**Comment by pinkfish** [comment]
I don't seem to be able to get the rebase to work correctly though.  It
either ended up with a huge mess, or reverted my changes altogether :(

**Comment by pinkfish** [comment]
Reverting this pull request in favour of the new one I just made that is less of a problem.

**Pull request closed without merging**
