### PR TITLE
add developer documentation

### PR DESCRIPTION
**Pull request by J-N-K**
Starting to add documentation as requested om #5448 

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by Hilbrand** [comment]
Great to start documenting! But why adding it here? We have a separate docs project: https://github.com/openhab/openhab-docs I think all documentation should be there. Even if this information is only relevant to this repository. Having all documentation in one place makes it much easier for developers to read. If we spread out the developer documentation to all repositories it makes it a lot more difficult to find the right information. Also if this documentation is limited to this repository, it probably requires some context information that is also relevant for all projects, and before you know it your having duplicated information here and in the docs project.

**Comment by J-N-K** [comment]
What would you suggest as a good place for this?

**Comment by davidgraeff** [comment]
@Hilbrand I don't agree. Sometimes duplication is the right way to go, especially for readme files and build instructions. If I'm checking this repo out as a new developer, I'm not having a dozen web browser windows open, but I expect all build information to be part of the repo.

The general picture how everything fits together should be part of openhab-docs, the individual build flags  for this repo must be part of this repo.

**Comment by Hilbrand** [comment]
I don't know what information should or shouldn't here. But the (potential) information in this pr is already far beyond just simple command line options for the build. What I do know is that the information on the docs repository is outdated. That on the ESH docs pages more development information is available that should be migrated and/or updated to the docs repository. If we start adding more and more information here nobody is going to update the (development) docs pages and we'll have the development up-to-date development pages here. I think the readme already contains to much information now. As a new developer the first thing you need to do is install eclipse and that information is on the docs page and the readme links to that page. Thus a developer already has to check different locations for information. So I think the information here should be as limited as relevant and we should update the information in the docs repository.

**Comment by davidgraeff** [comment]
If you look at the docs commits, you'll see that I'm slowly working through the pages.

What we have at the moment is absolutely not contributor friendly (target audience: a person with average programming knowledge, interested on how to get things done). A lot of the inner workings (implementation details) are mixed with how to develop a binding. And you want to put implementation details of the buildsystem for this particular repo into that mix as well.

I would really like to write a pictured guide on how to develop a binding, including all necessary concepts with how-to examples. But I don't like the current incoherence with xml-files/java-code. I have developed an annotation based solution, but I don't know where to present that for people to discuss about it, I don't know how to contribute to core as people over there are not even sure what they want.

Apart from that, buildsystem related stuff belongs into the actual repo. It is a reference for fellow maintainers mainly, not soo much for binding developers. Those will probably follow that future step by step guide.

**Comment by davidgraeff** [comment]
I have rewritten the developer docs section and submitted the PR already, this part is integrated. Closing now.

**Pull request closed without merging**
