### PR TITLE
[mihome] fix #2957 & add device inclusion to gateway (#2851)

### LINKED ISSUE #2957: [MIHOME]  "zero-fire" 1 Channel Wall Switch not working
I have 2  Xiaomi "zero-fire" Wall Switch
1 is one button and another one is 2 buttons.

2 buttons works fine and can be auto discovered but 1 button wall switch cant be discovered.
Manually add the thing and show online but actually not working.

**openhab.log :** 

[ERROR] [ndler.XiaomiAqaraActorSwitch1Handler] - Can't handle command ON on channel mihome:ctrl_ln1:158d0001f99045:ch1

**MI Home APPS gateway information :** 

version code：158
网关ID57831448
Zigbee通道：0
网关信息：
null

子设备信息：
**[{"model":"lumi.ctrl_ln1.aq1","did":"lumi.158d0001f99045","name":"AC3"},**  **------> not working**
{"model":"lumi.ctrl_ln2.v1","did":"lumi.158d0001da64da","name":"AC2 \/ AC1"},{"model":"lumi.sensor_ht.v1","did":"lumi.158d0001c2c368","name":"A1"},{"model":"lumi.sensor_ht.v1","did":"lumi.158d0001c2aeea","name":"A2"},{"model":"lumi.sensor_ht.v1","did":"lumi.158d0001c2b7ea","name":"A3"},{"model":"lumi.sensor_ht.v1","did":"lumi.158d0001b70b02","name":"MIS Temperature"},{"model":"lumi.sensor_ht.v1","did":"lumi.158d0001b70b32","name":"Server Room Temperature"},{"model":"lumi.sensor_ht.v1","did":"lumi.158d0001c2af3c","name":"Voice Temperature"}]

I'm using OH2 snapshot and uploaded the latest mihome binding from 
https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.mihome/2.2.0-SNAPSHOT/

Thanks.

### PR DESCRIPTION
**Pull request by dimalo**
Hi all!
After a while without any updates here comes a little one:
- __improvement:__ you can now trigger inclusion mode of the gateway from the binding (see #2851)! Have a look in the readme, there you have an example of a switch item for that. As the gateway only accepts new devices for 30sec after activation, it's hardcoded into the binding, that the channel resets to OFF 30sec after the ON command
- __bugfix:__ implemented a small fix for the issue #2957, so that the model `ctrl_ln1.aq1` is now discovered correctly
- __bugfix:__ reformatted all xml files to only have tabbed whitespace

Download link for snapshot JAR:
https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.mihome/2.3.0-SNAPSHOT/org.openhab.binding.mihome-2.3.0-SNAPSHOT.jar

### CODE REVIEW

**Comment by kubawolanin** [comment]
Hey @dimalo ! Awesome stuff, thank you so much for your update.
Will test it this week.

BTW. Did you know you can also [turn the radio on and off](https://github.com/openhab/openhab2-addons/pull/2548#issuecomment-368037343)? ;-) I've tested it with MiIO binding, but I believe it should work with mihome binding as well.

**Comment by dimalo** [comment]
hey @kubawolanin,
yeah I've read it your comment.
Not sure if the awesome sound quality of this thing is worth it 😆

**Comment by tavalin** [comment]
Hi guys, quick question about the inclusion mode...what are you thoughts about trigging this mode during the binding device discovery? So when OH runs the device discovery the gateway is put into inclusion mode to allow new devices to join?

**Comment by servim** [comment]
> Download link for snapshot JAR:
Clean installation openHAB2
Copied the bind file to the directory
Enabled debug
In the application, the android turned on / off the switch
in the log file the following lines:

```
2018-03-07 12:03:41.442 [DEBUG] [discovery.XiaomiItemDiscoveryService] - Detected Xiaomi smart device - sid: 286c078921f5 model: gateway
2018-03-07 12:03:47.884 [DEBUG] [.mihome.internal.socket.XiaomiSocket] - Received Datagram from 192.168.215.140:4321 on Port 9898
2018-03-07 12:03:47.885 [DEBUG] [discovery.XiaomiItemDiscoveryService] - Unknown discovered model: ctrl_ln1.aq1
2018-03-07 12:03:51.415 [DEBUG] [.mihome.internal.socket.XiaomiSocket] - Received Datagram from 192.168.215.140:4321 on Port 9898
2018-03-07 12:03:51.416 [DEBUG] [discovery.XiaomiItemDiscoveryService] - Detected Xiaomi smart device - sid: 286c078921f5 model: gateway
2018-03-07 12:03:58.449 [DEBUG] [.mihome.internal.socket.XiaomiSocket] - Received Datagram from 192.168.215.140:4321 on Port 9898
2018-03-07 12:03:58.450 [DEBUG] [discovery.XiaomiItemDiscoveryService] - Unknown discovered model: ctrl_ln1.aq1
2018-03-07 12:04:01.389 [DEBUG] [.mihome.internal.socket.XiaomiSocket] - Received Datagram from 192.168.215.140:4321 on Port 9898
```

**Comment by servim** [comment]
@dimalo a big request to you, please see [my log file](https://github.com/openhab/openhab2-addons/files/1788313/openhab.log)
, nothing was set up on a clean installation of OpenHAB2, no files were created, only additions to the addons directory downloaded from the link above were added (All as told by the message above.).
Several reboots have been made by OpenHAB2. The same problem is on working servers openHAB2.
Thanks!

**Comment by dimalo** [comment]
hi @servim,
thanks for the log. It doesn't show any information about the binding, so I cannot extract any information out of it.
Please set the log level to trace for more detail:
```log:set TRACE org.openhab.binding.mihome```

Then try to add the gateway and afterwards the devices.
If you switch something from the android app and the switch is not recognized is something different than the binding not working with the device.

By the way, which device is it in detail? I only know of one such switch and it is reported to work with the binding.

hey @tavalin,
sounds nice but I have two concerns:
1. you have to have the key entered correctly to be able to activate the mode. So on the very first addition it's simply not possible, as most users do not use the textual config and need to enter the key afterwards.
2. the mode is being cancelled by the gateway after 30sec. this timespan only makes sense when the user is ready to include a device. automatically activating the mode means that until the user is ready to include the device, the mode probably is already cancelled.

So it's not very encouraging for users and on the first setup it's simply not possible.

**Comment by servim** [comment]
Hi @dimalo,
Thank you for helping me. Here is my [device](https://www.gearbest.com/access-control/pp_626698.html).
Here's a new clip from the log file:
```
2018-03-09 14:45:03.595 [TRACE] [g.mihome.handler.XiaomiBridgeHandler] - Received message {"cmd":"get_id_list_ack","sid":"286c078921f5","token":"7j72TM2DVFK9jjil","data":"[\"158d00010c14aa\",\"158d000156e2bd\",\"158d000128b345\",\"158d00013e5f82\",\"158d000113ff30\",\"158d000106ae17\",\"158d0001872b75\",\"158d000149d797\",\"158d0001291464\",\"158d00012bd9f6\",\"158d00010b521f\",\"158d0001a3e90b\",\"158d00015b6161\",\"158d0001832cf4\",\"158d0001d78d81\",\"158d0001643f50\",\"158d0001d475c4\",\"158d0001d72e12\",\"158d000113e072\",\"158d0001875e77\",\"158d00017142a0\",\"158d000101c0d3\",\"158d0001bc2187\",\"158d000103ebf0\",\"158d0001f9add2\",\"158d00010b4a24\",\"158d0001b7b753\",\"158d0001b7b6af\"]"}
2018-03-09 14:45:03.634 [DEBUG] [g.mihome.handler.XiaomiBridgeHandler] - Send to bridge mihome:bridge:286c078921f5: {"cmd": "read", "sid": "158d0001f9add2"}
2018-03-09 14:45:03.634 [TRACE] [.mihome.internal.socket.XiaomiSocket] - Sending message: {"cmd": "read", "sid": "158d0001f9add2"} to /192.168.215.140:9898
2018-03-09 14:45:03.968 [TRACE] [g.mihome.handler.XiaomiBridgeHandler] - Received message {"cmd":"read_ack","model":"ctrl_ln1.aq1","sid":"158d0001f9add2","short_id":20559,"data":"{\"voltage\":3600,\"channel_0\":\"off\"}"}
2018-03-09 14:45:03.968 [TRACE] [g.mihome.handler.XiaomiBridgeHandler] - Updated "last time seen" for device 158d0001f9add2
2018-03-09 14:45:03.969 [DEBUG] [g.mihome.handler.XiaomiBridgeHandler] - Device 158d0001f9add2 honored read request
2018-03-09 14:45:03.969 [DEBUG] [discovery.XiaomiItemDiscoveryService] - Unknown discovered model: ctrl_ln1.aq1
2018-03-09 15:10:08.348 [TRACE] [g.mihome.handler.XiaomiBridgeHandler] - Received message {"cmd":"report","model":"ctrl_ln1.aq1","sid":"158d0001f9add2","short_id":20559,"data":"{\"channel_0\":\"on\"}"}
2018-03-09 15:10:08.348 [TRACE] [g.mihome.handler.XiaomiBridgeHandler] - Updated "last time seen" for device 158d0001f9add2
2018-03-09 15:10:08.348 [DEBUG] [discovery.XiaomiItemDiscoveryService] - Unknown discovered model: ctrl_ln1.aq1

```
In the inbox are 27 devices + gateway. This switch is not there, it was not automatically found, like the other 27 devices. Maybe I have an old binding without the support of this switch?

`188 │ Active   │  80 │ 2.3.0.201803061157     │ Xiaomi Mi Smart Home Binding
`
Thanks!

**Comment by dimalo** [comment]
hey @servim,
sorry to hear it's not working for you. Taht's strange, actually I checked it a couple of times in the code and everything should be fine. You shouldn't get the line
`2018-03-09 14:45:03.969 [DEBUG] [discovery.XiaomiItemDiscoveryService] - Unknown discovered model: ctrl_ln1.aq1`
Please try to setup with the latest snapshot, to be sure the version you've got is the latest.
Let me know if I shall compile a jar for you to be sure.

**Comment by servim** [comment]
I'm doing this in the last picture # 1224
But the binding was not installed through paper, but downloaded from the link from the first post

> Ссылка для загрузки снимка JAR: 
https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.mihome/2.3.0-SNAPSHOT/org.openhab.binding. mihome-2.3.0-SNAPSHOT.jar

Later, I'll try to fix the binding from the paper, the result will tell here

**Comment by servim** [comment]
```
apt remove openhab2 --purge
apt install openhab2
```
```
paperUI -> Add-ons -> Bindings ->Xiaomi Mi Smart Home Binding ->install
Inbox -> (+) -> Xiaomi Mi Smart Home Binding ->Xiaomi Gateway

```
After adding the bridge, in the inbox 28 devices (27 + gateway)
There is no switch ctrl_ln1.aq1 :(
When adding a device manually: Xiaomi "zero-fire" 1 Channel Wall Switch
(I understand the type of device correctly?) it is added as: mihome:ctrl_ln1:158d0001f9add2:ch1
I thought it should be: mihome:ctrl_ln1.aq1:158d0001f9add2:ch1 Were it all right?
sw

Later, I'll try to remove the switch from the gateway and re-add it, does it make sense? Physically, this is not near me, I need to go there, the adjustment is done remotely.

**Comment by dimalo** [comment]
really still no idea why it does not work and brings the "unknown model" message.
here is the latest build:
[org.openhab.binding.mihome-2.3.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab2-addons/files/1799820/org.openhab.binding.mihome-2.3.0-SNAPSHOT.jar.zip)

it is correct, that it's added as `mihome:ctrl_ln1` - the "old" model has the same functions, so why not use the same thing for that. All I did was add the mapping from `ctrl_ln1.aq1` to `ctrl_ln1`.

**Comment by servim** [comment]
#1225 
binding is installed through paper, without changes
`194 ¦ Active   ¦  80 ¦ 2.3.0.201803101457     ¦ Xiaomi Mi Smart Home Binding
`

> here is the latest build:
org.openhab.binding.mihome-2.3.0-SNAPSHOT.jar.zip

`194 │ Active   │  80 │ 2.3.0.201803102140     │ Xiaomi Mi Smart Home Binding
`

the switch appeared in the inbox!
```
2018-03-11 09:45:04.613 [TRACE] [g.mihome.handler.XiaomiBridgeHandler] - Received message {"cmd":"get_id_list_ack","sid":"286c078921f5","token":"iMqo59aSrdeN7wtv","data":"[\"158d00010c14aa\",\"158d000156e2bd\",\"158d000128b345\",\"158d00013e5f82\",\"158d000113ff30\",\"158d000106ae17\",\"158d0001872b75\",\"158d000149d797\",\"158d0001291464\",\"158d00012bd9f6\",\"158d00010b521f\",\"158d0001a3e90b\",\"158d00015b6161\",\"158d0001832cf4\",\"158d0001d78d81\",\"158d0001643f50\",\"158d0001d475c4\",\"158d0001d72e12\",\"158d000113e072\",\"158d0001875e77\",\"158d00017142a0\",\"158d000101c0d3\",\"158d0001bc2187\",\"158d000103ebf0\",\"158d0001f9add2\",\"158d00010b4a24\",\"158d0001b7b753\",\"158d0001b7b6af\"]"}
2018-03-11 09:45:04.692 [DEBUG] [g.mihome.handler.XiaomiBridgeHandler] - Send to bridge mihome:bridge:286c078921f5: {"cmd": "read", "sid": "158d0001f9add2"}
2018-03-11 09:45:04.693 [TRACE] [.mihome.internal.socket.XiaomiSocket] - Sending message: {"cmd": "read", "sid": "158d0001f9add2"} to /192.168.215.140:9898
2018-03-11 09:45:05.160 [TRACE] [g.mihome.handler.XiaomiBridgeHandler] - Received message {"cmd":"read_ack","model":"ctrl_ln1.aq1","sid":"158d0001f9add2","short_id":20559,"data":"{\"voltage\":3600,\"channel_0\":\"off\"}"}
2018-03-11 09:45:05.161 [TRACE] [g.mihome.handler.XiaomiBridgeHandler] - Updated "last time seen" for device 158d0001f9add2
2018-03-11 09:45:05.163 [DEBUG] [g.mihome.handler.XiaomiBridgeHandler] - Device 158d0001f9add2 honored read request
2018-03-11 09:45:05.165 [DEBUG] [discovery.XiaomiItemDiscoveryService] - Detected Xiaomi smart device - sid: 158d0001f9add2 model: ctrl_ln1.aq1
2018-03-11 09:45:05.172 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'mihome:ctrl_ln1:158d0001f9add2' to inbox.
2018-03-11 09:49:18.841 [TRACE] [g.mihome.handler.XiaomiBridgeHandler] - Received message {"cmd":"report","model":"ctrl_ln1.aq1","sid":"158d0001f9add2","short_id":20559,"data":"{\"channel_0\":\"on\"}"}
2018-03-11 09:49:18.842 [TRACE] [g.mihome.handler.XiaomiBridgeHandler] - Updated "last time seen" for device 158d0001f9add2
2018-03-11 09:49:18.843 [DEBUG] [discovery.XiaomiItemDiscoveryService] - Detected Xiaomi smart device - sid: 158d0001f9add2 model: ctrl_ln1.aq1

```
added bridge and switch to things, created the file xiaomi.items:

`Switch  room_wall_switch    "Wall Switch [%s]"  <switch>    { channel="mihome:ctrl_ln1:158d0001f9add2:ch1" } 
`
from paper switched off switch:

```
2018-03-11 10:34:31.442 [DEBUG] [home.handler.XiaomiDeviceBaseHandler] - Device 158d0001f9add2 on channel mihome:ctrl_ln1:158d0001f9add2:ch1 received command OFF
2018-03-11 10:34:31.443 [WARN ] [g.mihome.handler.XiaomiBridgeHandler] - No key set in the gateway settings. Edit it in the configuration.
2018-03-11 10:34:31.444 [DEBUG] [g.mihome.handler.XiaomiBridgeHandler] - Send to bridge mihome:bridge:286c078921f5: {"cmd": "write", "sid": "158d0001f9add2", "data": "{\"channel_0\": \"off\", \"key\": \""}"}
2018-03-11 10:34:31.446 [TRACE] [.mihome.internal.socket.XiaomiSocket] - Sending message: {"cmd": "write", "sid": "158d0001f9add2", "data": "{\"channel_0\": \"off\", \"key\": \""}"} to /192.168.215.140:9898
2018-03-11 10:34:31.447 [ERROR] [ndler.XiaomiAqaraActorSwitch1Handler] - Can't handle command OFF on channel mihome:ctrl_ln1:158d0001f9add2:ch1
2018-03-11 10:34:31.452 [DEBUG] [.mihome.internal.socket.XiaomiSocket] - Received Datagram from 192.168.215.140:9898 on Port 9898
2018-03-11 10:34:31.455 [TRACE] [g.mihome.handler.XiaomiBridgeHandler] - Received message {"cmd":"write_ack","sid":"158d0001f9add2","data":"{\"error\":\"Invalid key len\"}"}
2018-03-11 10:34:31.456 [TRACE] [g.mihome.handler.XiaomiBridgeHandler] - Updated "last time seen" for device 158d0001f9add2
2018-03-11 10:34:31.457 [DEBUG] [g.mihome.handler.XiaomiBridgeHandler] - Device 158d0001f9add2 honored write request
2018-03-11 10:34:31.458 [DEBUG] [home.handler.XiaomiDeviceBaseHandler] - Item got update: {"cmd":"write_ack","sid":"158d0001f9add2","data":"{\"error\":\"Invalid key len\"}"}

```
I was sure that the developer's key only affects the management of the gateway, is not it?
Added a developer key, switched the switch:

```
2018-03-11 10:40:11.743 [DEBUG] [home.handler.XiaomiDeviceBaseHandler] - Device 158d0001f9add2 on channel mihome:ctrl_ln1:158d0001f9add2:ch1 received command ON
2018-03-11 10:40:11.748 [DEBUG] [g.mihome.handler.XiaomiBridgeHandler] - Send to bridge mihome:bridge:286c078921f5: {"cmd": "write", "sid": "158d0001f9add2", "data": "{\"channel_0\": \"on\", \"key\": \"685407AD07D83F38707C7CFA281532ED"}"}
2018-03-11 10:40:11.752 [TRACE] [.mihome.internal.socket.XiaomiSocket] - Sending message: {"cmd": "write", "sid": "158d0001f9add2", "data": "{\"channel_0\": \"on\", \"key\": \"685407AD07D83F38707C7CFA281532ED"}"} to /192.168.215.140:9898
2018-03-11 10:40:11.753 [ERROR] [ndler.XiaomiAqaraActorSwitch1Handler] - Can't handle command ON on channel mihome:ctrl_ln1:158d0001f9add2:ch1
2018-03-11 10:40:11.756 [DEBUG] [.mihome.internal.socket.XiaomiSocket] - Received Datagram from 192.168.215.140:9898 on Port 9898
2018-03-11 10:40:11.757 [TRACE] [g.mihome.handler.XiaomiBridgeHandler] - Received message {"cmd":"write_ack","model":"ctrl_ln1.aq1","sid":"158d0001f9add2","short_id":20559,"data":"{\"voltage\":3600,\"channel_0\":\"off\"}"}
2018-03-11 10:40:11.757 [TRACE] [g.mihome.handler.XiaomiBridgeHandler] - Updated "last time seen" for device 158d0001f9add2
2018-03-11 10:40:11.757 [DEBUG] [g.mihome.handler.XiaomiBridgeHandler] - Device 158d0001f9add2 honored write request
2018-03-11 10:40:11.758 [DEBUG] [home.handler.XiaomiDeviceBaseHandler] - Item got update: {"cmd":"write_ack","model":"ctrl_ln1.aq1","sid":"158d0001f9add2","short_id":20559,"data":"{\"voltage\":3600,\"channel_0\":\"off\"}"}
2018-03-11 10:40:11.760 [TRACE] [.mihome.internal.socket.XiaomiSocket] - Data received and notified 1 listeners
2018-03-11 10:40:11.760 [TRACE] [.mihome.internal.socket.XiaomiSocket] - Thread Thread[Thread-59,5,main] waiting for data on port 9898
2018-03-11 10:40:11.861 [DEBUG] [.mihome.internal.socket.XiaomiSocket] - Received Datagram from 192.168.215.140:4321 on Port 9898
2018-03-11 10:40:11.862 [TRACE] [g.mihome.handler.XiaomiBridgeHandler] - Received message {"cmd":"report","model":"ctrl_ln1.aq1","sid":"158d0001f9add2","short_id":20559,"data":"{\"channel_0\":\"on\"}"}
2018-03-11 10:40:11.862 [TRACE] [g.mihome.handler.XiaomiBridgeHandler] - Updated "last time seen" for device 158d0001f9add2
2018-03-11 10:40:11.864 [DEBUG] [home.handler.XiaomiDeviceBaseHandler] - Item got update: {"cmd":"report","model":"ctrl_ln1.aq1","sid":"158d0001f9add2","short_id":20559,"data":"{\"channel_0\":\"on\"}"}

```
I do not properly use the channel? What channels and triggers work with this switch? What is it?:

`\"voltage\":3600
`
can you get the load, in the application android load is measured:

screenshot_20180311-111732

Thanks!

**Comment by dimalo** [comment]
hi @servim,
ok, so the only problem was, that the snapshot was not compiled from the PR... 😞 

No the key is needed to write to every device.

The device does not report power statistics. `\"voltage\":3600` is a nonsense value. All the battery powered devices report the battery voltage with this message. For powered devices just 3600mV is sent. so no chance to get the same functionality as with the app unless the device reports power usage.

So now all the changes are tested and working. @servim thanks for your patience and help!

@kaikreuzer @martinvw 
we're all set and hoping for your review and merge. not sure how to resolve the conflicts, any hints?

**Comment by martinvw** [comment]
@dimalo if you could rebase it should be fine after resolving that conflict during rebase, its because @wborn has cleaned all xml's to contain tabs only as we agreed upon in our code guidelines.

I think the quickest could be to either have a smart program to do the merge which understands that @wborn only did white space changes, or choose your files and replaces all spaces to tabs after resolving the conflicts.

**Comment by dimalo** [comment]
thanks @martinvw!
yeah I actually also replaced all spaces with tabs in this commit 😄 
Now it's good, rebased squashed and happy to be merged...

**Comment by servim** [comment]
Hi @dimalo, Thanks for your work!
but I still have a couple of questions from my previous post
1. If you do not specify a developer key for the gateway, the switch will not work?
```
2018-03-11 10:34:31.442 [DEBUG] [home.handler.XiaomiDeviceBaseHandler] - Device 158d0001f9add2 on channel mihome:ctrl_ln1:158d0001f9add2:ch1 received command OFF
2018-03-11 10:34:31.443 [WARN ] [g.mihome.handler.XiaomiBridgeHandler] - No key set in the gateway settings. Edit it in the configuration.

```
I thought the developer key is only needed to manage the gateway.

2. The switch is found in the inbox, but I can not manage it:
```
2018-03-11 10:40:11.752 [TRACE] [.mihome.internal.socket.XiaomiSocket] - Sending message: {"cmd": "write", "sid": "158d0001f9add2", "data": "{\"channel_0\": \"on\", \"key\": \"685407AD07D83F38707C7CFA281532ED"}"} to /192.168.215.140:9898
2018-03-11 10:40:11.753 [ERROR] [ndler.XiaomiAqaraActorSwitch1Handler] - Can't handle command ON on channel mihome:ctrl_ln1:158d0001f9add2:ch1

```
maybe I did not create the item correctly?

`Switch room_wall_switch "Wall Switch [%s]" <switch> { channel="mihome:ctrl_ln1:158d0001f9add2:ch1" }
`

Sorry for my English :(

**Pull request merged**
