### PR TITLE
removing ESH p2 repo references

### PR DESCRIPTION
**Pull request by kaikreuzer**
This PR requires https://github.com/openhab/openhab-core/pull/341 to be merged first.

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by wborn** [comment]
It properly downloads any missing artifacts from the openhab-artifactory-snapshot repository when I do a local build. WDYT @pfink?

**Comment by kaikreuzer** [comment]
@pfink is already happy as the sandbox build works as expected - so you can merge it :-)

**Comment by wborn** [comment]
Great! I'm looking forward to a pipeline milestone build. :-)

**Comment by pfink** [comment]
@wborn: Thanks for pinging me, Kai and me already agreed on removing the p2 references last week :)

**Pull request merged**
