### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vegarroe**
Added Aqara Temp, humidity and pressure sensor to things and items example.

Signed-off-by: Vegar Røyset <vegarroyset@gmail.com> (github: vegarroe)

### CODE REVIEW

**Comment by martinvw** [comment]
@dimalo can you take a quick look?

**Comment by dimalo** [comment]
LGTM

**Comment by martinvw** [comment]
@vegarroe do you agree to the DCO?  see http://docs.openhab.org/developers/contributing/contributing.html#sign-your-work

It would be great if you could include a `Signed-off-by` (to certify that you wrote it or otherwise have the right to pass it on as an open-source), for such a small change its okay to just write it down here.

**Comment by martinvw** [comment]
And of course @vegarroe thanks for your contribution, however because its (a little) more then a trivial contribution I would really appreciate you to either sign off the commit or in another way agree to the DCO and for example enter a full sign-off in a message here.

**Comment by martinvw** [comment]
Thanks!

**Pull request merged**
