### PR TITLE
[nikohomecontrol] Support for newer gson version

### PR DESCRIPTION
**Pull request by mherwege**
Made inner classes static to support newer gson version.
Use MQTT connection status callback to log connection errors.
Some cleanup.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Any idea why the diff shows the classes to be completely changed? Makes reviewing pretty difficult...

**Comment by mherwege** [comment]
@kaikreuzer It is probably because there is an issue with my formatter. Getting my dev environment back in a workable state wasn’t easy. However, I did notice that the diff on the github website, when using the ignoring whitespace differences function, correctly shows the code differences. No clue where the whitespace differences it chokes on are though.

**Comment by mherwege** [comment]
@kaikreuzer My IDE setup had converted the line endings to Windows line endings. Now corrected.

**Comment by martinvw** [comment]
@openhab/2-x-add-ons-maintainers anyone else?

**Pull request merged**
