### PR TITLE
[miele] fixed bullet point list and link to source repo

### PR DESCRIPTION
**Pull request by kaikreuzer**

### CODE REVIEW

**Comment by J-N-K** [comment]
Can you fix the sign-off?

**Comment by kaikreuzer** [comment]
Should not be relevant for a small patch exception - I didn't change any content...

**Comment by J-N-K** [comment]
So what is the exact definition of "small patch"? I had "not more than one line" in mind.

**Comment by kaikreuzer** [comment]
Well, any change that does not contain any copyrightable content, really. In this case, I merely added hyphens and fixed a link.

**Pull request merged**
