### PR TITLE
[pentair] Support for Feature circuits 1-8

### PR DESCRIPTION
**Pull request by mgranell**
[pentair] Add support for feature circuits

Add supports for feature circuits as well as AUX circuits.

Tested and working in local installation.

### CODE REVIEW

**Comment by cweitkamp** [comment]
Thank you very much for your first contribution. May I ask you to add a note to the README.md about the new channels?

**Comment by mgranell** [comment]
Updated README.md with examples of using feature circuit

**Comment by mgranell** [comment]
I squashed the commits, is that the right approach? or review/squash/approve?

**Comment by martinvw** [comment]
Thanks

**Pull request merged**
