### PR TITLE
adds Fahrenheit support to the tesla binding.

### PR DESCRIPTION
**Pull request by digitaldan**
Signed-off-by: Dan Cunningham <dan@digitaldan.com>

### CODE REVIEW

**Comment by digitaldan** [comment]
@kgoderis  Apologies for the massive formatting change on TeslaChannelSelect.java, the changes in the class are actually minimal, the only parts that changed will have a reference to the static function "CelsiusToFahrenheit"  .

**Comment by kgoderis** [comment]
Ah, does this mean that there is finally a fellow Tesla driver amongst us? ;-) ;-) did you have the change to test the binding? so far I was the only one to use it, and there will certainly be things I have overlooked. Beware, I have not upgraded the binding since a long time, so a lot of data returned by the car, after the launch of the Model S 90 and Model X, and autopilot, are not yet elaborated. These will show up in the logs

**Comment by digitaldan** [comment]
First off, thanks for doing so much work on the binding!  
>Ah, does this mean that there is finally a fellow Tesla driver amongst us? ;-) ;-) 

Yep , had mine for almost a year but have not had a ton of time until now to contribute to the binding, which I'm ebarrsed to admit since its such a HUGE toy for a software geek. 
> so a lot of data returned by the car, after the launch of the Model S 90 and Model X, and autopilot, are not yet elaborated. These will show up in the logs

 It does have all the autopilot/autopark stuff, so i can see those in the logs.  I have another branch where I have started adding additional channels, but its been a little while since I worked on it.  I figured lets start with getting the temperature functionality working first ;-) 

> did you have the change to test the binding? so far I was the only one to use it, and there will certainly be things I have overlooked. 

 I have not had to change anything, but i am seeing an issue with commands not being sent/ swallowed most of the time, I suspect they are being queued in the throttler but have not dug in yet to check, that was next on my list.  Also the binding seems to get a 401 not authorized response frequently, I assume the login token has timed out, but it takes a while for it to reconnect (EVENT_RECOVERY_INTERVAL time to be exact), I was also thinking about looking at this second.

**Comment by kgoderis** [comment]
> did you have the change to test the binding? so far I was the only one to use it, and there will certainly be things I have overlooked.
> I have not had to change anything, but i am seeing an issue with commands not being sent/ swallowed most of the time, I suspect they are being queued in the throttler but have not dug in yet to check, that was next on my list. Also the binding seems to get a 401 not authorized response frequently, I assume the login token has timed out, but it takes a while for it to reconnect (EVENT_RECOVERY_INTERVAL time to be exact), I was also thinking about looking at this second.

The back-end of Tesla is a real black-box. It is quite flaky from time to time, with http 500 errors as well. The expiration of the token is not really constant either. Their OAuth implementation does adhere fully to the standard. I have put in that throttler because in the early days when people figured out the API, and tried to abuse that/push the Tesla servers to the limit, Tesla closed down user accounts. Since recently, sometimes commands do not execute well, and I am not sure whether that is due to the servers or the firmware in the car.

**Comment by kaikreuzer** [comment]
Looks as if this binding would need https://github.com/eclipse/smarthome/issues/601...
Not ideal to only show "°" in the label, but ok for me for now.
@kgoderis Ok to merge?

**Comment by kgoderis** [comment]
Ok for me as well, but I have no experience with the stuff discussed in https://github.com/eclipse/smarthome/issues/601

**Comment by kgoderis** [comment]
@digitaldan Would you be interesting in testing and finetuning the connection part of the Tesla binding. The last few days I see massive issues with the Tesla server infrastructure, with a lot of 

'408:Request Timeout'
'500:Internal Server Error'
'502:Bad Gateway'

http error codes. It has never been this worse before. The consequence is that the Thing is put OFFLINE, and no further commands are handled anymore by the runtime.

**Comment by digitaldan** [comment]
@kgoderis the next few weeks may be tough for me, so it could be a little while before I can spend time looking at it, but yes I would like to help out and finetune a solution.

**Pull request merged**
