### PR TITLE
[souliss] Souliss Binding initial contribution

### PR DESCRIPTION
**Pull request by fazioa**
This is a working initial contribution for Souliss Binding for Openhab 2.

[Souliss](http://www.souliss.net/) is a networking framework for Arduino and compatibles boards.

It is an open-source and community driven project, This is the [wiki](https://github.com/souliss/souliss/wiki) and this is the [Community](https://github.com/souliss/souliss/wiki/Community).

To download compiled binding: [https://github.com/souliss/bindingopenhab2/releases](https://github.com/souliss/bindingopenhab2/releases)

Signed-off-by: Tonino Fazio

### CODE REVIEW

**Comment by fazioa** [comment]
Signed-off-by: Tonino Fazio

**Comment by fazioa** [comment]
Hi, what should I do now to complete the compilation?

**Comment by fazioa** [comment]
Signed-off-by: Tonino Fazio <fazioa@gmail.com>

**Comment by kaikreuzer** [comment]
Normally, you can reopen PRs, but here it says that you have deleted your repo from where the PR originated, so you will have to create a new one.

**Pull request closed without merging**
