### PR TITLE
Not exported packages renamed to .internal

### PR DESCRIPTION
**Pull request by svilenvul**
Some packages exported, when classes are interface for service registration.
Service component descriptions updated.

See openhab/static-code-analysis#100

Signed-off-by: Svilen Valkanov <svilen.valkanov@musala.com>

### CODE REVIEW

**Comment by martinvw** [comment]
Requesting rebuild

**Comment by martinvw** [comment]
@svilenvul i want to delay this after the upcoming release, although I think it's complex to review.

**Comment by kaikreuzer** [comment]
I am also definitely for waiting until next week 👍

**Comment by davidgraeff** [comment]
I highly recommend not to merge this huge move everything around commit as long as there a PRs open, that are heavily affected.

**Comment by hakan42** [comment]
Could we split up this PR so we have one PR for each binding? That way, rebasing would be much easier for the binding authors.

Else, I believe we will never find a moment where no PRs are open...

**Comment by martinvw** [comment]
@svilenvul also note that the build fails repeatedly

[ERROR] Failed to execute goal org.openhab.tools:static-code-analysis:0.0.6:checkstyle (default) on project org.openhab.binding.kostalinverter: Unable to execute mojo: An error has occurred in Checkstyle report generation. Failed during checkstyle configuration: Exception was thrown while processing /home/travis/build/openhab/openhab2-addons/addons/binding/org.openhab.binding.kostalinverter/META-INF/MANIFEST.MF: -2 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.openhab.binding.kostalinverter

**Comment by svilenvul** [comment]
@martinvw, thanks it was a typo in the manifest header :)

**Comment by martinvw** [comment]
@svilenvul @kaikreuzer what is your idea about the other remarks, I think we are going to hurt some of the bigger refactorings (which are already taking some time of us to get completely reviewed) which are pending by merging this, so what is wise?

**Comment by kaikreuzer** [comment]
Imho it should not be too hard to rebase any open PR onto the master, once this is merged; I'd hope that the git mechanisms are clever enough to get that done almost automatically, since we are mainly talking about moving files to a new location.

**Comment by davidgraeff** [comment]
It just pisses off people that work in their freetime on bindings and go through the relatively long review process (a proper review is a good think of course).
This is basically an automatically generated commit, it should be possible to exclude all binding directories where there is an open pr or that have changed within the last month (=actively maintained) and instead extend Travis ci to refuse new merge requests if the directory structure is incorrect. 
Just my 2ct.

**Comment by martinvw** [comment]
> It just annoyes people that work in their freetime on bindings and go through the relatively long review process (a proper review is a good think of course).
This is basically an automatically generated commit, it should be possible to exclude all binding directories where there is an open pr or that have changed within the last month (=actively maintained) and instead extend Travis ci to refuse new merge requests if the directory structure is incorrect.
Just my 2ct.

Hello @davidgraeff, I do understand and git is not that good in this. The problem is that our time is also limited and we want to put the code-standards higher and use automatic checking to make the review process shorter and less error-prone. Unfortunately we can not guard the repository without fixing everything first. 

> ... instead extend Travis ci to refuse new merge requests if the directory structure is incorrect.

Because the tooling (which we also had to builder) is not smart enough to know that it should not reject your (eg network binding) build because the 'allplay' binding forgot the hide its classes in the internal package. And it will require major changes to make the build tooling smart enough if it is even possible. So the only way to enable this check is to fix everything and then enable the check to make the actual build fail if the change or new binding does not follow this rule.

I checked some of your PR's to get insight in the impact.

https://github.com/openhab/openhab2-addons/pull/1781

Had one really small merge conflict, you changed a single file which was moved so you have to apply the changes to the moved files instead.

https://github.com/openhab/openhab2-addons/pull/2380

Was a more painful but if you squash it before rebasing it might work out okay-ish.

If you can free up some time to fix #2380 quickly then we can ask @kaikreuzer very politely to give it precedence (it is small so should not be that problematic for him) and we could merge that one before this one.

**Comment by svilenvul** [comment]
It has been a while since we discussed the topic for the last time. I see some conflicts now.

Please keep in mind that the check is with severity error, so the next release of the tool that includes it will break the OH2 addons build.

Should I rebase the branch ?

**Comment by svilenvul** [comment]
I have tried a rebase, but the result was terrible :-)

**Pull request closed without merging**
