### PR TITLE
Made thing configuration consistant throughout the file Signed-off-by: Kim Skatun <skatun@gmail.com> (github: github_handle)

### PR DESCRIPTION
**Pull request by skatun**
In the documentation it says:

Thing netatmo:NAMain:home:inside "Netatmo Inside" [ id="aa:aa:aa:aa:aa:aa" ]

and

Thing NAMain livingroom [ id="aa:aa:aa:aa:aa:aa" ]

According to the ESH docs the second one is the preferred way to use. So the syntax is Thing <thingTypeId> <thingId> [] . As a short cut it is possible to skip the Thing in the textual configuration, however this confuses the average user, so I changed the first one to to second one.

### CODE REVIEW

**Comment by skatun** [comment]
Not quite sure how to sign it off in the webbrowser.... I added the text to the pull request, lets see if that does the trick

**Comment by cweitkamp** [comment]
I am afraid not. The Signed-off-by line has to be in your commit message (see https://github.com/openhab/openhab2-addons/pull/3706#issuecomment-402296431 for a small tutorial).

If that does not work please state it here in a message that you do agree and conform to the DCO and we are able to merge.

**Comment by cweitkamp** [comment]
@skatun I just got the hint, that we can merge this with "small patch exception". Thanks for your patience.

**Comment by cweitkamp** [comment]
FTR: Related to #3871

**Pull request merged**
