### PR TITLE
[openhabcloud] Update README.md

### PR DESCRIPTION
**Pull request by marcopelly**
Explicitly added the need to install the add-on of openHAB Cloud connector

### CODE REVIEW

**Comment by wborn** [comment]
I agree it would help to instruct how to install an add-on. But this info applies to every add-on and it could also be generated. See https://github.com/openhab/website/issues/152.

**Comment by davidgraeff** [comment]
The change is just one sentence that indeed helps in this context. Can you please split up by sentences? In future reviews it is than more obvious if just one sentence got changed or added.

**Comment by wborn** [comment]
There seems to be common agreement add-on installation should not be part of every add-on documentation. See https://github.com/openhab/openhab2-addons/pull/3162.

**Comment by davidgraeff** [comment]
I see, in this case we cannot merge. @wborn can you please stop calling specific patterns "common agreement" because neither me nor J-N-K nor any other new maintainer agreed on those or even know about those pattern and it was just you and Kai actually.

**Comment by wborn** [comment]
OK let's call it something else. But if this gets merged, one day a similar PR for every other add-on might also get merged for the same reasons.

**Comment by J-N-K** [comment]
In general I agree with @wborn. But we should get the documentation update. After reading the issues linked above it is not clear to me what is missing and how to proceed.

**Comment by Hilbrand** [comment]
This isn't about adding installation. But the fact that the binding triggers the generation of the keys. This isn't clear from the current documentation as it refers to the generic term openHAB runtime. So it makes sense to change something. But I think the first sentence can be changed in: `To authenticate with the openHAB Cloud the openHAB cloud add-on generates two values when the add-on is installed, which need to be entered in your account settings of the openHAB Cloud service.`

**Comment by davidgraeff** [comment]
A new PR is very welcome.
Please remember that the documentation team like to have one sentence per line in readme.md files.

Closing this now.

**Pull request closed without merging**
