### PR TITLE
[netatmo] Made constants and handler packages internal

### PR DESCRIPTION
**Pull request by VelinYordanov**
See eclipse/smarthome#4330

Signed-off-by: VelinYordanov <velin.iordanov@gmail.com>

### CODE REVIEW

**Comment by wborn** [comment]
Code wise this looks good to me. 
Merging this may cause merge conflicts with the Netatmo refactoring (https://github.com/openhab/openhab2-addons/pull/3823) though.

**Comment by wborn** [comment]
Is it OK if we merge this PR @navybk? It may cause some merge conflicts on your refactoring though.

**Comment by navybk** [comment]
I am not quite sure if this is a good idea. It would replace the currently working binding of netatmo with an untested version. As I said, the documentation of netatmo with the "new" api endpoints is incomplete, so it may not work with without errors.
On the other hand, if you feel fine with this, just do it. I wont stop working on this ;)

**Comment by wborn** [comment]
This PR is about moving classes to internal packages and no longer exporting them. So its not your own Netatmo refactoring. This PR causes some merge conflicts on your PR @navybk. ;-)

**Comment by navybk** [comment]
I see. Was in the wrong thread. So just do it!

**Comment by ecki84** [comment]
how can i add valves without the thermostat?
Pending parent object initialization because i dont have the relay or thermostat, only the bridge.

**Pull request merged**
