### PR TITLE
New OH2 Binding KM200

### PR DESCRIPTION
**Pull request by Markinus**
The km200 binding is ported now to OH2. Please check it.
+ Device autodetection
+ Thing autodetection
+ Channel autodetection

### CODE REVIEW

**Comment by kubawolanin** [comment]
Hi @Markinus !
Before we dig into the code, please make sure your PR is compliant with the [Contribution Guidelines](http://docs.openhab.org/developers/contributing/contributing#contribution-guidelines).
For what I see at first glance, you need:
* A full `README.md` documentation describing the usage of this binding.
* `about.html` file containing info about external libs, licensing and attributions

Thank you for your work!
Cheers,
K

**Comment by whopperg** [comment]
Hi @Markinus,
I've just tried this one, but i cant get it to work. it just throws me a bunch of crap (like random ascii chars) in my openhab.log. i guess theres something wrong with the encryption. 
what should i present you for futher troubleshooting?

Cheers,

**Comment by Markinus** [comment]
@whopperg Check your encryption settings, password and hashes.

**Comment by Markinus** [comment]
Hi @kubawolanin,

I think it should be ok now. Take a look, please.

Cheers,
Markus

**Comment by whopperg** [comment]
OK i'm getting closer. How do I generate the MD5Salt or the Private Key? I got the Buderus control App working. so communication with the module is working fine.

Thanks!

**Comment by whopperg** [comment]
Hm - i just tried out to generate the md5 myself by using a string combo of the gateway password and my private password and got this:

`2017-02-02 21:10:31.399 [INFO ] [.binding.km200.internal.KM200Binding] - Update KM200 Binding configuration, it takes a minute....
2017-02-02 21:10:31.399 [INFO ] [.binding.km200.internal.KM200Binding] - Starting communication test..
2017-02-02 21:10:31.527 [INFO ] [.binding.km200.internal.KM200Binding] - Received data..
2017-02-02 21:10:31.528 [INFO ] [.binding.km200.internal.KM200Binding] - Test of the communication to the gateway was successful..
2017-02-02 21:10:31.528 [INFO ] [.binding.km200.internal.KM200Binding] - Init services..
2017-02-02 21:10:31.655 [ERROR] [hab.binding.km200.internal.KM200Comm] - Parsingexception in JSON: A JSONObject text must begin with '{' at 1 [character 2 line 1] data: ÞËJcÓåøî¨�|Ê�â 7Ýxü�Y£y�rÛþ�0/$t�µ÷äòý¥ «¦J¡hæ�ÒÄ+1çDÂÏì�×ô³:ékï�©nrð:�iÙuîµmma±�« OïW�XB�Ò³Ù�c�0üÈÞay[3`,á,)I%dü\
2017-02-02 21:10:31.818 [ERROR] [hab.binding.km200.internal.KM200Comm] - Parsingexception in JSON: A JSONObject text must begin with '{' at 1 [character 2 line 1] data: Æö
é¹Î©Üáum'+Q%ywx9m�jÿÙ<�$ýY*ÍÎf¹®J�*�/\D@oêþ��õé¦§<][ ·;üäÿë[óU�F��|ÃN�%ºHeØêHþ·ÕÒVÅ▒¤®3æ³í©R®@bL&oêþ��õé¦§<][ ·nÍ�º�Ò�#íß¥Zéó�ÔÁØà«PÜªÆpª»ïÅ�
¾5£¥¡céýí0Ð-oæ/L�▒ºª©   �4zJ"ÎEÐ·µLVcÒs¥t£ üîûG
\ù-ÃN�%ºHeØêHþ·ÕÒVÅ▒�¥Þ«å�      SÓÖJXË�sw�ôØÿTþì%ë�ñÚtÝ ¬               �·¾Ù ÊúÈ¯[ÕJ+|HÛ²vE[�Ú�Ì
                                                                                                úsy¶ðÅ�±/ø�P§   áÈ6/Z�&KØè&��É§��å`G�å~|¯Ìri"p�)�C ÕVP�g�ÿè�Á\?¦�"8µyOª��r¿¢yå»�êínVÄ×ê1ôÖd3íÅZ       S±ÕPí×½�$j�LW
·W&ÎFÄØÀØ_.n+³4ä^aûÞÛG�¼oÞp)"Ú³øj�ÔÁØà«PÜªÆpª»�¬¦÷a2� îAí$h     Pj;Óï
Ì¼�g¨ôd��ûä�Çý×xer¾Üwúsy¶ðÅ�±/ø�P§Æ�td6ká~�\Gãm"TíëDùNê¯
Ú¬@á�Sá Ù¢ó¹    Pj;Óï
�SìÔ'á!#sOSÍz¸!m¾�¬O£�ºðW<uM"ÐqRµ0ÿëUÛ$�Ø=Æh°�VJ�ñ;�ÍÉ^Dí�d/ï¢
�SìÔ    êÍ�<>y���Ý%ï�;�Bz#àéFK�'¦'�§Hàc ÔDÐ��&Ê%,?ãeÌûÚñXÚJCHvç¨É^Dí�d/ï¢
¾ÈÇ<rà��Ä��ÛÎ�Y:�iÙuîµmma±�« 9çnç·õÞ[éã°åµâ�Î� ÿs�&ÈÁôn�Û�=�ªKuác�O�!9æ64m�:¬Å0Î´? �qNß+?L¢yå»�êínVÄ×ê1ôÖd3íÅZ  S±ÕPí×½�µpOuÙh¸0ÜÁÛÖ½'_­�n³no³ô�Û:VO
��▒��½LÛí }§øÓàü9àu( AÖòù�½
                           Ló�FÝE�·hR/4ikÑåãØ('íº:�w����4>Ï�¹Ö³¸Ö"ÂØ▒É.;�Ý/
PuTTYPuTTYPuTTYPuTTY2017-02-02 21:10:31.937 [ERROR] [hab.binding.km200.internal.KM200Comm] - Parsingexception in JSON: A JSONObject text must begin with '{' at 1 [character 2 line 1] data: Ïæ�=R�ébfõådjQ{ËxôÓç
                   s¬vÜ°'Âs�`�ÿÛéG°�"�­�W¶QªÞ3  HE�y��n
L0w´ØnÓ^1m.1½­Åþ�jÞÊ5ÑÐÊ,Ò!Ö@[­t�TA��ëã�Ó�n
L0w´ØnÓ^1m.1��N7ÆfêoÀÌ'iGh´��7L!11�3¸`ÓB�[º
ÿ��¶)vk�p�ýx��ÞUL(ØÁr²´��7L!11�3¸`/Q�A`fmÐuÀË÷k
PuTTY2017-02-02 21:10:32.158 [ERROR] [hab.binding.km200.internal.KM200Comm] - Parsingexception in JSON: A JSONObject text must begin with '{' at 2 [character 3 line 1] data: S÷_d▒§´ã9»xÛ�Âe'ã ¬8&F¼P¤¹±�0/$t�µ÷äòý¥ «\é3�!}=ÈYw+¸\F~¹ì ø'¼É¶:;��N:�iÙuîµmma±�« [�°Ù±½       õ�8¾]Ç¬ªí{Ç¸ï&ÓÆÞ]O��­p2,AÞç,Ð@LR¤CI�`6B²«m�-ß²+Úè�ôp��!�¦¹Ö¬�T® ãCà�ÕýôN]Ò°2.¨®W�uÊ �´5^ÕÅU>[? 2WÄ���À�zøÛ¥×,8ÙËì1[(-ö®huEÒK�ùº¹ÔMÖ@[­t�TA��ëã�Ó��²Eu»G³Y-¯`Mæ�~Ö
}�ºÿ�ºQekÙ]O��­p2,AÞç,ÐâY8�R¿¬â}v�;�Bz#àéFK�'¦'�§
                                                 i­�Ýï`-P i©w\Æ�5Ü�c:ÜÆ¿¼ø¾¾à'Wï6]ð�.ú«ÕD¨ü��²Eu»G³Y-¯`Mæ�~ ã"÷`õ½¼�4ó�Ëé�:�iÙuîµmma±�« [�°Ù±½  õ�8¾$�Pr�È1¢ÄDÇ&ËAT�DS]�¨!è±ÓÎ�T@�ÖHà¯â¶2'­7_�©ÙÎ.påõ\�$n3%o�V"ú3�ÿÆá±¨ûñ5¿ªÒ"�<N�%ºHeØêHþ·ÕÒVÅ@�kÄGl�¸3{Þ¢W£|o×ª(g^öUÏpÙ;ë
o¯��«"{Ée²�ïà¯â¶2'­7_�©ÙÎ.p ¢Ë®Zc]5�ÇJ9Ó¨#_�ÛøìÑÐ)����Ë4¨ È�ûÒvCøD·ÉÊ;��Y3� bQYû�-Ì£dãª¶µíluÈ[ÿDb�_ØD5JPÿE� à
                                                                                                             Æ~n_Ìé"X¼d�l�Vyh® �ä²¢yå»�êínVÄ×ê1�O
÷_:#áø�È*lZÅD¸ø¹ézMçð½³¼Æh�´ä>Ã�ñÍÅJn_ÿ[mªP9nÃÂ¾;ïø�\�gÌ�òe¢,¨��ìö×©�ÔÁØà«PÜªÆpª»Ò      kÃù�¹ówÊÂ�Þ@�û¡+«¶¨ÎÙá'Ï%­h·�XV«ZmAVâ>Á�wN¿��7è�#Dækþ�«~8�{£¤�PWî²Ù_�ÛøìÑÐ)����Ë4¨ È�ûÒvCøD·ÉÊ;��7è�#Dækþ�«~8�{£¤�PWî²Ù5^ÕÅU>[? 2WÄ���ír=Üâ¿>JBü¾Fâ«¬y¶�{�    %�D&L Ö@[­t�TA��ëã�Ó�Yt-�%<e©�9'\ëJe£�(�vw�ÎÌÊh]O��­p2,AÞç,ÐwÏ·ù#H¾|d.?��Ù�;�Bz#àéFK�'¦'�§
                                                                                                                                                  i­�Ýï`-P i©w\Æº>UMt%¿^æÏY'3Ï5%
ö«Xw±#8�âQè×ÊE´JpiQâQ9LNso29äªÊ¨ç�=´¿ÙzÁ3�Éy�baÁuä�!¸"c�À­ÊÞâ�]®7±Ñ¼·O×�hn3õ®L�aÑÙ#õOç¤H<�*vu·Nà��ö·4ñ,c2�øÏ¶N�%ºHeØêHþ·ÕÒVÅ▒j�z·�n�¾¦�Þ��%Ú�`?2èª×Ö.(ñýC]O��­p2,AÞç,Ð`         0Ä×¢k�¦)�öd÷
î£1��d�FpÌ�;�Bz#àéFK�'¦'�§
                          i­�Ýï`-P i©w\Æ���s�ÀO¸��Q¤�ÁÝkoÊ©¤�9/$�'ËIÀIQöo¢ÿ�`?õ"M��Ñ�äH�E�%y            µw¢yå»�êínVÄ×ê1�O
÷_:#áø�È*lZÅZ*ë TÃÛ°OãòE�
¤Z�3{×ÂÛ�¬ªÃ;/F�_µ¤L�ÞW�0KDÎp�¬TÇwG�|t�c���2:�iÙuîµmma±�« [�°Ù±½        õ�8¾BhG#¢W5mÊs
                                                                                      ¾Ç¯wëI3Á�Vê%w8�B­âMÀñd¢ã,\îý�Ûj¤òz\�d±�?èù'dãçt@â«¬y¶�{�  %�D&L Ö@[­t�TA��ëã�Ó�▒}y�YLK>9!�¬]�2`�_M�4I«�QµUo¯��«"{Ée²�ïÝ�þ�Ó
§øßÃ½þKî�
R�@ýQ<±V´ï¢�Þ}I¾]±Pe
�O�â\~=*a¶²{SP4�cÄ
[®¯�²�è#æ´}´vÕl&¶°~©á®�£ÎMÓ|+é▒ð×¨èq�öé�.°]O��­p2,AÞç,Ð�q�V²î¥G+�-kxPÏ�;�Bz#àéFK�'¦'�§
                                                                                      i­�Ýï`-P i©w\Æ÷²M�H�Ô?áü�gWï6]ð�.ú«ÕD¨ü��GæJ▒(Ò�yþ �àç'�íZ/2î�mwB qm�-ß²+Úè�ôp��!�¦¹Ö¬�T® ãCà�ÕýôN¦-���/6µµD`+¾[="�Y§6Ê�È�éØ®µV
»·[îrü~ðQ
�â@$7û-{á
 Ô¹�(�Oÿ9�uo%Â�û�Bc�ÚG,î±{3ï(N\�PöºDÒ¶�SËã5\.\Ûb�▒ù��Æ°]O��­p2,AÞç,ÐþÁ�_8`}Ü~�É10Ö@[­t�TA��ëã�Ó�SE
PuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTY2017-02-02 21:10:32.297 [ERROR] [hab.binding.km200.internal.KM200Comm] - Parsingexception in JSON: A JSONObject text must begin with '{' at 1 [character 2 line 1] data: ã�áVl� �PRà§/jZA:;ø÷ç¼Ñ$É��áÐ�?Ò�WÐv0b�²�[0ëRp´½�ÙÉà$¾ï¦¢ýõwq�®��vò±e{°$´lYòóc�EÇyY_àÔ
PuTTY2017-02-02 21:10:32.417 [ERROR] [hab.binding.km200.internal.KM200Comm] - Parsingexception in JSON: A JSONObject text must begin with '{' at 1 [character 2 line 1] data: 'MOøb±êØã¬Æ!åS¯�&]
  dñÝ­íêbOÒa¦ÍFNõ'Ä³ÝÝ¢X½�×ù7'ä>ûZ!Òè�§ÙäM*¹ç5�ðÄ*NÅMÁÛÒïõ3ª¸ø>>Ú_Ö@[­t�TA��ëã�Ó�Ì¤ZÚ2å|�E,ã'P)ÆÀ
                                                                                                 �°��BøÔÂ2�k$·°
_ÑÈÛÄ¢�GÚA¡°õµýt�N�%ºHeØêHþ·ÕÒVÅ▒10¸Ç©ë��R8·�kjwR��Xh®pe¹▒ðÏÓ±ôG¤P8B�W6.Y�D�Ú� {ÔÔtàkïytmþÖ@[­t�TA��ëã�Ó���uga³Ù÷/ÐYµéÀ�¿ÓAG$Ñ,&×°H×C5É(ï{���N��·Ñ©
ïÎ®�à��f«w?ÊSÃm�-ß²+Úè�ôp��!��ddÅ¥\��LÆtÿ&*V�·-k�ð=Ssªx£±Gp|_QmI¬»ºH
2017-02-02 21:10:32.537 [ERROR] [hab.binding.km200.internal.KM200Comm] - Parsingexception in JSON: A JSONObject text must begin with '{' at 2 [character 3 line 1] data: r
\��ú�\v`�DG»KfL³ÒÍ:¤XFqzpCæ9{Ð��ü°<÷?Jõ´DYM»»4¶ÝÓ!+óT(ÁÆ4KE­UðÏÅ�$)�_�ÛøìÑÐ)����Ë48!    �©Q*�RÏÚî'>Ë�Í,º$â �¸�E±'q�-Gðç$;NyäÕÙÜ
�èæ±¤ÕbwÄ(s�Î:10:32.658 [ERROR] [hab.binding.km200.internal.KM200Comm] - Parsingexception in JSON: A JSONObject text must begin with '{' at 1 [character 2 line 1] data: CÜ�w
£R>R]-þmÁ¹P%�íÅßfç�"¯×[:ÝÑ�T��6Î�Î^%Ñ¼og�51bô�;ïPÕ=�S¹Ö@[­t�TA��ëã�Ó�kIåÅo âTnÊÿ¶P*�.¬¹�ôbF�Íp,&1R¶ë�äÄ*úVðÆï%a�ÔÁØà«PÜªÆpª»��uÖ^ÿÚa^óNÈT�¹:ñÏGÕÄºBÆ�#Ui
«±¹�ªÿ§FXêý zm�-ß²+Úè�ôp��!�»3
�·hR/4ikÑåãØ(E¾zNEm¶ä�P1T=DÜ�/¡XÙ@3)}ëNMkÚá°ùMÖ×6¸ó�áKØtr}ÃÉø�¦HÂ�·hR/4ikÑåãØ(E¾zNEm¶ä�P1T�áKØtr}ÃÉø�¦HÂV▒sràéÄøØ�@��PïÚ pÓÌè�¼E0�%�$°Ç;ÎáJêÔNô¾¾+Ñ$�Ñc
                                                                                                                                                       °aKûºÌl'¬bë�j
è,ÄF�T�Êw�(�Ú�Ø�=÷wÊ&Cr}f�vÜL{\~=*a¶²{SP4�cÄ�UKJÓqÄ®sÔyåð,)1æ&ãÓpcS£ÿÆ�4{<P%�áÞÑçÿSß4Ñ~§(uªk¸ %�$°Ç;ÎáJêÔNô¾¾/ßð.�"¤;r£?!ï�`ÿ|üË�ÆÙI²_
¿W�°�êßnâD,<�«ù�è8�±P1ìT
                        v7FL�
2017-02-02 21:10:32.658 [INFO ] [b.binding.km200.internal.KM200Device] - ##################################################################
2017-02-02 21:10:32.658 [INFO ] [b.binding.km200.internal.KM200Device] - List of avalible services
2017-02-02 21:10:32.658 [INFO ] [b.binding.km200.internal.KM200Device] - readable;writeable;recordable;virtual;type;service;value;allowed;min;max
2017-02-02 21:10:32.658 [INFO ] [b.binding.km200.internal.KM200Device] - ##################################################################
2017-02-02 21:10:32.658 [INFO ] [.binding.km200.internal.KM200Binding] - ... Update of the KM200 Binding configuration completed
PuTTY2017-02-02 21:10:32.659 [INFO ] [b.core.service.AbstractActiveService] - KM200 Binding has been started
`

**Comment by Markinus** [comment]
look to this thread:
https://community.openhab.org/t/binding-request-buderus-web-gateway/2575/136

**Comment by whopperg** [comment]
Forum seems to be broken right now so i’ll drop this here:

 

‘2017-02-02 21:46:24.777 [INFO ] [.binding.km200.internal.KM200Binding] - Update KM200 Binding configuration, it takes a minute....

2017-02-02 21:46:24.778 [INFO ] [.binding.km200.internal.KM200Binding] - Starting communication test..

2017-02-02 21:46:24.913 [INFO ] [.binding.km200.internal.KM200Binding] - Received data..

2017-02-02 21:46:24.913 [ERROR] [hab.binding.km200.internal.KM200Comm] - Exception on encoding: {}

java.security.InvalidKeyException: Illegal key size or default parameters

        at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1026)[:1.8.0_121]

        at javax.crypto.Cipher.implInit(Cipher.java:801)[:1.8.0_121]

        at javax.crypto.Cipher.chooseProvider(Cipher.java:864)[:1.8.0_121]

        at javax.crypto.Cipher.init(Cipher.java:1249)[:1.8.0_121]

        at javax.crypto.Cipher.init(Cipher.java:1186)[:1.8.0_121]

        at org.openhab.binding.km200.internal.KM200Comm.decodeMessage(KM200Comm.java:260)[250:org.openhab.binding.km200:1.9.0]

        at org.openhab.binding.km200.internal.KM200Binding.updated(KM200Binding.java:161)[250:org.openhab.binding.km200:1.9.0]

        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189)[3:org.apache.felix.configadmin:1.8.12]

        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152)[3:org.apache.felix.configadmin:1.8.12]

        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)[3:org.apache.felix.configadmin:1.8.12]

        at org.apache.felix.cm.impl.ConfigurationManager$UpdateConfiguration.run(ConfigurationManager.java:1772)[3:org.apache.felix.configadmin:1.8.12]

        at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:141)[3:org.apache.felix.configadmin:1.8.12]

        at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:109)[3:org.apache.felix.configadmin:1.8.12]’

 

btw:I did copied the policy files into $java_home/jre/lib/security

also did I restart openhab…

No clue what could be wrong…

 

Von: Markus Eckhardt [mailto:notifications@github.com] 
Gesendet: Donnerstag, 2. Februar 2017 21:17
An: openhab/openhab2-addons <openhab2-addons@noreply.github.com>
Cc: whopperg <masterx1x@gmx.de>; Mention <mention@noreply.github.com>
Betreff: Re: [openhab/openhab2-addons] New OH2 Binding KM200 (#1805)

 

look to this thread:
https://community.openhab.org/t/binding-request-buderus-web-gateway/2575/136

**Comment by Markinus** [comment]
@whopperg , this is a merge request, this is not the right place. For you problem, please take a look to the wiki: https://github.com/openhab/openhab1-addons/wiki/KM200-Binding
Look to the **important** section.

**Comment by whopperg** [comment]
Did that already as i mentioned before. If the forum is back up, I will continue there. Till then and thanks so far.

 

Von: Markus Eckhardt [mailto:notifications@github.com] 
Gesendet: Donnerstag, 2. Februar 2017 21:56
An: openhab/openhab2-addons <openhab2-addons@noreply.github.com>
Cc: whopperg <masterx1x@gmx.de>; Mention <mention@noreply.github.com>
Betreff: Re: [openhab/openhab2-addons] New OH2 Binding KM200 (#1805)

 

@whopperg <https://github.com/whopperg>  , this is a merge request, this is not the right place. For you problem, please take a look to the wiki: https://github.com/openhab/openhab1-addons/wiki/KM200-Binding
Look to the important section.

**Comment by Markinus** [comment]
From my side this binding is ready for marging. Could you check it?

**Comment by Markinus** [comment]
This pull request is to dirty. I will clean it and create a new pull request,

**Pull request closed without merging**
