### PR TITLE
[camel] Apache Camel IO initial contribution

### PR DESCRIPTION
**Pull request by paulianttila**

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Hi @paulianttila!

Now that's a long list of dependencies here! I would not be happy to have that checked into our (source) code repository.

Especially since we are now using Karaf, there should be much smoother ways to integrate with Camel, i.e. by directly using the Camel Karaf features, see http://camel.apache.org/karaf.html.

For getting your openHAB IO bundle compile, I'd suggest to use the Maven nature - I did the same for the bundle, which depends on Karaf libraries, see [here](https://github.com/kaikreuzer/openhab-core/blob/master/bundles/org.openhab.core.karaf/pom.xml).

**Comment by paulianttila** [comment]
@kaikreuzer: I fully agree, but I just followed SmartHome guideline about [3rd party libraries](https://www.eclipse.org/smarthome/documentation/development/bindings/dependencies.html#rd-party-libraries) :) 

I was able to introduce Maven nature and now eclipse project is happy (camel jars are download, etc). 


screen shot 2016-06-03 at 21 53 13

I can also build successfully project via mvn install. But when I try debug/start the project on eclipse, I got an runtime error:

```
!ENTRY org.eclipse.equinox.ds 4 0 2016-06-03 21:45:11.281
!MESSAGE Exception occurred while creating new instance of component Component[
	name = org.openhab.camel
	activate = activate
	deactivate = deactivate
	modified = modified
	configuration-policy = optional
	factory = null
	autoenable = true
	immediate = true
	implementation = org.openhab.io.camel.internal.CamelService
	state = Unsatisfied
	properties = {service.pid=org.openhab.camel, service.config.category=io, service.config.label=Apache Camel, service.config.description.uri=io:camel}
	serviceFactory = false
	serviceInterface = [org.eclipse.smarthome.core.persistence.PersistenceService, org.eclipse.smarthome.core.events.EventSubscriber, org.eclipse.smarthome.model.script.engine.action.ActionService]
	references = {
		Reference[name = ItemRegistry, interface = org.eclipse.smarthome.core.items.ItemRegistry, policy = dynamic, cardinality = 1..1, target = null, bind = setItemRegistry, unbind = unsetItemRegistry]
		Reference[name = EventPublisher, interface = org.eclipse.smarthome.core.events.EventPublisher, policy = dynamic, cardinality = 0..1, target = null, bind = setEventPublisher, unbind = unsetEventPublisher]
	}
	located in bundle = org.openhab.io.camel_2.0.0.qualifier [38]
] 
!STACK 0
java.lang.NoClassDefFoundError: org/apache/camel/CamelContext
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.createInstance(ServiceComponent.java:493)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.createInstance(ServiceComponentProp.java:270)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:331)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:914)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:225)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:464)
	at org.eclipse.equinox.internal.ds.InstanceProcess.registerService(InstanceProcess.java:536)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:213)
	at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473)
	at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217)
	at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816)
	at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783)
	at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.camel.CamelContext cannot be found by org.openhab.io.camel_2.0.0.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 28 more

```

Any idea how to solve this?

**Comment by kaikreuzer** [comment]
> Any idea how to solve this?

It isn't possible to run this in Eclipse. Instead, you should deploy your bundle to a runtime (export it from eclipse and place it in the addons folder), add the Camel Karaf features as well, and then use remote debugging.
(Note aside: I am currently investigating a bnd-based IDE setup where Eclipse can automate this process on every single save of a file - this should become available in a few months time and will be ideal for your purposes)

**Comment by paulianttila** [comment]
Thanks Kai.

I installed Camel to online openhab distribution.

```
openhab> feature:repo-add camel 2.17.1
openhab> feature:install aries-blueprint
openhab> feature:install camel
openhab> feature:list
Name                                      | Version          | Required | State       | Repository                  | Description
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
xml-specs-api                             | 2.6.0            |          | Started     | camel-2.17.1                |
camel                                     | 2.17.1           | x        | Started     | camel-2.17.1                |
camel-core                                | 2.17.1           |          | Started     | camel-2.17.1                |
camel-catalog                             | 2.17.1           |          | Uninstalled | camel-2.17.1                |
camel-blueprint                           | 2.17.1           |          | Started     | camel-2.17.1                |
camel-spring                              | 2.17.1           |          | Uninstalled | camel-2.17.1                |
camel-scr                                 | 2.17.1           |          | Uninstalled | camel-2.17.1                |
camel-ahc                                 | 2.17.1           |          | Uninstalled | camel-2.17.1                |
camel-ahc-ws                              | 2.17.1           |          | Uninstalled | camel-2.17.1                |
camel-amqp                                | 2.17.1           |          | Uninstalled | camel-2.17.1                |
camel-apns                                | 2.17.1           |          | Uninstalled | camel-2.17.1                |
camel-atmosphere-websocket                | 2.17.1           |          | Uninstalled | camel-2.17.1                |
camel-atom                                | 2.17.1           |          | Uninstalled | camel-2.17.1                |
camel-avro                                | 2.17.1           |          | Uninstalled | camel-2.17.1                |
camel-aws                                 | 2.17.1           |          | Uninstalled | camel-2.17.1                |
camel-bam                                 | 2.17.1           |          | Uninstalled | camel-2.17.1                |
...

```
 
And when I install binding (cp binding to addons folder) and got exactly the same execption than in eclipse.

```
09:25:41.443 [ERROR] [org.openhab.io.camel                ] - FrameworkEvent ERROR - org.openhab.io.camel
org.osgi.framework.ServiceException: Exception in org.apache.felix.scr.impl.manager.SingleComponentManager.getService()
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:222)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:111)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:45)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:496)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:461)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:619)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.apache.felix.scr.impl.manager.SingleRefPair.getServiceObject(SingleRefPair.java:72)[33:org.apache.felix.scr:2.0.2]
	at org.apache.felix.scr.impl.helper.BindMethod.getServiceObject(BindMethod.java:646)[33:org.apache.felix.scr:2.0.2]
	at org.apache.felix.scr.impl.manager.DependencyManager.getServiceObject(DependencyManager.java:2137)[33:org.apache.felix.scr:2.0.2]
	at org.apache.felix.scr.impl.manager.DependencyManager.doInvokeBindMethod(DependencyManager.java:1651)[33:org.apache.felix.scr:2.0.2]
	at org.apache.felix.scr.impl.manager.DependencyManager.invokeBindMethod(DependencyManager.java:1636)[33:org.apache.felix.scr:2.0.2]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.invokeBindMethod(SingleComponentManager.java:370)[33:org.apache.felix.scr:2.0.2]
	at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.addedService(DependencyManager.java:319)[33:org.apache.felix.scr:2.0.2]
	at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.addedService(DependencyManager.java:295)[33:org.apache.felix.scr:2.0.2]
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1215)[33:org.apache.felix.scr:2.0.2]
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1136)[33:org.apache.felix.scr:2.0.2]
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:945)[33:org.apache.felix.scr:2.0.2]
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:881)[33:org.apache.felix.scr:2.0.2]
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1167)[33:org.apache.felix.scr:2.0.2]
	at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:120)[33:org.apache.felix.scr:2.0.2]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:914)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:225)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:464)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:869)[33:org.apache.felix.scr:2.0.2]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:857)[33:org.apache.felix.scr:2.0.2]
	at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:133)[33:org.apache.felix.scr:2.0.2]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:915)[33:org.apache.felix.scr:2.0.2]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:715)[33:org.apache.felix.scr:2.0.2]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:399)[33:org.apache.felix.scr:2.0.2]
	at org.apache.felix.scr.impl.config.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:676)[33:org.apache.felix.scr:2.0.2]
	at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:339)[33:org.apache.felix.scr:2.0.2]
	at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:360)[33:org.apache.felix.scr:2.0.2]
	at org.apache.felix.scr.impl.Activator.access$000(Activator.java:53)[33:org.apache.felix.scr:2.0.2]
	at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:260)[33:org.apache.felix.scr:2.0.2]
	at org.apache.felix.utils.extender.AbstractExtender.createExtension(AbstractExtender.java:259)[33:org.apache.felix.scr:2.0.2]
	at org.apache.felix.utils.extender.AbstractExtender.modifiedBundle(AbstractExtender.java:232)[33:org.apache.felix.scr:2.0.2]
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:482)[org.osgi.core-6.0.0.jar:]
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:415)[org.osgi.core-6.0.0.jar:]
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232)[org.osgi.core-6.0.0.jar:]
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:444)[org.osgi.core-6.0.0.jar:]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:902)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:165)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:75)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:67)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:102)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:466)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.container.Module.start(Module.java:457)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:393)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1245)[8:org.apache.felix.fileinstall:3.5.0]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1217)[8:org.apache.felix.fileinstall:3.5.0]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:509)[8:org.apache.felix.fileinstall:3.5.0]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:358)[8:org.apache.felix.fileinstall:3.5.0]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:310)[8:org.apache.felix.fileinstall:3.5.0]
Caused by: java.lang.NoClassDefFoundError: org/apache/camel/CamelContext
	at java.lang.Class.getDeclaredMethods0(Native Method)[:1.8.0_40]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)[:1.8.0_40]
	at java.lang.Class.getDeclaredMethods(Class.java:1975)[:1.8.0_40]
	at org.apache.felix.scr.impl.helper.BindMethod.getServiceObjectAssignableMethod(BindMethod.java:454)
	at org.apache.felix.scr.impl.helper.BindMethod.doFindMethod(BindMethod.java:186)
	at org.apache.felix.scr.impl.helper.BaseMethod.findMethod(BaseMethod.java:171)
	at org.apache.felix.scr.impl.helper.BaseMethod.access$400(BaseMethod.java:37)
	at org.apache.felix.scr.impl.helper.BaseMethod$NotResolved.resolve(BaseMethod.java:558)
	at org.apache.felix.scr.impl.helper.BaseMethod$NotResolved.methodExists(BaseMethod.java:580)
	at org.apache.felix.scr.impl.helper.BaseMethod.methodExists(BaseMethod.java:513)
	at org.apache.felix.scr.impl.helper.BindMethod.getServiceObject(BindMethod.java:643)
	at org.apache.felix.scr.impl.manager.DependencyManager.getServiceObject(DependencyManager.java:2137)
	at org.apache.felix.scr.impl.manager.DependencyManager$SingleDynamicCustomizer.prebind(DependencyManager.java:872)
	at org.apache.felix.scr.impl.manager.DependencyManager.prebind(DependencyManager.java:1457)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.collectDependencies(AbstractComponentManager.java:983)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:812)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:774)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:212)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at java.security.AccessController.doPrivileged(Native Method)[:1.8.0_40]
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:210)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	... 60 more
Caused by: java.lang.ClassNotFoundException: org.apache.camel.CamelContext cannot be found by org.openhab.io.camel_2.0.0.201606040619
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)[:1.8.0_40]
	... 80 more

```

Btw: not sure if this have nothing to do this, but I'm not able to export camel binding from eclipse. 

```
# 6/4/16 9:51:23 AM EEST
# Eclipse Compiler for Java(TM) xx-201601131831-e45, 3.11.0, Copyright IBM Corp 2000, 2015. All rights reserved.
----------
1. ERROR in /Users/Pali/Projects/openhab2/git/openhab2-addons/addons/io/org.openhab.io.camel/src/main/java/org/openhab/io/camel/internal/CamelService.java (at line 35)
	import org.apache.camel.CamelContext;
	       ^^^^^^^^^^^^^^^^
The import org.apache.camel cannot be resolved
----------
2. ERROR in /Users/Pali/Projects/openhab2/git/openhab2-addons/addons/io/org.openhab.io.camel/src/main/java/org/openhab/io/camel/internal/CamelService.java (at line 36)
	import org.apache.camel.impl.DefaultCamelContext;
	       ^^^^^^^^^^^^^^^^
... lot of other errors ...

```
But mvn work from the command line fine.

**Comment by kaikreuzer** [comment]
Do you have an import package of org.apache.camel in your MANIFEST.MF?

**Comment by paulianttila** [comment]
> Do you have an import package of org.apache.camel in your MANIFEST.MF?

No, I didn't have that. I tried that and now project does not compile. Now it does not compile even I remove the import, so most probably my jar which I tried with distribution was from my early builds. 

Anyhow, I committed my changes to the repo, so if you or someone else with enough skills could have a look.

**Comment by kaikreuzer** [comment]
I'd love to, but I cannot promise when I can find the time - I am completely drowning in todos...

**Comment by paulianttila** [comment]
I'm out of ideas. Maven nicely download camel artifacts, but some reason imported bundles can't be resolved (No available bundle exports package 'org.apache.camel'). I tried to imitate everything from org.openhab.core.karaf but without success. That seems to be only bundle which currently use maven nature.

**Comment by davidgraeff** [comment]
Is there still interest in implementing this @paulianttila ? Otherwise I'm closing this. With maven/bnd it should also be a bit easier with external dependencies.

**Comment by paulianttila** [comment]
I will open new PR, if i some day continue this one.

**Pull request closed without merging**
