### PR TITLE
Added missing command handling in MilightLedHandler (#1322)

### PR DESCRIPTION
**Pull request by patrickse**
Added missing command handling in MilightLedHandler (#1322)

 - CHANNEL_COLOR: added PercentType
 - CHANNEL_BRIGHTNESS: added PercentType, OnOffType

### CODE REVIEW

**Comment by patrickse** [comment]
I´ve got no clue why it´s failing

**Comment by kaikreuzer** [comment]
Doesn't seem to be your fault. Thanks for updating!

**Comment by kaikreuzer** [comment]
Oops, I just noticed that you missed to sign-off your commits. Could you quickly squash and add a sign-off line? Thanks!

**Comment by patrickse** [comment]
Looks better now ;)

**Comment by kaikreuzer** [comment]
Perfect, thanks!

**Pull request merged**
