### PR TITLE
[Freebox] Handle transparently the SSL certificate

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@martinvw for review

**Comment by martinvw** [comment]
Did you test it in an environment where the certificates were removed from the trust store? The changes look good, maybe the paragraph about certificates is now superfluous and could be completely removed

**Comment by lolodomo** [comment]
Yes of course, first tested on my Win 10 PC in a dev environment with certificates never installed and then tested on my RPI 2 after removing the two certificates from cacerts.

**Comment by lolodomo** [comment]
Paragraph about HTTPS access has been suppressed from the documentation.

**Comment by martinvw** [comment]
Thank you very much!

**Comment by lolodomo** [comment]
Thank you for a so fast review & merge, especially during this period of the year 👍

**Pull request merged**
