### PR TITLE
Changed to openHAB Core feature of JAXB

### PR DESCRIPTION
**Pull request by cweitkamp**
- Changed to openHAB Core feature of JAXB

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by maggu2810** [comment]
As you have used "to satisfy missing dependencies" on the bundles, you could use the same for the future, too...

**Comment by cweitkamp** [comment]
I am afraid I did not understand your comment. Did you mean "future" or "feature"?

**Comment by maggu2810** [comment]
feature...

You replaced `<bundle dependency="true">` by `<feature>`.
Why not using `<feature dependency="true">` if it has not been a mandatory requirement before?

**Comment by cweitkamp** [comment]
Alright now it makes sense.

**Pull request merged**
