### PR TITLE
removed static reference to scheduler

### PR DESCRIPTION
**Pull request by kaikreuzer**
Related to https://github.com/eclipse/smarthome/pull/5227

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by lolodomo** [comment]
@kaikreuzer : with all the last code retrieved (ESH, OH core, OH 2 addons, OH ditrib), I have several OH2 bindings no more compiling in Eclipse IDE due to variable scheduler. The error message is "scheduler cannot be resolved."
In which package is defined this object ?
I have reloaded the openHAB target platform.
What could be wrong ?

PS: Maven compilation is OK.

**Comment by kaikreuzer** [comment]
@lolodomo I'd guess you still have the old ESH bundles resolved in your target platform.
Make sure to pull the latest openhab-distro and possibly also do "update" on the ESH p2 repo in the openhab.target editor.

**Comment by lolodomo** [comment]
@kaikreuzer : thank you for the advice. The sequence number is 180 in the repo; when I force an update like you suggested, the new sequence number is 183 but it does not help. By the way, this is not very important as I don't need the bindings that are not compiling.
Like previously for the UoM, I imagine the next update of the openHAB target platform will solve these problems.

**Comment by martinvw** [comment]
It seems  that this makes the 2.3-SNAPSHOT binding incompatible with openHAB 2.2:

@Wire82 got a stacktrace:

```
2018-03-24 10:42:46.463 [WARN ] [e.jetty.servlet.ServletHandler:624 ] - javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.IncompatibleClassChangeError: Expected non-static field org.openhab.binding.zway.internal.discovery.ZWayBridgeDiscoveryService.scheduler
at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:489)
at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.service(ServletContainerBridge.java:76)
at org.eclipse.equinox.http.servlet.internal.HttpServiceRuntimeImpl$LegacyServlet.service(HttpServiceRuntimeImpl.java:1223)
at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:148)
at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62)
at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:131)
at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.service(ProxyServlet.java:74)
Caused by: org.glassfish.jersey.server.ContainerException: java.lang.IncompatibleClassChangeError: Expected non-static field org.openhab.binding.zway.internal.discovery.ZWayBridgeDiscoveryService.scheduler
at org.glassfish.jersey.servlet.internal.ResponseWriter.rethrow(ResponseWriter.java:278)
at org.glassfish.jersey.servlet.internal.ResponseWriter.failure(ResponseWriter.java:260)
at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:509)
at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:334)
at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
Caused by: java.lang.IncompatibleClassChangeError: Expected non-static field org.openhab.binding.zway.internal.discovery.ZWayBridgeDiscoveryService.scheduler
at org.openhab.binding.zway.internal.discovery.ZWayBridgeDiscoveryService.scan(ZWayBridgeDiscoveryService.java:65)
at org.openhab.binding.zway.internal.discovery.ZWayBridgeDiscoveryService.startScan(ZWayBridgeDiscoveryService.java:128)
at org.eclipse.smarthome.config.discovery.AbstractDiscoveryService.startScan(AbstractDiscoveryService.java:222)
at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScan(DiscoveryServiceRegistryImpl.java:409)
at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScans(DiscoveryServiceRegistryImpl.java:394)
at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScan(DiscoveryServiceRegistryImpl.java:241)
at org.eclipse.smarthome.io.rest.core.internal.discovery.DiscoveryResource.scan(DiscoveryResource.java:97)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
```

**Comment by martinvw** [comment]
I think its worth it but a warning would be suitable

**Comment by kaikreuzer** [comment]
Using 2.3 bundles on 2.2 runtime is not supported anyhow, so that is anyhow "on your own risk" - no additional warning necessary imho (and especially not manageable=.

**Pull request merged**
