### PR TITLE
[RFXCOM] Adding support for CURRENT messages

### PR DESCRIPTION
**Pull request by martinvw**
Follow-up of #1271

Also-by:  Jordan Cook <jordan@jc.me.uk> (github: netjordan)

### CODE REVIEW

**Comment by martinvw** [comment]
@netjordan please review!

**Comment by martinvw** [comment]
[org.openhab.binding.rfxcom-2.2.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab2-addons/files/1566006/org.openhab.binding.rfxcom-2.2.0-SNAPSHOT.jar.zip)

**Comment by martinvw** [comment]
@Jamstah good to see you around! Thanks!

**Comment by Jamstah** [comment]
Great to see you still working on this. The improvements to the github process are great, and I like the new interfaces and abstract classes for battery information etc. Its clever stuff :+1:

**Pull request merged**
