### PR TITLE
[icloud] Update certificate so that binding can communicate with iCloud

### PR DESCRIPTION
**Pull request by mauryquijada**
[icloud] Update certificate so that binding can communicate with iCloud API.

Signed-off-by: Maury Quijada <maury.quijada@gmail.com>

### CODE REVIEW

**Comment by J-N-K** [comment]
I understand that this is necessary from time to time. How do we get the new certificate and can we automate the process?

**Comment by mauryquijada** [comment]
You can get the certificate by running
`echo -n | openssl s_client -servername fmipmobile.icloud.com -host fmipmobile.icloud.com -port 443 -prexit -showcerts 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > fmipmobile.crt`.

I suppose there are a few ways to go about handling this moving forward:
1. Automate this, which is what you suggested. I had a thought about manipulating Maven so that it runs that command every time the binding is built, but I have never used Maven so I don't know if/how to do so. Also, this has the disadvantage of requiring users to update the binding whenever the certificate expires (which will happen on “Sun Aug 23 08:45:49 PDT 2020”).
1. Remove the certificate from the binding, and put the onus on the user to update the certificate whenever it expires. This I believe is what @martinvw suggested in the [post tracking this issue](https://community.openhab.org/t/icloud-ssl-issue-again/79182/19?u=wsd33904). We can make this more painless for the user by (1) writing extensive documentation in the binding about how likely this is to happen and (2) creating a Bash script a user can run to update the certificates on their openHAB.

**Comment by J-N-K** [comment]
Mhm. If we can‘t get it from another server we should probably stay where we are now.

**Comment by martinvw** [comment]
I thought (hoped) I aimed to only configure the root certificate, did they change that or did I end up adding the complete chain? I'll give this some more thoughts in the upcoming weeks, thanks for taking care!

**Comment by mauryquijada** [comment]
The only certificate I saw and changed was the certificate for fmipmobile.icloud.com. My understanding is that this is not a root certificate; the root certificate is the Apple authority that signed the fmipmobile.icloud.con

If we are going to continue to check in the certificate (which I am wary of, because it’ll only have to be updated in August 2020), could we add some kind of manual override? Or instead, could we download the certificate into the jar when it’s built?

**Comment by martinvw** [comment]
I like that idea the implementation should be cross platform if you have ideas how to implement that it’s welcome.

**Pull request merged**
