### PR TITLE
[homekit] better configuration handling

### LINKED ISSUE #5269: [homekit] networkInterface needs to be defined
## Expected Behavior
If networkInterface is not defined, the addon should get it's own IP.

## Current Behavior
My current setup (just one light) only works if I define the networkInterface, but there is no reason (basic Openhabian image used) to not to work when networkInterface is not set.

## Possible Solution
It seems related in how InetAddress.getLocalHost() function works in the HomekitSettings.java. I don't know what should be changed, event not sure how to test/debug it (I don't know how to add log messages in the code and recompile it).

## Steps to Reproduce (for Bugs)

1. Openhabian default image.
2. Do not set the org.openhab.homekit:networkInterface configuration parameter.

## Context
It's a mess that the IP of the own device should be provided, adn this goes against DHCP typical configurations.

## Your Environment

* Version used: openhab 2.4.0 stable and addon 2.4.0 stable (I didn't found any newest commit that seems to solve it).
* Operating System and version: Raspbian Stretch.

### PR DESCRIPTION
**Pull request by J-N-K**
Fixes #5269 

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by grzegorz914** [comment]
OH 2.5.0 build 1599 and 1600 

If we change something in Homekit config menu through PaperUI after save alway get error:

```
2019-05-25 13:00:16.083 [ERROR] [org.openhab.io.homekit              ] - bundle org.openhab.io.homekit:2.5.0.201905250651 (248)[org.openhab.io.homekit.internal.HomekitImpl(242)] : The modified method has thrown an exception
java.lang.NullPointerException: null
	at org.openhab.io.homekit.internal.HomekitAccessoryRegistry.lambda$0(HomekitAccessoryRegistry.java:62) ~[?:?]
	at java.util.HashMap$Values.forEach(HashMap.java:981) ~[?:?]
	at org.openhab.io.homekit.internal.HomekitAccessoryRegistry.setBridge(HomekitAccessoryRegistry.java:62) ~[?:?]
	at org.openhab.io.homekit.internal.HomekitChangeListener.setBridge(HomekitChangeListener.java:143) ~[?:?]
	at org.openhab.io.homekit.internal.HomekitImpl.stop(HomekitImpl.java:120) ~[?:?]
	at org.openhab.io.homekit.internal.HomekitImpl.modified(HomekitImpl.java:81) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:228) ~[42:org.apache.felix.scr:2.1.16]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) ~[42:org.apache.felix.scr:2.1.16]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:664) ~[42:org.apache.felix.scr:2.1.16]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:510) [42:org.apache.felix.scr:2.1.16]
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:317) [42:org.apache.felix.scr:2.1.16]
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:307) [42:org.apache.felix.scr:2.1.16]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.invokeModifiedMethod(SingleComponentManager.java:836) [42:org.apache.felix.scr:2.1.16]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.modify(SingleComponentManager.java:791) [42:org.apache.felix.scr:2.1.16]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.reconfigure(SingleComponentManager.java:709) [42:org.apache.felix.scr:2.1.16]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.reconfigure(SingleComponentManager.java:673) [42:org.apache.felix.scr:2.1.16]
	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.configurationUpdated(ConfigurableComponentHolder.java:435) [42:org.apache.felix.scr:2.1.16]
	at org.apache.felix.scr.impl.manager.RegionConfigurationSupport.configurationEvent(RegionConfigurationSupport.java:316) [42:org.apache.felix.scr:2.1.16]
	at org.apache.felix.scr.impl.manager.RegionConfigurationSupport$2.configurationEvent(RegionConfigurationSupport.java:118) [42:org.apache.felix.scr:2.1.16]
	at org.apache.felix.cm.impl.ConfigurationManager$FireConfigurationEvent.sendEvent(ConfigurationManager.java:1704) [9:org.apache.felix.configadmin:1.9.14]
	at org.apache.felix.cm.impl.ConfigurationManager$FireConfigurationEvent.run(ConfigurationManager.java:1646) [9:org.apache.felix.configadmin:1.9.14]
	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:138) [9:org.apache.felix.configadmin:1.9.14]
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:105) [9:org.apache.felix.configadmin:1.9.14]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by J-N-K** [comment]
I hate NPEs. Will fix that. 

That would have been prevented with proper null annotations, which are unfortunately not possible. Since we have no officially uploaded HAP-java version anyway I‘m thinking of forking and providing those.

**Comment by grzegorz914** [comment]
Other 2 error after restart OH2:
```
==> /var/log/openhab2/openhab.log <==
2019-05-25 13:48:29.010 [ERROR] [p.characteristics.BaseCharacteristic] - Could not retrieve value com.beowulfe.hap.impl.characteristics.smokesensor.SmokeDetectedCharacteristic
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604) [?:?]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614) [?:?]
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983) [?:?]
	at com.beowulfe.hap.impl.characteristics.smokesensor.SmokeDetectedCharacteristic.getValue(SmokeDetectedCharacteristic.java:22) ~[248:org.openhab.io.homekit:2.5.0.201905250651]
	at com.beowulfe.hap.characteristics.BaseCharacteristic.makeBuilder(BaseCharacteristic.java:71) [248:org.openhab.io.homekit:2.5.0.201905250651]
	at com.beowulfe.hap.characteristics.EnumCharacteristic.makeBuilder(EnumCharacteristic.java:39) [248:org.openhab.io.homekit:2.5.0.201905250651]
	at com.beowulfe.hap.characteristics.BaseCharacteristic.toJson(BaseCharacteristic.java:61) [248:org.openhab.io.homekit:2.5.0.201905250651]
	at com.beowulfe.hap.impl.json.AccessoryController.toJson(AccessoryController.java:76) [248:org.openhab.io.homekit:2.5.0.201905250651]
	at com.beowulfe.hap.impl.json.AccessoryController.listing(AccessoryController.java:37) [248:org.openhab.io.homekit:2.5.0.201905250651]
	at com.beowulfe.hap.impl.connections.HttpSession.handleAuthenticatedRequest(HttpSession.java:72) [248:org.openhab.io.homekit:2.5.0.201905250651]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.doHandleRequest(ConnectionImpl.java:53) [248:org.openhab.io.homekit:2.5.0.201905250651]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.handleRequest(ConnectionImpl.java:47) [248:org.openhab.io.homekit:2.5.0.201905250651]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:52) [248:org.openhab.io.homekit:2.5.0.201905250651]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:17) [248:org.openhab.io.homekit:2.5.0.201905250651]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [245:io.netty.netty-all:4.0.32]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [245:io.netty.netty-all:4.0.32]
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32) [245:io.netty.netty-all:4.0.32]
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:299) [245:io.netty.netty-all:4.0.32]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36) [245:io.netty.netty-all:4.0.32]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [245:io.netty.netty-all:4.0.32]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [245:io.netty.netty-all:4.0.32]
	at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:?]
	... 21 more
```

`2019-05-25 13:48:31.091 [ERROR] [p.characteristics.BaseCharacteristic] - Error retrieving value
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[?:?]
	at com.beowulfe.hap.characteristics.BaseCharacteristic.supplyValue(BaseCharacteristic.java:123) [248:org.openhab.io.homekit:2.5.0.201905250651]
	at com.beowulfe.hap.impl.json.EventController.getMessage(EventController.java:20) [248:org.openhab.io.homekit:2.5.0.201905250651]
	at com.beowulfe.hap.impl.connections.SubscriptionManager.addSubscription(SubscriptionManager.java:49) [248:org.openhab.io.homekit:2.5.0.201905250651]
	at com.beowulfe.hap.impl.json.CharacteristicsController.put(CharacteristicsController.java:86) [248:org.openhab.io.homekit:2.5.0.201905250651]
	at com.beowulfe.hap.impl.connections.HttpSession.handleAuthenticatedRequest(HttpSession.java:77) [248:org.openhab.io.homekit:2.5.0.201905250651]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.doHandleRequest(ConnectionImpl.java:53) [248:org.openhab.io.homekit:2.5.0.201905250651]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.handleRequest(ConnectionImpl.java:47) [248:org.openhab.io.homekit:2.5.0.201905250651]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:52) [248:org.openhab.io.homekit:2.5.0.201905250651]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:17) [248:org.openhab.io.homekit:2.5.0.201905250651]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [245:io.netty.netty-all:4.0.32]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [245:io.netty.netty-all:4.0.32]
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32) [245:io.netty.netty-all:4.0.32]
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:299) [245:io.netty.netty-all:4.0.32]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36) [245:io.netty.netty-all:4.0.32]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [245:io.netty.netty-all:4.0.32]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [245:io.netty.netty-all:4.0.32]
	at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983) ~[?:?]
	at com.beowulfe.hap.impl.characteristics.smokesensor.SmokeDetectedCharacteristic.getValue(SmokeDetectedCharacteristic.java:22) ~[?:?]
	... 17 more`

**Comment by J-N-K** [comment]
Did someone remove a post here? I got a notification with additional errors which I can‘t see.

**Comment by wborn** [comment]
Maybe it was this one? https://github.com/openhab/openhab2-addons/issues/5635#issuecomment-495920158

**Comment by J-N-K** [comment]
No. I have no idea about that one. I also don't see why any of these changes should affect bundle-loading from the addons directory. It was something related to smoke-detectors-accessories but unfortunately I deleted the mail.

**Comment by grzegorz914** [comment]
Yes, 
it was wrong declaration in my .items file. 
The errors do not more exist anymore.

**Comment by J-N-K** [comment]
@grzegorz914 would you like to test the new bundle?

**Comment by grzegorz914** [comment]
> @grzegorz914 would you like to test the new bundle?

Yes

**Comment by J-N-K** [comment]
Ok. It is a bit difficult since we need to keep all dependencies in place. Please download [this](https://janessa.me/esh/org.openhab.io.homekit-fix-npe.jar). Open the karaf console and type `bundle:list | grep -i homekit`. You should get the bundle number of the installed version. Stop it with `bundle:stop <bundle-number>`. Check with `bundle:list | grep -i homekit`, the bundle state shpuld have changed to `Resolved`. Drop the new version in your addons directory. After it started, `bundle:list | grep -i homekit` should show two bundles, one in `Resolved` and one on `Active` state. Finally uninstall the old bundle with `bundle:install <bundle-number>`. Done.

**Comment by wborn** [comment]
You can simplify that procedure with:

`bundle:update <bundle-number> https://janessa.me/esh/org.openhab.io.homekit-fix-npe.jar`

No need for downloads, uninstalls and installs. :stuck_out_tongue_winking_eye:

**Comment by J-N-K** [comment]
Nice. Didn't now that.

**Comment by grzegorz914** [comment]
I get error:
```
openhab> bundle:list | grep -i homekit
248 │ Active │  80 │ 2.5.0.201905250651    │ openHAB Add-ons :: Bundles :: IO :: Homekit
openhab>    openhab> bundle:update 2.5.0.201905250651  https://janessa.me/esh/org.openhab.io.homekit-fix-npe.jar                                                                                                        
Error executing command: Bundle 2.5.0.201905250651 does not match any bundle
```

**Comment by wborn** [comment]
Try:

`bundle:update 248 https://janessa.me/esh/org.openhab.io.homekit-fix-npe.jar`

:-)

**Comment by grzegorz914** [comment]
OK,

after update looks like the error is fixed.

**Pull request merged**
