### PR TITLE
Update version number regex

### PR DESCRIPTION
**Pull request by martinvw**
Signed-off-by: Martin van Wingerden <martinvw@mtin.nl>

### CODE REVIEW

**Comment by martinvw** [comment]
@pfink it would be great if we could embed this logic too, or just make sure this parameter is read from some parent pom...

**Comment by martinvw** [comment]
Background, otherwise the first binding breaks on the SAT, with the error:

```
[INFO] --- sat-plugin:0.5.0:report (default) @ org.openhab.binding.airquality ---
[INFO] Individual report appended to summary report.
[ERROR] Code Analysis Tool has found: 
 1 error(s)! 
 0 warning(s) 
 1 info(s)
[ERROR] .binding.airquality/META-INF/MANIFEST.MF:[0]
The manifest version did not match the requirements ^2\.3\.0
[INFO] Detailed report can be found at: file:////home/travis/build/openhab/openhab2-addons/addons/binding/org.openhab.binding.airquality/target/code-analysis/report.html
```

**Comment by wborn** [comment]
Yes it would be nice to get these changes automated as well. :-)

**Comment by pfink** [comment]
@wborn @martinvw: I'm already aware of this issue and opened openhab/static-code-analysis#304 some weeks ago.

**Comment by martinvw** [comment]
@pfink I already had some memory of that indeed :-) Thanks for your tremendous work of the last days!

**Pull request merged**
