### PR TITLE
[transform.javascript] Migrate to bnd build

### PR DESCRIPTION
**Pull request by wborn**
Migrates the Javascript Transformation add-on to the bnd build.

### CODE REVIEW

**Comment by davidgraeff** [comment]
I know one PR or soon coming PR that is working on the javascript transformation.

**Comment by wborn** [comment]
Is it also about migrating the bundle to the bnd build? :wink:

**Comment by davidgraeff** [comment]
No. But it is rude to cause a merge conflict. Additionally we do not have a working guideline for Eclipse IDE development. If we throw the new buildsystem at people in between their contribution, they will probably quit that contribution.

**Comment by martinvw** [comment]
> No. But it is rude to cause a merge conflict. Additionally we do not have a working guideline for Eclipse IDE development. If we throw the new buildsystem at people in between their contribution, they will probably quit that contribution.

So you would propose to delay this migration until after that PR?

**Comment by wborn** [comment]
I guess we can't wait forever for other PRs to be created some day?

**Comment by davidgraeff** [comment]
Yup. And it is not much work to copy the file over if there is indeed some work done already.

**Pull request merged**
