### PR TITLE
Removed dependency on 'org.apache.commons.collections'

### PR DESCRIPTION
**Pull request by cweitkamp**
- Removed dependency on `org.apache.commons.collections`

See https://github.com/openhab/openhab-core/pull/1236

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Test failures on Travis seem unrelated.

@cweitkamp Why did you add the "awaiting other PR" label on this one?

**Comment by cweitkamp** [comment]
I restarted the Travis build.

IIRC the itests will fail unless we remove the dependency on `org.apache.commons.collections` in OHC too. It complained about unresolved dependencies.

**Comment by kaikreuzer** [comment]
If the test executions still require commons, you should not remove it from the bnd configuration now. But there should be no reason, why you should not refactor the bindings to not require that dependency anymore.

**Comment by kaikreuzer** [comment]
The tests can be adapted in a separate PR, which then indeed depends on https://github.com/openhab/openhab-core/pull/1236.

**Comment by cweitkamp** [comment]
Moved code changes into separate PR https://github.com/openhab/openhab2-addons/pull/6467

**Comment by wborn** [comment]
I see that Travis is currently [not happy](https://travis-ci.org/openhab/openhab2-addons/builds/618783352). Can we make it happy again by merging this PR because of the changes in https://github.com/openhab/openhab-core/pull/1244?

**Pull request merged**
