### PR TITLE
Swapped byte detection in Multi Channel Encapsulation.

### LINKED ISSUE #738: ZWave: Fix for incorrect Multi-channel encapsulation messages
Per Z-wave spec the source endpoint is specified as byte 0 of the payload and the destination endpoints(s) are either:
- a bit mask of seven endpoints (bit 0-6 of byte 1) to address at once when bit 7 of byte 1 is high.
- an individual endpoint id (1 to 127) when bit 7 of byte 1  is high.

Messages that are sent to the controller (node id 1, no endpoints ever) should not have the destination endpoint byte != 1. However the infamous green wave 6 (and possibly 5) node devices have a bug that have the source and destination (endpoint) bytes swapped in unsolicited messages to the controller. As this is seriously incorrect it reports all unsolicited reports to endpoint 1 as the originating node is in byte 1 instead of 0.

I will create a pull request that swaps the bytes if destination node != 1 and source node=1.

It has been discussed before, but somehow it never made it to a patch. 

https://community.openhab.org/t/zwave-binding-issue-with-metering-and-multiple-endpoints/6904/4

Of course i've tested the unsolicited reports with different loads on each port and indeed load changes on a specific endpoint are reported with originating endpoint = 1 and destination endpoint equal to the endpoint number of the port.

### PR DESCRIPTION
**Pull request by jspuij**
This code detects swapped bytes in Multi Channel Encapsulation messages
sent to the controller. The controller has no endpoints and therefore
should always be addressed as 1, while originating can be between 1 and
127. When destination != 1 for the controller, the packet is invalid.
The greenwave nodes make this mistake in their firmware.

Fixes #738.

Polling code based on seconds and fixed as well.

Signed-off-by: Jan-Willem Spuij <jw@spuij.nl> (github: jspuij)

### CODE REVIEW

**Comment by jspuij** [comment]
@cdjackson I took the liberty of converting all constants and polling code to seconds as well in this pull request. Miliseconds and seconds were mixed which resulted in a polling refresh every 7200 miliseconds (7.2 seconds). If you want to use miliseconds, you should probably convert all constants back to long but also multiply them by 1000. I did this but the code actually looked a lot less readable and a milisecond resolution seemed overkill anyway. This version of the binding seems very happy on my network.

**Comment by jspuij** [comment]
And with this I can finally say that we have tamed the GreenWave power bars. It runs in my network with a default polling interval of 30 minutes.

All intermediate reports come from the device without polling. I've set the parameters to report any 1% variation in load and to run for 60 minutes before setting the no communication light. 

schermafbeelding 2016-03-18 om 15 33 49
schermafbeelding 2016-03-18 om 15 40 06

I'm going to buy some more I guess.

**Comment by cdjackson** [comment]
We can't merge this with the polling initial interval in seconds - it needs to allow a sub-second value as it's used for fast polling during updates.  Can you limit this PR to just the multi-instance change?

The polling issue is already fixed, so polling times should be ok. I do agree that having some times in seconds, and others in milliseconds is not nice - maybe we should change everything to seconds internally (we'd still want to only allow the user to specify seconds though I think).  However, I think it's best to just provide the multi-instance changes for now - can you update without the change in times?

**Comment by jspuij** [comment]
@cdjackson Done.

**Comment by cdjackson** [comment]
Thanks.

**Pull request merged**
