### PR TITLE
New IHC binding for openhab2

### PR DESCRIPTION
**Pull request by NielsPeterEnemark**
New OpenHAB 2 binding for the LK IHC Controller Visual2.

Based on the OpenHAB 1 Binding written by Pauli Anttila

Initial Release.

### CODE REVIEW

**Comment by paulianttila** [comment]
Hi @NielsPeterEnemark, damn I have done openHAB 2 binding as well :(

https://github.com/paulianttila/openhab2-addons/tree/ihc-binding2/addons/binding/org.openhab.binding.ihc

**Comment by NielsPeterEnemark** [comment]
Hi Pali,

Sorry about that !

No worries though - I did this during the Holiday Seasons to get acquainted
with the IHC controller and Java.
This is my first Java project and it might be reflected in the code.

I haven't tried your but it is probably much better than mine.

I can't understand Github so it will probably never be included in the
openhab2 thing. But I tried.


Regards
Niels Peter

**Comment by paulianttila** [comment]
@NielsPeterEnemark, don't be sorry. It's just stupid that we both used lot of time to implement the same binding. 

I took a little bit different broach than you did. I made one thing which have a dynamic channels. If you like to test mine, compiled version can be found [here](https://www.dropbox.com/s/4c8ls5ovd3apfmf/org.openhab.binding.ihc_2.3.0.201806062121.jar?dl=0)

**Comment by NielsPeterEnemark** [comment]
Hi Pali,

Thanks !
Of cause I am curious to see how you have solved the challenges with the
GUI interface.

Regards
Niels Peter

**Comment by wborn** [comment]
Did you already have a look at each others binding implementation and decide on how to continue?

**Comment by wborn** [comment]
Closing this PR since @NielsPeterEnemark doesn't want to stop progress on the @paulianttila's IHC binding   (see https://github.com/openhab/openhab2-addons/pull/3708#issuecomment-415095039).

**Pull request closed without merging**
