### PR TITLE
[autelis] Update for solar sensor

### PR DESCRIPTION
**Pull request by javiergarza**
support for solar sensor (present on my pentair SunTouch)

### CODE REVIEW

**Comment by martinvw** [comment]
Thanks for your contribution!

It would be great if you could include a `Signed-off-by` (to certify that you wrote it or otherwise have the right to pass it on as an open-source), see http://docs.openhab.org/developers/contributing/contributing.html#sign-your-work

If running a local git client you can use `git commit --amend --signoff`

**Comment by javiergarza** [comment]
If it helps, here is the XML returned by my Autelis Pentair Suntouch. As you can see below, I have 3 temperature sensors: water, air and solar measuring 67, 79 and 104 respectively. Having support for the solar temperature sensor is very important in terms of automation as it would allow the creation of rules to use the solar heater more efficiently.

<response>
<script/>
<system>
<runstate>50</runstate>
<model>11</model>
<haddr>1</haddr>
<opmode>0</opmode>
<freeze>0</freeze>
<sensor1>0</sensor1>
<sensor2>0</sensor2>
<sensor3>0</sensor3>
<sensor4>0</sensor4>
<sensor5>0</sensor5>
<version>1.6.8</version>
<time>1571768570</time>
<systime>11,22,4,22,10,19,0,0</systime>
</system>
<equipment>
<circuit1>0</circuit1>
<circuit2>0</circuit2>
<circuit3>1</circuit3>
<circuit4>0</circuit4>
<circuit5>0</circuit5>
<circuit6>1</circuit6>
<circuit7>0</circuit7>
<circuit8>0</circuit8>
<circuit9>0</circuit9>
<circuit10/>
<circuit11/>
<circuit12/>
<circuit13/>
<circuit14/>
<circuit15/>
<circuit16/>
<circuit17/>
<circuit18/>
<circuit19/>
<circuit20/>
<feature1/>
<feature2/>
<feature3/>
<feature4/>
<feature5/>
<feature6/>
<feature7/>
<feature8/>
<feature9/>
<feature10/>
</equipment>
<temp>
<poolht>3</poolht>
<spaht>1</spaht>
<htstatus>0</htstatus>
<poolsp>100</poolsp>
<spasp>100</spasp>
<maxplsp/>
<pooltemp>67</pooltemp>
<spatemp>67</spatemp>
<airtemp>79</airtemp>
<soltemp>104</soltemp>
<tempunits>F</tempunits>
<htpump>0</htpump>
</temp>
</response>

**Comment by digitaldan** [comment]
👍

**Comment by digitaldan** [comment]
@javiergarza  i was a bit hasty with my review, can you please add the new channel to the README file ?  Thanks.

**Comment by javiergarza** [comment]
done on https://github.com/openhab/openhab2-addons/pull/6292

**Comment by javiergarza** [comment]
Thanks a lot, I upgraded the OPENHAB version on my pi, and I confirm the solar temperature now displays fine. THANKS YOU!

**Pull request merged**
