### PR TITLE
[homematic] Update README.md - piVCCU supports gateway discovery, too

### PR DESCRIPTION
**Pull request by alexreinert**

### CODE REVIEW

**Comment by martinvw** [comment]
@gerrieg

**Comment by gerrieg** [comment]
Can‘t verify, never used it. But from the description of pivccu this PR is OK

**Comment by alexreinert** [comment]
I,m the author of piVCCU. The process for the discovery (same binary as original CCU) runs inside a lxc container. I also verified, that the magic packet on udp port 43439 will be answered by this process, even if it is sent from another device inside the same broadcast domain.

**Comment by martinvw** [comment]
Thanks!

**Pull request merged**
