### PR TITLE
[MQTT] fix typo in config example

### PR DESCRIPTION
**Pull request by menaceone**
changed line 250 from `Thing topic mything` to `Thing mqtt:topic:mything` 

Cost me an hour to figure out why my config wasn't working. 
I hope the pull request is in correct form, it's my first.

Signed-off-by: William Rother <menace_one@gmx.net> (github: menaceone)

### CODE REVIEW

**Comment by davidgraeff** [comment]
Isn't this reverting your change @crxporter?

**Comment by crxporter** [comment]
@menaceone - also if you can share one of your item configurations I’d appreciate it. 

I was just working on this documentation yesterday and tried it as you put with the mqtt:topic:mything in the thing configuration and it did not work on the bridged mqtt broker. I have a feeling you may not be using a bridged mqtt broker - in which case your configuration is probably correct - but should be added as another example for people not using the bridged broker.

**Comment by meingraham** [comment]
It seems that having one syntax for the bridged broker and a different syntax otherwise is going to cause lots of confusion with users and lots of issues raised for help to the Community or in GitHub, regardless of documentation examples. The choice of broker be transparent to how one specifies Things and topics.

**Comment by davidgraeff** [comment]
This is not mqtt binding related if anyone wonders.
`.thing` files and their weird syntax are a feature of openHAB and should be documented somewhere.

**Comment by crxporter** [comment]
For my part I would like to learn the proper configuration of the bridged and non-bridged brokers along with the things channel setup to go along with. 

Once I figure that out I’d like to help update the documentation with appropriate examples for each configuration. As it stands we have:

 - mqtt broker documentation shows only how to configure a broker as a thing (not a bridge)
 - mqtt generic things only shows how to configure with a bridged broker and not any examples to match the “broker as thing” documentation

This certainly is not ideal. And will cause issues. I’ll dig through the forums over the next couple of days to see if I can get things sorted out on the different combinations so we can update the docs to be more specific. 

Then again - if we do it like the people who made the binding (David) then we wouldn’t be using the files at all but be doing all of this in the paper UI! We can keep the fragmentation discussion for another day...

**Comment by meingraham** [comment]
> if we do it like the people who made the binding (David) then we wouldn’t be using the files at all but be doing all of this in the paper UI!

True... but some of us started when using files was the means of setting openHAB up (way back in July 2018). Yes, we can teach this old dog a new trick, but the migration is really painful.

It's particularly painful because doing things through PaperUI on a Raspberry 3B is painfully slow going with numerous clicks and re-clicks and refreshes. The RPi is perfectly acceptable from a performance standpoint during normal operation. It is only when configuration changes have to be made that using PaperUI is, let's say, not ideal.

There are also other reasons to use files (like when making wholesale changes which are easy to do in configuration files). Basically maintenance of the deployment from time to time. Yes, I can still do this by editing the jsondb... but, that's not really a supported or documented means. Yes, I make backups before ever touching it, but I'm always paranoid that I'm going to miss something and mess things up royally!

Mike

**Comment by crxporter** [comment]
> way back in July 2018

We started like right at the same time! And I completely agree with you on all points. My production system is still on MQTT 1.x - I’ve been trying to wrap my head around the switch over with my dev system (both pi 3B+’s). Until Insteon gets a 2.x binding (which may never happen) I’ll be using config files where I can. 

I was putting together what will eventually become my production mqtt 2.x things file and it clicked for me how to set it up. If everything is lined up in columns in a nice text editor I can easily see everything that is going on and copy my one working switch config to the other 10. Not really possible with a json file (Paper UI) but I guess the proper solution there would be to rewrite my firmware to use homie discovery, which is also on my to do list. But there’s only so many hours in a day!

Back on topic-
I’m wanting to get these documents figured out and updated so that I can give back to the community. I don’t know how to program a new binding but I have plenty of free time to test stuff and edit the documentation so here I am!

**Comment by menaceone** [comment]
wow, fast and deep response.
After your statements I was even more confused, deleted all and startet from scratch using MQTT doc `latest`.
Now it's working fine. I thing I mixed up doc usage `2.4` and `latest`.
Also important: Paper UI shows config updates just after config file update, but functionality is only given after complete openhab restart.

Here a strong position on textual config as well. Because this way one is able to use git for versioning and backup and is able to understand what is happening.
The paper UI database actions are a total blackbox for me.

I'm closing my merge request, as it is not correct.
Thanks again guys, hoping to use openhab more and more and will definitve give feedback/contribute to the doc.

**Pull request closed without merging**
