### PR TITLE
[neohub] NeoHub Binding new PR to replace PR #5688

### PR DESCRIPTION
**Pull request by andrewfg**
The pull request https://github.com/openhab/openhab2-addons/pull/5688 was incorrectly closed; so this is a new one to continue cleanly from that old one.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
I am afraid, this PR still isn't clean - please check https://github.com/openhab/openhab2-addons/pull/5952/files and see the changes that should not be there right at the top.

**Comment by kaikreuzer** [comment]
Looks like [this commit](https://github.com/openhab/openhab2-addons/pull/5952/commits/988e1608ccfdf5dd20e2addd72c138a4b357b4b1) is the culprit.

**Comment by andrewfg** [comment]
Sorry for this. I had added my name to the CODEOWNERS file and the binding to the bom/openhab-addons/pom.xml file. However other people had edited those files since my original fork was made which caused conflicts. I have now removed these two files entirely from the neohub branch of my repo. So perhaps you can kindly add the relevant entries into the master version of those files when you do the merge?

**CODEOWNERS**
`/bundles/org.openhab.binding.neohub/ @andrewfg
`

**bom/openhab-addons/pom.xml**
```
    <dependency>
      <groupId>org.openhab.addons.bundles</groupId>
      <artifactId>org.openhab.binding.neohub</artifactId>
      <version>${project.version}</version>
    </dependency>

```

**Comment by kaikreuzer** [comment]
Git isn't your friend, indeed ;-)
Now you have removed those two files, but they clearly must be kept and your additions should be added to them.
I think the problem was that you didn't base your branch on the latest version of the master branch and thus there were already changes on master that were not included in your branch. Do you maybe want to have another try...?

**Comment by kaikreuzer** [comment]
> other people had edited those files since my original fork was made which caused conflicts.

The magic process to do in such a case is a "rebase on master" - that will allow you to merge the changes locally before committing them.

**Comment by andrewfg** [comment]
> the magic process to do in such a case is a "rebase on master" 

Argh!! Can someone please help me with the EXACT git commands? My fork andrewfg:master branch was forked from the openhab2-addons:master branch about 2 months ago. And in my fork andrewfg I deleted and recreated today a branch called andrewfg:neohub. My pull request is to merge andrewfg:neohub with openhab2-addons:master. And specifically to merge my binding specific additions to CODEOWNERS and bom/openhab-addons/pom.xml into openhab2-addons/master without any adds or deletes that other people may have made to those two files in the meantime.

**Comment by andrewfg** [comment]
Hi @kaikreuzer, I think it is now clean, so I would appreciate it if you can move it onwards before your master diverges from my fork yet again. :)

**Comment by andrewfg** [comment]
Many thanks Kai :)

**Comment by bjoernbrings** [comment]
There seems to be some kind of problem around this binding with the sandbox build:

> Failed to create archive: Could not find artifact org.openhab.addons.bundles:org.openhab.binding.neohub:jar:2.5.0 in sandbox-all


Don't know whether this is really related to this binding or just some build problem.

**Comment by Hilbrand** [comment]
@bjoernbrings  I think that could be the problem. If created a pr to add it #5974 5974

**Comment by bjoernbrings** [comment]
Thanks for the quick reaction.
Could/should have done this myself, but was not sure whether it was really the root. Will monitor it with the next build.

**Pull request merged**
