### PR TITLE
[hueemulation] Fix integration tests and cleanup

### LINKED ISSUE #5907: [hueemulation] Integration tests fail
Build on Windows 10:
```
08:46:02.840 [EventAdmin Async Event Dispatcher Thread] INFO org.ops4j.pax.web.utils.ServletContainerInitializerScanner - will add ch.qos.logback.classic.servlet.LogbackServletContainerInitializer to ServletContainerInitializers
08:46:02.840 [EventAdmin Async Event Dispatcher Thread] WARN org.ops4j.pax.web.utils.ServletContainerInitializerScanner - failed to parse and instantiate of javax.servlet.ServletContainerInitializer in classpath
08:46:02.840 [EventAdmin Async Event Dispatcher Thread] INFO org.ops4j.pax.web.utils.ServletContainerInitializerScanner - will add org.glassfish.jersey.servlet.init.JerseyServletContainerInitializer to ServletContainerInitializers
08:46:02.840 [EventAdmin Async Event Dispatcher Thread] INFO org.ops4j.pax.web.utils.ServletContainerInitializerScanner - added ServletContainerInitializer: org.glassfish.jersey.servlet.init.JerseyServletContainerInitializer
08:46:02.840 [main] DEBUG org.eclipse.smarthome.core.common.registry.AbstractRegistry - Provider "ManagedRuleProvider" has been removed.
TEST UpnpServiceTest(org.openhab.io.hueemulation.internal.HueEmulationServiceOSGiTest) <<< ERROR:
Expected: not null
     but: was null
java.lang.AssertionError:
Expected: not null
     but: was null
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.openhab.io.hueemulation.internal.HueEmulationServiceOSGiTest.setUp(HueEmulationServiceOSGiTest.java:82)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
        at junit.framework.TestSuite.runTest(TestSuite.java:252)
        at junit.framework.TestSuite.run(TestSuite.java:247)
        at aQute.junit.Activator.test(Activator.java:340)
        at aQute.junit.Activator.automatic(Activator.java:236)
        at aQute.junit.Activator.run(Activator.java:177)
        at aQute.launcher.Launcher.lambda$serviceChanged$0(Launcher.java:1385)
        at aQute.launcher.Launcher.run(Launcher.java:352)
        at aQute.launcher.Launcher.main(Launcher.java:152)
08:46:02.855 [EventAdmin Async Event Dispatcher Thread] DEBUG org.eclipse.jetty.util.DecoratedObjectFactory - Adding Decorator: org.eclipse.jetty.util.DeprecationWarning@23c86965
08:46:02.855 [EventAdmin Async Event Dispatcher Thread] DEBUG org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection - Adding bean: HttpServiceContext{httpContext=null}
08:46:02.855 [EventAdmin Async Event Dispatcher Thread] DEBUG org.eclipse.jetty.util.component.ContainerLifeCycle - org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection@45a8f827[HttpServiceContext{httpContext=null}] added {HttpServiceContext{httpContext=null},UNMANAGED}
08:46:02.855 [EventAdmin Async Event Dispatcher Thread] DEBUG org.eclipse.jetty.util.component.ContainerLifeCycle - HttpServiceContext{httpContext=null} added {org.eclipse.jetty.server.session.SessionHandler1829120867==dftMaxIdleSec=-1,MANAGED}
08:46:02.871 [EventAdmin Async Event Dispatcher Thread] DEBUG org.eclipse.jetty.util.component.ContainerLifeCycle - org.eclipse.jetty.security.ConstraintSecurityHandler@48ae51a2 added {org.eclipse.jetty.security.DefaultAuthenticatorFactory@757402e,POJO}
08:46:02.871 [EventAdmin Async Event Dispatcher Thread] DEBUG org.eclipse.jetty.util.component.ContainerLifeCycle - org.eclipse.jetty.server.session.SessionHandler1829120867==dftMaxIdleSec=-1 added {org.eclipse.jetty.security.ConstraintSecurityHandler@48ae51a2,MANAGED}
Tests run  : 1
Passed     : 0
Errors     : 1
Failures   : 0
```

### PR DESCRIPTION
**Pull request by wborn**
Fixes #5907

The tricky part was to get the jupnp components to start. These require a configuration to be provided by the `ConfigurationAdmin`.

### CODE REVIEW

**Comment by J-N-K** [comment]
Nice. I found that the config was missing but didn’t manage to add one.

**Comment by APajonk** [comment]
Hi guys,

unfortunetely it looks like this change causes issues on existing environments now?

2019-09-30 12:03:58.483 [DEBUG] [org.openhab.io.hueemulation         ] - BundleEvent STARTING - org.openhab.io.hueemulation
2019-09-30 12:03:58.532 [DEBUG] [org.openhab.io.hueemulation         ] - BundleEvent STARTED - org.openhab.io.hueemulation
2019-09-30 12:03:58.534 [DEBUG] [ig.xml.osgi.XmlDocumentBundleTracker] - Reading the XML document '/ESH-INF/config/config.xml' in module 'org.openhab.io.hueemulation'...
2019-09-30 12:03:58.877 [ERROR] [org.apache.felix.scr                ] - bundle org.apache.felix.scr:2.1.16 (43)Error while loading components of bundle org.openhab.io.hueemulation:2.5.0.201909300426 (235)
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
	at org.apache.felix.cm.impl.ConfigurationImpl.configure(ConfigurationImpl.java:659) ~[?:?]
	at org.apache.felix.cm.impl.ConfigurationImpl.configureFromPersistence(ConfigurationImpl.java:619) ~[?:?]
	at org.apache.felix.cm.impl.ConfigurationImpl.<init>(ConfigurationImpl.java:194) ~[?:?]
	at org.apache.felix.cm.impl.ConfigurationManager.listConfigurations(ConfigurationManager.java:547) ~[?:?]
	at org.apache.felix.cm.impl.ConfigurationAdminImpl.listConfigurations(ConfigurationAdminImpl.java:190) ~[?:?]
	at org.apache.felix.scr.impl.manager.RegionConfigurationSupport.findConfigurations(RegionConfigurationSupport.java:655) ~[?:?]
	at org.apache.felix.scr.impl.manager.RegionConfigurationSupport.findSingletonConfiguration(RegionConfigurationSupport.java:554) ~[?:?]
	at org.apache.felix.scr.impl.manager.RegionConfigurationSupport.configureComponentHolder(RegionConfigurationSupport.java:199) ~[?:?]
	at org.apache.felix.scr.impl.BundleComponentActivator.setRegionConfigurationSupport(BundleComponentActivator.java:763) ~[?:?]
	at org.apache.felix.scr.impl.helper.ConfigAdminTracker$1.addingService(ConfigAdminTracker.java:69) ~[?:?]
	at org.apache.felix.scr.impl.helper.ConfigAdminTracker$1.addingService(ConfigAdminTracker.java:41) ~[?:?]
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941) ~[?:?]
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870) ~[?:?]
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) ~[?:?]
	at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183) ~[?:?]
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:318) ~[?:?]
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:261) ~[?:?]
	at org.apache.felix.scr.impl.helper.ConfigAdminTracker.<init>(ConfigAdminTracker.java:86) ~[?:?]
	at org.apache.felix.scr.impl.BundleComponentActivator.<init>(BundleComponentActivator.java:275) ~[?:?]
	at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:380) ~[?:?]
	at org.apache.felix.scr.impl.Activator.access$200(Activator.java:49) ~[?:?]
	at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:264) ~[?:?]
	at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196) ~[?:?]
	at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169) ~[?:?]
	at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49) ~[?:?]
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:482) ~[?:?]
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:415) ~[?:?]
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232) ~[?:?]
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:444) ~[?:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:908) ~[?:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) ~[?:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:213) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:120) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:112) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:168) ~[?:?]
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:476) ~[?:?]
	at org.eclipse.osgi.container.Module.start(Module.java:467) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402) ~[?:?]
	at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.startBundle(BundleInstallSupportImpl.java:165) ~[?:?]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:1153) ~[?:?]
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:1036) ~[?:?]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062) ~[?:?]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]

**Comment by martinvw** [comment]
I'm not sure whether it's related to this specific PR, maybe @wborn or @J-N-K know more.

But I expect some other changes to be causing this, could still be related to recent changes around this subject but this PR looks unrelated.

**Comment by wborn** [comment]
This PR only removed unused imports/commented code and fixed the integration tests. :-)

**Pull request merged**
