### PR TITLE
[allplay] Add support for zone (multiroom) creation and deletion

### PR DESCRIPTION
**Pull request by dominicdesu**
Signed-off-by: Dominic Lerbs <dominicdesu@hallojapan.de>

Adds functionality to create zones and clear zones to the AllPlay binding.
Zones can be creates by sending a list of comma separated speaker names (thing labels) to the speaker which should act as the master.
This is a first simple version to support multiroom, more sophisticated functionality (e.g. add/remove a single speaker to/from an existing zone) could be evaluated and submitted in a separate PR.

Solves #1631.

### CODE REVIEW

**Comment by dominicdesu** [comment]
Actually I have two questions/remarks:
1. To create zones, labels of other speaker things (basically the name of an openHAB thing?) have to be used. This has the advantage, that users can rename their speakers outside of openHAB and existing rules will continue to work. It has the disadvantage that it is not possible to add speakers to a zone which are not managed by openHAB. Is this the right approach?
2. When trying to create a zone but the slave speaker is unreachable, the call to the alljoyn library blocks and I get this message in the logs: `[WARN ] [ore.internal.events.OSGiEventManager] - Dispatching event to subscriber 'org.eclipse.smarthome.core.thing.internal.CommunicationManager@14799d2' takes more than 5000ms.` However, sending other commands afterwards still seem to work. Should I call the zone creation in a new thread to avoid this warning, or this somehow handled by openHAB?

**Comment by martinvw** [comment]
1. It seems not friendly if you cannot use the speakers without openHAB, but I do not completely understand the reason of this dependency.

2. The proper solution would indeed be to schedule a runnable to the scheduler available from the abstract handler. I don't know the impact on your code, but if it takes less then a second in  the normal case i'm okay with delaying to add a scheduler for a new pr.

**Comment by dominicdesu** [comment]
@martinvw thanks for the feedback.
1. Sorry I guess my wording was unclear. The speakers and zones work fine without openHAB. What I wanted to say was that you can only create a zone of speakers in openHAB if **all** speakers are managed as things in openHAB. Actually this should not really be a problem...
2. I have updated the PR and call the method in a new thread now. Should I squash both commits into one or can you do that when merging?

**Comment by martinvw** [comment]
Thanks, its fine!

**Pull request merged**
