### PR TITLE
[avmfritz] Update README.md

### PR DESCRIPTION
**Pull request by FlorianSW**
Tested in the OH 2 release, updted from:
https://www.eclipse.org/smarthome/documentation/features/dsl.html

Signed-off-by: Florian Schmidt florian.schmidt.welzow@t-online.de

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Why do you think the current example is wrong?

**Comment by FlorianSW** [comment]
Because it doesn't work with OH2, the things are kept in the state "Initializing" with the current example and starts working with the one documented for Eclipse SmartHome.

**Comment by kaikreuzer** [comment]
We should analyze in detail, why the existing example is not working; from what I see, its syntax looks fully correct, while yours doesn't (as the AIN is a config parameter of a thing and thus needs to be specified as such).

**Comment by cweitkamp** [comment]
I did some tests. Every change in the configuration I tested was followed by a restart of the openhab2.service.

First of all I confirm that the current documentation in demo.things does not work. The things kept staying in state "INITIALIZING" until they switched to "UNINITIALIZED - HANDLER_MISSING_ERROR". Linked channels neither returned values nor updated them. All devices poped up in Paper UI Inbox as result of discovery job.

After changing the configuration to the suggested syntax the states of the things changed to "ONLINE" in Paper UI. But in the Configuration Parameters the AIN was missing. The linked channels somehow returned correct values. Sending values triggered a NPE:

`2017-02-26 21:47:34.639 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occured while calling handler: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)[:1.8.0_65]
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)[:1.8.0_65]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:188)[99:org.eclipse.smarthome.core:0.9.0.b4]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:81)[99:org.eclipse.smarthome.core:0.9.0.b4]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:65)[99:org.eclipse.smarthome.core:0.9.0.b4]
	at org.eclipse.smarthome.core.thing.internal.ThingManager.receiveCommand(ThingManager.java:369)[106:org.eclipse.smarthome.core.thing:0.9.0.b4]
	at org.eclipse.smarthome.core.items.events.AbstractItemEventSubscriber.receive(AbstractItemEventSubscriber.java:46)[99:org.eclipse.smarthome.core:0.9.0.b4]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)[99:org.eclipse.smarthome.core:0.9.0.b4]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)[99:org.eclipse.smarthome.core:0.9.0.b4]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:179)[99:org.eclipse.smarthome.core:0.9.0.b4]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
Caused by: java.lang.NullPointerException
	at org.openhab.binding.avmfritz.handler.DeviceHandler.handleCommand(DeviceHandler.java:175)[249:org.openhab.binding.avmfritz:2.1.0.201702142127]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$4.call(ThingManager.java:372)[106:org.eclipse.smarthome.core.thing:0.9.0.b4]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$4.call(ThingManager.java:1)[106:org.eclipse.smarthome.core.thing:0.9.0.b4]
	... 5 more`

I did another change in the thing configuration to set the ain config parameter which looks like this:
```
Bridge avmfritz:fritzbox:1 [ ipAddress="192.168.xxx.xxx", password ="xxx", user="xxx" ] {
    FRITZ_DECT_200 xxxxxxxxxxx "Name" [ ain="xxxxxxxxxxx" ]
}
```

After a restart everything was fine in Paper UI. States changed to "ONLINE", channels worked correctly.

Any thoughts?

**Comment by CWempe** [comment]
I got it working too with this example.
Thanks.

```
Bridge avmfritz:fritzbox:k [ ipAddress="192.168.1.1", password="xxxxxx", user="openhab" ] {
    FRITZ_DECT_200 xxxxxxxxxxx "DECT1"
}
```

But the created thing has not the name I expected.

It is now called `avmfritz:FRITZ_DECT_200:k:xxxxxxxxxxx ` instead of `avmfritz:FRITZ_DECT_200:k:DECT1`.

In PaperUI it shows the thing as ONLINE, but weh I edit the thing the AIN field is empty.
The name is correct though.

**Comment by martinvw** [comment]
@CWempe do you mean that it does or does not work with example in this PR? You also describe something going wrong.
@FlorianSW did you already look at log given by @cweitkamp?

**Comment by CWempe** [comment]
I was refering to @cweitkamp 's example.
But without the AIN.

So, yes, I got it working like the example in https://github.com/openhab/openhab2-addons/pull/1963/commits/417c6bf49c153f7f6e908bf1ed68f54b338567d9.

Like I mentioned, The name of the thing is not like I expected it to be.
But I dod not follow this issue and use the generated thing name now.

**Comment by martinvw** [comment]
@FlorianSW  Any updates on this PR? Thanks for you time!

**Comment by FlorianSW** [comment]
@martinvw sorry, I haven't looked at this further, as it works with the suggested config. However, I can understand that this should be investigated more deeply.

**Comment by cweitkamp** [comment]
All.

I took the time and did a completly new test today. I set up a fresh OH2 environment on my new RPI3 with raspbian (Debian Stretch 9.0) and snapshot of OH2 2.2.0 Build # 1023. (No configuration using Paper UI, only textual configuration).

The only binding I installed is the fresh AVM FRITZ! version located here: https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.avmfritz/2.2.0-SNAPSHOT/

My files look like this

fritz.things:
```
Bridge avmfritz:fritzbox:1 [ ipAddress="fritz.box", user="xxx", password="xxx" ] {
    Thing FRITZ_DECT_200 xxxxxxxx "FRITZ!DECT 200 #1"
}
```

fritz.items:
```csv
Switch fritzDECT200Outlet "Switchable outlet" {
    channel="avmfritz:FRITZ_DECT_200:1:xxxxxxxx:outlet"
}
```

fritz.sitemap:
```php
sitemap fritz label="AVM FRITZ!Box 7490" {
    Frame label="AVM FRITZ!DECT 200 #1" {
        Switch item=fritzDECT200Outlet
    }
}
```

The result is the same like I posted above. The Item and the Sitemap gets updated as expected. Meaning, I can see the status of the Switch and it changes, if I changed it in my FRITZ!OS. Every time I tried to toggle the Switch in my Sitemap I got the following NPE:

```
2017-08-24 15:19:40.874 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occurred while calling handler: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at org.eclipse.smarthome.core.common.SafeMethodCaller.executeDirectly(SafeMethodCaller.java:220) [100:org.eclipse.smarthome.core:0.9.0.201708151402]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:189) [100:org.eclipse.smarthome.core:0.9.0.201708151402]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:83) [100:org.eclipse.smarthome.core:0.9.0.201708151402]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:67) [100:org.eclipse.smarthome.core:0.9.0.201708151402]
	at org.eclipse.smarthome.core.thing.internal.ThingManager.receiveCommand(ThingManager.java:379) [107:org.eclipse.smarthome.core.thing:0.9.0.201708151402]
	at org.eclipse.smarthome.core.items.events.AbstractItemEventSubscriber.receive(AbstractItemEventSubscriber.java:47) [100:org.eclipse.smarthome.core:0.9.0.201708151402]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:193) [100:org.eclipse.smarthome.core:0.9.0.201708151402]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1) [100:org.eclipse.smarthome.core:0.9.0.201708151402]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:181) [100:org.eclipse.smarthome.core:0.9.0.201708151402]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:?]
Caused by: java.lang.NullPointerException
	at org.openhab.binding.avmfritz.handler.DeviceHandler.handleCommand(DeviceHandler.java:152) ~[?:?]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$3.call(ThingManager.java:382) ~[?:?]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$3.call(ThingManager.java:1) ~[?:?]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.executeDirectly(SafeMethodCaller.java:218) ~[?:?]
	... 12 more
```

I finally got it working with my suggested Thing configuration which additionally sets the `ain`:

fritz.things:
```
Bridge avmfritz:fritzbox:1 [ ipAddress="fritz.box", user="xxx", password="xxx" ] {
    Thing FRITZ_DECT_200 xxxxxxxx "FRITZ!DECT 200 #1" [ ain="xxxxxxxx" ]
}
```

It follows that not only the `demo.things` example of the documentation has to be changed, the `demo.items` examples have to be adopted as well.

**Comment by cweitkamp** [comment]
@martinvw What shall we do now? I have two confirmed examples from the community for my suggested Thing configuration. Let's close this. I will create a new PR.

**Comment by martinvw** [comment]
Great

**Comment by cweitkamp** [comment]
See #2920

**Pull request closed without merging**
