### PR TITLE
maven + bnd migration: org.openhab.binding.avmfritz + tests

### PR DESCRIPTION
**Pull request by maggu2810**

### CODE REVIEW

**Comment by J-N-K** [comment]
Thanks, most of it looks pretty straight-forward. I don‘t think it should be too difficult to port other bindings.

 But how do I know which bundles need to be included in itest.bndrun?

**Comment by maggu2810** [comment]
> But how do I know which bundles need to be included in itest.bndrun?

That's basically very simple...

It has been complicated by that change: https://github.com/openhab/openhab-core/pull/530/files#diff-600376dffeb79835ede4a0b285078036R177
That change simplifies the usage of pom derivied dependencies for Tycho projects and it's validation step.

I am using f1c74e5d87f6a425303d42fa94fc50e586908c4c all the time.
Use this commit and build openhab-core then the core bundles will contain also the require capability sections caused by DS requirements.
For Maven + Bnd on openhab2-addons it is already enabled.

After that you just need to set the part above `# done`.
It should be only the name of the bundle to test (fragment host) and the test bundle name (as required bundle to be present).

Execute once a build with the `withResolver` property set (I added that switch to some parent pom) of the specific test project only (I assume the bundle to test has been already build before and is present in your local repo):

```
mvn clean install -DwithResolver` -pl itests/org.openhab.core.storage.json.tests
```

This will enable the bnd revolver and it generates the `runbundles`.

**Comment by maggu2810** [comment]
Otherwise feel free to ask.
Perhaps we could create a documentation page that describes how the things are wired and working and what needs to be done to create a new one or migrate an existing one

**Comment by wborn** [comment]
Thanks for the example! 
We'll also need to update the CODEOWNERS file for these changes (see #5061). :wink:

**Comment by maggu2810** [comment]
Thank you for that hint. Will try to fix it next time myself.

**Pull request merged**
