### PR TITLE
migrate unifi binding to bnd

### PR DESCRIPTION
**Pull request by J-N-K**
Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by J-N-K** [comment]
@mgbowman, I can't request a review from. you. Could you have a look here? Thanks.

**Comment by wborn** [comment]
Can you resolve the merge conflicts @J-N-K ?

**Comment by J-N-K** [comment]
done

**Comment by mgbowman** [comment]
LGTM

**Pull request merged**
