### PR TITLE
Zwave device updates

### PR DESCRIPTION
**Pull request by jspuij**
Two small updates to the device database:

- Fibaro FGD211 application version 1.9
- Added Everspring SE812 Indoor Siren

Of course tested on my own network.

### CODE REVIEW

**Comment by cdjackson** [comment]
Welcome back :)

Can you update this in the [online database](http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/) rather than editing the XML directly? I can't merge this as I need to add some changes into the XML file and doing that to hundreds of files is a nightmare, so I try and do it in the exporter which allows update of all files in one hit...

If you have the XML file, then just loading this to the [database page for this device](http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/36) should be enough.

The next update of the binding will update every file in the database...

**Comment by jspuij** [comment]
Thanks ;-) As you notice I'm a bit rusty ;-) Will update the database.

**Comment by cdjackson** [comment]
Thanks - I’ve just updated your access so you can edit :)

Any issues, thoughts or comments - just yell (it’s still reasonably new!).

**Comment by jspuij** [comment]
First impression: WOW! Great. I've adjusted both devices. Really very nice.

**Comment by cdjackson** [comment]
Thanks - database maintenance was just getting to be a major task, so this at least means ‘anyone’ can edit stuff…

**Comment by cdjackson** [comment]
Unfortunately, we now have an overlaping version on the FGD211… There’s another version in the database for version 1.9, so if you’re device is 1.9, can you load the XML to that one there… I suspect it’s the same as the one for the earlier version - normally with Fibaro they just change some of the parameters…

http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/118 <http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/118>

Thanks
Chris

**Comment by jspuij** [comment]
Oops. Sorry. I tried updating the 1.9 to 1.11 version with my node.xml but nothing happens, it's not completed by the info. I clicked review, but don't know if you reviewing it is going to matter ;-)

**Comment by jspuij** [comment]
BTW, here's the node info:

```xml
<node>
  <deviceClass>
    <basicDeviceClass>ROUTING_SLAVE</basicDeviceClass>
    <genericDeviceClass>MULTILEVEL_SWITCH</genericDeviceClass>
    <specificDeviceClass>POWER_SWITCH_MULTILEVEL</specificDeviceClass>
  </deviceClass>
  <homeId>0xd46e75c4</homeId>
  <nodeId>3</nodeId>
  <version>4</version>
  <manufacturer>0x10f</manufacturer>
  <deviceId>0x109</deviceId>
  <deviceType>0x100</deviceType>
  <listening>true</listening>
  <frequentlyListening>false</frequentlyListening>
  <routing>true</routing>
  <security>false</security>
  <beaming>true</beaming>
  <maxBaudRate>40000</maxBaudRate>
  <nodeInformationFrame>
    <int>114</int>
    <int>134</int>
    <int>112</int>
    <int>133</int>
    <int>142</int>
    <int>38</int>
    <int>39</int>
    <int>115</int>
    <int>239</int>
  </nodeInformationFrame>
  <supportedCommandClasses>
    <entry>
      <commandClass>SWITCH_MULTILEVEL</commandClass>
      <multiLevelSwitchCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </multiLevelSwitchCommandClass>
    </entry>
    <entry>
      <commandClass>MANUFACTURER_SPECIFIC</commandClass>
      <manufacturerSpecificCommandClass>
        <version>1</version>
        <instances>1</instances>
      </manufacturerSpecificCommandClass>
    </entry>
    <entry>
      <commandClass>BASIC</commandClass>
      <basicCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </basicCommandClass>
    </entry>
    <entry>
      <commandClass>NO_OPERATION</commandClass>
      <noOperationCommandClass>
        <version>1</version>
        <instances>1</instances>
      </noOperationCommandClass>
    </entry>
    <entry>
      <commandClass>POWERLEVEL</commandClass>
      <powerLevelCommandClass>
        <version>1</version>
        <instances>1</instances>
      </powerLevelCommandClass>
    </entry>
    <entry>
      <commandClass>VERSION</commandClass>
      <versionCommandClass>
        <version>1</version>
        <instances>1</instances>
        <libraryType>LIB_SLAVE_ENHANCED</libraryType>
        <protocolVersion>3.42</protocolVersion>
        <applicationVersion>1.9</applicationVersion>
      </versionCommandClass>
    </entry>
    <entry>
      <commandClass>CONFIGURATION</commandClass>
      <configurationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configParameters>
          <entry>
            <int>1</int>
            <configurationParameter>
              <index>1</index>
              <size>1</size>
              <value>-1</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>6</int>
            <configurationParameter>
              <index>6</index>
              <size>1</size>
              <value>0</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>7</int>
            <configurationParameter>
              <index>7</index>
              <size>1</size>
              <value>0</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>39</int>
            <configurationParameter>
              <index>39</index>
              <size>2</size>
              <value>600</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>8</int>
            <configurationParameter>
              <index>8</index>
              <size>1</size>
              <value>1</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>9</int>
            <configurationParameter>
              <index>9</index>
              <size>1</size>
              <value>5</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>10</int>
            <configurationParameter>
              <index>10</index>
              <size>1</size>
              <value>1</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>11</int>
            <configurationParameter>
              <index>11</index>
              <size>1</size>
              <value>1</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>12</int>
            <configurationParameter>
              <index>12</index>
              <size>1</size>
              <value>99</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>13</int>
            <configurationParameter>
              <index>13</index>
              <size>1</size>
              <value>2</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>14</int>
            <configurationParameter>
              <index>14</index>
              <size>1</size>
              <value>0</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>15</int>
            <configurationParameter>
              <index>15</index>
              <size>1</size>
              <value>1</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>16</int>
            <configurationParameter>
              <index>16</index>
              <size>1</size>
              <value>1</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>17</int>
            <configurationParameter>
              <index>17</index>
              <size>1</size>
              <value>0</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>18</int>
            <configurationParameter>
              <index>18</index>
              <size>1</size>
              <value>0</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>19</int>
            <configurationParameter>
              <index>19</index>
              <size>1</size>
              <value>0</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>20</int>
            <configurationParameter>
              <index>20</index>
              <size>1</size>
              <value>-120</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>30</int>
            <configurationParameter>
              <index>30</index>
              <size>1</size>
              <value>3</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
        </configParameters>
      </configurationCommandClass>
    </entry>
    <entry>
      <commandClass>SWITCH_ALL</commandClass>
      <switchAllCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
        <mode>SWITCH_ALL_INCLUDE_ON_OFF</mode>
      </switchAllCommandClass>
    </entry>
    <entry>
      <commandClass>ASSOCIATION</commandClass>
      <associationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configAssociations>
          <entry>
            <int>1</int>
            <associationGroup>
              <index>1</index>
              <associations>
                <multiAssociationCommandClass>
                  <node>1</node>
                  <endpoint>0</endpoint>
                </multiAssociationCommandClass>
              </associations>
            </associationGroup>
          </entry>
          <entry>
            <int>2</int>
            <associationGroup>
              <index>2</index>
              <associations>
                <multiAssociationCommandClass>
                  <node>1</node>
                  <endpoint>0</endpoint>
                </multiAssociationCommandClass>
              </associations>
            </associationGroup>
          </entry>
          <entry>
            <int>3</int>
            <associationGroup>
              <index>3</index>
              <associations>
                <multiAssociationCommandClass>
                  <node>1</node>
                  <endpoint>0</endpoint>
                </multiAssociationCommandClass>
              </associations>
            </associationGroup>
          </entry>
        </configAssociations>
        <maxGroups>3</maxGroups>
      </associationCommandClass>
    </entry>
  </supportedCommandClasses>
  <nodeNeighbors>
    <int>6</int>
    <int>11</int>
    <int>12</int>
    <int>13</int>
    <int>14</int>
    <int>15</int>
    <int>16</int>
    <int>17</int>
    <int>18</int>
    <int>21</int>
    <int>22</int>
    <int>26</int>
    <int>27</int>
    <int>28</int>
  </nodeNeighbors>
  <lastSent>2016-03-14 06:44:22.17 UTC</lastSent>
  <lastReceived>2016-03-14 06:44:22.102 UTC</lastReceived>
</node>
```

**Pull request closed without merging**
