### PR TITLE
[nuki] Clean handling of bridge/things

### LINKED ISSUE #5859: [nuki] Bridge remains in INITIALIZING state
My nuki bridge worked some times but now it remains in the state initializing. Even a openhab restart does not fix this.
I have absolutely no idea, how to root cause this problem. 
Is this a known bug?

As you can see in the log, at the openhab restart on 17. July nuki binding threw an error, yesterday (23. July) it didn't. But it stays not connected to openhab.
grafik

```
2019-07-17 05:58:32.138 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'nuki.items'
2019-07-17 05:58:37.561 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'nuki.things'
        at org.openhab.binding.nuki.internal.dataexchange.NukiHttpClient.executeRequest(NukiHttpClient.java:83) ~[?:?]
        at org.openhab.binding.nuki.internal.dataexchange.NukiHttpClient.getBridgeCallbackRemove(NukiHttpClient.java:230) ~[?:?]
        at org.openhab.binding.nuki.internal.handler.NukiBridgeHandler.manageNukiBridgeCallbacks(NukiBridgeHandler.java:151) ~[?:?]
        at org.openhab.binding.nuki.internal.handler.NukiBridgeHandler.initializeHandler(NukiBridgeHandler.java:107) ~[?:?]
        at org.openhab.binding.nuki.internal.handler.NukiBridgeHandler.lambda$0(NukiBridgeHandler.java:83) ~[?:?]
        at org.openhab.binding.nuki.internal.dataexchange.NukiHttpClient.executeRequest(NukiHttpClient.java:83) ~[?:?]
        at org.openhab.binding.nuki.internal.dataexchange.NukiHttpClient.getBridgeLockState(NukiHttpClient.java:147) ~[?:?]
        at org.openhab.binding.nuki.internal.handler.NukiSmartLockHandler.initializeHandler(NukiSmartLockHandler.java:98) ~[?:?]
        at org.openhab.binding.nuki.internal.handler.NukiSmartLockHandler.lambda$0(NukiSmartLockHandler.java:63) ~[?:?]
        at org.openhab.binding.nuki.internal.dataexchange.NukiHttpClient.executeRequest(NukiHttpClient.java:83) ~[?:?]
        at org.openhab.binding.nuki.internal.dataexchange.NukiHttpClient.getBridgeCallbackList(NukiHttpClient.java:209) ~[?:?]
        at org.openhab.binding.nuki.internal.handler.NukiBridgeHandler.manageNukiBridgeCallbacks(NukiBridgeHandler.java:138) ~[?:?]
        at org.openhab.binding.nuki.internal.handler.NukiBridgeHandler.initializeHandler(NukiBridgeHandler.java:107) ~[?:?]
        at org.openhab.binding.nuki.internal.handler.NukiBridgeHandler.lambda$0(NukiBridgeHandler.java:83) ~[?:?]
        at org.openhab.binding.nuki.internal.dataexchange.NukiHttpClient.executeRequest(NukiHttpClient.java:83) ~[?:?]
        at org.openhab.binding.nuki.internal.dataexchange.NukiHttpClient.getBridgeInfo(NukiHttpClient.java:118) ~[?:?]
        at org.openhab.binding.nuki.internal.handler.NukiBridgeHandler.checkBridgeOnline(NukiBridgeHandler.java:119) ~[?:?]
        at org.openhab.binding.nuki.internal.handler.NukiBridgeHandler.lambda$1(NukiBridgeHandler.java:84) ~[?:?]
2019-07-23 21:19:11.151 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler NukiSmartLockHandler of thing nuki:smartlock:nuki_bridge:Eingang tried updating channel lock although the handler was already disposed.
2019-07-23 21:19:11.159 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler NukiSmartLockHandler of thing nuki:smartlock:nuki_bridge:Eingang tried updating channel lockState although the handler was already disposed.
        at org.openhab.binding.nuki.internal.handler.NukiBridgeHandler.manageNukiBridgeCallbacks(NukiBridgeHandler.java:141) ~[?:?]
        at org.openhab.binding.nuki.internal.handler.NukiBridgeHandler.initializeHandler(NukiBridgeHandler.java:107) ~[?:?]
        at org.openhab.binding.nuki.internal.handler.NukiBridgeHandler.lambda$0(NukiBridgeHandler.java:83) ~[?:?]
2019-07-23 21:19:57.140 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'nuki.items'
2019-07-23 21:20:07.451 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'nuki.things'
```

I have openhab 2.5.0~S1592-1 running on debian stretch.

BTW: my nuki smartlock work as expected with my mobile or nuki web.

### PR DESCRIPTION
**Pull request by lolodomo**
Check that callbacks is not null to avoid a NPE

Fix #5859

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
I finished the reworking of the bridge/thing handling.
Of course, I was not able to test it.

Here is a jar for testing the change: [org.openhab.binding.nuki-2.5.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/3586612/org.openhab.binding.nuki-2.5.0-SNAPSHOT.zip)

**Comment by lolodomo** [comment]
I fixed another issue that could lead to a NPE during the initialize process and so to a thing remaining in INITIALIZING state.

I also checked that exceptions are correctly caught, and I think it was already done correctly. So it should not be another cause for the thing to remain in INITIALIZING state.

Please find a new test jar:
[org.openhab.binding.nuki-2.5.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/3586720/org.openhab.binding.nuki-2.5.0-SNAPSHOT.zip)

**Comment by lolodomo** [comment]
I fixed another issue that could lead to a NPE during the initialize process and so to a bridge remaining in INITIALIZING state.

I also checked that exceptions are correctly caught, and I think it was already done correctly. So it should not be another cause for the thing to remain in INITIALIZING state.

Please find a new test jar:
[org.openhab.binding.nuki-2.5.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/3586744/org.openhab.binding.nuki-2.5.0-SNAPSHOT.zip)

**Comment by lolodomo** [comment]
Please find a new test jar:
[org.openhab.binding.nuki-2.5.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/3586766/org.openhab.binding.nuki-2.5.0-SNAPSHOT.zip)

**Comment by lolodomo** [comment]
New jar with a fix that tries to avoid job crashing:
[org.openhab.binding.nuki-2.5.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/3637675/org.openhab.binding.nuki-2.5.0-SNAPSHOT.zip)

**Comment by lolodomo** [comment]
New jar for testing if a delay between each request to the bridge helps to avoid the remaining exception at reconnection:
[org.openhab.binding.nuki-2.5.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/3638671/org.openhab.binding.nuki-2.5.0-SNAPSHOT.zip)

**Comment by lolodomo** [comment]
New jar for testing:
[org.openhab.binding.nuki-2.5.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/3639653/org.openhab.binding.nuki-2.5.0-SNAPSHOT.zip)

**Comment by lolodomo** [comment]
What are the news ?

**Comment by Dustinhoefer** [comment]
@lolodomo Can you fix the errors here? Seems like your commits were signed incorrectly. Looking forward to those fixes :)

**Comment by lolodomo** [comment]
There is no error.

I will finsh this PR by making logging and error catching reasonable.

**Comment by lolodomo** [comment]
This is certainly time to review and merge this PR.
We got 2 positive feedbacks (here and in the forum).
The only changes I just done compared to the tested version is the suppress of the throwable catching I introduced only for test purpose.

**Comment by lolodomo** [comment]
Anyone to merge this fix before the release?

**Pull request merged**
