### PR TITLE
[feed] Migrate to bnd

### PR DESCRIPTION
**Pull request by JueBag**
Signed-off-by: JueBag <opus42@gmx.de>

### CODE REVIEW

**Comment by Hilbrand** [comment]
This binding has a test extending `JavaOSGiTest`. That test should be in the `itest` location.

**Comment by JueBag** [comment]
Just noticed, ATM I'm trying to create the needed `itest.bndrun`. note sure if I*m able too.

**Comment by davidgraeff** [comment]
Thank you anyway @JueBag . Always nice to see people helping out.

**Comment by JueBag** [comment]
At least I learned something about handling git. Bloodpressure is back to normal again.

**Pull request closed without merging**
