### PR TITLE
Chromecast binding: fix audio sink (fix #1784)

### LINKED ISSUE #1784: Chromecast: the play and say console commands not working
With my Freebox Player Mini 4k (Android TV), the following console commands are not working (the palyer is switching to a notification screen but the audio file is never played):
```
openhab> smarthome:audio play chromecast:chromecast:68531fbf51cfff589ca6043630b411bb doorbell.mp3
openhab> smarthome:audio play chromecast:chromecast:68531fbf51cfff589ca6043630b411bb barking.mp3
openhab>
openhab> smarthome:voice say voici un essai de texte
```

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by tavalin** [comment]
What happens when the audio stream is longer than 30 seconds?

**Comment by lolodomo** [comment]
Note that it concerns only audio files provided by openHAB and so notifications. The playback will very probably stop after the 30 seconds. This can be checked by downloading a big MP3 in conf/sounds and then play it.

**Comment by lolodomo** [comment]
Tested and oh surprise, the playback is finally not stopped :)
To be honest, I think it is due a bug in the audio servlet that is cleaning streams only when handling a new request. If no request arrives, the audio file is still delivered even after the 30 seconds ;)

**Comment by tavalin** [comment]
OK, if that is how it is supposed to work (30 seconds to receive any new requests) then in theory I am OK with the change.  

If it is meant to cut the stream after x seconds then I think we need to look at the guidance for using audio sinks (i.e. audio length should be less than x seconds) as I had previously been using the audio play <stream url> to play a radio stream to different audio sinks depending on my room location - I would not like that functionality to break.

**Comment by lolodomo** [comment]
I updated my code (same code as the other PR for the Onkyo binding).

@tavalin : note that for a radio stream, there will be no change (no duration limit), it will not be handled by the audio servlet, just a direct link.
PS: I have not yet tested direct streams...

**Comment by tavalin** [comment]
Yes I see that bit now. 

LGTM then.

**Comment by lolodomo** [comment]
@tavalin : I tested the stream console command using different WEB radios as URL and it is working well. My PR is not impacting this part.

**Comment by kaikreuzer** [comment]
> The playback will very probably stop after the 30 seconds.

It should not. Existing streams should not be killed by the servlet. If this is what this issue is about, we should indeed rather look at fixing the AudioServlet.
Did you do any detailed analysis on the exact behavior?

**Comment by lolodomo** [comment]
It is not killed, confirmed by a test with a big MP3. In this case, the duration has apparently no impact which is finally a very good thing. I am just not sure that is what you expect ?
But the reason of the change is that without the change Android TV is not able to play the audio file.

**Comment by kaikreuzer** [comment]
> which is finally a very good thing. I am just not sure that is what you expect ?

Yes, this is what I expect - you can access the stream and you fully receive it.

> Android TV is not able to play the audio file.

So we would have to figure out why. Could you enable debug logging for the audio servlet:

```
log:set DEBUG org.eclipse.smarthome.core.audio
```
We should then see what kind of requests the Android TV is doing.

**Comment by lolodomo** [comment]
I will do and let you know the result.

**Comment by lolodomo** [comment]
@kaikreuzer @tavalin  : reading again the code from the audio servlet, I understood that the provided duration is only used to define a delay in which the file can be requested (with no restriction) to the servlet, and not a delay after which the servlet will break an already handled request. So it looks good and I understand now why I can cast a MP3 with a long duration without any interruption.

**Comment by lolodomo** [comment]
That now understood, reducing the delay from 20s to 10s should probably be enough.

**Comment by lolodomo** [comment]
I can now confirm that Android TV is requesting the audio file twice:
```
19:07:35.505 [DEBUG] [ome.core.audio.internal.AudioServlet] - Removed timed out stream 92640c90-dfe8-45e8-a8c5-1824c75d1b8f
19:07:35.509 [DEBUG] [ome.core.audio.internal.AudioServlet] - Stream to serve is 2e740657-b8e5-4ca8-9629-6b0c758d6105
19:07:35.576 [DEBUG] [ome.core.audio.internal.AudioServlet] - Stream to serve is 2e740657-b8e5-4ca8-9629-6b0c758d6105
```

**Comment by lolodomo** [comment]
Trying a TTS command, I even noticed 3 requests:
```

19:12:09.414 [DEBUG] [ome.core.audio.internal.AudioServlet] - Removed timed out stream 2e740657-b8e5-4ca8-9629-6b0c758d6105
19:12:09.420 [DEBUG] [ome.core.audio.internal.AudioServlet] - Stream to serve is 366b8ffb-9a6d-4730-83a6-ded1e4caaa85
19:12:09.456 [DEBUG] [ome.core.audio.internal.AudioServlet] - Stream to serve is 366b8ffb-9a6d-4730-83a6-ded1e4caaa85
19:12:12.298 [DEBUG] [ome.core.audio.internal.AudioServlet] - Stream to serve is 366b8ffb-9a6d-4730-83a6-ded1e4caaa85
```

**Comment by lolodomo** [comment]
After several tests, it seems to be generally 3 requests to the audio file. Even if my long duration MP3 audio file (several minutes), I only got 3 requests at the beginning of the playback

All that seems to confirm that my PR is totally appropriate ;)

**Comment by kaikreuzer** [comment]
Thanks, that is proof enough :-)
But didn't you want to reduce the time from 20 to 10 now?

**Comment by lolodomo** [comment]
Done.

**Pull request merged**
