### PR TITLE
Adapt OSGi tests to the new ThingHandler initialization

### PR DESCRIPTION
**Pull request by svilenvul**
See #1425.

Binding OSGi test do not use getService(ThingHandler) anymore.

Signed-off-by: Svilen Valkanov <svilen.valkanov@musala.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks!

**Comment by kaikreuzer** [comment]
It doesn't seem to fully fix the tests yet, see https://openhab.ci.cloudbees.com/job/openHAB2-Bundles/lastCompletedBuild/testReport/

@svilenvul Could you please check again? Thanks!

**Comment by svilenvul** [comment]
Yes, I will take a look.

**Comment by svilenvul** [comment]
@kaikreuzer 
This should fix the failing tests https://github.com/openhab/openhab2-addons/pull/1433 in the build.

**Pull request merged**
