### PR TITLE
[FolderWatcher] [WIP] Initial contribution

### PR DESCRIPTION
**Pull request by goopilot**
This is initial contribution of FTP FolderWatcher binding discussed here: https://github.com/openhab/openhab2-addons/issues/4547 
It's purpose is to monitor specific FTP folder with subfolders and update channel with new file names.

I'm asking community support to review code style and binding logic since it's my first binding and first experience with Java.

### CODE REVIEW

**Comment by goopilot** [comment]
https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.folderwatcher/2.5.0-SNAPSHOT/org.openhab.binding.folderwatcher-2.5.0-SNAPSHOT.jar JAR file

**Comment by Hilbrand** [comment]
Thank you for your contribution. Before I'll do a complete review here are some initial comments:

I'm not sure if a binding. That means a Thing, is the right conceptual implementation of this feature. It looks more it should be a Trigger type. Because with a thing the channel is a state. But here it's not a state but a pass-through for new files found. It would be more logical to be implemented as a trigger that send and event each time a new file is found. @kaikreuzer  what is your opinion on this?

Some general remark related to the code:
* You've marked the pull request [WIP]. Are you still working on it? because as long it's work in progress no review will be done.
* Cleanup: There are a lot of comments from the skeleton script and commented out code left in your code that should be removed.
* Replace the about.html with NOTICE license file: see https://community.openhab.org/t/tutorial-update-license-to-epl-v2-0-of-your-binding-in-development-or-pull-request

**Comment by davidgraeff** [comment]
The name would need to be changed as well, as it implies atm that this binding is watching a local directory.
So either change the name or extend this binding to more protocols like add a local file watcher and maybe a http(s) one as well. What is at least necessary would be support for sftp and ftps. Plain http+ftp are dying out.

**Comment by kaikreuzer** [comment]
> @kaikreuzer what is your opinion on this?

@Hilbrand Better ping @openhab/2-x-add-ons-maintainers, I don't like being a bottleneck ;-)

But I have indeed some important input here: In general, I am not opposed to having "ftp upload" feature as a binding - as long as the long-term goal is to have more than a notification upon new files, but also potentially consider the content of uploaded files. And hey, we already have this, see https://www.openhab.org/addons/bindings/ftpupload.
@goopilot Are you aware of this binding? Wouldn't it make a lot of sense to extend the existing one instead of creating a new one?
You might also want to read through the [discussion at that time](https://github.com/openhab/openhab2-addons/pull/3137#issuecomment-3845784169) about the general idea of that binding.

**Comment by goopilot** [comment]
>I'm not sure if a binding. That means a Thing, is the right conceptual implementation of this feature. It looks more it should be a Trigger type.

If I understand correctly Trigger is a channel type, but it's still a Thing. So all I need to do in this case is change channel <kind> from State to Trigger, which is absolutely fine with me. Please correct me if I'm wrong.

https://www.eclipse.org/smarthome/documentation/development/bindings/xml-reference.html

> * You've marked the pull request [WIP]. Are you still working on it? because as long it's work in progress no review will be done.

Yes, I'm still working on it. Technically it's doing what it's suppose to do, but I'd like to see if I'm going into right direction.

> * Cleanup: There are a lot of comments from the skeleton script and commented out code left in your code that should be removed.

Sure, I'll do it.

> * Replace the about.html with NOTICE license file: see https://community.openhab.org/t/tutorial-update-license-to-epl-v2-0-of-your-binding-in-development-or-pull-request

Thanks

**Comment by goopilot** [comment]
> The name would need to be changed as well, as it implies atm that this binding is watching a local directory.
> So either change the name or extend this binding to more protocols like add a local file watcher and maybe a http(s) one as well. What is at least necessary would be support for sftp and ftps. Plain http+ftp are dying out.

There are definitely plans to implement local folder watching option as well as ftps and sftp, thanks for bringing this up.

**Comment by davidgraeff** [comment]
> So all I need to do in this case is change channel from State to Trigger

And within java you do not call "updateChannel" but "triggerChannel".

**Comment by goopilot** [comment]
> @goopilot Are you aware of this binding? Wouldn't it make a lot of sense to extend the existing one instead of creating a new one?

@kaikreuzer yes, I'm aware of this binding. But I just want to make sure that we are on the same page: I'm building a binding that will monitor new files on local or remote FTP, SFTP folders. I'm not sure that it can be an extension of ftpupload binding which has different logic and acts as FTP server.

**Comment by goopilot** [comment]
> > So all I need to do in this case is change channel from State to Trigger
> 
> And within java you do not call "updateChannel" but "triggerChannel".

Oh I see, thanks!

**Pull request closed without merging**
