### PR TITLE
[meteoblue] Fix items example

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@9037568 for review.

**Comment by 9037568** [comment]
Can you explain what you're trying to "fix" ? Because there's nothing broken here that I can see.

**Comment by lolodomo** [comment]
- iday is not an exiting openHAB icon (not inside the classic iconset).
- icon channel is not a channel of type String but Image.
- snow icon is more appropriate than climatre or rain for snow channels.
- item todayPCode : I suppressed it as it is the same channel as item todayCond. It was before I understood that this channel is a number and not a text. If the value of the item is finally really a number and so different from the item todayCond, we could keep it.

**Comment by davidgraeff** [comment]
Please port the changes to the new path. meteoblue seem to have been ported to the new buildsystem.

**Pull request closed without merging**
