### PR TITLE
[openhabcloud] Reduce logging levels

### LINKED ISSUE #1782: [openhabcloud] Jetty request failed: null
Here are warnings I can find in my logs:
```
2017-01-26 19:42:16.119 [WARN ] [io.openhabcloud.internal.CloudClient] - Jetty request 101571 failed: null
2017-01-26 19:42:16.254 [WARN ] [io.openhabcloud.internal.CloudClient] - Jetty request 101464 failed: null
```
By the way, the binding is working well.

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #1782

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
Ok but you were the first and not the last to tell me never using WARN  and ERROR levels in a binding. I was even requested sometimes to change from INFO to DEBUG.
It looks clear that this binding is using inappropriate log levels.

**Comment by lolodomo** [comment]
But of course we can discuss in all my changes what logs should keep a high log level anbd why.

**Comment by kaikreuzer** [comment]
> Ok but you were the first and not the last to tell me never using WARN and ERROR levels in a binding. 

First thing to notice here is that we are not talking about a binding.

The general guideline about log levels is that if there is something technically wrong in the system (i.e. within the runtime itself), it must be logged as ERROR or WARN and in most cases, the user should report it as an issue - just what has happened here.

> especially when the functionnality is working well.

This is what I meant with "if we consider this situation "normal"". But I doubt that all the places that you touched here are such normal situations. Imho, they all mean that something within the runtime isn't working as expected. If you have arguments why a certain logging is irrelevant and the situation does NOT mean that anything is not working correctly, just say so and it is absolutely fine to change the log level to DEBUG. I do not say that this is not the case here, I just do not see any arguments yet.

**Comment by smartnakh** [comment]
Do we have any progress ? 
it's a really annoying issue . it makes the android app outside lan not reliable.

will be glad to help.

i do not see a way to get more logs on this issue 

```
2019-01-13 16:02:27.520 [WARN ] [io.openhabcloud.internal.CloudClient] - Jetty request 2034944 failed: null
2019-01-13 16:02:27.526 [WARN ] [io.openhabcloud.internal.CloudClient] - Response Failure: null
```

Should i raise of the log level of another binding ?

**Comment by kaikreuzer** [comment]
>  it makes the android app outside lan not reliable.

What do you mean by this?
This PR suggested to reduce the log level of the warning in the hope that there is no functional issue at all related to it. If you have a different experience, please provide detailed information on what "not reliable" means and how it can potentially be reproduced by someone else. Best to add such information on https://github.com/openhab/openhab2-addons/issues/1782 and not here on this PR.

**Comment by smartnakh** [comment]
Thanks

I have added a comment in 1782
<https://github.com/openhab/openhab2-addons/issues/1782> with a movie of
the issue



Le lun. 14 janv. 2019 à 15:20, Kai Kreuzer <notifications@github.com> a
écrit :

**Comment by kaikreuzer** [comment]
Let's close this PR as it seems to rather suppress a problem instead of fixing it.

We should check whether #4500 might improve the situation.

**Comment by smartnakh** [comment]
#4500 <https://github.com/openhab/openhab2-addons/pull/4500> did NOT
improve my situation.

Le dim. 27 janv. 2019 à 20:20, Kai Kreuzer <notifications@github.com> a
écrit :

**Pull request closed without merging**
