### PR TITLE
added esh release p2 repo

### PR DESCRIPTION
**Pull request by kaikreuzer**
related to https://github.com/openhab/openhab-core/pull/259

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by martinvw** [comment]
I think that it looks fine!

**Comment by kaikreuzer** [comment]
@martinvw And now it looks even finer and I think it can be merged ;-)

**Comment by martinvw** [comment]
But both builds are red is that expected....

**Comment by kaikreuzer** [comment]
PR builds usually do not work for such stuff. I'd suggest to merge it anyhow.

**Comment by martinvw** [comment]
Please note that travis does a full build...

**Pull request merged**
