### PR TITLE
Adds GroupItem support to the homekit binding.

### PR DESCRIPTION
**Pull request by digitaldan**
Signed-off-by: Dan Cunningham <dan@digitaldan.com>

### CODE REVIEW

**Comment by digitaldan** [comment]
This is in regards to #986 , @beowulfe , this was a quick attempt at getting group item support, I was more interested in seeing how hard it would be to do with the current design.

**Comment by digitaldan** [comment]
@beowulfe , I had a chance to test this last night and all works well.

**Comment by kaikreuzer** [comment]
So good to merge, @beowulfe?

**Comment by beowulfe** [comment]
Looks good to me. Thanks @digitaldan. It's too bad there's no common interface shared by SwitchItem and GroupItem with a send method...

**Comment by kaikreuzer** [comment]
We could think about adding a generic "send" to GroupItem, which throws an exception in case it is an illegal command...

**Pull request merged**
