### PR TITLE
Changed data retrieving approach to 24 time window by default.

### PR DESCRIPTION
**Pull request by clinique**
Changed data retrieving approach to 24 time window by default. JavaIzed to v8.
Complements to comments raised in PR #2480 
Signed-off-by: Gaël L'hopital <glhopital@gmail.com>

### CODE REVIEW

**Comment by martinvw** [comment]
@mherwege can you test it, somewhere in the upcoming week :-)

**Comment by mherwege** [comment]
@martinvw @clinique Thank you for the update. I did a quick check and the result returned is what I expected. I did not run it for a full day yet, but looking at the code I do not expect issues anymore. @clinique Thank you for the compliments. You earn all praise for creating the binding in the first place.

**Comment by clinique** [comment]
@mhwerge it's such a pleasure to work in this community! Thanks a lot for your work

**Comment by martinvw** [comment]
Thanks both of you!

**Pull request merged**
