### PR TITLE
migrate helios binding to bnd

### PR DESCRIPTION
**Pull request by J-N-K**
This still needs JDK11 support.

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by J-N-K** [comment]
The problem with this (and probably at least `dlinksmarthome`) is that `com.sun.xml.bind/jaxws-ri/2.2.10` (needed for SOAP) is not JDK11 compatible because the POM has `com.sun.xml.ws/jbundles/2.2.10` as parent POM and that includes 

```
            <!-- JDK dependencies -->
            <dependency>
                <groupId>com.sun</groupId>
                <artifactId>tools</artifactId>
                <version>1.6</version>
                <scope>system</scope>
                <systemPath>${tools.jar}</systemPath>
            </dependency>
```

which is not available on for JDK>8. This is no problem with `com.sun.xml.bind/jaxws-ri/2.3.2`, compilation works fine then. But then the feature validation fails because the jar cannot be found, that works perfectly on JDK8 with `com.sun.xml.bind/jaxws-ri/2.2.10`. 

So either we need to find out how we can make the tools available or how we can use 2.3.2.

**Comment by davidgraeff** [comment]
Sounds like we just need to add another maven repo to the reactor so that the missing dependencies can be found. I'm reviewing two 5k loc PRs at the moment, so would rather not do this now.

**Comment by J-N-K** [comment]
Finally i managed to get a version that compiles and passes feature validation on java 8 and 11. The bundle starts in my OH 2.5 Snapshot, but someone should have a closer look. I must admit that this is mostly based on trial and error. But was very instructive on how OSGI works.

**Comment by davidgraeff** [comment]
conflicts :/

**Comment by J-N-K** [comment]
@wborn requested a review from @maggu2810 for dlinksmarthome. I suggest to wait for that, I‘ll resolve afterwards.

**Comment by J-N-K** [comment]
Unfortunately we can‘t remove CXF here. The binding heavily depends on it and would require substantial refactoring. I can replace the JAXB components with the one from the other PR, so we have at least that in common.

**Comment by davidgraeff** [comment]
It is really sad that karaf has no installation progress. Those fat libraries will take some time to be downloaded and installed and the user has no feedback in the mean time.

But at the same time it is no difference to before, where we just had a fat jar file.

**Comment by davidgraeff** [comment]
Can you fix the conflicts? And then for the sake of j11 compatibility we merge this one

**Comment by J-N-K** [comment]
rebased

**Comment by J-N-K** [comment]
could someone re-trigger travis? build timed out

**Comment by J-N-K** [comment]
Looks like Jenkins isn‘t willing to rebuild. Will re-open ASAP

**Comment by J-N-K** [comment]
Still not in queue. Maybe we should merge if Travis agreed for the second time.

**Comment by davidgraeff** [comment]
Travis is green

**Pull request merged**
