### PR TITLE
[Nest] Add last event channels to camera thing

### LINKED ISSUE #3458: [Nest] Add channels for Camera Aware API calls
## Expected Behavior

I was expecting the Nest Aware API calls for Nest Camera to also be in the code, but unfortunately they are not. I hope there are plans to add those to the Nest Camera Thing as channels.

## Current Behavior

Currently the channels for:
```
• last_event/image_url
• last_event/animated_image_url
• last_event/activity_zone_ids

```
are not available as they are subscription based API calls. This should not be a reason to exclude them (in my view)

## Possible Solution

Add the missing API calls as channels to the Nest Camera

## Your Environment

* Openhab 2.2.0 and Nest 2.2.0 Binding
* Mac Mini MacOS Sierra

I have a Nest Thermostat, Cam and Protect.

### PR DESCRIPTION
**Pull request by wborn**
* Move existing camera channels to camera# channel group
* Add new last event camera channels to last_event# channel group
* Update documentation and unit tests

Fixes #3458

### CODE REVIEW

**Comment by wborn** [comment]
Here is a JAR [org.openhab.binding.nest-2.3.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab2-addons/files/1916957/org.openhab.binding.nest-2.3.0-SNAPSHOT.jar.zip) to test this PR (@rzwarts74).
Remove the .zip extension when adding the file to your /addons dir.

**Comment by wborn** [comment]
Did you already find some time to test the last_event channels @rzwarts74?

**Comment by rzwarts74** [comment]
@wborn I will test it this weekend. Thanks

**Comment by rzwarts74** [comment]
@kaikreuzer @wborn  how can I become reviewer ?

**Comment by martinvw** [comment]
Can you go to the tab 'Files Changed' and add comments there

**Comment by rzwarts74** [comment]
Initial review running on OH2.2 / Macos 10.13.3
Running with both NEST modules installed trying to activate one

`214 │ Installed │  80 │ 2.2.0                  │ Nest Binding
252 │ Installed │  80 │ 2.3.0.201804161940     │ Nest Binding
`

`openhab> bundle:start 214
Error executing command: Error executing command on bundles:
	Error starting bundle 214: Could not resolve module: org.openhab.binding.nest [214]
  Another singleton bundle selected: osgi.identity; type="osgi.bundle"; version:Version="2.3.0.201804161940"; osgi.identity="org.openhab.binding.nest"; singleton:="true"

openhab> bundle:start 252
Error executing command: Error executing command on bundles:
	Error starting bundle 252: Could not resolve module: org.openhab.binding.nest [252]
  Unresolved requirement: Import-Package: javax.measure

openhab>
`

**Comment by rzwarts74** [comment]
```
openhab> bundle:uninstall 252
openhab> bundle:start 214
openhab>
```

**Comment by wborn** [comment]
> Initial review running on OH2.2

Yes those exceptions are to be expected when you run an OH 2.3 binding on OH 2.2.
Please test this with OH 2.3.0-SNAPSHOT instead.

**Comment by rzwarts74** [comment]
>  Please test this with OH 2.3.0-SNAPSHOT instead.

Is there a way to do this upgrade to OH2.3.0-SNAPSHOT without loosing all functionality? My house is running on the system.
Or maybe run a second instance (although then both OH's will fight over control).

**Comment by wborn** [comment]
There is a whole [community thread](https://community.openhab.org/t/stabelize-a-production-system-by-working-on-a-test-system/43536) on this subject @rzwarts74. :-)

I always test on another openHAB instance on my desktop PC that only runs what I'm testing. Before I start my tests I always create a fresh new latest greatest openHAB instance. My test openHAB instance only lasts for a day or sometimes just a few hours.

**Comment by rzwarts74** [comment]
> I always test on another openHAB instance on my desktop PC that only runs what I'm testing.

Ok @wborn  I'll have to install another OS for that (as my main OS is macOS).  So the test will not be respresentative of what I'm running :-(

**Comment by wborn** [comment]
> Could you please also create a PR for the update.lst file and add an info the release notes wiki?

Yes when this PR is merged I can add the following:

`Nest Binding: The 'camera' Thing Type now has channel groups. Add 'camera#' before the channel ID in the channel UID of existing camera channels.`

**Pull request merged**
