### PR TITLE
Yamaha: Prepare for json protocol addition

### PR DESCRIPTION
**Pull request by davidgraeff**
This commit does not add any functionality. This commit depends on #2525.

* Remove old ControlFlow and Class diagram pictures, they are outdated now.
* Move constants from all over the code to YamahaReceiverBindingConstants class.
* Move states out of protocol communication classes. States are POJO + invalidate() method and live in the `state` package.
* Move communication classes to `protocol/xml` package and extract protocol interfaces.
* Protocol interfaces are in the `protocol` package now.
* Refactor `HttpXMLSendReceive` to `AbstractConnection` and `XMLConnection` implementation.
* Create factory class in `protocol` package.

This prepares the code for a new `protocol/json` package and a JSONConnection implementation. The new protocol is called **Yamaha Extended Control protocol** (YXC) and is exclusively used on all AVRs produced later than 2013 (MusicCast enabled products). The basic protocol is similar to the old XML one. The advanced functionality includes DLNA based audio streaming.

### Specification
* https://github.com/neutmute/swimbait/tree/master/doc/yamaha
* https://hexdocs.pm/musiccast/api-reference.html

### Other implementations
* https://github.com/foxthefox/yamaha-yxc-nodejs (Node JS)
* https://github.com/onkelrico/yxc-client (Java)
* https://community.home-assistant.io/t/support-for-new-yamaha-receivers-and-musiccast-devices/17001 (Python / Home Assistant)

Signed-off-by: David Gräff <david.graeff@web.de>

### CODE REVIEW

**Comment by davidgraeff** [comment]
travis fails because of " java.lang.RuntimeException: Failed to load p2 repository with ID 'jetty-eclipse' from location http://download.eclipse.org/eclipse/updates/4.5"

**Comment by zarusz** [comment]
I tested the latest changes with my OpenHAB 2.2.0 and Yamaha RX-S601D and all works fine.
Hopefully, this will help the review process as this PR is a dependency for my other PR #2558.

**Comment by davidgraeff** [comment]
It might make sense to concentrate the review on PR #2558. The other PR contains some small fixes as well next to the DAB support.

**Comment by martinvw** [comment]
> It might make sense to concentrate the review on PR #2558. The other PR contains some small fixes as well next to the DAB support.

@davidgraeff what do you mean, can you just present the optimal review order for me 😄 

Thanks!

**Comment by davidgraeff** [comment]
@martinvw: only review the other PR :) at some point the commits of this or needs to be squashed but we'll sort this out after the review

**Comment by davidgraeff** [comment]
Or=pr, the mobile version of github doesn't allow edits. sigh

**Comment by martinvw** [comment]
@davidgraeff the other PR also contains all the changes of this PR it makes the reviewing really unpure especially if I give review comments on your changes in his PR. For example: https://github.com/openhab/openhab2-addons/pull/2558/files#diff-e330a739a7efc448b72cee1e0bcb482bR25

**Comment by davidgraeff** [comment]
The problem is that I have some copy paste errors in this PR, for example I update wrong channels in the handler etc. The other PR fixed those issues. But I can't close this one, my commits couldn't be squashed without a valid signature anymore. What would u say, how should we continue?

**Comment by davidgraeff** [comment]
Integrated into https://github.com/openhab/openhab2-addons/pull/2558

**Pull request closed without merging**
