### PR TITLE
[innogy] added BT-PSS Support

### PR DESCRIPTION
**Pull request by nik70000**
[innogy] Added BT-PSS (Bluetooth Pluggable Smart Switch)

Added first basic support for the Bluetooth Pluggable Smart Switch (by Medion)

Added basic support for BT-PSS, i.e. ability to switch connected devices on and off. Power metering capabilities of the device will be added later

### CODE REVIEW

**Comment by martinvw** [comment]
@ollie-dev are you still around to review this?

If you are, you should be added to the codeowners file to automaticly get a ping to review changes :-)

**Comment by martinvw** [comment]
BTW: @nik70000 the code does not yet seem to compile should it be marked as work-in-progress or is there another problem? Could you also make sure your commits are signed of

**Comment by Hilbrand** [comment]
This should probably not be a PR to master here yet. It's part of wip on innogy, which is in my repo. When changes made by others are done I'm going to clean up and make a new pr. I'm guessing it was an mistake to open here. There is already a pr for the changes added here to my repo. For others, discussions are taking place in https://community.openhab.org/t/innogy-update-to-new-api-1-1-and-new-devices-tested/77928

**Comment by ollie-dev** [comment]
@martinvw, yes I can help reciewing the changes. But I agree with @hilbrand, that we should wait a bit until things are ready.

**Comment by nik70000** [comment]
Waiting for a stable version that works with OH 2.5 and innogy API 1.1 - adding more devices at this stage does not help.

**Pull request closed without merging**
