### PR TITLE
[allplay] migrate to bnd

### PR DESCRIPTION
**Pull request by J-N-K**
I fail here. The problem is that a local library is used that is not available in any repo. I managed to compile and get it in the jar (like before) but the feature verification fails. I don't own these devices so I can't test if it really works. Any ideas appreciated.

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by maggu2810** [comment]
Who contributes that JAR file?
Why not adding the JAR file to a bintry repo?
We could also unpack the sources (once, not at build time) and build it ourself as part of the bundle.

**Comment by J-N-K** [comment]
I have no idea who contributed the jar. The source seems to be from https://github.com/dominicdesu/tchaikovsky? and is Apache licensed. 

I‘ll investigate the „unpack and compile“ option.

**Comment by wborn** [comment]
Recompiling libraries in this build might significantly increase the already huge build time. 

If the artifacts aren't in Maven repositories (yet) another way might be to use a bnd file with `includeresource` for JARs, see:

* [What should I use instead of the Bundle-ClassPath?](https://bnd.bndtools.org/chapters/920-faq.html?#bundleclasspath2)
* [includeresource iclause](https://bnd.bndtools.org/instructions/includeresource.html)

The dependency then doesn't need to be added to the features file.

**Comment by maggu2810** [comment]
But you still need to add is as a dependency, so the classes are part of the classpath at build time.
Or do you suggest to use both?

The installation of the file in the initialize phase seems a little bit hackish.

I would prefer to publish it to a repo and use the standard ways all the tools can handle.

**Comment by J-N-K** [comment]
That‘s exactly the problem: I can use the deprecated `<scope>system</scope>` and reference the file, use bnd to include it in the final bundle but then the feature verification fails. 

If we don’t want to compile it ourselves, we should go with publishing to a repo. I‘ll check how to do that.

**Comment by wborn** [comment]
> Or do you suggest to use both?

I haven't tested this approach myself so I don't exactly know if and how it works. :wink: 

> I would prefer to publish it to a repo and use the standard ways all the tools can handle.

That would also be my preferred (long-term) solution. If we want to do this already I'd be interested in the opinion of the other @openhab/2-x-add-ons-maintainers what other Maven repos we allow and in which POMs they are defined. Can we use the openHAB Bintray repo for this during the migration or should people who migrate bindings (and don't maintain them) add artifacts to their own Binray repo?

**Comment by J-N-K** [comment]
I have now added it to my own bintray, but this is a bit ridiculous. I have no knowledge on the package itself. It's still awaiting inclusion in jcenter but maybe it would  be easier to include it in openhab/mvn.

**Comment by J-N-K** [comment]
The tchaikovsky bundle is now included in jcenter. It includes slf4j instead of declaring it as a dependency, but this is not so important for this PR and I'll try to remove that some time in the future. The binding itself now compiles fine with standard tooling, the feature resolution still fails.

**Comment by J-N-K** [comment]
I would suggest to make a new repo openhab-3rdparty or so and include all libraries needed by addons there and allow this repo only.

**Comment by davidgraeff** [comment]
> I would suggest to make a new repo openhab-3rdparty

This is already existing ^^. But only a limited amount of people have access, I think it is only Kai and Markus.

**Comment by J-N-K** [comment]
I have reverted to the original library. Should be fine now.

**Comment by maggu2810** [comment]
> > I would suggest to make a new repo openhab-3rdparty
> 
> This is already existing ^^. But only a limited amount of people have access, I think it is only Kai and Markus.

Can you give me a link? :wink: 
There has been a ESH 3rd party one, about OH I don't know ATM.

**Comment by mvalla** [comment]
The binding does not build due to missing dependency related to tchaikovsky lib:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:54 min
[INFO] Finished at: 2019-04-23T10:21:32+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project org.openhab.binding.allplay: Could not resolve dependencies for project org.openhab.addons.bundles:org.openhab.binding.allplay:jar:2.5.0-SNAPSHOT: The following artifacts could not be resolved: org.openhab.addons.bundles:org.openhab.binding.allplay-tchaikovsky.jar:jar:2.5.0-SNAPSHOT, org.openhab.addons.bundles:org.openhab.binding.allplay-tchaikovsky-sources.jar:jar:2.5.0-SNAPSHOT: Could not find artifact org.openhab.addons.bundles:org.openhab.binding.allplay-tchaikovsky.jar:jar:2.5.0-SNAPSHOT in openhab-artifactory-snapshot (https://openhab.jfrog.io/openhab/libs-snapshot) -> [Help 1]

```

**Comment by J-N-K** [comment]
I had several successful builds today. Can you tell us more About how you did the build?

**Comment by mvalla** [comment]
sorry, now I did a `mvn clean install` and it was successfull (did not use clean before)

**Pull request merged**
