### PR TITLE
[openweathermap] Moved binding to new build system

### PR DESCRIPTION
**Pull request by cweitkamp**
- Moved binding to new build system

Depends on #5070 

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by wborn** [comment]
Can you resolve the merge conflicts now #5070 got merged?

**Comment by cweitkamp** [comment]
@wborn Done.

**Comment by wborn** [comment]
There's a BOM (bom/openhab-addons/pom.xml) for the addons now. So it also needs to be updated for the bundle groupId change.

**Comment by cweitkamp** [comment]
@wborn Done.

**Pull request merged**
