### PR TITLE
Add PR build profile to disable artifact install

### PR DESCRIPTION
**Pull request by dvanherbergen**

### CODE REVIEW

**Comment by dvanherbergen** [comment]
retest this please

**Comment by dvanherbergen** [comment]
This one can be merged.

**Comment by maggu2810** [comment]
It seems okay, but why do we need this?
Shouldn't it enough to use the verify phase instead the install and keep the POMs clean?

**Comment by dvanherbergen** [comment]
That's a good question. I started working on this when the PR and CI build were done using a single jenkins config. You are right, it is no longer needed now. I will clean up.

**Comment by kaikreuzer** [comment]
And I won't merge stuff anymore without giving @maggu2810 a chance to comment ;-)

**Pull request merged**
