### PR TITLE
[max] Updated README.md and added german translations

### PR DESCRIPTION
**Pull request by cweitkamp**
- added missing description of "locked" channel
- added units and description of possible values for channels
- added "Available on thing" column for channels to fix format
- added german translations

Signed-off-by: Christoph Weitkamp github@christophweitkamp.de

### CODE REVIEW

**Comment by cweitkamp** [comment]
I don't believe the jenkins failure is related to my changes at all.

**Comment by MHerbst** [comment]
You are right. We currently have some general problems with the Jenkins builds.

**Comment by cweitkamp** [comment]
@marcelrv Thanks for approval.

May I ask you a question? Do you know if the new MAX! device ([MAX! Heizkörperthermostat basic](http://www.eq-3.de/produkte/max-heizungssteuerung/max-hausloesung/max-heizkoerperthermostat-basic.html)) can be used with this version of the binding? Or do we have to create a new thing type for it?

**Comment by marcelrv** [comment]
@cweitkamp 
I don't know, I have not seen that one before. 

However I would expect that it presents itself as a regular thermostat. For example the MAX! Zwischenstecker which is a power plug also presents itself as a thermostat. The MAX software has not been updated for a year either. If anything major was changed it would have required a software update as well.

Do you have one?

**Comment by cweitkamp** [comment]
@marcelrv Alright. No I don't own such device. I'm just interested because it is not very expensive.

**Comment by marcelrv** [comment]
I have send a message to the manufacturer about this. I'll let you know if I a clear answer comes back.

**Comment by cweitkamp** [comment]
Thank you.

**Comment by marcelrv** [comment]
@cweitkamp I've received a basic thermostat. I connected it to OH2 the usual way.
The device reports itself as regular thermostat (not the plus version).
I have not seen anything that is out of the ordinary yet, outside that it directly reported the actual temperature after inclusion. I don't remember seeing that in other devices. 

So indeed, nice buy. Also it seems bit less noisy than the other ones.

**Comment by cweitkamp** [comment]
@marcelrv Thank you very much for the information.

**Pull request merged**
