### PR TITLE
[homekit] Add support for WindowCovering tagging

### PR DESCRIPTION
**Pull request by Xento**
I'm trying to add a windowcovering device.
It recognises the item but I get some null pointer exceptions when getting the current state etc.
I'm trying to map it to a homematic rollershutter:
Rollershutter RolloWohnzimmer "Wohnzimmer" [ "WindowCovering" ] {channel="homematic:HM-LC-Bl1PBU-FM:1572a53b39c:NEQ0393620"}

Maybe somebody can look over my code an fix the issues.

### CODE REVIEW

**Comment by beowulfe** [comment]
I have WindowCoverings implemented here: https://github.com/beowulfe/openhab2/tree/homekit/addons/io/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/windowcovering

Waiting to merge it until we finalize the ontology in https://github.com/eclipse/smarthome/issues/1093

**Comment by Xento** [comment]
I can't wait for it xD

**Comment by BennieGe** [comment]
Is there a way I can use the WindowCovering allready?

**Comment by Gozilla01** [comment]
Any update on this? 
thank you

**Comment by davidgraeff** [comment]
Please reopen if there is still interest :)

**Pull request closed without merging**
