### PR TITLE
Renamed a few packages to internal in the cometvisu bundle.

### PR DESCRIPTION
**Pull request by VelinYordanov**
See openhab/static-code-analysis#100

Signed-off-by: VelinYordanov <velin.iordanov@gmail.com>

### CODE REVIEW

**Comment by martinvw** [comment]
@peuter please review, thanks!

**Comment by peuter** [comment]
Can someone tell me whats the reason for a class to be marked as "internal"? 
Some of the renamed classes here are somehow public accessible via REST, so the renaming doesn't seem to fit here from my point-of-view. 
I don't have a problem with the renaming, but I just want to understand the reason.

**Comment by martinvw** [comment]
@VelinYordanov can you answer @peuter

**Comment by VelinYordanov** [comment]
@peuter If the packages are not exported they should be internal imo.
About the REST resources there was a familiar situation in eclipse/smarthome#4225 and it was decided for them to be private.
If you think the packages should be renamed a suppression can be added for that bundle.

**Pull request merged**
