### PR TITLE
[icloud] Made constants and handler packages internal

### PR DESCRIPTION
**Pull request by VelinYordanov**
See eclipse/smarthome#4330

Signed-off-by: VelinYordanov <velin.iordanov@gmail.com>

### CODE REVIEW

**Comment by cweitkamp** [comment]
@martinvw shall we wait for #3919?

**Comment by cweitkamp** [comment]
#3919 has been merged. We can rebase and finish this PR now.

**Comment by wborn** [comment]
:sparkles: Your wish is my command. :sparkles:

**Comment by martinvw** [comment]
That is some teamwork 👍

**Pull request merged**
