### PR TITLE
[mqtt] Fix restructure mqtt package names for integration tests

### PR DESCRIPTION
**Pull request by esdeboer**
Fixes the integration tests of the mqtt binding (homie and homeassistant), by doing the same package restructuring as in PR  #5430.

### CODE REVIEW

**Comment by davidgraeff** [comment]
Could you rebase? Because just today a fix for the timing problem came in. Thanks

**Comment by esdeboer** [comment]
I did a rebase. The tests compile fine now, but they don't succeed yet ( I thought I saw them succeeding yesterday, but a clean install says they are not)
The homeassistant test is complaining it can't find mapdb, while homie is having issues with finding some  org.eclipse.smarthome requirements. I'll see if I can find out what goes wrong

**Comment by esdeboer** [comment]
I've taken a look at the bndrun files of the other tests and added a couple of missing bundles, that fixes the errors I had. I guess both the homie and the homeassistant tests need to have the embedded MQTT broker, which has the moquette-broker as dependency, however it can't find it (I've added it to the test pom and the bndrun file). Without the embedded MQTT server the test seems to hang on startup, so there might be some other things missing.

Below is my current bndrun file for the homie itest

```
-include: ../itest-common.bndrun

Bundle-SymbolicName: ${project.artifactId}
Fragment-Host: org.openhab.binding.mqtt.homie

-runrequires: bnd.identity;id='org.openhab.binding.mqtt.homie.tests'

#
# done
#
-runbundles: \
	ch.qos.logback.classic;version='[1.2.3,1.2.4)',\
	ch.qos.logback.core;version='[1.2.3,1.2.4)',\
	com.google.gson;version='[2.8.2,2.8.3)',\
	javax.measure.unit-api;version='[1.0.0,1.0.1)',\
	org.apache.commons.io;version='[2.2.0,2.2.1)',\
	org.apache.commons.lang;version='[2.6.0,2.6.1)',\
	org.apache.felix.http.servlet-api;version='[1.1.2,1.1.3)',\
	org.apache.felix.configadmin;version='[1.9.8,1.9.9)',\
	org.apache.felix.scr;version='[2.1.10,2.1.11)',\
	org.eclipse.equinox.event;version='[1.4.300,1.4.301)',\
	org.eclipse.jetty.http;version='[9.4.11,9.4.12)',\
	org.eclipse.jetty.io;version='[9.4.11,9.4.12)',\
	org.eclipse.jetty.security;version='[9.4.11,9.4.12)',\
	org.eclipse.jetty.server;version='[9.4.11,9.4.12)',\
	org.eclipse.jetty.servlet;version='[9.4.11,9.4.12)',\
	org.eclipse.jetty.util;version='[9.4.11,9.4.12)',\
	org.openhab.core;version='[2.5.0,2.5.1)',\
	org.openhab.core.config.core;version='[2.5.0,2.5.1)',\
	org.openhab.core.storage.json;version='[2.5.0,2.5.1)',\
	org.openhab.core.persistence;version='[2.5.0,2.5.1)',\
	org.openhab.core.transform;version='[2.5.0,2.5.1)',\
	org.openhab.core.io.transport.mqtt;version='[2.5.0,2.5.1)',\
	org.eclipse.paho.client.mqttv3;version='[1.2.0,2.0.0)',\
	org.apache.commons.collections;version='[3.2.1,3.2.2)',\
	org.objenesis;version='[2.6.0,2.6.1)',\
	org.openhab.core.test;version='[2.5.0,2.5.1)',\
        org.openhab.binding.mqtt;version='[2.5.0,2.5.1)',\
	org.openhab.binding.mqtt.homie;version='[2.5.0,2.5.1)',\
	org.openhab.binding.mqtt.homie.tests;version='[2.5.0,2.5.1)',\
	org.osgi.service.event;version='[1.4.0,1.4.1)',\
	org.openhab.binding.mqtt.generic;version='[2.5.0,2.5.1)',\
	org.openhab.core.config.discovery;version='[2.5.0,2.5.1)',\
	org.openhab.core.io.console;version='[2.5.0,2.5.1)',\
	org.openhab.core.thing;version='[2.5.0,2.5.1)',\
	net.bytebuddy.byte-buddy;version='[1.9.7,1.9.8)',\
	net.bytebuddy.byte-buddy-agent;version='[1.9.7,1.9.8)',\
	org.mockito.mockito-core;version='[2.25.0,2.25.1)',\
	org.apache.servicemix.specs.activation-api-1.1;version='[2.9.0,2.9.1)',\
	org.apache.servicemix.specs.annotation-api-1.3;version='[1.3.0,1.3.1)',\
	org.apache.servicemix.specs.jaxb-api-2.2;version='[2.9.0,2.9.1)',\
	org.apache.servicemix.specs.stax-api-1.2;version='[2.9.0,2.9.1)',\
	org.openhab.io.mqttembeddedbroker;version='[2.5.0,2.5.1)',\
	io.moquette.moquette-broker;version='[0.12.1,0.12.2)',\
	osgi.enroute.hamcrest.wrapper;version='[1.3.0,1.3.1)',\
	osgi.enroute.junit.wrapper;version='[4.12.0,4.12.1)',\
	slf4j.api;version='[1.7.25,1.7.26)',\
	tec.uom.lib.uom-lib-common;version='[1.0.2,1.0.3)',\
	tec.uom.se;version='[1.0.8,1.0.9)'
```

**Comment by davidgraeff** [comment]
>  I guess both the homie and the homeassistant tests need to have the embedded MQTT broker, 

Yes that's correct.

> Without the embedded MQTT server the test seems to hang on startup

Also correct. But you would not add "org.openhab.io.mqttembeddedbroker". That was possible with the old buildsystem, because it added the transitive dependencies as well. Now you need to add "io.moquette.moquette-broker" (as you already did) and also the transitive dependencies (as seen in the feature.xml file of the "org.openhab.io.mqttembeddedbroker" bundle.

**Pull request merged**
