### PR TITLE
Update Azure IoT Hub -> not working note

### PR DESCRIPTION
**Pull request by sorryusernameisalreadytaken**
Update Azure IoT Hub -> not working note

Add a note that there is a issue. This connector is not working at the moment and there is currently no process in the code. I would find it better if a potential user of openHAB get this information from the root -> the wiki.

Change also the quotes for connection string - primary key. This keyword should be marked together because there is also string for the primary shared access key only. I add a sentence to make 100% clear that the user need the primary shared access key with the url inside.

### CODE REVIEW

**Comment by martinvw** [comment]
I think it makes sense to merge it like this or maybe completely disable it, @openhab/2-x-add-ons-maintainers wdyt?

**Comment by kaikreuzer** [comment]
If it isn't functional, we should imho remove it from the distro (while we could keep the code in the repo, if anybody wants to make it work again).

**Comment by J-N-K** [comment]
I agree with @kaikreuzer. We shpuld remove it from the distro then. Why is it not working anymore?

**Comment by martinvw** [comment]
@J-N-K see https://github.com/openhab/openhab2-addons/issues/3647#issue-330968778

**Comment by kaikreuzer** [comment]
Superseded by https://github.com/openhab/openhab2-addons/pull/5944.

**Pull request closed without merging**
