### PR TITLE
[azureiot] remove temporarily

### PR DESCRIPTION
**Pull request by J-N-K**
Supersedes #5934 

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by bjoernbrings** [comment]
Didn't digg deeper into this change, but since that day the sandbox build broke with "Failed to execute goal org.apache.karaf.tooling:karaf-maven-plugin:4.2.6:kar (default-kar) on project openhab-addons: Failed to create archive: Could not find artifact org.openhab.addons.bundles:org.openhab.io.azureiothub:jar:2.5.0 in sandbox-all" and as this PR was the only azure related, could it be that this change is responsible for the breaktdown?

**Comment by kaikreuzer** [comment]
Yes, clearly sounds like it (ftr: https://ci.openhab.org/view/Sandbox/job/sandbox-openhab2-release/1225/console).

@J-N-K Any idea why the distro still tries to include it? Is the "exclude" line for the feature aggregation not working as expected?

**Comment by J-N-K** [comment]
Will Check that later today.

**Comment by J-N-K** [comment]
https://github.com/openhab/openhab2-addons/pull/5961

**Pull request merged**
