### PR TITLE
Replaced Apache HttpClient with Jetty

### PR DESCRIPTION
**Pull request by svilenvul**
Please merge after eclipse/smarthome#1864

----------------------------------------------
Apache HttpClient is replaced in 3 bindings:
- in Ipp binding it is removed the dependency to Apache HttpClient 4.x
  with the replacement of the cups4j distribution
  (cups4j.runnable-0.6.4.jar includes the dependency to Apache HttpClient)
- Squeezebox binding (Apache HttpClient 3.x replaced with Jetty)
- Autelis binding (Apache HttpClient 3.x replaced with Jetty)

With this PR all dependencies to Apache HttpClient 3.x and 4.x are
removed. (see eclipse/smarthome#1689)

Signed-off-by: Svilen Valkanov <svilen.valkanov@musala.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@svilenvul Is this PR also updated wrt the latest discussions on the ESH PR? I.e. using BasicAuth directly through a header and not the authstore and potentially having support for proxies?

> cups4j.runnable-0.6.4.jar includes the dependency to Apache HttpClient

It includes ALL its dependencies, incl. Apache Commons, slf4j, etc.
It would be better to keep the original file and only add apache http client to it.

**Comment by svilenvul** [comment]
@kaikreuzer 
I removed the unnecessary classes from the cups4j.jar and changed the authentication to add the header directly. Now the code should be up to date. 
I have not added only the proxy support, because I didn`t want to repeat [this method](https://github.com/MusalaSoft/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/HttpUtil.java#L227) across different bindings.

**Comment by kaikreuzer** [comment]
> I removed the unnecessary classes from the cups4j.jar 

Sorry, but this is imho even worse. It is the same filename as the original file, but it has been manually tweaked; this asks for trouble when someone updates it to a more recent version in future. Why not keep the dependency from the ipp binding to apache http and thus require that these bundles are installed when the ipp binding is used?

**Comment by svilenvul** [comment]
I made this changes, because I thought that after this PR Apache HttpClient will be removed from the Target Platform, this is why I wanted to remove all dependencies, including the IPP binding.
If it is not the case, it makes more sense to keep this jar untouched of course.

**Comment by kaikreuzer** [comment]
Thanks @svilenvul!

@kgoderis Could you please test that the Autelis binding still works ok with that change?
@digitaldan Could you please test that the Squeezebox binding still works ok with that change?

**Comment by digitaldan** [comment]
@kaikreuzer the Autelis binding is mine, so I will be testing both ;-)

**Comment by kaikreuzer** [comment]
Oops, sorry - but even better then 😎 .

**Comment by digitaldan** [comment]
Both look good so far, I'll report back if anything shows up after running for a bit.

**Pull request merged**
