### PR TITLE
[miio] adding device strings

### PR DESCRIPTION
**Pull request by marcelrv**
Added several devices

Signed-off-by: Marcel Verpaalen <marcel@verpaalen.com>

### CODE REVIEW

**Comment by marcelrv** [comment]
> Don't forget the readme 😄

mmm, It is not updated as I have seem to have lost my readme creator. 
Need to rewrite it or bring back from death the laptop it was residing on...
Manually editing/creating these files for all these devices would be very ticky to get proper maintained

**Comment by martinvw** [comment]
> Need to rewrite it or bring back from death the laptop it was residing on...

Feel free to commit it in some (sub) directory of the binding it will help other contributors and you to update it next time.

**Comment by marcelrv** [comment]
@martinvw yes... sure, that is also my ultimate goal.
but it is/was a very much hacked thing now, certainly not (yet) in the quality we want to have in the OH repository...

**Comment by marcelrv** [comment]
I finally found an older version of my readme creator, Updated it to match it again  with the output of the current files. I've submitted it so others can use it as well.

**Pull request merged**
