### PR TITLE
[mqtt] homeassistent: allow device.identifiers to be single string

### PR DESCRIPTION
**Pull request by jochen314**
This patch allows the device.identifiers to be a single string.

I created a custom TypeAdapter, which is able to read both formats and returns a common type (list<string>)

see https://github.com/openhab/openhab2-addons/issues/5632#issuecomment-497660801

### CODE REVIEW

**Comment by martinvw** [comment]
LGTM

**Comment by J-N-K** [comment]
LGTM. Can you add tests for that? We had so many unexpected bugs and regressions in MQTT that I would like to see at least new contributions covered by test.

**Comment by J-N-K** [comment]
@jochen314 Would you be willing to add some tests?

**Comment by jochen314** [comment]
Yes.
There is already one test. I modified one existing test to cover this also.

But i can add explicit tests, but it might take a day or two... 

Am 24. August 2019 15:12:18 MESZ schrieb J-N-K <notifications@github.com>:

**Comment by J-N-K** [comment]
Jenkins fails unrelated

**Pull request merged**
