### PR TITLE
fixed JRE version

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by martinvw** [comment]
@kaikreuzer or other person merging sign-of is not yet in the commit, given @kaikreuzer signed of in the PR we could add it to the commit message :-)

**Comment by kaikreuzer** [comment]
Yeah, yeah, I also noticed that it was missing in the commit (I did it through the IDE, which I didn't do for years, so I missed the sign-off....), but I was too lazy to add it afterwards ;-)

**Comment by davidgraeff** [comment]
Ups. Forgot to add the signed-off-by. sigh. This merge-now button was just so tempting to be clicked. Revert?

**Comment by kaikreuzer** [comment]
No, that also accounts for the "small patch exception", which does not require a sign-off :-)

**Pull request merged**
