### PR TITLE
[spotify] fix items label syntax

### PR DESCRIPTION
**Pull request by zero-24**
Make sure the label syntax in the readme does not give messages in the log.
Signed-off-by: zero-24 <zero-24@users.noreply.github.com>

### CODE REVIEW

**Comment by Hilbrand** [comment]
Thanks for your fixing this. One last request. Can you add a sign-off to the pr text (Just click edit to the description and add the sign-off like this :`Signed-off-by: [firstname] [lastname] <e-mail address>`

**Comment by zero-24** [comment]
Done cc @Hilbrand

**Comment by Hilbrand** [comment]
Sorry it must be your real name and actual e-mail address.

**Comment by zero-24** [comment]
> Sorry it must be your real name and actual e-mail address.

Can I ask why you need that to fix an doc issue, I don't like to publicly post my mail adresses to avoid spams. Feel free to close the issue for sure.

**Comment by J-N-K** [comment]
https://www.openhab.org/docs/developer/contributing.html#sign-your-work

**Pull request closed without merging**
