### PR TITLE
[vitotronic] Removed Guava dependency

### PR DESCRIPTION
**Pull request by cweitkamp**
- Removed Guava dependency

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by wborn** [comment]
The other Vitotronic PRs are: #2016, #4034

**Comment by kaikreuzer** [comment]
Now that https://github.com/openhab/openhab2-addons/pull/2016 is merged, could you please rebase this PR, @cweitkamp?

**Comment by cweitkamp** [comment]
@kaikreuzer Done.

**Comment by kaikreuzer** [comment]
Wow, that was quick!

**Pull request merged**
