### PR TITLE
[chromecast] Use device ID as representational property

### LINKED ISSUE #4186: [chromecast] Audio Groups IP's dont get updated when the group moves to another member
As the title states, the audio group's dont get updated when the group moves to another member. Ie the group is now master on another chromecast which is in the group.

I dont know if this is a more widespread issue where things of the other types dont get updated either, as I use fixed IP with dhcp reservations. So these never change.

Please let me know what information you need. I cannot really tell when one will move, but i can force it by turning the one its currently hosted on off.

Thanks
Chris

### PR DESCRIPTION
**Pull request by cweitkamp**
- Removed representational property

> The way the groups work is they are virtual on the audio. So the same ip will be listed multiple times under different things.

See https://community.openhab.org/t/chromecast-binding-how-to-send-stopmovetype/63547/16

Fixed #4186 

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by wborn** [comment]
Wouldn't it make sense to use the device ID for the representational property instead?

https://github.com/openhab/openhab2-addons/blob/0e8bbd52397fa51a5c93b2eea0c81392a4f217e9/addons/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/discovery/ChromecastDiscoveryParticipant.java#L93

**Comment by cweitkamp** [comment]
Yes, that will be a good replacement. Thanks for the hint.

**Comment by cweitkamp** [comment]
@wborn Done.

**Comment by jim77** [comment]
I tried installing the latest snapshot for the chromecast addons:

> openhab> bundle:list -s |grep chrome
> 230 │ Active   │  80 │ 2.5.0.201905061836     │ org.openhab.binding.chromecast
> 231 │ Active   │  80 │ 0.11.0                 │ su.litvak.chromecast.api-v2

However, I can't see where this "deviceId" is being used. The thing configuration still requires an ip address and port number, and not deviceId.

**Comment by cweitkamp** [comment]
@jim77 Maybe there is a misunderstanding what the [representation property](https://www.openhab.org/docs/developer/bindings/thing-xml.html#representation-property) really is. Nothing to be configured by the user but an internal identifier to avoid duplicate discovery of one device.

**Pull request merged**
