### PR TITLE
RFXCom Spelling error rainrate

### PR DESCRIPTION
**Pull request by fremel75**
Fixes reciving rainrate and raintotal

### CODE REVIEW

**Comment by paulianttila** [comment]
Which problem should this fix? All channel id's on channel.xml use lower case letters.

**Comment by fremel75** [comment]
Yes sorry this is a mistake, can you remove this or do i make a new Pull to undo?

**Comment by kaikreuzer** [comment]
I reverted it with https://github.com/openhab/openhab2-addons/pull/1493.

@paulianttila Sorry for having merged it without checking myself - looking at the PR I assumed that it was something obvious that clearly needed to be fixed. Will leave it to you in future to first give a lgtm!

**Comment by paulianttila** [comment]
@kaikreuzer, no problem

**Pull request merged**
