### PR TITLE
[MiHome] Use DS annotations, fix static code analysis findings

### PR DESCRIPTION
**Pull request by wborn**
* Use DS annotations
* Fix static code analysis findings

### CODE REVIEW

**Comment by martinvw** [comment]
@dimalo is this okay with you?

**Comment by martinvw** [comment]
and of course @pboos

**Comment by dimalo** [comment]
Just reviewed the code. Not much experience with annotations but looks good to me. Thanks for the contribution!

**Comment by pboos** [comment]
I am a little late I guess. But for what it is worth: This pull request seems totally okay. Didn't know you can use annotations. I am totally in favour for using them instead of the long xml!

**Pull request merged**
