### PR TITLE
[openweathermap] Update the French translation

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
What is the problem with my sign-off ?

**Comment by davidgraeff** [comment]
> Author: lolodomo, Committer: lolodomo; Expected "lolodomo lg.hc@free.fr", but got "Laurent Garnier lg.hc@free.fr".

The bot seem to compare to previous commits or your github name settings or so. It expected "lolodomo".

**Comment by lolodomo** [comment]
I always committed with my name rather than a pseudo because I was asked to do it ! So I will not use now a pseudo...

**Comment by cweitkamp** [comment]
@lolodomo Please continue to use your full name for sign-offs. Currently I have no clue why it is failing in your case. How do your local Git setting look like when you type in `git config --get user.name`?

**Comment by cweitkamp** [comment]
@ghys @clinique May I ask you for a quick review? Thanks.

**Comment by lolodomo** [comment]
`git config --get user.name` returns lolodomo

**Comment by cweitkamp** [comment]
Try to set it to your real name `git config --global user.name "John Doe"` of `git config user.name "John Doe"` (second command only affects current repository).

**Comment by davidgraeff** [comment]
@openhab/2-x-add-ons-maintainers Please merge

**Pull request merged**
