### PR TITLE
[meteostick] advanced channels for wind statistics

### PR DESCRIPTION
**Pull request by watou**
Add three advanced channels to summarise wind speed and direction over last two minutes. Instantaneous wind speed and direction samples are not useful in isolation, and relying on automation to compute statistics is much more burdensome on the system than doing so directly in the binding. (The same thinking applies to the existing current and last hour rain channels.)

The use case of using openHAB as a personal weather station for data upload to Wunderground, for example, is made easy with this change, along with unit-of-measure support.

Signed-off-by: John Cocula <john@cocula.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks! Please allow me a comment for discussion: These new channels are purely "software", i.e. the integrated hardware does not provide this information by itself. The way the values of these new channels are calculated are not specific to this binding, but could be applied to any other binding likewise, correct?
This is thus another example, where a generic solution as discussed in https://github.com/eclipse/smarthome/issues/4748 would be very helpful.
As a first feature into this direction, @triller-telekom is working on https://github.com/eclipse/smarthome/pull/5679. I could imagine that an "average over timespan x" profile could be a good candidate for such a system profile as well. Wdyt?

**Comment by watou** [comment]
> The way the values of these new channels are calculated are not specific to this binding, but could be applied to any other binding likewise, correct?

It is true that these channels are only derived, but integral to them are the assumptions that wind speed and direction samples are taken at the same moment from the same hardware, and that the hardware delivers samples sufficiently frequently that average and max are meaningful over the two-minute window.  Who's to say that other bindings will match these conditions?  The same thing can be said about the existing rain channels in that they are software only, but driven by a hardware tick counter that might not exist in other hardware as such.  I don't see it as clearly black or white that the implementation of the derived wind or rain channels are free-standing from the specifics of this binding; it's a bit of both.   All five channels could have been implemented using rules and even a persistence service, for example, but with a lot of overhead, awkwardness and poor packaging.

If this PR is merged and QuantityType.toUnit is fixed, I can then add to the README.md a concise example that shows exactly how to implement a Weather Underground personal weather station using only the binding and .things., .items and .rule files.

If the work in progress in https://github.com/eclipse/smarthome/pull/5679 could create new channels derived from 0 or more other channels, take configuration data, be stateful in order to implement what the derived wind and rain channels do in this binding, implement [hysteresis](https://en.wikipedia.org/wiki/Hysteresis) generically, remove jitter generically, remove wild (impossible) data samples generically, etc., this would be a great addition to ESH and/or OH.  But it still might not be preferable to users, for the major sake of simplicity, over new channels implemented in the respective bindings.  

I picture Java 8 streams as being a nice model with which to build a stateful transformation channel system.

In the meantime, though, I would love to see this PR merged (after I fix one bug I just discovered 😇 ).

**Comment by kaikreuzer** [comment]
> Who's to say that other bindings will match these conditions?

Clearly no one, but what I would have in mind is a configurable profile, which can be applied to all those situations and having different configurations for different bindings/setup. Your 2 minutes e.g. appear arbitrary, other users might prefer a 5 minute average - with a profile, they could easily reconfigure it, with the current solution they are stuck.

> implement hysteresis generically, remove jitter generically, remove wild (impossible) data samples generically, etc

Are you doing all this in the binding here? In any case, all this required logic and complexity is a clear sign that one would want to offer that to the binding from the framework and not have binding developers figure such algorithms out for themselves (over and over again in slightly different ways).

> But it still might not be preferable to users, for the major sake of simplicity, over new channels implemented in the respective bindings.

This is a question of how those profiles are presented to the user. We were just discussing the simple cases for https://github.com/eclipse/smarthome/pull/5679 so far, but if you have good ideas how such additional derived functionality could be presented to the user, so that it isn't overly complex for him, please join the discussion!

@triller-telekom & @sjka What I am feeling is that we might need to be able to pass a suggested configuration with an ProfileAdvisor - wdyt?

**Comment by watou** [comment]
> Your 2 minutes e.g. appear arbitrary

Definitely hard-coded for the use case of the Weather Underground weather station, and the one hour of rain data is also hard-coded.  Adding more configuration to control how much history is considered would be easy though.

> Are you doing all this [implement hysteresis generically, remove jitter generically, remove wild (impossible) data samples generically, etc] in the binding here?

No, just listing related kinds of problems a generalised solution could be addressing in addition to what this PR does. Thanks for the discussion and the merge!

**Comment by sjka** [comment]
> What I am feeling is that we might need to be able to pass a suggested configuration with an ProfileAdvisor - wdyt?

Yes! Good idea. I created https://github.com/eclipse/smarthome/issues/5755 in order to not hijack this (closed) PR.

**Pull request merged**
