### PR TITLE
Remove wrong groupIds from nest and network binding tests

### PR DESCRIPTION
**Pull request by pfink**
Signed-off-by: Patrick Fink <mail@pfink.de>

### CODE REVIEW

**Comment by martinvw** [comment]
You have a talent for bad luck with strang build errors

**Comment by pfink** [comment]
@martinvw: Jenkins build is showing an issue that I also had on my local environment: It seems like the binding tests cannot be built separately without building/installing the actual binding before. When building the actual binding first and the tests afterward, it works fine. So I'm not sure if there is an easy and predictable way to get this build green. From my observations, sometimes the local maven repo is shared across Jenkins jobs, sometimes not... This time, the latter was obviously the case.

**Comment by martinvw** [comment]
It sounds more like one of openHAB dependencies has an inconsistency between the file and the hash. Can your u validate that the errror is the same

**Comment by pfink** [comment]
No, the error that appears on the Travis build is something different (I referred to the one by Jenkins). But honestly, I have currently no idea where the Travis error comes from... Did you already rebuild on Travis?

**Comment by pfink** [comment]
I can reproduce the hash error on builds that do not contain this change and also with a fresh local maven repo. Maybe a general infrastructure issue?

**Comment by martinvw** [comment]
> I can reproduce the hash error on builds that do not contain this change and also with a fresh local maven repo. Maybe a general infrastructure issue?

I fear so

**Pull request merged**
