### PR TITLE
Exported the tool package in the org.openhab.voice.voicerss bundle.

### PR DESCRIPTION
**Pull request by VelinYordanov**
See openhab/static-code-analysis#100

Signed-off-by: VelinYordanov <velin.iordanov@gmail.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Hm, I am not sure that this should be exposed as a package. There is a single class inside, which is meant to be called from the command line.
Moving it to "internal" is also not ideal as it is a documented tool. So I would actually prefer to make an exception to the rule for that case. Can we deactivate this specific check for that bundle?

**Comment by VelinYordanov** [comment]
Ok, we can do that.

**Comment by martinvw** [comment]
@VelinYordanov so this can be closed?

**Comment by VelinYordanov** [comment]
@martinvw Yes, a supression was added in the static-code-analysis tool for this bundle.

**Pull request closed without merging**
