### PR TITLE
Enable tests with full Travis CI build

### PR DESCRIPTION
**Pull request by wborn**
Since all tests in https://github.com/openhab/openhab2-addons/issues/5775 have been fixed, it should be possible to enable them with a full build.

### CODE REVIEW

**Comment by J-N-K** [comment]
LGTM. Let's see if Travis agrees. I don't see Jenkins anymore, has that been removed?

**Comment by wborn** [comment]
I usually see the result of the Jenkins check added when it finishes. I've also enabled tests on the Jenkins OH2 add-on PR build. 

Do you think it should also be enabled on  the openHAB2-Bundles build @kaikreuzer ?

**Comment by kaikreuzer** [comment]
I probably makes the Jenkins build terrible slow (with 1:45h it is already painful). So if we have tests covered by Travis and SAT by Jenkins that should be fine.

**Comment by wborn** [comment]
Some of the MQTT tests still seem a bit unstable. I might look into that later today. Feel free to improve these on my branch while I enjoy the weather. :sun_with_face: 

Another bug is that the Travis CI build script only builds a single add-on instead of everything when the last commit only changed one add-on. :open_mouth:

**Comment by kaikreuzer** [comment]
At least the hueemulation tests are fixed now (thanks), so let's merge this and see what unstable tests there might still be...

**Pull request merged**
