### PR TITLE
[hue] Splitted tests into unit / integration tests

### PR DESCRIPTION
**Pull request by cweitkamp**
- Moved and fixed unit tests

Also-by: Wouter Born <github@maindrain.net>
Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by wborn** [comment]
Good! Are all tests working again now? :-)

**Comment by cweitkamp** [comment]
> Are all tests working again now?

The unit tests are fine. The integration tests are failing. But I do not know why.

**Comment by J-N-K** [comment]
Did you recreate the bndrun?

**Comment by wborn** [comment]
I made some fixes in https://github.com/cweitkamp/openhab2-addons/pull/2!

**Comment by wborn** [comment]
I'm happy all Hue tests are fixed now after the migration. :smile:

**Pull request merged**
