### PR TITLE
HueEmulation: Fixes and test bundle

### PR DESCRIPTION
**Pull request by davidgraeff**
Unfortunately PR #4313 broke the HueEmulation (within the class hierarchy of `hueState` is two times a field with the name "alert" and that cannot be serialised by gJson). I have therefore created a Test bundle for the HueEmulation to catch those breaking commits.

Refactor
* Create subpackages in internal.dto
* Move REST API parts out of HueEmulationServlet into RestApi class (two classes < 300 lines of code instead of one with > 600 lines)
* Don't let HueEmulationServlet extend HttpServlet, but use an anonymous class field.
  This is because two servlets are required.
* Rename HueEmulationServlet to HueEmulationService
* Hierarchical processing of the REST URI in RestApi class
  for easier maintenance and extendability.
* Use StorageService instead of files for storing users, light mapping and
  user modified bridge parameters.

Rest API Extensions:
* Support POST on /api/{username}/lights
* Support GET on  /api/{username}/lights/new
* Support PUT on  /api/{username}/config (for renaming the emulated bridge)
* Support for groups on /api/{username}/groups

Support for /description.xml next to /api/description.xml, because some Philips devices expect a Hue bridge to have that file on the root path, no matter what the upnp discovery message says.

Test bundle:
* Full implementation test with
  - check for /description.xml upnp file
  - check for invalid user access, valid user access, user creation
  - access for /api/{username}/lights and /api/{username}/lights/{id}
* Unit tests for RestApi class for
  - user management
  - request lights, change light state

Signed-off-by: David Graeff <david.graeff@web.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
The Jenkins PR build failed, could you have a look at https://ci.openhab.org/job/PR-openHAB2-Addons/11441/console?

**Comment by davidgraeff** [comment]
Hm, I do not understand what jenkins is complaining about. It says:
```
RESTApi cannot be resolved to a type
ConfigManagement cannot be resolved to a type
HueEmulationService cannot be resolved to a type
```
But those classes are public, in the same package, the manifest file is correct, local maven runs through, travis succeed and eclipse builds correctly. I really have no clue.

**Comment by kaikreuzer** [comment]
Let's retry then...

**Comment by kaikreuzer** [comment]
Build succeeded, but it shows test failures. Could you please check https://ci.openhab.org/job/openHAB2-Bundles/485/org.openhab.io$org.openhab.io.hueemulation.test/testReport/?

**Comment by davidgraeff** [comment]
Hm, in the failing OSGI-test class code I'm doing this:
```
    @Mock
    ConfigurationAdmin configurationAdmin;
    ...
    @Before
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        ...
        registerService(configurationAdmin);
```

and jenkins tells me:
```
Components implementing org.openhab.io.hueemulation.internal.HueEmulationService:
97 [UNSATISFIED_REFERENCE] org.openhab.io.hueemulation.internal.HueEmulationService in org.openhab.io.hueemulation
	ConfigurationAdmin (org.osgi.service.cm.ConfigurationAdmin)
		No component implementing org.osgi.service.cm.ConfigurationAdmin is currently registered.
```

**Pull request merged**
