### PR TITLE
[Nest] Use DS annotation with NestTestHandlerFactory

### PR DESCRIPTION
**Pull request by wborn**
Depends on https://github.com/openhab/openhab-core/issues/318 so https://github.com/openhab/openhab-core/pull/395 should be merged first.

When fixed, this PR adds the DS annotation again on NestTestHandlerFactory and removes the generated XML from the repository.

### CODE REVIEW

**Comment by martinvw** [comment]
Travis is unhappy, restarting

**Comment by wborn** [comment]
Looks like the build fails because it's still using a pom-tycho from openhab-core without the changes. Perhaps some Cloudbees Jenkins build needs to be triggered before openhab2-addons can use a newer the newer POM?

It's downloading from:
https://openhab.jfrog.io/openhab/libs-snapshot/org/openhab/pom-tycho/2.4.0-SNAPSHOT/

**Comment by martinvw** [comment]
I merged the PR around the time I triggered the build, so another attempt

**Comment by wborn** [comment]
Yes I already tried that by just pushing the "Restart build" button on Travis so I didn't have to close/reopen this PR. ;-) 

It also fails on my own PC when I use the latest available [pom-tycho from the jfrog repo](https://openhab.jfrog.io/openhab/libs-snapshot/org/openhab/pom-tycho/2.4.0-SNAPSHOT/). But since it was build yesterday it doesn't have the changes of https://github.com/openhab/openhab-core/pull/395 that were merged today.

So I wonder which build would normally upload it? The Travis build doesn't do this. And [openHAB-Core](https://openhab.ci.cloudbees.com/job/openHAB-Core/) is disabled and didn't have a successful build either yesterday. Let's hope @kaikreuzer knows the answer. :-)

**Comment by wborn** [comment]
For unknown reasons the new POM is now available so I've restarted Travis again.

**Comment by martinvw** [comment]
Thanks it looks fine now!

**Pull request merged**
