### PR TITLE
[amazonechocontrol] Added jsoup to NOTICE file

### PR DESCRIPTION
**Pull request by Hilbrand**
Maybe jsoup is a candidate to provide in the core as it's used by more bindings (and a pending new binding)?

### CODE REVIEW

**Comment by mgeramb** [comment]
Thank you! Looks good to me.

**Comment by cweitkamp** [comment]
Please correct me if I am wrong but do we include an external library for one line of code? Should we think about a refactoring here and introduced e.g. a regular expression for this case?

https://github.com/openhab/openhab2-addons/blob/43726b47c78a61040f09f2ef3f337d6742962153/addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java#L470

**Comment by Hilbrand** [comment]
replace by #4838. The library is not needed.

**Comment by mgeramb** [comment]
@cweitkamp This line should be 
!StringUtil**s**.isEmpty(value)
So it should not use this jsoup library
The library was used and included in a previous version for parsing html, which is not longer needed.

**Comment by cweitkamp** [comment]
@mgeramb No problem. Did not want to blame you for that. Removing the library will be a nice little improvement for the binding.

**Pull request closed without merging**
