### PR TITLE
Freebox binding: enhancements #888 #889 #890 #897

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: lolodomo lg.hc@free.fr

Redesign of the Freebox binding to manage different thing types, to add discovery of things, and to restore missing features that were included in the 1.x binding.

### CODE REVIEW

**Comment by clinique** [comment]
@lolodomo : great work and nice enhancements that goes in the right way toward OH2 approach. Looking forward to test/deploy this when I'll be back in France this summer.

**Comment by kaikreuzer** [comment]
> Looking forward to test/deploy this when I'll be back in France this summer.

@clinique Could you nonetheless briefly review it and say whether or not it can be merged? Scanning briefly through it, I do not have any concern regarding code style and license, so I'd merge it if you give a lgtm.

**Comment by jongj** [comment]
@kaikreuzer what about "using your real name (sorry, no pseudonyms or anonymous contributions." as stated in https://github.com/openhab/openhab2-addons/blob/master/CONTRIBUTING.md

**Comment by kaikreuzer** [comment]
Good point, you are right that this is our policy...

**Comment by clinique** [comment]
Well, having browsed the code, apart from sus-mentionned realname usage, no problem for me.

**Comment by lolodomo** [comment]
I changed author to put my real name.
@Kai, please merge and include this PR in the coming beta 3.

**Comment by kaikreuzer** [comment]
Many thanks, @lolodomo!
Merged and part of beta3 :-)

**Comment by lolodomo** [comment]
Thank you.
Now I hope mDNS discovery could be fixed soon. If not, I will implement the other way to discover the Freebox server using HTTP rather than mDNS.

**Pull request merged**
