### PR TITLE
RFXCom Fix Rainsensor #1498

### PR DESCRIPTION
**Pull request by fremel75**
Change rainRate & rainTotal to match channel id 
Fix for Issue #1498

### CODE REVIEW

**Comment by fremel75** [comment]
@paulianttila could have a look at this one please?

**Comment by Jamstah** [comment]
Seems like a sensible fix to me.

You will need to check the "Sign your work" section of https://github.com/openhab/openhab-distro/blob/master/CONTRIBUTING.md.

**Comment by paulianttila** [comment]
Lgtm as well.

**Comment by Jamstah** [comment]
Hi @fremel75, you need to modify the commit message, not just comment here. I think you can do that on within now. Otherwise, use "git commit --amend" and "git push --force".

**Comment by kaikreuzer** [comment]
I added his sign-off to the commit.

**Pull request merged**
