### PR TITLE
[knx] update README.md

### PR DESCRIPTION
**Pull request by udo1toni**
Minor typo, clarified default ipAddress for ROUTER mode, corrected false localSourceAddr (this is no group address but a not necessarilly real physical address)

Signed-off-by: Udo Hartmann <udo1toni@gmail.com>

### CODE REVIEW

**Comment by udo1toni** [comment]
new try for https://github.com/openhab/openhab2-addons/pull/4115

**Comment by AngelosF** [comment]
don't get pissed :) but in order to close also https://github.com/openhab/openhab2-addons/issues/3768 you need to make an small additional change:

```
Also in Section Things
....basic Things are wrappers around an arbitrary physical addresses on the KNX bus
```

**Comment by AngelosF** [comment]
Also: The existing doc (https://www.openhab.org/addons/bindings/knx/) uses already the term " Individual Address" instead of "Physical Address"

Should we stick with one term? (PA or IA)?

I think the "official" one is the IA (https://support.knx.org/hc/en-us/articles/115003185789-Individual-Address)

**Comment by udo1toni** [comment]
Ah. Well, I did not look at the english version... https://support.knx.org/hc/de/articles/115003185789-Physikalische-Adresse 
:)

**Comment by udo1toni** [comment]
> 
> 
> don't get pissed :) but in order to close also #3768 you need to make an small additional change:
> 
> ```
> Also in Section Things
> ....basic Things are wrappers around an arbitrary physical addresses on the KNX bus
> ```

I'm not pissed of :) but in this case, "group addresses is the correct term. 

One thing -> at least one GA, but as many GAs as you wish. A knx thing does not need to have a IA (then it's a generic thing).

**Comment by AngelosF** [comment]
> but in this case, `group addresses` is the correct term.

You are very correct!

I think that now your PR needs just a reviewer to approve it.  It looks good to me :)

**Comment by AngelosF** [comment]
by the way: did you check this comment on the previous PR?
https://github.com/openhab/openhab2-addons/pull/4115#issuecomment-438807999
I think that he is right and it is missing an opening square bracket at https://www.openhab.org/addons/bindings/knx/#group-address-notation

**Pull request merged**
