### PR TITLE
Use own service reference to 'ThingRegistry'

### PR DESCRIPTION
**Pull request by cweitkamp**
- Use own service reference to `ThingRegistry`

Bindings should no longer use the property `thingRegistry` from `BaseThingHandler`. It is deprecated and will be removed in the future.

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by cweitkamp** [comment]
@kaikreuzer Can you please add @dominicdesu to the [contributors team](https://github.com/orgs/openhab/teams/contributors)? Thanks.

**Comment by kaikreuzer** [comment]
> @kaikreuzer Can you please add @dominicdesu to the contributors team? Thanks.

Most certainly - done! (although I do not see the relation to this PR...?)

**Comment by kaikreuzer** [comment]
> Bindings should no longer use the property thingRegistry from BaseThingHandler. It is deprecated and will be removed in the future.

Well, it is deprecated because bindings should not use the ThingRegistry at all. So this PR doesn't improve the situation much.
But yes, if it is your intension to soon refactor the BaseThingHandler, then this change makes sense. It just should be clear that this code should not be taken as a blueprint for others.

**Comment by cweitkamp** [comment]
> although I do not see the relation to this PR...?

He is the contributor of the AllPlay binding which got touched in this PR.

> Well, it is deprecated because bindings should not use the ThingRegistry at all. So this PR doesn't improve the situation much.

I know. Maybe we can motivate the developers to start refactoring the bindings to not use the ThingRegistry anymore.

> But yes, if it is your intension to soon refactor the BaseThingHandler, then this change makes sense.

Yes, exactly. That is what I am planning to do. At least for OH3.

FTR: https://github.com/eclipse/smarthome/issues/5182 and https://github.com/eclipse/smarthome/issues/6007

**Comment by kaikreuzer** [comment]
> Maybe we can motivate the developers to start refactoring the bindings to not use the ThingRegistry anymore.

Would it make sense to add a todo/note/warning as a comment in the touched bindings that this is NOT how it should be done?

**Comment by lolodomo** [comment]
For the Sonos binding, it will require a bridge thing representing the Sonos network that will know the network topology with the different groups. But it will break all existing user setups and will make setup more complex than today.

**Comment by cweitkamp** [comment]
> Would it make sense to add a todo/note/warning as a comment in the touched bindings that this is NOT how it should be done?

Done.

**Pull request merged**
