### PR TITLE
Updated channel types to values in RFXComBindingConstants.java fixes #1754

### LINKED ISSUE #1754: RFXCOM: item linked to channel humiditystatus not updated
I use a Cresta temperature and humidity sensor. Items to both value channels are updated. In debug mode the binding logs the telegram from the receiver and it includes a value for humiditystatus. However, the item linked to the channel does not get updated with the value.

Item:
```
String Weather_Home_HumidityStatus "Luchtvochtigheid [%s]" <humidity> { channel="rfxcom:temperaturehumidity:usb1:16142:humiditystatus" }
```

Log:
```
2017-01-22 12:56:32.761 [DEBUG] [binding.rfxcom.handler.RFXComHandler] - Received message from bridge: rfxcom:bridge:usb1 message: Raw data = 0A5207003F0E0098210269, Packet type = TEMPERATURE_HUMIDITY, Seq number = 0, Sub type = TH7, Device Id = 16142, Temperature = 15.200000000000001, Humidity = 33, Humidity status = DRY, Signal level = 6, Battery level = 9
```

Karaf returns NULL as the value
```
openhab> smarthome:status Weather_Home_HumidityStatus
NULL
```

cc binding author @paulianttila

### PR DESCRIPTION
**Pull request by rtvb**
Fixes case sensitive channel types.

I have noticed that the constants file contains more possible values in the docs, but I am not sure if these are already supported. Therefor I have not added those to the README as well.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks!
For future PRs, please remember to [sign-off your commit](https://github.com/openhab/openhab2-addons/blob/master/CONTRIBUTING.md#sign-your-work) - this is also possibly through the Github editor by entering the signed-off-by line in the description field.

**Comment by rtvb** [comment]
> Thanks!

>  For future PRs, please remember to sign-off your commit[1] - this is
>  also possibly through the Github editor by entering the signed-off-by
>  line in the description field.


Will do that next time. But I was under the assumumption that this
commit was an allowed "small patch exception" (since it was a minor
update to the documentation, not the code itself).


https://github.com/openhab/openhab2-addons/blob/master/CONTRIBUTING.md#small-patch-exception

Links:

  1. https://github.com/openhab/openhab2-addons/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by kaikreuzer** [comment]
It is, therefore I merged it nonetheless :-)
But it is a good practice to always add the footer, then you do not run the risk to forget it one day on a non-so-small patch exception ;-)

**Comment by rtvb** [comment]
Fixes #1754 (not auto closed yet)

**Pull request merged**
