### PR TITLE
[samsungtv] Add LE40C650 to tested models list

### LINKED ISSUE #4227: [samsungtv] Add LE40C650 to tested models list
I can confirm that the SamsungTV Binding works with my OpenHab 2.3 and LE40C650 L1KXXU

Thank you for all your efforts on this.

Matt

### PR DESCRIPTION
**Pull request by mc9662**
Fixes #4227

### CODE REVIEW

**Comment by wborn** [comment]
Thanks this look good!

Can you also provide us with a `Signed-off-by: ` line so we can add it to the comment? 
See also [Sign you work](https://www.openhab.org/docs/developer/contributing/contributing.html#sign-your-work).

**Comment by mc9662** [comment]
Signed-off-by: Matt Chitty <matt@mattandsaran.plus.com> (github: @mc9662)

**Comment by mc9662** [comment]
I've added the sign off.  I did read the referenced doc re sign off, but thought the following re it being a one line document change applied?

"Small Patch Exception
There are several exceptions to the signing requirement. Currently these are:
Your patch fixes spelling or grammar errors.
Your patch is a single line change to documentation"

Thanks

Matt

**Comment by wborn** [comment]
Yes you're right about the exception. But proper sign offs make PRs even better! :smile:

**Pull request merged**
