### PR TITLE
removed dependency to annotations

### LINKED ISSUE #3292: [Kodi] missing requirement [org.openhab.binding.kodi/2.3.0.201803022259] osgi.wiring.package
Since snapshot build 1221, OH will not load any bindings if the Kodi binding is installed, and reports the following error...

`2018-03-04 21:40:12.931 [ERROR] [org.openhab.core.karaf.internal.FeatureInstaller  ] - Failed installing 'openhab-persistence-jdbc-mariadb, openhab-misc-restdocs, openhab-misc-openhabcloud, openhab-transformation-javascript, openhab-binding-network, openhab-binding-caldav-command1, openhab-ui-habpanel, openhab-transformation-regex, openhab-misc-hueemulation, openhab-binding-weatherunderground, openhab-transformation-jsonpath, openhab-binding-mqtt1, openhab-binding-zoneminder, openhab-binding-wifiled, openhab-transformation-map, openhab-ui-classic, openhab-action-mail, openhab-binding-kodi, openhab-binding-caldav-personal1, openhab-binding-astro, openhab-ui-habmin, openhab-ui-paper': Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-binding-kodi; type=karaf.feature; version="[2.3.0.SNAPSHOT,2.3.0.SNAPSHOT]"; filter:="(&(osgi.identity=openhab-binding-kodi)(type=karaf.feature)(version>=2.3.0.SNAPSHOT)(version<=2.3.0.SNAPSHOT))" [caused by: Unable to resolve openhab-binding-kodi/2.3.0.SNAPSHOT: missing requirement [openhab-binding-kodi/2.3.0.SNAPSHOT] osgi.identity; osgi.identity=org.openhab.binding.kodi; type=osgi.bundle; version="[2.3.0.201803022259,2.3.0.201803022259]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.binding.kodi/2.3.0.201803022259: missing requirement [org.openhab.binding.kodi/2.3.0.201803022259] osgi.wiring.package; filter:="(osgi.wiring.package=org.osgi.service.component.annotations)"]]`

This is affecting others, [as reported in the forum](https://community.openhab.org/t/after-oh2-3-upgrade-fail-to-install-any-features-error-core-karaf-internal-featureinstaller-failed-installing-openhab/41209).

### PR DESCRIPTION
**Pull request by kaikreuzer**
fixes #3292

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by martinvw** [comment]
What about:

https://github.com/openhab/openhab2-addons/blob/e5e13a561a16521c6debc92b303dc0b4b1c51439/addons/binding/org.openhab.binding.lametrictime/META-INF/MANIFEST.MF#L40-L42

Or should both of them be like this:

https://github.com/openhab/openhab2-addons/blob/2ec67bac23ca1601a2c23263cd31a93b337f267d/addons/binding/org.openhab.binding.nikohomecontrol/META-INF/MANIFEST.MF#L26-L28

But why I assume to actually use them at runtime it requires them or not?

**Comment by martinvw** [comment]
Please note that travis also fails so that suggests that this is not the complete solution.

**Comment by kaikreuzer** [comment]
The annotations are only relevant at build time. You are right, the other two bindings can be fixed as well (in a separate PR).
Travis failed due to Feed tests, that's not related. Jenkins PR build succeeded.

**Comment by martinvw** [comment]
Complete grep:

```
addons/binding/org.openhab.binding.kodi/META-INF/MANIFEST.MF: org.osgi.service.component.annotations,
addons/binding/org.openhab.binding.icloud/META-INF/MANIFEST.MF: org.osgi.service.component.annotations;resolution:=optional,
addons/binding/org.openhab.binding.netatmo/META-INF/MANIFEST.MF: org.osgi.service.component.annotations;resolution:=optional,
addons/binding/org.openhab.binding.nikohomecontrol/META-INF/MANIFEST.MF: org.osgi.service.component.annotations;resolution:=optional,
addons/binding/org.openhab.binding.lametrictime/META-INF/MANIFEST.MF: org.osgi.service.component.annotations,
```

**Comment by kaikreuzer** [comment]
Ok, if you merge this, I will create a PR for the others as well :-)

**Comment by martinvw** [comment]
> Ok, if you merge this, I will create a PR for the others as well :-)

👍 hooray

**Comment by kaikreuzer** [comment]
Created https://github.com/openhab/openhab2-addons/pull/3295.

**Pull request merged**
