### PR TITLE
[plugwise] Migrate to bnd build

### PR DESCRIPTION
**Pull request by wborn**
Migrates the Plugwise Binding to the bnd build.

### CODE REVIEW

**Comment by J-N-K** [comment]
Looks good. I think this will help with all bindings without tests and without external libraries. I'll concentrate on those then.

**Comment by wborn** [comment]
The script also migrates tests. But it isn't smart enough to see which tests are integration tests. I could check if there isn't any test extending from JavaOSGiTest and then not create a test bundle at all. :-)

**Comment by davidgraeff** [comment]
Guys, what is the plan? Can we (not me sadly) also merge the all-green migration PRs? Or do we just accumulate them? That's about 20 PRs so far.

**Comment by J-N-K** [comment]
I can‘t xD

**Comment by wborn** [comment]
Everything still open now is:
* waiting for conflicts to be resolved
* builds to succeed
* created by me and thus waiting for other maintainers to review/merge

**Comment by J-N-K** [comment]
Will resolve all merge conflicrs in the next hour

**Pull request merged**
