### PR TITLE
Netatmo binding: updated French translation

### LINKED ISSUE #2517: Netatmo binding: missing translations in French
Using the new Paper UI page for bindings, I got this for the Netatmo binding:
* the binding description has no sense: "Le binding Netatmo gre station Netatmo Personal Weather et les modules additionels."
* some things types are displayed in French like for example NAMain or NAModule1, but others in English like for example netatmoapi or NATherm1
* the French description of the thing type NAModule3 has apparently an encoding problem

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #2517 

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
This PR already includes translations for changes done by the PR #2510.

**Comment by martinvw** [comment]
@lolodomo @clinique does one of you think that it will break without merging #2510 yet? I would be surprised and I dare to take the risk 😄

**Comment by clinique** [comment]
@martinvw : no, translation files are not modified by #2510, so no issue for me to merge this PR.

**Comment by martinvw** [comment]
Thanks to both of you!

**Pull request merged**
