### PR TITLE
[dlinksmarthome] migrate to bnd

### PR DESCRIPTION
**Pull request by J-N-K**
Needs Java 11 compatibility (see #5148)

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by J-N-K** [comment]
Feature verification fails because the `com.sun.xml.ws:jaxws-ri` bundle is not available. After some testing, we probably have to adjust the denonmarantz to `com.sun.xml.bind:jaxb-impl`, the api helps compiling but is not enough for running it, so that will fail, too.

**Comment by davidgraeff** [comment]
> After some testing, we probably have to adjust the denonmarantz to com.sun.xml.bind:jaxb-impl

No necessarily. You can have the compile time dependency on the api and add the implementation dependency in the karaf feature. 

Advantage: Smaller bundle
Disadvantage: Runtime maven dependency must be downloaded and karaf is not very talkative regarding download progress.

**Comment by J-N-K** [comment]
The problem is not compile-time. This works perfectly (jcenter is available at build time). The problem is the feature. For `denonmarantz` this can be solved `jaxb-impl/2.2.11` is available. 2.3.2 is newest, but does not work with karaf as far as google knows. `jaxws-ri` is not available at all, and google indicates one should use apache-cxf, which seems a bit heavy.

**Comment by davidgraeff** [comment]
> jaxb-impl/2.2.11

Should be fine. The API hasn't changed since a long time, I wonder what a new release of that library can even offer.

**Comment by wborn** [comment]
Is this still WIP @J-N-K ?

**Comment by J-N-K** [comment]
I found out we already have CXF as `/lib` in the helios binding. But the feature is still  not resolving on Java 11 (complilation is fine). So yes, I still need some time here.

**Comment by davidgraeff** [comment]
Since java 9 and the module system you might also need to take extra steps?

**Comment by J-N-K** [comment]
See #5182. Please review the feature and pom more thoroughly

**Comment by wborn** [comment]
That looks much better @J-N-K ! Now if only there were some reusable features so these bundles can be easily reused with all impacted bindings. :wink:

**Comment by J-N-K** [comment]
I have added an alternative set of bundles that provides the necessary bundles. However, I see

```
[INFO] Unable to determine whether the meta annotation com.sun.istack.NotNull applied to type com.oracle.webservices.api.message.BaseDistributedPropertySet provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation com.sun.istack.Nullable applied to type com.oracle.webservices.api.message.BaseDistributedPropertySet provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation org.glassfish.gmbal.ManagedAttribute applied to type com.sun.xml.ws.api.addressing.OneWayFeature provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation org.glassfish.gmbal.ManagedData applied to type com.sun.xml.ws.api.addressing.OneWayFeature provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation org.glassfish.gmbal.ManagedObject applied to type com.sun.xml.ws.client.MonitorRootClient provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation org.glassfish.gmbal.Description applied to type com.sun.xml.ws.client.MonitorRootClient provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation org.glassfish.gmbal.AMXMetadata applied to type com.sun.xml.ws.client.MonitorRootClient provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation org.glassfish.gmbal.InheritedAttributes applied to type com.sun.xml.ws.server.DummyWebServiceFeature provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation org.glassfish.external.probe.provider.annotations.Probe applied to type com.sun.xml.ws.transport.http.servlet.JAXWSRIDeploymentProbeProvider provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation org.glassfish.external.probe.provider.annotations.ProbeParam applied to type com.sun.xml.ws.transport.http.servlet.JAXWSRIDeploymentProbeProvider provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation org.glassfish.external.probe.provider.annotations.ProbeProvider applied to type com.sun.xml.ws.transport.http.servlet.JAXWSRIDeploymentProbeProvider provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation javax.servlet.annotation.HandlesTypes applied to type com.sun.xml.ws.transport.http.servlet.WSServletContainerInitializer provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation com.sun.xml.txw2.annotation.XmlAttribute applied to type com.sun.xml.ws.wsdl.writer.UsingAddressing provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation com.sun.xml.txw2.annotation.XmlElement applied to type com.sun.xml.ws.wsdl.writer.UsingAddressing provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation com.sun.xml.txw2.annotation.XmlNamespace applied to type com.sun.xml.ws.wsdl.writer.document.http.package-info provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
```

The verification passes, so I guess this is not a problem. I'll check if I can find out what is missing.

**Comment by wborn** [comment]
I think I saw similar logging with #5219. In the end it still worked. Getting rid of all that noise would be even better of course!

**Comment by J-N-K** [comment]
@wborn, after we got the requested review, I can add the features. As already said, I would prefer to have the possibility to include only one dependency in POMs, too. I'm still investigation how to do that.

**Comment by davidgraeff** [comment]
But there is actually not really a necessity to do that, is it? If you use javax.xml you have to live with the fact of requiring 3 to 4 dependencies. Newer products are not building up on xml anyway so future PRs will most certainly not require those dependencies.

**Comment by J-N-K** [comment]
@davidgraeff I doubt that. Every binding that uses SOAP needs that.

**Comment by wborn** [comment]
I should be possible to have a POM with dependencies (see the BOM `bom/openhab-addons/pom.xml`). Then if you add a dependency on such a POM in the project you depend on its dependencies through transitivity. 

I thought @maggu2810 would be back sooner. :wink:  But he won't return until the beginning of April. So with the "heavy" CXF dependency gone I'm more confident this is a better solution. It would still be nice to hear from him if this is the way to go. 

If we use a POM with dependencies and use feature dependencies for bundles it should also be easy to fix/improve this in the future. :smile:

**Comment by J-N-K** [comment]
Where should the features be added? At the top of the features.xml or in openhab-core for the target platform?

**Comment by wborn** [comment]
> Where should the features be added? At the top of the features.xml or in openhab-core for the target platform?

According to the current [coding guidelines](https://www.openhab.org/docs/developer/development/guidelines.html#c-language-levels-and-libraries) we shouldn't depend on packages such as `javax.xml.bind` and `javax.xml.soap` which are only available in the "Full JRE". That's also why [these issues](https://github.com/openhab/openhab2-addons/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+depends+on+full+JRE) were created.

Do you still think that coding guideline is valid @kaikreuzer now that we forked OHC from ESH? If we keep the coding guideline I think it makes less sense to add these features to the core. These features should then only exist to keep the impacted bindings working on Java 11 until they have been refactored such that they no longer depend the Full JRE packages.

**Comment by J-N-K** [comment]
There are a some bindings. At least those I fixed recently for Java11. There are others in openhab1-addons which will depend on that, too (after they have been ported). I think we should define a clear set of allowed dependencies for such bindings (i.e. those we have here). We should avoid CXF for new contributions (or switch to that completely).

**Pull request merged**
