### PR TITLE
fix max test

### PR DESCRIPTION
**Pull request by maggu2810**

### CODE REVIEW

**Comment by maggu2810** [comment]
https://github.com/openhab/openhab-distro/commit/623134ee9ecdf75033f4f0d4adf5a87fbbf59070#commitcomment-17217421 :wink:

**Comment by maggu2810** [comment]
Related to: https://github.com/eclipse/smarthome/pull/1407/files

**Comment by maggu2810** [comment]
Hi, @kaikreuzer before you merge, I don't think it is very comfortable to the developers that it needs such a start-level and auto start configuration at all.
I add now a second commit, that does solve it another way.
I like this approach much more, because it does not need such a configuration and relies on the OSGi framework to do their work.

**Comment by maggu2810** [comment]
Done, please compare commit 1 and commit 2.
WDYT?

**Comment by maggu2810** [comment]
aaaah, wait a moment, will change the commit 2 and remove the whitespace fix for the moment....

**Comment by maggu2810** [comment]
@kaikreuzer So, done... Please have a look at now (compare the two commits).
Which one do you prefer?
* the more manual approach
* the automatic one, that relies on the OSGi framework
The whole test configuration is similar to that of the Eclipse Runtime Launch one...

**Comment by kaikreuzer** [comment]
I am a bit worried that changing the start level of eventadmin and ds might cause issues for existing tests. Nonetheless you are right that the launch config also uses default start levels for these bundles, so in general I agree that the second option is the nicer (and simpler) one.

**Comment by maggu2810** [comment]
Of course it is also possible to mix the two approaches(set ds + eventadmin, and the remaining use the default one)

**Comment by kaikreuzer** [comment]
We might do this if it is too hard to get certain tests working.
For here, let's take your second commit. If I squash&merge, it should be just fine as it is, right?

**Comment by maggu2810** [comment]
Correct

**Comment by kaikreuzer** [comment]
Many thanks - you are the unit test master (after myself and @marcelrv have failed...)!

**Comment by marcelrv** [comment]
Great... thanks

**Pull request merged**
