### PR TITLE
Replace Runnables with lambdas

### PR DESCRIPTION
**Pull request by wborn**
Removes 500+ lines of boiler plate code by using lambdas instead of Runnables.

### CODE REVIEW

**Comment by martinvw** [comment]
I would love it if you could exclude some of the conflicting changes with open PR's for example the exec binding pops up in my mind. If possible it would be great if you could do a quick check for other bindings.

A good starting point could be:

https://github.com/openhab/openhab2-addons/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+-label%3Anewbinding+

**Comment by wborn** [comment]
@martinvw After looking at the files touched by the other PR's, I've excluded modifications to the following bindings: autelis, exec, lutron, max, squeezebox, vitotronic

**Comment by martinvw** [comment]
Thanks, and also especially for excluding those bindings.

**Comment by mhilbush** [comment]
> excluded modifications to the following bindings: ... squeezebox ...

I just pushed a change to my squeezebox PR to replace the Runnables with lambdas.

**Pull request merged**
