### PR TITLE
[daikin] Add homekitmode for use with homekit/alexa/google assistant

### PR DESCRIPTION
**Pull request by psmedley**
[daikin] Add homekitmode for use with homekit/alexa/google assistant

Add a mode that is compatible with homekit, alexa, google assistant, which don't understand the power/mode combinations that the daikin binding uses.

homekitmode currently supports off, on, heat & cool and maps these to the appropriate airbase settings

Posted link in https://community.openhab.org/t/daikin-airbase-binding/77179/66

### CODE REVIEW

**Comment by jimtng** [comment]
This PR seems to include teslapowerwall binding too?

**Comment by psmedley** [comment]
Uggh it shouldn't. I'll fix tonight

**Comment by psmedley** [comment]
Definitely something broke, my GitHub has this as a specific branch atvhttps://github.com/psmedley/openhab2-addons/commit/2c6ef568b96ba114e43d7c4e8a11acacad80a619

**Comment by psmedley** [comment]
replaced by 6497

**Pull request closed without merging**
