### PR TITLE
Tesla : Refactor event stream handling + handle out of sync events re…

### PR DESCRIPTION
**Pull request by kgoderis**
…ceived from the Tesla servers

Signed-off-by: Karel Goderis <karel.goderis@me.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Do the error logs really qualify for that level wrt http://docs.openhab.org/developers/development/guidelines.html#e-logging?

**Comment by kgoderis** [comment]
@kaikreuzer Yes, for the time being. Tesla is changing (again) the behaviour of their API backend, and I need to capture a maximum of information to grasp what they are doing. Anyways, with respect to the logging  guidelines I will review all my bindings accordingly and push out a big commit with all changes, if you don't mind

**Comment by kgoderis** [comment]
@kaikreuzer This one can be put on hold as I am solving more issues with the Tesla backend API

**Comment by kgoderis** [comment]
@kaikreuzer Closing this PR so that I can push a new one later on. In the meantime https://github.com/openhab/openhab2-addons/pull/2063 can be merged

**Pull request closed without merging**
