### PR TITLE
Systeminfo  binding - add process info

### PR DESCRIPTION
**Pull request by svilenvul**
Added process info to Systeminfo binding (please see [Systeminfo discussion](https://github.com/openhab/openhab2-addons/issues/365#issuecomment-219880088)) .
Process CPU load, memory used, PID (process identifier), name and path info is now available.

The new functionality comes with various fixes and improvements:
- Improved tests stability 
- thingUpdated() method overwritten to  handle channel configuration changes at runtime 
- changed initialize() method to better handle errors 
- OSHI version updated to release 2.5
- added new channels for process info and new configuration parameter (process identifier)
- updated README and javadoc   

Signed-off-by: Svilen Valkanov, svilen.valkanov@musala.com (github: svilenvul)

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks for the updates and sorry for taking so long to merge it!

**Comment by kaikreuzer** [comment]
@svilenvul Could you have a look at the failing tests, please?
https://openhab.ci.cloudbees.com/job/openHAB2-Addons/642/testReport/

**Comment by svilenvul** [comment]
@kaikreuzer Yes, I will take a look, it has been a while, since I made these changes.

**Comment by svilenvul** [comment]
@kaikreuzer I think the tests are failing, because of this PR  - eclipse/smarthome#1677, I will take a look, what can be done to fix them.

**Pull request merged**
