### PR TITLE
[Keba] fix factory + add new firmware + remove RefreshType handling

### PR DESCRIPTION
**Pull request by kgoderis**
Signed-off-by: Karel Goderis <karel.goderis@me.com>

### CODE REVIEW

**Comment by kgoderis** [comment]
> This looks like a breaking change. You should also adapt the README.md and please also add information on what people have to do when switching from 2.1 to 2.2 at https://github.com/openhab/openhab-distro/wiki/Draft-for-openHAB-2.2-Release-Notes#keba-binding.

For my understanding, that should be on this specific wiki page, or on the page that is linked from this wiki page

> 
> Btw, why did you remove the refresh handling? In general, the binding should be able to handle this command?

It generated too many (repetitive) calls to the Keba frontend, each timing fetching the same info, whereas the runnable to get all that information is scheduled anyways.

**Comment by kaikreuzer** [comment]
> For my understanding, that should be on this specific wiki page

Yes, it should be directly on the release notes wiki page.

> It generated too many (repetitive) calls to the Keba frontend

We have a solution for that by now! See https://github.com/eclipse/smarthome/issues/3302

**Comment by martinvw** [comment]
@kaikreuzer since you are already involved I'll assign it to you and will not be involved :-)

**Comment by kgoderis** [comment]
@kaikreuzer Whilst considering your suggestion to use ExpiringCacheMap in this binding, I noticed that the way it works is not compatible with the Keba binding, in the sense that it expects the function/action to refresh the cached value to be synchronous, e.g. it needs to return the value immediately. In the Keba binding all the communication with the device is asynchronous, e.g. I can perfectly define what action to use to update a value in the Cache, but the cached value will not be updated until later (and in another thread), so .get() does not necessarily return the correct value. 

I therefore suggest to merge the PR as is. I have already adjusted the wiki page in this sense. I will squash the commits

**Comment by kgoderis** [comment]
@kaikreuzer @martinvw I reworked this PR and overhauled the binding so that it communicates with the charge stations in a more synchronous way, so that also the ExpiringCacheMap can be used as suggested by Kai. I ran it through the static code analyser, and all the items flagged by the analyser are fixed as well. I hope it it now in a state that it can be merged and closed

**Comment by kgoderis** [comment]
Replaced by https://github.com/openhab/openhab2-addons/pull/2844

**Pull request closed without merging**
