### PR TITLE
Update tycho repositories

### PR DESCRIPTION
**Pull request by dvanherbergen**
Signed-off-by: Davy Vanherbergen <davy.vanherbergen@gmail.com>

### CODE REVIEW

**Comment by dvanherbergen** [comment]
This PR is now ready to be merged. The last [PR-openhab2-addons build] (https://openhab.ci.cloudbees.com/view/Pull%20Request%20Builds/job/PR-openHAB2-Addons/30/) on a small instance took 3m 37s.

**Comment by kaikreuzer** [comment]
Sounds cool. How does it work? I only see that you removed the reference to the target file and added more repos. But where are the pom dependencies declared? Is that not at all required...?

**Comment by dvanherbergen** [comment]
It turns out there was an easier way than adding the pom dependencies on by one. By just declaring the maven repos directly with a p2 layout, Tycho knows where to find them. This is a nice way of getting rid of the circular dependency.
In the future things could be simplified further by reducing the number of repos to a single openhab [composite repo] (https://wiki.eclipse.org/Equinox/p2/Composite_Repositories_(new)). That would allow the launch config and other projects to just reference one single 'target platform p2 repository', which would redirect internally to the actual repos.
Most of the speed improvement of the build is due to changes on Jenkins. When a new pull request build starts, it starts by default with an empty maven repo for security reasons. To improve loading time, the PR-openhab2-addons build now first installs an initial copy of the repo. 
And with the changed tycho dependency, it was also possible to set up mirroring setup for some of the p2 repos.

**Comment by kaikreuzer** [comment]
Wow, I didn't know that this is possible - great work, thanks!

**Comment by maggu2810** [comment]
Isn't the difference between the target platform file and the repositories in the pom that in the target file we also define which bundles / features of a repository are candidates that should be used?
We are using different p2 repositories that contains a lot of bundles. Couldn't this lead to problems if there are different versions in the different repos of the same bundle? Using the target platform file we already selected some bundles / feature of a repo and do not use all the content ATM.
Perhaps I am missing something...

**Comment by maggu2810** [comment]
But perhaps if this will be a problem, we have to add the version constraints in the manifest.

**Comment by kaikreuzer** [comment]
Valid point, but as the build is green, there does not seem to be any problem right now - nonetheless, we should have an eye on it.

**Comment by dvanherbergen** [comment]
> But perhaps if this will be a problem, we have to add the version constraints in the manifest.

That may indeed be necessary if apis between different versions change.

An alternative could be to generate an 'aggregate p2 repo' which only contains the exact set of runtime bundles. This would also allow us to make the cloudbees build a little faster.

**Comment by kaikreuzer** [comment]
Yes, an aggregate repo definitely makes sense!

**Pull request merged**
