### PR TITLE
Tesla binding : fix minor issue with trace log

### PR DESCRIPTION
**Pull request by kgoderis**
Signed-off-by: Karel Goderis <karel.goderis@me.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Your commit is missing the sign-off.

**Comment by kaikreuzer** [comment]
@kgoderis Ping!

**Comment by kgoderis** [comment]
huh.... ok. Sign-off in the PR is not sufficient?

**Comment by kaikreuzer** [comment]
Nope, what ends up in the repo is the commit, not the PR.

**Comment by kgoderis** [comment]
@kaikreuzer done

**Pull request merged**
