### PR TITLE
Exported the ahamodel and hardware packages in the avmfritz binding.

### PR DESCRIPTION
**Pull request by VelinYordanov**
Currently the public API is unusable, because it uses internal types DeviceModel  and FritzahaWebInterface.

See openhab/static-code-analysis#210

Signed-off-by: VelinYordanov <velin.iordanov@gmail.com>

### CODE REVIEW

**Comment by martinvw** [comment]
@kaikreuzer I would like to discuss first whether we are not solving this the wrong way around, I think that in cases like this it is more likely that the incorrect api was exposed. 

Now we are dragging the complete internal representation of the underlying rest service to the api of this binding.

**Comment by kaikreuzer** [comment]
@martinvw I agree, this is something that should be discussed. When exposing a handler API, we should make sure that the API is sensible. For most bindings, there probably won't ever be a use case for those exported handlers, though. So the question is whether it is worth putting effort into a "clean" API - the other, simpler way would be to simply move the whole handler to an internal package.

Our archetype currently creates it to be exported. The discussion around whether this makes sense or not is at https://github.com/eclipse/smarthome/issues/4330.

**Comment by wborn** [comment]
I think a better fix would be to stop exporting the handler packages and move the classes to the internal package. Since the conclusion of https://github.com/eclipse/smarthome/issues/4330 was to no longer export handlers by default. Can you update the PR @VelinYordanov?

**Comment by VelinYordanov** [comment]
@cweitkamp @wborn I updated the PR. Can you take a look? Also ,if the decision is final, I can fix all issues regarding this matter.

**Comment by kaikreuzer** [comment]
Yes, it is final, see https://github.com/eclipse/smarthome/pull/5434.

**Pull request merged**
