### PR TITLE
[onkyo] Migrate to bnd build

### PR DESCRIPTION
**Pull request by Hilbrand**
Automigrated with https://gist.github.com/Hilbrand/a7127d0fb7afd36124a78a248453ff03

### CODE REVIEW

**Comment by J-N-K** [comment]
Since the comment in #5147 states it will take weeks, I would recommend to merge here. The feature PR can easily be restored by copying the changed files to the new location if rebase is not possible.

**Comment by davidgraeff** [comment]
Can you resolve the conflicts? The author of the open PR cannot continue working on the code for some weeks so we are migrating first

**Comment by Hilbrand** [comment]
Conflicts resolved.

**Comment by davidgraeff** [comment]
Jenkins has auth problems with snapshot uploads apparently, no build problems

**Pull request merged**
