### PR TITLE
Fixes pattern issue with readonly channels, add additional player and …

### PR DESCRIPTION
**Pull request by digitaldan**
…sync commands, fixes time counter issue with multiple players

Signed-off-by: Dan Cunningham <dan@digitaldan.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
This PR shows many code changes due to the auto formatting.
On the XML files though, there is still a mix of tab&spaces - it should actually be all spaces in there.
Did you edit them through the IDE as well? Could you check if manually applying the formatter replaces the tabs by spaces?

**Comment by digitaldan** [comment]
Hi Kai, the Java changes are due to the file being 9 months old and did not have our current up to daet formatting rules (you probably knew that), but XML with tabs was a surprise to me.  When I added a few more elements to it  I went ahead and did a right click -> Source -> Format Element on the document and let eclipse format it. This has seemed to add tabs instead of spaces.  I'm using the official IDE setup with no custom formatting changes.  I'll go ahead and revert that file and manually format it with spaces.

**Comment by maggu2810** [comment]
IIRC The formatter will use spaces for Java files and tabs for XML files.

**Comment by maggu2810** [comment]
Cannot find the current discussion, but we already discussed it.
Perhaps I should add a reference / link the next time to such a comment: https://github.com/eclipse/smarthome/pull/668#issuecomment-162805772 :wink:

**Comment by maggu2810** [comment]
> Cannot find the current discussion, but we already discussed it.

https://github.com/eclipse/smarthome/issues/561#issuecomment-162585567

**Pull request merged**
