### PR TITLE
[PLCLogo] Fix compiler warnings. (fixes #4335)

### LINKED ISSUE #4335: [plclogo] Null annotation errors in configurations
In Eclipse several null annotation errors show:

errors

Can you have a look @falkena ?

Maven output:

```
[INFO] Compiling 18 source files to /home/wouter/git/openhab/openhab2-addons/addons/binding/org.openhab.binding.plclogo/target/classes
[WARNING] /home/wouter/git/openhab/openhab2-addons/addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/handler/PLCBridgeHandler.java:[96] 
	int result = client.readDBArea(1, 0, memory.length, S7Client.S7WLByte, buffer);
	             ^^^^^^
Potential null pointer access: this expression has a '@Nullable' type
[WARNING] /home/wouter/git/openhab/openhab2-addons/addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/handler/PLCBridgeHandler.java:[100] 
	if (handler == null) {
	    ^^^^^^^
Null comparison always yields false: The variable handler cannot be null at this location
[WARNING] /home/wouter/git/openhab/openhab2-addons/addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/handler/PLCBridgeHandler.java:[153] 
	int result = client.readDBArea(1, layout.address, buffer.length, S7Client.S7WLByte, buffer);
	             ^^^^^^
Potential null pointer access: this expression has a '@Nullable' type
[WARNING] /home/wouter/git/openhab/openhab2-addons/addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/handler/PLCBridgeHandler.java:[261] 
	rtcJob.cancel(false);
	^^^^^^
Potential null pointer access: this expression has a '@Nullable' type
[WARNING] /home/wouter/git/openhab/openhab2-addons/addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/handler/PLCBridgeHandler.java:[272] 
	readerJob.cancel(false);
	^^^^^^^^^
Potential null pointer access: this expression has a '@Nullable' type
[WARNING] /home/wouter/git/openhab/openhab2-addons/addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/handler/PLCBridgeHandler.java:[360] 
	if (!client.isConnected() && (local != null) && (remote != null)) {
	     ^^^^^^
Potential null pointer access: this expression has a '@Nullable' type
[WARNING] /home/wouter/git/openhab/openhab2-addons/addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/handler/PLCBridgeHandler.java:[361] 
	client.Connect(config.get().getAddress(), local.intValue(), remote.intValue());
	^^^^^^
Potential null pointer access: this expression has a '@Nullable' type
[WARNING] /home/wouter/git/openhab/openhab2-addons/addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/handler/PLCBridgeHandler.java:[363] 
	result = client.isConnected();
	         ^^^^^^
Potential null pointer access: this expression has a '@Nullable' type
[WARNING] /home/wouter/git/openhab/openhab2-addons/addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/handler/PLCBridgeHandler.java:[376] 
	if (client.isConnected()) {
	    ^^^^^^
Potential null pointer access: this expression has a '@Nullable' type
[WARNING] /home/wouter/git/openhab/openhab2-addons/addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/handler/PLCBridgeHandler.java:[377] 
	client.Disconnect();
	^^^^^^
Potential null pointer access: this expression has a '@Nullable' type
[WARNING] /home/wouter/git/openhab/openhab2-addons/addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/handler/PLCBridgeHandler.java:[379] 
	result = !client.isConnected();
	          ^^^^^^
Potential null pointer access: this expression has a '@Nullable' type
[WARNING] /home/wouter/git/openhab/openhab2-addons/addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/config/PLCPulseConfiguration.java:[37] 
	return observe;
	       ^^^^^^^
Null type mismatch (type annotations): required '@NonNull String' but this expression has type '@Nullable String'
[WARNING] /home/wouter/git/openhab/openhab2-addons/addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/config/PLCPulseConfiguration.java:[58] 
	return getBlockKind(observe);
	                    ^^^^^^^
Null type mismatch (type annotations): required '@NonNull String' but this expression has type '@Nullable String'
[WARNING] /home/wouter/git/openhab/openhab2-addons/addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/config/PLCLogoBridgeConfiguration.java:[23] 
	private String address;
	               ^^^^^^^
The @NonNull field address may not have been initialized
[WARNING] /home/wouter/git/openhab/openhab2-addons/addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/config/PLCLogoBridgeConfiguration.java:[24] 
	private String family;
	               ^^^^^^
The @NonNull field family may not have been initialized
[WARNING] /home/wouter/git/openhab/openhab2-addons/addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/config/PLCMemoryConfiguration.java:[24] 
	private String block;
	               ^^^^^
The @NonNull field block may not have been initialized
[WARNING] /home/wouter/git/openhab/openhab2-addons/addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/config/PLCDateTimeConfiguration.java:[24] 
	private String block;
	               ^^^^^
The @NonNull field block may not have been initialized
[WARNING] /home/wouter/git/openhab/openhab2-addons/addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/config/PLCDateTimeConfiguration.java:[25] 
	private String type;
	               ^^^^
The @NonNull field type may not have been initialized
[WARNING] /home/wouter/git/openhab/openhab2-addons/addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/config/PLCDigitalConfiguration.java:[24] 
	private String kind;
	               ^^^^
The @NonNull field kind may not have been initialized
[WARNING] /home/wouter/git/openhab/openhab2-addons/addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/handler/PLCCommonHandler.java:[244] 
	return family;
	       ^^^^^^
```

### PR DESCRIPTION
**Pull request by falkena**
@wborn Please, review.

Kind regards,

Alaxander.

### CODE REVIEW

**Comment by falkena** [comment]
Thanks @wborn. Well, this is really crazy stuff... Let's go to code...
    public String getObservedBlock() {
        if (observe == null) {
            observe = getBlockName();
        }
        return observe;
    }

observe can be null, but getBlockName() returns always not null. Adding synchronize to method signature change nothing... The same situation is in getObservedBlockKind(). I tried to make the same you explaned in bug ticket: Same warning. Do you have more hint's for me? Sorry to pepper you with questions: I'm learning Java by writing bindings for openHAB. And mainly C++ guy :-)

**Comment by falkena** [comment]
Well, this change a logic behind. Reason: I'll set observed block to "normal" one on first access, if it was not set before. Only one solution i see, is to go via "NOT_SET" - like stuff.

**Comment by wborn** [comment]
The compiler will also be happy if you assign `observe` before returning the result :wink: :

```java
    public String getObservedBlock() {
        String result = observe;
        if (result == null) {
            result = getBlockName();
            observe = result;
        }
        return result;
    }
```

**Comment by falkena** [comment]
Hi @wborn ,
thanks! I've learned some java patterns:-) And performed changes you request.

Kind regards,

Alexander

**Comment by falkena** [comment]
Cool :-) Thanks

**Pull request merged**
