### PR TITLE
Changed Chromecast Library to original

### LINKED ISSUE #1382: Chromecast does not play/pause videos from all sources
I've installed the new chromecast binding, and the play/pause and volume buttons work very well when it is playing videos streamed from services like YouTube. When trying to pause or play a video from Airflow (A PC application which allows you to stream any video file to your chromecast) I receive the following errors (and the video does not play or pause):

```
21:02:32.954 [WARN ] [maggu2810.shk.chromecast_api.Channel] - Error while reading: Unrecognized field "videoInfo" (Class de.maggu2810.shk.chromecast_api.MediaStatus), not marked as ignorable
 at [Source: java.io.StringReader@538d7f; line: 1, column: 1023] (through reference chain: de.maggu2810.shk.chromecast_api.MediaStatus["videoInfo"])
21:02:32.957 [WARN ] [maggu2810.shk.chromecast_api.Channel] -  <-- {"type":"MEDIA_STATUS","status":[{"mediaSessionId":2,"playbackRate":1,"playerState":"PAUSED","currentTime":0,"supportedMediaCommands":15,"volume":{"level":1,"muted":false},"videoInfo":{"width":320,"height":240,"hdrType":"sdr"},"media":{"contentId":"http://192.168.0.3:46634/live-transcoding/segment/session1-e93aad4c-a207-11e6-b71a-d8cb8a772ec6/simple-mx0-pl0/segment0.mkv","contentType":"video/x-matroska","duration":30.121666,"metadata":{"metadataType":0,"title":"Sample Video"},"streamType":"BUFFERED"},"currentItemId":2,"items":[{"itemId":2,"media":{"contentId":"http://192.168.0.3:46634/live-transcoding/segment/session1-e93aad4c-a207-11e6-b71a-d8cb8a772ec6/simple-mx0-pl0/segment0.mkv","contentType":"video/x-matroska","duration":30.121666,"metadata":{"metadataType":0,"title":"Sample Video"},"streamType":"BUFFERED"},"autoplay":false,"customData":{"logoURL":"https://s3.amazonaws.com/Airflow/GoogleCast/v1/AirflowIconGoogleCast.png","placeholderText":"Airflow is ready to cast"}}],"repeatMode":"REPEAT_OFF"}],"requestId":7}
21:02:37.676 [WARN ] [ore.internal.events.OSGiEventManager] - Dispatching event to subscriber 'org.eclipse.smarthome.core.thing.internal.ThingManager@140e0d6' takes more than 5000ms.
21:02:37.676 [WARN ] [ome.core.thing.internal.ThingManager] - Handler for thing 'chromecast:chromecast:9e4179b4-7c59-aa7b-d1d6-d1f60324ed94' takes more than 5000ms for processing event
```

Volume control still works well though.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/38937852-chromecast-does-not-play-pause-videos-from-all-sources?utm_campaign=plugin&utm_content=tracker%2F2164344&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F2164344&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by BClark09**
Library built from https://github.com/vitalidze/chromecast-java-api-v2

Fixes #1382 

Signed-off-by: Ben Clark <ben@benjyc.uk>

### CODE REVIEW

**Comment by JackTheDipper** [comment]
Hi, BClark09!

Thank you very much for this binding. I have one question concerning the underlying library: What is the reason to use this library compared to ConnectSDK [1]?
(ConnectSDK is an open source library that allows controlling/streaming to different devices, Supported are the following platforms: webOS, Roku, Chromecast, AppleTV, Amazon Fire, Sonos, XBox, LG TVs. And: There is already a connectsdk binding for openHAB, which, however, supports only controlling LG WebOS TVs, but no streaming so far.)

I don't know which library is easier to develop with. Just wanted to make sure that this library is not lost. ;-)

[1]: http://www.svlconnectsdk.com/

**Comment by BClark09** [comment]
Hi @JackTheDipper! I didn't make this binding, this was an openHAB contribution of @kaikreuzer and I just moved the library so that it used an original upstream of the same library instead of a fork. Kai might be able to answer your question better than I can!

**Comment by JackTheDipper** [comment]
Ah, thanks and sorry, @BClark09. ;-)

**Comment by kaikreuzer** [comment]
I have to pass on the kudos to @maggu2810 as I have built on top of [his work](https://github.com/maggu2810/shk/tree/master/bundles/shk-binding-chromecast) :-)

@JackTheDipper Regarding ConnectSDK: From what I can see, there is no Java library available. It targets mobile phone apps and thus supports Android, which builds on top of https://developers.google.com/cast/docs/downloads - which definitely isn't working on pure Java.

**Comment by JackTheDipper** [comment]
Heh, next time I'll dig deeper into the commit logs. ;-)

@kaikreuzer Yeah, that was my finding as well when I was considering to build a connectsdk binding for openhab. However, to me, it looks like @sprehn's connectsdk binding does contain a connectsdk java libary [1]. I wouldn't imagine that google's cast library is used as connectsdk is developed by LG to build webOS apps and supports other platforms like airplay, too. But in order to be sure, I'll contact @sprehn.

[1]: https://github.com/sprehn/openhab2-addons/tree/master/addons/binding/org.openhab.binding.connectsdk/src/main/java/com/connectsdk

**Comment by sprehn** [comment]
Hi @JackTheDipper ,connectsdk lib in my binding is a fork from the LG project. I adapted the android interfaces so that I could merger future upstream versions. The LG project seems to be abandoned now, so I started to remove android dependencies in my own connect sdk fork.  Gave a more detailed answer in my thread on the connect sdk binding.

**Comment by JackTheDipper** [comment]
Hey, @sprehn, this sounds great!
(Just for the record, the corresponding thread is here: https://community.openhab.org/t/connect-sdk-binding-for-lg-webos-tvs/4726/139 )

What do you think, would it be much work to make the connectsdk binding including your libary fork, once it is ready, work as an audio sink (for webos, chromecast, apple tv, etc.) in openhab?

**Pull request merged**
