### PR TITLE
Fix running mvn license:format on tycho pom.

### PR DESCRIPTION
**Pull request by Hilbrand**
With adding bnd build structure the formatting of licenses seem to be broken. This change tries to fix that. With this change you can update the license by running from the root directory:
`mvn license:format -pl :<artifactId>`

I'm not sure if my proposed solution is the correct one. It does work.

### CODE REVIEW

**Comment by maggu2810** [comment]
I assume we could also move `src/etc/NOTICE` to `NOTICE`.

If this fixes the issues, then we need to apply the same changes for the bnd parent pom.
Do people really use Maven's project argument?

We could also add the license execution to the POM in the base.
So if you call `mvn license:format` in the root directory of the repo all files gets updated.

This will not allow to limit to use a specific project, but it should work for the whole repo.
And we do not need to change the bnd and tycho pom...

Whatever you prefer.

**Comment by wborn** [comment]
With #5072 the builds use a single reactor again. So maybe it's also possible to adapt the POMs such that the command can be run at the repository root?

**Comment by Hilbrand** [comment]
AFAIK the NOTICE in `src/etc` is only used by the skeleton scripts to copy this repository specific NOTICE files to a generated binding project. This was relevant when ESH used a different license. With a new maven generator project this file might not be needed here. So I left it untouched here to not change other things too.

I tried adding the configuration to the root pom, but that doesn't work and fails on the bundle projects. So I kept both configuration in the tycho and bnd pom files. Still when running from root it will fail at the last project; the root pom. But does it's job. It also does runs on individual projects. But I have no idea to make it error free.

**Comment by davidgraeff** [comment]
@openhab/2-x-add-ons-maintainers I have reviewed a few bindings recently and a way to fix fix the license is desperately needed. Can we add this for the time being?

**Pull request merged**
