### PR TITLE
Removed Action class. This will be implemented in a separate bundle.

### PR DESCRIPTION
**Pull request by sprehn**
[lgwebos] Removed Action class. This will be implemented in a separate bundle.
Signed-off-by: Sebastian Prehn <sebastian.prehn@gmx.de> (github: sprehn)

### CODE REVIEW

**Comment by martinvw** [comment]
Thanks!

BTW I waited for the the build to be completed

**Comment by sprehn** [comment]
@martinvw on https://openhab.ci.cloudbees.com/job/openHAB-Distribution/ the last build seems to be #1​09​9 26.11.2017 01:19 which was before the binding merged. where could I find the latest build, and what determines when  a new snapshot version gets built?

**Comment by martinvw** [comment]
@kaikreuzer did you notice that the build server does not build anymore:

https://openhab.ci.cloudbees.com/job/openHAB-Distribution/

> #1​10​1 (pending—Builds currently disabled due to disk space quota full or subscription problems.)

**Comment by kaikreuzer** [comment]
Yes, noticed. Also tried to clean some space, but it seems it wasn't enough yet. Trying again harder...

**Pull request merged**
