### PR TITLE
[harmonyHub] fix for a not completed change in #2151

### PR DESCRIPTION
**Pull request by pail23**
only the xml was adapted in #2151 , but not the binding constant

Signed-off-by: Paul Frank <pail@gmx.net>

### CODE REVIEW

**Comment by martinvw** [comment]
It makes things match again, but why was the old one wrong, I don't like the new thinguid which comes from this: `harmonyhub:harmonyhub` @kaikreuzer @digitaldan @svilenvul 

Why was the old one fixed and should revert that fix or perform this PR

**Comment by martinvw** [comment]
@pail23 do you think that this causes https://github.com/openhab/openhab2-addons/issues/2166

**Comment by pail23** [comment]
Yes, I got the same error as in #2166. This error should be fixed by this PR (or by reverting the changes in #2151 related to the harmony binding)

**Comment by kaikreuzer** [comment]
I think the correct fix would indeed be the revert of [this line](https://github.com/openhab/openhab2-addons/pull/2151/files#diff-d63cc266785e6cb988afe4e2c8d88820L7) - the bridge type id of the hub seems to be "hub" as this is also referenced from the child things. @svilenvul, I assume that change was a mistake in #2151?

**Comment by svilenvul** [comment]
> I think the correct fix would indeed be the revert of this line - the bridge type id of the hub seems to be "hub" as this is also referenced from the child things. 

The child things are [referencing](https://github.com/MusalaSoft/openhab2-addons/blob/b9dc3588edf667f33ead2244a24d574995972d52/addons/binding/org.openhab.binding.harmonyhub/ESH-INF/thing/thing-types.xml#L33): 
```
 <supported-bridge-type-refs>
            <bridge-type-ref id="harmonyHub" />
 </supported-bridge-type-refs>
```
(and this was the state before #2151).

So we have two options:
- revert the change in the bridge-type id and change the above line to ..`<bridge-type-ref id="hub" />`..(which I start to think it may be the better option, but might cause conflicts with other bindings providing the same bridge-type id="hub"..);
OR;
- rename the binding constant, but as well update all places in the [README ](https://github.com/MusalaSoft/openhab2-addons/tree/b9dc3588edf667f33ead2244a24d574995972d52/addons/binding/org.openhab.binding.harmonyhub#channels) and maybe other places that I have missed...

**Comment by kaikreuzer** [comment]
> The child things are referencing "harmonyHub"

Ah, I saw https://github.com/openhab/openhab2-addons/pull/2151/files#diff-5c9f63d8343fc882822747a681b3c6e1 and thought it is "hub" - but I didn't see that this was a change to hdpowerview...

As the README uses "hub", I think option 1 is the preferred one as this seems to be the original intention of the author.

**Comment by digitaldan** [comment]
Sorry I'm late to the party, it should be indeed "hub" , I see where the confusion is however, I wonder why the incorrect "bridge-type-ref" value in the XML has not caused any issues?  I appeared to make this mistake on the initial commit of this file, thanks for finding it btw.

**Comment by pail23** [comment]
OK, I changed it to "hub"

**Comment by martinvw** [comment]
LGTM

**Comment by digitaldan** [comment]
👍

**Pull request merged**
