### PR TITLE
Replaced Arrays.asList with Stream.of.

### PR DESCRIPTION
**Pull request by Hilbrand**

### CODE REVIEW

**Comment by martinvw** [comment]
@openhab/2-x-add-ons-maintainers did you any successfull status reports of travis or Jenkins, it has been 3 hours.

**Comment by davidgraeff** [comment]
Something went wrong here with the CI's

**Comment by wborn** [comment]
Jenkins just has the long/slow build queue. Maybe Travis is MIA because of https://github.com/openhab/openhab2-addons/issues/4935?

**Comment by wborn** [comment]
Travis does work if I push to my own repos that also have Travis enabled:

https://travis-ci.org/wborn/openhab2-addons/builds/516337155?utm_source=github_status&utm_medium=notification

**Comment by martinvw** [comment]
> Jenkins just has the long/slow build queue. Maybe Travis is MIA because of https://github.com/openhab/openhab2-addons/issues/4935?

Yes, I checked to enable the Travis-ci.com but it complained that the old/legacy one already/ still enabled, maybe we should kill that one (first)

**Comment by davidgraeff** [comment]
In this other PR (https://github.com/openhab/openhab2-addons/pull/5405/checks) travis at least is registered on the checks page.

**Pull request merged**
