### PR TITLE
ZWave: Fixes default value for scale, adds scale to setpoints, fixes passing…

### PR DESCRIPTION
**Pull request by digitaldan**
… config_scale to converters.

Signed-off-by: digitaldan <dan@digitaldan.com>

### CODE REVIEW

**Comment by digitaldan** [comment]
@cdjackson, couple more thermostat fixes.  I'm still having trouble setting the conf_scale property in Habmin, doesn't seem to stick but no error is getting thrown.

**Comment by cdjackson** [comment]
> I'm still having trouble setting the conf_scale property in Habmin, doesn't seem to stick but no error is getting thrown

It's a problem in ESH - see here https://github.com/eclipse/smarthome/issues/1103

**Comment by cdjackson** [comment]
Hmmm - I just merged a bunch of changes that seems to conflict with some of this here - can you pull those over and update the PR?

**Comment by digitaldan** [comment]
My merge was fixing the same thing your merge did ;-)  This now adds the scale option to setpoints.

**Comment by cdjackson** [comment]
So did I add everything you’d also done? (I remember thinking I needed to add the option to the setpoint class, but forget if I did it!)

Is this still needed?

**Comment by digitaldan** [comment]
The only missing from you PR was adding the scale option to setpoints in the XML, thats all this PR does now.

**Comment by digitaldan** [comment]
@cdjackson , actually hold off from merging, I realize there one place that was missed.

**Comment by digitaldan** [comment]
I'm testing this now, but I think that's it!

**Comment by digitaldan** [comment]
everything looks good on my end, not sure what the build failure is from, jenkins says it passed, but the status ball is grey, not sure what that means.  Thanks again for all the work you have put into this.

**Comment by xsnrg** [comment]
https://openhab.ci.cloudbees.com/view/Pull%20Request%20Builds/job/PR-openHAB2-Addons/128/console
00:46:52.834  |  ERROR: Failed to parse POMs
00:46:52.834  |  java.io.IOException: Backing channel is disconnected.

It was aborted, does not say how or by whom, but it looks like it was successful until that point:

00:45:25.773  |  [INFO] Verification of feature openhab-binding-zwave/2.0.0.SNAPSHOT succeeded

**Comment by digitaldan** [comment]
Thanks @xsnrg !

**Comment by xsnrg** [comment]
For some reason it looks like it ran longer than previous builds.  I cannot see the job config, but it could be it hit a limit at 12 minutes? @kaikreuzer Is there such a thing?  Perhaps build #128 can be restarted if still needed.

**Comment by kaikreuzer** [comment]
I don't exactly know, @dvanherbergen set up the PR builds, but I think there was a build time limitation, yes.
@dvanherbergen Is there an easy way to retrigger a build of a PR?

**Comment by dvanherbergen** [comment]
There is no hard limit on PR builds. This looks like there was an infrastructure issue.
To retrigger a PR build, I usually amend my last commit (e.g. update a comment) and then push that change.

**Comment by digitaldan** [comment]
re-pushed the branch and all seem well, thanks.

**Pull request merged**
