### PR TITLE
Updated the openhabVersion in the skeleton scripts

### LINKED ISSUE #6609: New binding skeleton didn't work
It seems that after this [commit](
https://github.com/ConfusedTA/openhab2-addons/commit/676d69a20962a3073684c1950b85690d94871535), the new binding skeleton didn't work.

## Steps to reproduce:
- git clone https://github.com/openhab/openhab2-addons.git
- cd bundles
- ./create_openhab_binding_skeleton.sh MyNewBinding foo foo
- cd org.openhab.binding.mynewbinding
- mvn clean install -DskipTests -DskipChecks
image

I think it was caused by the pom.xml
## Difference:
new pom.xml:
image

pom.xml created by sketeton:
image

### PR DESCRIPTION
**Pull request by hyf980817**
Updated the openhabVersion in the skeleton scripts to fix #6609 

Signed-off-by: Yifeng Huang hyf980817@163.com

### CODE REVIEW

**Comment by cweitkamp** [comment]
This fix looks good. What was wrong with it?

**Comment by Hilbrand** [comment]
We can just reopen it and merge it I guess :smile: ?

**Comment by hyf980817** [comment]
image
Sorry, I was trying to fix DCO and I faied

**Comment by Hilbrand** [comment]
Thanks for this fix. You can also set the sign off in the description of this pull request.

**Comment by hyf980817** [comment]
> Thanks for this fix. You can also set the sign off in the description of this pull request.
Thanks for your advice , actually this is my first time contributing to a project in Github😄

**Pull request merged**
