### PR TITLE
[RFXCOM] Ported the support for IT message on Lighting5

### LINKED ISSUE #1019: [RFXCOM] New PacketType: IT
I have some Flamingo FA500 switches lying around that are supported by the RFXCOM device through the IT protocol. It would be great if the binding will support that protocol, too.

Product page:
http://www.elro.eu/en/products/cat/flamingo/electricite/wireless-control-flamingo/2-switches-with-remote-control6

RFXtrx User Guide (see: 2.2.2. Alphabetic list):
http://www.rfxcom.com/WebRoot/StoreNL2/Shops/78165469/MediaGallery/Downloads/RFXtrx_User_Guide.pdf

Reverse engineering for Arduino:
**rf433 code for ELRO Flamingo home devices (FA500)**
https://forum.arduino.cc/index.php?topic=201771.0
##

### PR DESCRIPTION
**Pull request by martinvw**
Fixes #1019 

Signed-off-by: Martin van Wingerden <martinvw@mtin.nl>

### CODE REVIEW

**Comment by martinvw** [comment]
@Jamstah sorry one more, forgot to mention your name

**Comment by Jamstah** [comment]
Same changes as from v1? Or is this a different message type?

Either way, approach was validated last time, and the code LGTM for this one.

**Comment by martinvw** [comment]
Same as for v1, thanks again for your time!

2016-12-21 14:04 GMT+01:00 James Hewitt <notifications@github.com>:

**Comment by martinvw** [comment]
@kaikreuzer Merry Christmas and I just validated that I can also switch my Christmas lights with OH2 and this version 👍

**Comment by kaikreuzer** [comment]
Sounds wonderful, many thanks to all of you :-)

**Pull request merged**
