### PR TITLE
This PR adds radiation calculation (in W/m2) to the Astro Binding.

### PR DESCRIPTION
**Pull request by clinique**
New channels are :
 * direct radiation : heat level provided directly by the sun in W/m²
 * diffuse radiation : heat level provided through the atmospheric and cloud layer
 * totale radiation level

It adds an altitude (optional) configuration item.

Signed-off-by: Gaël L'hopital <glhopital@gmail.com>

### CODE REVIEW

**Comment by hakan42** [comment]
Could you please rename "totale" to "total" in all the sources, including the example in the README.md ? This would be the proper spelling in english:

https://translate.google.com/#fr/en/totale

**Comment by clinique** [comment]
Yes, obviously

**Comment by gerrieg** [comment]
@clinique 
You must add the three radiation properties to the [positionalChannelIds in the SunHandler](https://github.com/clinique/openhab2-addons/blob/0354f6e511b4e48ce202172c8af504c2d8f96ee4/addons/binding/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/handler/SunHandler.java#L32)
Otherwise the positional job won't start, if only a radiation property is linked to an item.

Everything else lgtm

**Comment by clinique** [comment]
@gerrieg, @kaikreuzer  : sorry, I did not solve the conflicts on the readme.md file :(

**Comment by kaikreuzer** [comment]
@clinique Then please do whenever you find the time for it :-)

**Comment by kaikreuzer** [comment]
You may want to run the auto code formatter first as @gerrieg just applied it on some other PR on parts of the code - this might be some source of your troubles...

**Comment by clinique** [comment]
Commit now seems fine, but I'm not able to squash it :( Can you ...please... merge it , I can no more spend time on this.

**Comment by kaikreuzer** [comment]
There are still some problems with tabs vs. spaces in the XMLs, but let's ignore that for now - the rest looks good, so let's merge. Thanks!

**Comment by clinique** [comment]
You're thanked ! I was going crary with these merge conflicts

**Pull request merged**
