### PR TITLE
[onkyo] bring back Album Art URL channel

### PR DESCRIPTION
**Pull request by marcelrv**
This channel got lost in the previous onkyo album art PR
To be used for UI's that don't support image Itemtype yet (basic/classic)

### CODE REVIEW

**Comment by lolodomo** [comment]
LGTM except one thing: refresh command is not handled by the new channel.

**Comment by marcelrv** [comment]
Indeed, I was doubting about it, as it would possibly trigger twice the data pull (due to the 2 types of album art channels).
Anyway, indeed if one would only use basic/classic UI, the other channel would not be included and the refresh would not be triggered

**Comment by lolodomo** [comment]
@marcelrv :  you should first check if the channel is linked in handleCommand. If not, do nothing. That way, no risk to request data for mothing.

**Comment by marcelrv** [comment]
@lolodomo how you mean, does the fact that the channel trigger a REFRESH in handlecommand not automatically mean that it is linked?

**Comment by watou** [comment]
> you should first check if the channel is linked in handleCommand. If not, do nothing. That way, no risk to request data for nothing.

Note that if no client is observing the image item, the data pull is still for nothing, even if the channel is linked.

**Comment by lolodomo** [comment]
Refresh command is sent to all channels, either linked to an item or not.

**Comment by kaikreuzer** [comment]
Really? No, it should imho only be sent to linked channels.

**Comment by lolodomo** [comment]
I have a doubt now. That is to be checked.

**Comment by marcelrv** [comment]
I did small test, and as far as I can see it only refreshed linked channels

**Comment by lolodomo** [comment]
So in this case, LGTM

**Pull request merged**
