### PR TITLE
Weather binding

### PR DESCRIPTION
**Pull request by pinkfish**
Ported the weather binding over to openhab 2.0.  This is mostly just a shim around the existing code which is pretty nicely structured overall.

### CODE REVIEW

**Comment by kubawolanin** [comment]
FYI: @lolodomo works on [Weather Underground binding](https://github.com/eclipse/smarthome/pull/2748) on ESH as well.

**Comment by lolodomo** [comment]
It was concluded that we need one binding per weather provider.
https://github.com/eclipse/smarthome/issues/2649

**Comment by pinkfish** [comment]
Ah. Interesting.  How far along are you with the wunderground binding?

**Comment by lolodomo** [comment]
The wunderground binding is finished for me except the documentation in which I have to add full examples (items, sitemap). I am waiting for a reivew and merge of my PR.
One or two additional data provided by wunderground service could be made available additionally by the binding.

if you read the full discussion about weather data integration in ESH, you will discover that several underlying subjects are pending (or in stand-by):
* defining system channels (I made proposals that were not validated) that could then be used by any weather binding
* integrationg a unit management feature in the ESH framework that will then avoid multiplying the channels in the weather bindings
* adding weather icons and access them in the bindings

**Comment by pinkfish** [comment]
Yes, I read through the bug.  We can checkin without resolving those issues right?  We don't need the icons or the system channels at the very least.  The unit management piece sounds like quite a large piece of work, I think we choose a unit, like Celsius, and do everyhing in that.  If you want to convert, you should do the conversions on the edge.  Eg: all the data inside of the system should be celcius and then UX can convert temperatures from C to F if needed when displaying to the user, or in a rule.  Keep the conversions localized to the edges.  Otherwise you end up with a mess in the middle of different units.

**Pull request closed without merging**
