### PR TITLE
migrate atlona to bnd

### PR DESCRIPTION
**Pull request by J-N-K**
Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by J-N-K** [comment]
@tmrobert8, I can't request a review from you. Could you have a look here? Thanks.

**Comment by tmrobert8** [comment]
I can if you can give me a quick overview of what is happening (haven't been able to follow all the discussions on this).  Plus it would help me in migrating my sony addons (which I'm going to be committing after all this falls out) to the new style as well...

**Comment by J-N-K** [comment]
@tmrobert8: We are moving the Openhab build system from Tycho to BND. You can find mit information in #5005

**Comment by wborn** [comment]
Are you OK if we merge the PR @tmrobert8 ?

**Comment by tmrobert8** [comment]
Yep

**Pull request merged**
