### PR TITLE
Revert "Revert "removed homematic binding""

### PR DESCRIPTION
**Pull request by kaikreuzer**
See also https://github.com/openhab/openhab-distro/pull/734

Reverts openhab/openhab2-addons#3703

### CODE REVIEW

**Comment by wborn** [comment]
I hope this doesn't revert too much because of all those other commits that show up. Is that just some issue in the GitHub UI or did you modify the PR afterwards? The changed files look good though! :-)

**Comment by kaikreuzer** [comment]
Yeah, that always happens when using the "revert" button in Github - but as you should anyhow squash on merge, the content is what counts!

**Comment by wborn** [comment]
Thanks! Also for the new ESH stable. The other commits are indeed still there.

**Comment by kaikreuzer** [comment]
Indeed - assuming that change was on purpose by @maggu2810, could you come up with an easy adaption for the test?

**Comment by wborn** [comment]
I'll have a look.

**Comment by maggu2810** [comment]
Yes, it has been done on purpose, see:
https://github.com/eclipse/smarthome/pull/5838#issuecomment-401627830

**Pull request merged**
