### PR TITLE
[KNX] Update `localSourceAddr` label & description

### PR DESCRIPTION
**Pull request by AngelosF**
Closes https://github.com/openhab/openhab2-addons/issues/4236

Signed-off-by: Angelos Fountoulakis agf@wired-net.gr (github: AngelosF)

### CODE REVIEW

**Comment by J-N-K** [comment]
Isn‘t „physical address“ a more common wording than „individual address“?

**Comment by lewie** [comment]
AngelosF is right, it is absolutelly no "Group Address" or GA.

Yes! localSourceAddr is the "device address" or (if there is a Hardware) „physical address“.
I would I would call it "local device address". So I can later change the internally used variable name to "localDeviceAddress"?!

**Comment by AngelosF** [comment]
"Official" terminology is: Individual Address

https://support.knx.org/hc/en-us/articles/115003185789-Individual-Address

Should I change it to "Local Device Address" @lewie ?

It would look like this:
```
<label>Local KNX Address</label>
<description>The Local Device Address in x.y.z notation for identification of this KNX/IP gateway within the KNX bus</description>
```

**Comment by lewie** [comment]
@AngelosF, you are right. 

http://knx.com.ua/attachments/article/132/KNX-basic_course_full.pdf
grafik

From ETS Interface we know:
grafik

The physical address or the simular individual address are both assigned to a device:
grafik

As a beginner in KNX, these naming is horrible! 
Yes, "physical address" is understandable, refers to a physical device. But what should "individual address" say? ;-)

The term "device" is easy to understand and pictorial. To help newbies, I suggest using all terms in the description. What would you say to:

```
<label>Local Device Address</label> or <label>Local KNX Device Address</label>
<description>The Physical Address (Individual Address) in x.y.z notation for identification of this KNX/IP gateway within the KNX bus</description>
```

Please excuse that this simple matter is now so complicated! ;-)

**Comment by AngelosF** [comment]
Thanx Lewie!  👍 

Closing this PR because I deleted by mistake my previous fork and I cannot edit the existing PR :(

New one: https://github.com/openhab/openhab2-addons/pull/4308

**Pull request closed without merging**
