### PR TITLE
Remove org.osgi.service.component.annotations import from manifests

### PR DESCRIPTION
**Pull request by wborn**
This is a WIP to remove the unnecessary org.osgi.service.component.annotations import from manifests (see #2880).

After the previous PR got merged Jenkins somehow generated an [online-repo](https://openhab.jfrog.io/openhab/webapp/#/builds/openHAB-Distribution/1096/1511563757684/published/org.openhab.distro:online-repo:2.2.0-SNAPSHOT) that had no generated XML files in the OSGI-INF directory of the JARs. On a local build the generated XML files are still properly added to JARs when the import is removed from the manifests.

As a test I've also added an empty "DsAnnotations" binding skeleton to this PR that does not have the import in its manifest to see if the Jenkins PR build adds the generated XML files to the JAR in [Artifactory](https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/).

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks! Once it is validated, you should remove the DsAnnotations bundle again from the PR.

**Comment by wborn** [comment]
As it seems this PR build did add a generated XML file to OSGI-INF in the [org.openhab.binding.dsannotations-2.2.0-SNAPSHOT.jar](https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.dsannotations/2.2.0-SNAPSHOT/org.openhab.binding.dsannotations-2.2.0-SNAPSHOT.jar).

Possible hypothesis:
* there is a configuration difference between the openHAB2-Bundles and PR-openHAB2-Addons build that can explain this. Running Maven with --debug could help with this.
* the (Jenkins) builds randomly don't add the generated XML (which we can test by retriggering this builds)

> Once it is validated, you should remove the DsAnnotations bundle again from the PR.

Yes that was exactly the idea. It would be nice to check for these regressions using some sort of unit test though. But I didn't quite manage to get DS components in a unit test from the bundle context. :-)

**Comment by martinvw** [comment]
> there is a configuration difference between the openHAB2-Bundles and PR-openHAB2-Addons build that can explain this. Running Maven with --debug could help with this.

I compared the configuration:

Both builds use latest Java 8 (although they are configure such that they don't need to end up on the same node, the PR builds are on nodes with the tag 'm1.small' the openHAB-Bundles for the distribution has no restriction set)

The PR build has a pre-step '# Bulk load maven repo' to get earlier downloaded compiled sources.

The PR builds are set to Maven 3.3.9 the distro to latest Maven.

The PR build has the goal:

`-DskipTests=true -DskipChecks=true clean install`

And has the setting 'Incremental build - only build changed modules' active

@kaikreuzer do you remember why tests are disabled for the PR build?

The other build has the goal:

`clean install -DskipChecks=true`

FTR `skipChecks` is there because the checks required more memory then we had available.

**Comment by kaikreuzer** [comment]
> @kaikreuzer do you remember why tests are disabled for the PR build?

Yes, because tests usually break when doing an incremental build.

**Comment by kaikreuzer** [comment]
But let's give it a new try then - @wborn please remove the test bundle and we can merge.

**Comment by martinvw** [comment]
> > @kaikreuzer do you remember why tests are disabled for the PR build?
>
>Yes, because tests usually break when doing an incremental build.

But that is of course not a problem because Travis does a normal build :-)

**Comment by wborn** [comment]
Thanks for having a look at the config @martinvw. 

I also tried to reproduce the issue locally with Maven 3.3.3 but it only failed **once** to generate the XML files once locally. That was when I just switched from Maven 3.5.0 to Maven 3.3.3 locally.

So I made some bash scripts that continuously rebuild this PR locally (with with Maven 3.3.3 and logging --debug output to a file). After each build it checks if the generated JARs contain the generated XML and it stops building when the files are missing. However it was still running this morning so what ever the issue is it is not easily reproducible on my system.

It would be interesting to know how often the issue reoccurs in the Jenkins builds. Maybe the openhab2-addons build that ended up in distro # 1096 was also a random failure. Perhaps the issue could also happen regardless of whether the imports are deleted from the manifest.

It could also be related to [FELIX-5451](https://issues.apache.org/jira/browse/FELIX-5451) that got fixed in v1.24.0 of the maven-scr-plugin.

**Comment by kaikreuzer** [comment]
> Maybe the openhab2-addons build that ended up in distro # 1096 was also a random failure

I doubt that it is a random failure (and I very much hope it isn't!).
I had changed the scr maven plugin config in the parent pom a few days before it failed, so I think that was related. I cannot tell why it now works, maybe some build still used an old snapshot of the pom or whatever. But if the builds now look good, I would dare to merge it.

Having some automated smoke tests one day would be wonderful, though. There is so much more that could be tested than just checking the existance of some XMLs ;-)

**Comment by wborn** [comment]
The similar upstream PR https://github.com/eclipse/smarthome/pull/4624 did not cause any mayhem. So I think we could give it another try here as well. :-)

**Comment by kaikreuzer** [comment]
Let's hope the best 🙄

**Comment by kaikreuzer** [comment]
Houston, we have a problem:

Latest distro #1108:
```
11:39:45.413 [ERROR] [org.openhab.binding.homematic        ] - Component descriptor entry 'OSGI-INF/*.xml' not found
```
Guess I have to again revert as a temporary measure 🙄

**Comment by wborn** [comment]
@kaikreuzer Would it be possible that the Jenkins distro build is somehow using local Maven repository artifacts from other (PR) builds that do not yet contain the necessary changes?

**Comment by kaikreuzer** [comment]
@wborn I just tried to figure out where the KAR packaging exactly takes the artifacts from. At least it seems that they do not care about a "-U" at all - so we do not necessarily see the latest versions, if there had been another build the same day already.

I have now reconfigured the distro build plan to use a private Maven repo that is cleared on every start and told it to resolve artefacts from our artifactory - let's see if that makes any difference...

**Comment by wborn** [comment]
Thanks for the perseverance on this! If the private repo fixes it, it will also fix other issues that seem to magically appear/disappear. I did notice that with removing the imports Eclipse now starts showing the related warning "DS Annotations missing from permanent build path".

**Comment by kaikreuzer** [comment]
Now that you say it, I see such warnings as well. @triller-telekom Are we missing any special IDE setting in the openHAB IDE here?

**Comment by triller-telekom** [comment]
In the ESH IDE I do get the very same warning for the Astro binding for example. But as you can see in the screenshot the xml files are generated.

image

**Comment by wborn** [comment]
It looks like the XML files are still properly being generated ever since the private repo was introduced. Do the other build jobs also use a private repo @kaikreuzer? A private repo may solve build issues for the other jobs as well.

**Comment by kaikreuzer** [comment]
@wborn FTR: It used to be generated ever since, unfortunately it wasn't generated for the 2.2.0 release build, which I have to fully discard now... So I guess we still need to figure out what exactly is happening here.

**Comment by kaikreuzer** [comment]
I've just tried to build the 2.2.0 tag on openhab2-addons locally on my machine. I also get 
```
[INFO] --- maven-scr-plugin:1.24.0:scr (generate-scr-scrdescriptor) @ org.openhab.binding.homematic ---
[WARNING] NoClassDefFoundError: org/osgi/service/component/annotations/Component
[WARNING] NoClassDefFoundError: org/osgi/service/component/annotations/Component
[WARNING] NoClassDefFoundError: org/osgi/service/component/annotations/Component
[WARNING] NoClassDefFoundError: org/osgi/service/component/annotations/Component
[WARNING] NoClassDefFoundError: org/osgi/service/component/annotations/Component
[WARNING] NoClassDefFoundError: org/osgi/service/component/annotations/Component
[WARNING] NoClassDefFoundError: org/osgi/service/component/annotations/Component
[WARNING] NoClassDefFoundError: org/osgi/service/component/annotations/Component
[WARNING] NoClassDefFoundError: org/osgi/service/component/annotations/Component
[WARNING] NoClassDefFoundError: org/osgi/service/component/annotations/Component
[WARNING] NoClassDefFoundError: org/osgi/service/component/annotations/Component
```
and no XMLs are generated. I really have no clue what to do anymore. Going to bed seems to be the only viable option right now :-(

**Comment by J-N-K** [comment]
This is really strange. I can‘t help much, but the XML for the binding.dmx.test isn‘t generated either, while it works for binding.dmx. It might be worth looking at that, even though I didn‘t find any difference.

**Comment by wborn** [comment]
That's really bad @kaikreuzer :-( Since it was a release you'd expect other builds generating SNAPSHOTS not to interfere at all. Do you see the necessary for generating XML in the artifacts used by your local build?

As I understand the sandbox build did continuously generate 2.2.0 artifacts so it may have been using an old artifact that it once build itself without the necessary changes. In Sonatype Nexus there is a setting that prohibits redeployment of new release artifacts. Perhaps Bintray/Artifactory also have one?

**Comment by martinvw** [comment]
@kaikreuzer @pfink maybe a really stupid question, but do all our build slaves use the same Maven versions? I saw that @wborn once mentioned that it only failed with an older maven version.

```
openhab
--
DEV@cloud (m1.small) | 2,000 min left
DEV@cloud (m1.large) | 500 min left
DEV@cloud (standard) | 844 min used
DEV@cloud (hi-speed) | 0 min used
DEV@cloud (small) | 725 min used
```

**Comment by kaikreuzer** [comment]
@J-N-K Is there an issue in ESH about that?

@wborn Bintray does not allow re-deployment, so all is clean. And I checked the logs and it shows indeed that the XMLs are not generated. Just as I can reproduce on my local machine.
Interestingly, for openhab-core and org.openhab.binding.zigbee, the XMLs WERE generated.

@martinvw Yes, they use the version that is configured in the build plan.

**Comment by martinvw** [comment]
Can we just revert this commit would that solve it for this release?

**Comment by kaikreuzer** [comment]
The release is already tagged and the master on 2.3.0-SNAPSHOT. So at the moment I would prefer to find out a way to make it correctly build that tag.

**Comment by wborn** [comment]
There is generated XML in JARs when I wipe my local .m2/repository/org/openhab, build the openhab-core 2.2.0 tag and then the openhab2-addons 2.2.0 tag.

**Comment by kaikreuzer** [comment]
@wborn Can you prove this by showing that you have something different than
```
[INFO] --- maven-scr-plugin:1.24.0:scr (generate-scr-scrdescriptor) @ org.openhab.binding.homematic ---
[WARNING] NoClassDefFoundError: org/osgi/service/component/annotations/Component
[WARNING] NoClassDefFoundError: org/osgi/service/component/annotations/Component
[WARNING] NoClassDefFoundError: org/osgi/service/component/annotations/Component
[WARNING] NoClassDefFoundError: org/osgi/service/component/annotations/Component
[WARNING] NoClassDefFoundError: org/osgi/service/component/annotations/Component
[WARNING] NoClassDefFoundError: org/osgi/service/component/annotations/Component
[WARNING] NoClassDefFoundError: org/osgi/service/component/annotations/Component
[WARNING] NoClassDefFoundError: org/osgi/service/component/annotations/Component
[WARNING] NoClassDefFoundError: org/osgi/service/component/annotations/Component
[WARNING] NoClassDefFoundError: org/osgi/service/component/annotations/Component
[WARNING] NoClassDefFoundError: org/osgi/service/component/annotations/Component
```
in your log?

> Interestingly, for openhab-core and org.openhab.binding.zigbee, the XMLs WERE generated.

Simple reason: The bundles in there still have the optional import in the manifest...

**Comment by J-N-K** [comment]
@kaikreuzer, no there is no issue. When discussing the DMX binding we decided to go with a static XML, since it is only a test package.

**Comment by wborn** [comment]
Yes I see the warnings but there still is generated XML in the JARs @kaikreuzer .

**Comment by kaikreuzer** [comment]
So are you completely sure that they do not already exist as ignored files in your OSGI-INF, because the IDE has generated them for you?

**Comment by wborn** [comment]
Hmm yes it must have been the IDE @kaikreuzer  :-(

**Comment by kaikreuzer** [comment]
I think I have a break-through: With [this commit](https://github.com/openhab/openhab2-addons/commit/f1e3ee7064ca97c828c1e474eed87da7bb5852ca), it now correctly generates the XMLs. I have only added that to the release tag for now, a proper solution will have to adjust the parent poms in openhab-core instead - but I won't touch them for the 2.2 release anymore.

Build and upload is just running - wish me luck!

**Comment by wborn** [comment]
That would be great! I was just checking the classpath of the plugin and also did not see such a dependency. At least the issue is now reproducible.

Here's the debug logging of the plugin if you didn't already have it (for historic reasons otherwise):

```
[INFO] --- maven-scr-plugin:1.24.0:scr (generate-scr-scrdescriptor) @ org.openhab.binding.nest ---
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=0, ConflictMarker.markTime=0, ConflictMarker.nodeCount=38, ConflictIdSorter.graphTime=0, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=20, ConflictIdSorter.conflictIdCycleCount=0,$
[DEBUG] org.apache.felix:maven-scr-plugin:jar:1.24.0:
[DEBUG]    org.apache.maven:maven-plugin-api:jar:2.0.7:compile
[DEBUG]    org.apache.maven:maven-archiver:jar:2.2:compile
[DEBUG]       org.apache.maven:maven-project:jar:2.0:compile
[DEBUG]          org.apache.maven:maven-profile:jar:2.0:compile
[DEBUG]          org.apache.maven:maven-model:jar:2.0:compile
[DEBUG]          org.apache.maven:maven-artifact-manager:jar:2.0:compile
[DEBUG]             org.apache.maven:maven-repository-metadata:jar:2.0:compile
[DEBUG]          org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-8:compile
[DEBUG]             junit:junit:jar:4.12:compile
[DEBUG]                org.hamcrest:hamcrest-core:jar:1.3:compile
[DEBUG]             classworlds:classworlds:jar:1.1-alpha-2:compile
[DEBUG]       org.codehaus.plexus:plexus-archiver:jar:1.0-alpha-7:compile
[DEBUG]       org.apache.maven:maven-artifact:jar:2.0:compile
[DEBUG]    org.apache.felix:org.apache.felix.scr.generator:jar:1.16.0:compile
[DEBUG]       org.ow2.asm:asm-all:jar:5.1:compile
[DEBUG]       org.osgi:org.osgi.core:jar:4.2.0:compile
[DEBUG]       org.osgi:org.osgi.compendium:jar:4.2.0:compile
[DEBUG]    org.sonatype.plexus:plexus-build-api:jar:0.0.7:compile
[DEBUG]       org.codehaus.plexus:plexus-utils:jar:1.5.8:compile
[DEBUG] Created new class realm plugin>org.apache.felix:maven-scr-plugin:1.24.0
[DEBUG] Importing foreign packages into class realm plugin>org.apache.felix:maven-scr-plugin:1.24.0
[DEBUG]   Imported:  < project>org.openhab.binding:org.openhab.binding.nest:2.2.0
[DEBUG] Populating class realm plugin>org.apache.felix:maven-scr-plugin:1.24.0
[DEBUG]   Included: org.apache.felix:maven-scr-plugin:jar:1.24.0
[DEBUG]   Included: org.apache.maven:maven-archiver:jar:2.2
[DEBUG]   Included: junit:junit:jar:4.12
[DEBUG]   Included: org.hamcrest:hamcrest-core:jar:1.3
[DEBUG]   Included: org.codehaus.plexus:plexus-archiver:jar:1.0-alpha-7
[DEBUG]   Included: org.apache.felix:org.apache.felix.scr.generator:jar:1.16.0
[DEBUG]   Included: org.ow2.asm:asm-all:jar:5.1
[DEBUG]   Included: org.osgi:org.osgi.core:jar:4.2.0
[DEBUG]    org.sonatype.plexus:plexus-build-api:jar:0.0.7:compile
[DEBUG]       org.codehaus.plexus:plexus-utils:jar:1.5.8:compile
[DEBUG] Created new class realm plugin>org.apache.felix:maven-scr-plugin:1.24.0
[DEBUG] Importing foreign packages into class realm plugin>org.apache.felix:maven-scr-plugin:1.24.0
[DEBUG]   Imported:  < project>org.openhab.binding:org.openhab.binding.nest:2.2.0
[DEBUG] Populating class realm plugin>org.apache.felix:maven-scr-plugin:1.24.0
[DEBUG]   Included: org.apache.felix:maven-scr-plugin:jar:1.24.0
[DEBUG]   Included: org.apache.maven:maven-archiver:jar:2.2
[DEBUG]   Included: junit:junit:jar:4.12
[DEBUG]   Included: org.hamcrest:hamcrest-core:jar:1.3
[DEBUG]   Included: org.codehaus.plexus:plexus-archiver:jar:1.0-alpha-7
[DEBUG]   Included: org.apache.felix:org.apache.felix.scr.generator:jar:1.16.0
[DEBUG]   Included: org.ow2.asm:asm-all:jar:5.1
[DEBUG]   Included: org.osgi:org.osgi.core:jar:4.2.0
[DEBUG]   Included: org.osgi:org.osgi.compendium:jar:4.2.0
[DEBUG]   Included: org.sonatype.plexus:plexus-build-api:jar:0.0.7
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:1.5.8
[DEBUG] Configuring mojo org.apache.felix:maven-scr-plugin:1.24.0:scr from plugin realm ClassRealm[plugin>org.apache.felix:maven-scr-plugin:1.24.0, parent: sun.misc.Launcher$AppClassLoader@5c647e05]
[DEBUG] Configuring mojo 'org.apache.felix:maven-scr-plugin:1.24.0:scr' with basic configurator -->
[DEBUG]   (f) generateAccessors = true
[DEBUG]   (f) outputDirectory = /home/wouter/git/openhab/openhab2-addons/addons/binding/org.openhab.binding.nest/target/classes
[DEBUG]   (f) project = MavenProject: org.openhab.binding:org.openhab.binding.nest:2.2.0 @ /home/wouter/git/openhab/openhab2-addons/addons/binding/org.openhab.binding.nest/pom.xml
[DEBUG]   (f) scanClasses = false
[DEBUG]   (f) skipVolatileCheck = false
[DEBUG]   (f) strictMode = false
[DEBUG]   (f) supportedProjectTypes = [eclipse-plugin]
[DEBUG] -- end configuration --
```

**Comment by martinvw** [comment]
@kaikreuzer that sounds great, keep us posted :-)

**Comment by kaikreuzer** [comment]
Build is done and published. Let's do some testing...

**Comment by wborn** [comment]
So far this 2.2.0 seems to work well for me with several bindings, KAR files and existing data. :+1: 

I only saw these exception when I first started the runtime:

```
12:02:35.900 [WARN ] [org.eclipse.smarthome.core           ] - FrameworkEvent WARNING - org.eclipse.smarthome.core
org.osgi.framework.ServiceException: Recursive ServiceFactory call in org.apache.felix.scr.impl.manager.SingleComponentManager.getService()
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:104) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:45) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:496) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:461) ~[?:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:619) ~[?:?]
	at org.apache.felix.scr.impl.manager.SingleRefPair.getServiceObject(SingleRefPair.java:72) ~[?:?]
	at org.apache.felix.scr.impl.inject.BindMethod.getServiceObject(BindMethod.java:651) ~[?:?]
	at org.apache.felix.scr.impl.manager.DependencyManager.getServiceObject(DependencyManager.java:2201) ~[?:?]
	at org.apache.felix.scr.impl.manager.DependencyManager$SingleDynamicCustomizer.prebind(DependencyManager.java:925) ~[?:?]
...
12:02:35.933 [WARN ] [org.eclipse.smarthome.core.autoupdate] - FrameworkEvent WARNING - org.eclipse.smarthome.core.autoupdate
org.osgi.framework.ServiceException: org.apache.felix.scr.impl.manager.SingleComponentManager.getService() returned a null service object
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:232) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:111) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:45) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:496) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:461) ~[?:?]

```

The second startup there were no exceptions.

**Comment by kaikreuzer** [comment]
Thanks for the feedback! I saw those as well once. Might file an issue on ESH later...

**Comment by kaikreuzer** [comment]
FTR, I created https://github.com/eclipse/smarthome/issues/4775 for it.

**Pull request merged**
