### PR TITLE
[hpprinter] HP Printer Binding initial contribution

### PR DESCRIPTION
**Pull request by Cossey**
**_I somehow stuffed up PR #4664 which contained the HP Printer Binding when I was rebasing and shifting code from one branch to another, apologies all._**

This is a binding for HP Printers using the printers _Embedded Web Interface_. It reads the following files on the printer for information:

```
http://<PrinterIP>/DevMgmt/ProductUsageDyn.xml
http://<PrinterIP>/DevMgmt/ProductStatusDyn.xml
```

It supports Dynamic Channels based on what data the Web Interface provides, uses the Shared Jetty Instance (HttpClient) and has simplified configuration (IP Address, Refresh intervals).

Binding supports auto-discovery using mdns/Bonjour (I used the the IPP binding auto-discovery as a guide on how to implement this).

Binding can be downloaded here: https://www.dropbox.com/s/tqxc57dgp74026o/org.openhab.binding.hpprinter-2.5.0-SNAPSHOT.jar?dl=1

### CODE REVIEW

**Comment by Hilbrand** [comment]
There is no need for opening a new pr, as that will loose all comments. Simply git reset --hard the original branch from this branch and push force to GitHub. That will cleanup your original branch.

**Comment by Cossey** [comment]
> There is no need for opening a new pr, as that will loose all comments. Simply git reset --hard the original branch from this branch and push force to GitHub. That will cleanup your original branch.

That doesn't seem to be working... and any changes I push to the branch on the previous PR is not being picked up by GitHub at all... and I've tried changing things and rebasing a few times to see if that it was something to do with that... it won't reset since its already pushed to origin and going back to a previous commit and trying to apply changes isn't doing anything. I can't even reopen the PR since it says there's no changes. 😢 

I didn't want to open a new Pull Request but I really don't know what to do here, if someone is willing to help then I am happy to put in a bit more time but this is starting to frustrate me now...

**Comment by mgeramb** [comment]
Hi Stewart,
I have dowloaded your new version and it works still fine with my HP LaserJet M15w printer. Thank you for your work! 
Best Michael

**Comment by Cossey** [comment]
Yay! First binding contribution done! I'll keep an eye out for any issues that someone may post in the future.

**Comment by cweitkamp** [comment]
Nice.

@kaikreuzer Can you please add @Cossey to the contributors team? Thanks.

**Comment by kaikreuzer** [comment]
Sure, done, thanks for the reminder! I should really remember to do it myself...

**Pull request merged**
