### PR TITLE
Update feature.xml

### PR DESCRIPTION
**Pull request by kgoderis**
Oceanic Binding missing

Signed-off-by: Karel Goderis <karel.goderis@me.com>

### CODE REVIEW

**Comment by kgoderis** [comment]
Check on Jenkins failed, but in the details on jenkins there is no trace of a problem?

**Comment by kaikreuzer** [comment]
> Maven JVM terminated unexpectedly with exit code 137

I think this might mean that the job was killed by Jenkins.
Never mind, it does not seem to be a problem with this PR.

**Comment by kaikreuzer** [comment]
This PR unfortunately broke the build - https://github.com/openhab/openhab2-addons/pull/1358 should hopefully fix it again.

**Comment by watou** [comment]
Does this feature depend on gnu.io but it's not included?

**Comment by watou** [comment]
Ah thanks.

**Pull request merged**
