### PR TITLE
VoiceRSS TTS: one voice per locale (fix #1418)

### LINKED ISSUE #1418: VoiceRSS TTS: voices
Following discussed issue https://github.com/eclipse/smarthome/issues/2453 , we need a voice per locale with a unique label.
@kaikreuzer @JochenHiller : I think it could be simply fixed by updating the methods getAvailableVoices() and getAvailableVoices(Locale locale) in class VoiceRSSCloudImplementation. The default voice for a locale could be named using "locale.toLanguageTag()" rather than a systematic name "default".

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39187839-voicerss-tts-voices?utm_campaign=plugin&utm_content=tracker%2F2164344&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F2164344&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by lolodomo**
Suppress the display of the API key from the log

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

PS: sorry I only updated few things but because the original source files have not the expected indentation, all appear as changed.

### CODE REVIEW

**Comment by lolodomo** [comment]
Of course I tested the change. You can now select and save the default voice in Paper UI. The console command "smarthome:voice say" works well (tested with a Sonos as sink), the right language is used.

**Comment by lolodomo** [comment]
Here is now the result of "smarthome:voice voices":
```
openhab> smarthome:voice voices
voicerss:default_frCA default_fr-CA (fr_CA)
voicerss:default_esMX default_es-MX (es_MX)
voicerss:default_enAU default_en-AU (en_AU)
voicerss:default_ptBR default_pt-BR (pt_BR)
voicerss:default_ruRU default_ru-RU (ru_RU)
voicerss:default_daDK default_da-DK (da_DK)
voicerss:default_enUS default_en-US (en_US)
voicerss:default_ptPT default_pt-PT (pt_PT)
voicerss:default_esES default_es-ES (es_ES)
voicerss:default_deDE default_de-DE (de_DE)
voicerss:default_nbNO default_nb-NO (nb_NO)
voicerss:default_zhCN default_zh-CN (zh_CN)
voicerss:default_frFR default_fr-FR (fr_FR)
voicerss:default_nlNL default_nl-NL (nl_NL)
voicerss:default_plPL default_pl-PL (pl_PL)
voicerss:default_enIN default_en-IN (en_IN)
voicerss:default_fiFI default_fi-FI (fi_FI)
voicerss:default_jaJP default_ja-JP (ja_JP)
voicerss:default_koKR default_ko-KR (ko_KR)
voicerss:default_svSE default_sv-SE (sv_SE)
voicerss:default_zhHK default_zh-HK (zh_HK)
voicerss:default_caES default_ca-ES (ca_ES)
voicerss:default_enCA default_en-CA (en_CA)
voicerss:default_itIT default_it-IT (it_IT)
voicerss:default_enGB default_en-GB (en_GB)
voicerss:default_zhTW default_zh-TW (zh_TW)
```

**Comment by kaikreuzer** [comment]
Thanks! Indeed the formatting of the initial contribution was wrong, this escaped me when I reviewed it. So nothing wrong with your PR when it shows everything as being changed.

May I suggest one improvement?
The "default_" for the voice id is redundant as we simply only have the one voice per locale.
So I'd suggest to simply have "voicerss:enGB" as the voice UIDs.
Then, the label should look nice in UIs. So instead of "default_en-GB (en_GB)", I would suggest to have "VoiceRSS English (Great Britain)" instead.

**Comment by lolodomo** [comment]
@kaikreuzer : ok for suppressing the "default_".

For the label in UI, can you tell me how it is built (what methods are called) ?
Currently, I get "default_fr-FR (français)". So after suppressing "default_", I will certainly get "fr-FR (français)" and so not exactly what you would expect.

**Comment by kaikreuzer** [comment]
I didn't check in detail, but I would have hoped that you can assemble as string like the one in my suggestion using the methods http://docs.oracle.com/javase/7/docs/api/java/util/Locale.html#getDisplayLanguage() and http://docs.oracle.com/javase/7/docs/api/java/util/Locale.html#getDisplayCountry().

**Comment by lolodomo** [comment]
I have now suppressed "default_" from the voice labels.
```
openhab> smarthome:voice voices
voicerss:enGB en-GB (en_GB)
voicerss:fiFI fi-FI (fi_FI)
voicerss:nlNL nl-NL (nl_NL)
voicerss:frCA fr-CA (fr_CA)
voicerss:deDE de-DE (de_DE)
voicerss:enIN en-IN (en_IN)
voicerss:zhHK zh-HK (zh_HK)
voicerss:daDK da-DK (da_DK)
voicerss:caES ca-ES (ca_ES)
voicerss:nbNO nb-NO (nb_NO)
voicerss:svSE sv-SE (sv_SE)
voicerss:enAU en-AU (en_AU)
voicerss:ptPT pt-PT (pt_PT)
voicerss:zhTW zh-TW (zh_TW)
voicerss:enCA en-CA (en_CA)
voicerss:zhCN zh-CN (zh_CN)
voicerss:enUS en-US (en_US)
voicerss:ruRU ru-RU (ru_RU)
voicerss:ptBR pt-BR (pt_BR)
voicerss:itIT it-IT (it_IT)
voicerss:plPL pl-PL (pl_PL)
voicerss:jaJP ja-JP (ja_JP)
voicerss:koKR ko-KR (ko_KR)
voicerss:esMX es-MX (es_MX)
voicerss:esES es-ES (es_ES)
voicerss:frFR fr-FR (fr_FR)
```
Remains to check how to adjust the label in Paper UI...

**Comment by lolodomo** [comment]
@kaikreuzer : the label displayed in Paper UI is nothing that is directly saved in the voice object. So I assume that Paper UI is building a label from the "voice" object and the "locale" of the "voice": first the voice label and then in parenthesis the full language of the locale.
If I am right, it is not something I can control.

**Comment by lolodomo** [comment]
Or maybe it is the REST API that is building the label shown in Paper UI ?

**Comment by kaikreuzer** [comment]
The label is provided by your service in [this line](https://github.com/openhab/openhab2-addons/pull/1421/files#diff-6606c1ac07d25fa304c62d5f5ff9c5c8R147).

**Comment by lolodomo** [comment]
This line just create a voice object with a label and a locale, it does not build the label displayed in Paper UI.

The best would be to check how Paper UI is retrieving voice data and how is built the list for the default voice config paramater.

**Comment by kaikreuzer** [comment]
>  it does not build the label displayed in Paper UI.

Are you REALLY sure? I very much doubt that. Try putting in "xyz" as a second parameter and see what happens.

**Comment by lolodomo** [comment]
Ok, I think I found where this label is built, that is by the voicemanager: https://github.com/eclipse/smarthome/blob/063326ce8e7aa8cc299d8c2370f8b1df38afb965/bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/internal/VoiceManagerImpl.java#L562 It corresponds exactly to what Paper UI is displaying.

**Comment by kaikreuzer** [comment]
Which means that it TAKES the label that I mentioned above, but it also already adds the language, right - so this might be duplicated with my suggestion. I think the correct solution would be to use the label as it is given in the Voice and make sure that these labels contain all relevant locale information when they are provided by the TTS services.

**Comment by lolodomo** [comment]
Of course the voice label was used but not alone.
Ok so first we have to update the voice manager to consider only the voice label.
And I can update the label of Voice RSS voices.
Voice labels of other TTS services have to be checked too.

**Comment by kaikreuzer** [comment]
> Ok so first we have to update the voice manager to consider only the voice label.

Maybe I was too quick on this. After all, the Voice interface has the "Locale" besides the Label. So in order to have the same mechanism in all TTS services, it would make sense to keep that in the VoiceManager, wdyt? What it currently does not cover is the case where a voice is available several times for the same language, but different countries; but it should be possible to check such a case in the VoiceManager and enhance the label in that case.

**Comment by lolodomo** [comment]
We have the choice. Maybe it is better to let the voice manager add the language + the country in parenthesis, this will make labels displayed by Paper UI more homogeneous over all TTS services. In this case, the TTS services have to build basic labels. The voice label for VoiceRRS would be only  "VoiceRSS". The voice manager will add " francais (France)".
I will have to update the code for the voice UID as it is currently based on voice label. No problem, I will use the locale.
I am waiting for your GO before going further.

**Comment by kaikreuzer** [comment]
> The voice label for VoiceRRS would be only "VoiceRSS". The voice manager will add " francais (France)".

Sounds like a good solution to me. If you like it too, feel free to go!

**Comment by lolodomo** [comment]
Done.
```
openhab> smarthome:voice voices
voicerss:frCA VoiceRSS (fr_CA)
voicerss:ptBR VoiceRSS (pt_BR)
voicerss:enAU VoiceRSS (en_AU)
voicerss:itIT VoiceRSS (it_IT)
voicerss:frFR VoiceRSS (fr_FR)
voicerss:zhHK VoiceRSS (zh_HK)
voicerss:plPL VoiceRSS (pl_PL)
voicerss:fiFI VoiceRSS (fi_FI)
voicerss:zhCN VoiceRSS (zh_CN)
voicerss:enUS VoiceRSS (en_US)
voicerss:esES VoiceRSS (es_ES)
voicerss:svSE VoiceRSS (sv_SE)
voicerss:koKR VoiceRSS (ko_KR)
voicerss:zhTW VoiceRSS (zh_TW)
voicerss:enGB VoiceRSS (en_GB)
voicerss:nlNL VoiceRSS (nl_NL)
voicerss:daDK VoiceRSS (da_DK)
voicerss:enIN VoiceRSS (en_IN)
voicerss:ptPT VoiceRSS (pt_PT)
voicerss:caES VoiceRSS (ca_ES)
voicerss:enCA VoiceRSS (en_CA)
voicerss:jaJP VoiceRSS (ja_JP)
voicerss:esMX VoiceRSS (es_MX)
voicerss:deDE VoiceRSS (de_DE)
voicerss:ruRU VoiceRSS (ru_RU)
voicerss:nbNO VoiceRSS (nb_NO)
```
Remains to update the voice manager because the label currently displayed by UI can be identical for several voices. Will require another PR in smarthome repo.

**Comment by kaikreuzer** [comment]
Thanks!
FYI: I have also just created https://github.com/eclipse/smarthome/pull/2470, so that the console shows the same as the Paper UI.

**Pull request merged**
