### PR TITLE
rfxcom.test: Add missing CP entry in .classpath

### PR DESCRIPTION
**Pull request by sja**
This line is added after fresh install with eclipse installer. Maybe one of those changes wich only appear after Eclipse IDE close+open projects.

### CODE REVIEW

**Comment by martinvw** [comment]
We don't have any groovy tests there why would this change be needed?

**Comment by martinvw** [comment]
Can't we convince eclipse not to add it?

**Comment by martinvw** [comment]
Let's just add it, next time that I'm working on the rfxcom tests I'll check why there is a reference to groovy 😊

**Comment by sja** [comment]
Yes, I also search for any Groovy reference but found none. But Eclipse is sure about that. 🙄

**Pull request merged**
