### PR TITLE
[onkyo] Add support for Onkyo HT-RC560.

### PR DESCRIPTION
**Pull request by Cossey**
Adds support for model HT-RC560 as requested via a post in #2922 by @dabbith 

Confirm working by user.

Signed-off-by: Stewart Cossey <stewart.cossey@gmail.com> (github: Cossey)

### CODE REVIEW

**Comment by Cossey** [comment]
Sorry guys originally merged online from this pull request area but couldn't update commit text with sign off so fixed it all offline with rebase and force push but looks like DCO didn't update at all.

**Comment by cweitkamp** [comment]
Hi @Cossey,

I guess the new [DCO](https://probot.github.io/apps/dco/) app has a problem with validating sign-offs containing the GitHub handle. Can you try to use only:

```
Signed-off-by: Stewart Cossey stewart.cossey@gmail.com
```

**Comment by Cossey** [comment]
Thanks @cweitkamp it seems like that's the problem. I used to manually sign off, but now the app I use can pass through the -s command to git so it signs off automatically (without the github handle).

The page [https://www.openhab.org/docs/developer/contributing/contributing.html]() states to include the github handle for the signed off by - should I open a new PR on openhab-docs correcting this or will the DCO config be changed in the future to be able to accept to the github handle? 

Thanks heaps!

**Comment by cweitkamp** [comment]
Yes. I second your opinion. I think it is superfluous. The github username is not part of the DCO anyways.

And I think @kaikreuzer (and team) too: (see https://github.com/openhab/openhab-core/pull/663#issuecomment-473331750).

I appreciate if you will take care of the documentation change. Please ping me for approval.

// CC @openhab/2-x-add-ons-maintainers @openhab/core-maintainers

**Pull request merged**
