### PR TITLE
[Nest] Bugfixes and improvements

### PR DESCRIPTION
**Pull request by wborn**
To get the Nest Binding working I had to make some bugfixes:
* The `HttpClient` is now started so HTTP requests are actually made :-)
* Obtaining  the access token with the pincode via HTTP did not work because the `NestBindingConstants.NEST_ACCESS_TOKEN_URL` was missing from the URL
* The access token stored in the file was overwritten with null when the request to obtain it via the pincode failed (which it always does after a second call because you can use the pin code only once)
* The access token could become null during initialization even though it was stored in the file

I've also corrected and tuned some logging to debug level.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks, @wborn!
@pinkfish fyi. Btw, please remember to update the README as requested on the initial PR :-)

**Comment by martinvw** [comment]
@wborn I still get an NPE when starting, any ideas?

```
2017-09-09 17:16:10.710 [ERROR] [nternal.DiscoveryServiceRegistryImpl] - Cannot trigger scan for thing types '[nest:structure, nest:camera, nest:thermostat, nest:smoke_detector]' on 'NestDiscoveryService'!
java.lang.NullPointerException: null
	at org.openhab.binding.nest.handler.NestBridgeHandler.compareThings(NestBridgeHandler.java:202) [214:org.openhab.binding.nest:2.2.0.201709071552]
	at org.openhab.binding.nest.handler.NestBridgeHandler.refreshData(NestBridgeHandler.java:178) [214:org.openhab.binding.nest:2.2.0.201709071552]
	at org.openhab.binding.nest.handler.NestBridgeHandler.startDiscoveryScan(NestBridgeHandler.java:339) [214:org.openhab.binding.nest:2.2.0.201709071552]
	at org.openhab.binding.nest.discovery.NestDiscoveryService.startScan(NestDiscoveryService.java:61) [214:org.openhab.binding.nest:2.2.0.201709071552]
	at org.eclipse.smarthome.config.discovery.AbstractDiscoveryService.startScan(AbstractDiscoveryService.java:200) [98:org.eclipse.smarthome.config.discovery:0.9.0.201709071501]
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScan(DiscoveryServiceRegistryImpl.java:399) [98:org.eclipse.smarthome.config.discovery:0.9.0.201709071501]
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScans(DiscoveryServiceRegistryImpl.java:384) [98:org.eclipse.smarthome.config.discovery:0.9.0.201709071501]
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScan(DiscoveryServiceRegistryImpl.java:228) [98:org.eclipse.smarthome.config.discovery:0.9.0.201709071501]
	at org.eclipse.smarthome.io.rest.core.discovery.DiscoveryResource.scan(DiscoveryResource.java:86) [118:org.eclipse.smarthome.io.rest.core:0.9.0.201709071501]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
```

**Comment by martinvw** [comment]
It returns `null` for devices I don't have, I will add null checks.

**Comment by wborn** [comment]
I can't reproduce this exception @martinvw . Not even when I disable all of the device permissions. But then again I have most of their devices. ;-) So far I've only tested the binding with UI based configurations.

**Comment by martinvw** [comment]
That explains it 😉 

It works now, will create a PR later:

```
2017-09-09 18:14:46.662 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'nest:smoke_detector:1d463929:hagR1ousC1RPdYPy7A7_LlPBtG5BVEFV' to inbox.
2017-09-09 18:14:46.676 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'nest:structure:1d463929:PHSZLHFXjrEIIsPQDYiZXqAnyD8NCQQHP87v_nHOFj0mN6Zsjvahsw' to inbox.
```

**Pull request merged**
