### PR TITLE
[timer] Timer Binding initial contribution

### PR DESCRIPTION
**Pull request by foxy82**
Created a pull request as requested by: hakan

This is a new binding that allows timers to be setup as Things in the UI. Meaning that timers can be moved out of rules.

Currently a work in progress this is a very early alpha state to allow testing and feedback by the community.

Note: Currently a lot of tidy up is needed before this can be merged.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Could you point us to any discussion on the forum about that feature?
This is clearly nothing that I would think should be done as a binding - it rather sounds like a candidate of a rule trigger module for the new rule engine.

**Comment by kubawolanin** [comment]
@kaikreuzer I believe it's this thread:
https://community.openhab.org/t/new-binding-timer-scheduling-binding/29034/5

**Comment by Misiu** [comment]
@foxy82 anything going on here?
I'm looking for a way to add scheduling to UI. I can help with testing and with UI (js).
Can additional changes (not related to this binding) be removed from this PR? It's terrible to review changes.
@kaikreuzer what new rule engine are You writing about?

**Comment by foxy82** [comment]
Hi. I've moved away from openhab to home assistant (https://www.home-assistant.io) which already supports scheduling via the UI. So I'm not working on this anymore. 

The other things in the pull request are merges from master.

**Comment by Misiu** [comment]
@foxy82 thanks for quick reply.
I'll take a look at home assistant.
Lack of scheduling via UI is a really big feature missing in OpenHAB

**Comment by foxy82** [comment]
@Misiu https://www.home-assistant.io/components/input_datetime/ 

It looks like this: 

image

image

image

**Comment by Misiu** [comment]
@foxy82 I am looking for something [like this](https://github.com/SUPLA/supla-cloud/issues/152).

My idea is to allow basic scheduling for:
-garden sprinklers (on/off on specific time and specific day of week)
-temperature (each room must have weekly scheduler with temperatures specified)

Do You think this is doable HA?

**Comment by davidgraeff** [comment]
I'm closing this, as we will now use the new rule engine for timing related tasks.

**Comment by Misiu** [comment]
@davidgraeff could You pint me to more information about new rule engine? My idea (and my wife demand before I can move everything to OpenHAB) is to be able to simply change scheduler via UI, something like [this](https://github.com/SUPLA/supla-cloud/issues/152).
There is a thread on forum related to timing/scheduling binding and UI related with it (https://community.openhab.org/t/new-binding-timer-scheduling-binding/29034).

**Comment by davidgraeff** [comment]
The concepts are all implemented. The rule engine requires a few more advanced time triggers, but that's what I'm tackling next. The initial proposal was using Things+Channels because that is what you can edit with Paper UI. But Paper UI is officially unmainted and different people are working on replacements.

You can check out my suggestion: https://davidgraeff.github.io/paperui-ng. You will find time related tasks in the "Scheduler" page. I'm updating every Friday, the next release will change that page to a calendar overview. But still you get the idea.

**Comment by Misiu** [comment]
@davidgraeff thank You for the update :)
This already looks amazing, but as I mentioned this is for more advanced users (I think PaperUI is for advanced users).
Do You think than simple scheduler editor could be added to Basic UI?
An example could be changing the temperature in the thermostat or when watering must be done in the watering system.

**Comment by davidgraeff** [comment]
@Misiu For OH3 there is a general overhaul of the UI landscape planed. Basic UI, classic UI, modern UI, Paper UI control will all be merged into an exiting new control UI. And that one will probably support new concepts like Scenes and "Alarms". So I guess you still have to wait a bit unfortunately.

**Comment by Misiu** [comment]
@davidgraeff all is going in a good direction :)
I must find a good course on web development, so I'll be able to join the effort of creating such controls.

**Pull request closed without merging**
