### PR TITLE
Migrate HarmonyHub to bnd and infra for adding libraries to bundles

### PR DESCRIPTION
**Pull request by wborn**
This PR uses the bnd [includeresource](https://bnd.bndtools.org/instructions/includeresource.html) option which allows for adding library JARs to bundles without having to create bundles or adding them to Maven repositories. This could simplify the bnd migration since we don't need to add JARs to repos at the same time.

I don't like all the juggling with properties and rather use a bnd.bnd file to override just parts of the main bnd configuration. Maybe that's also possible with spending some more time on it.

bnd inspects the bytecode of JARs and adds imports for packages. Some of these are not used for this binding so I had to add an additional property for making these imports optional.

WDYT of this solution @openhab/2-x-add-ons-maintainers ?

### CODE REVIEW

**Comment by davidgraeff** [comment]
I like the solution

**Comment by J-N-K** [comment]
This is also a solution for allplay. I think for libraries that are specific to one bundle and not available on bintray this might be a good solution. 

I agree with @maggu2810 that we should use proper dependencies for libraries that are available. And including CXF in the /lib folder (like in Helios) doesn‘t seem to be a good idea.

**Comment by cweitkamp** [comment]
:+1:

Just to clarify: After this PR will be merged we can use the includeresource option in other bindings. Meaning: we simply have to create a `lib/` folder and put all external JARs into it? Is that correct? Sounds good. If so we should add it to the migration manual in #5005.

**Comment by wborn** [comment]
That's right, the profile is activated based on the presence of a `lib` directory so it should work automatically when the directory is migrated with the projects. 

The [addjars-maven-plugin](https://code.google.com/archive/p/addjars-maven-plugin/) adds the libraries to the classpath at compile time during a Maven build. Using bnd includeresource the libraries are added to the bundle and the manifest is updated accordingly. After importing a project in Eclipse the libraries should still be manually added to the Eclipse classpath to make it compile.

Karaf feature validation may fail if there are no bundles for all generated package imports from the libraries. If you're really sure these are unneccessary you can make these optional using the property in the add-on POM.

I also agree we should only use this if libraries are not easiliy available through other means. It's still preferred that contributors adapt their libraries and publish them so they an be added using Maven/Karaf dependencies.

**Comment by mhilbush** [comment]
@wborn I tried this out on one my WIP bindings, and I'm getting the error shown below. I'm running the build on Windows, which may explain why the directory path separators are missing. I don't now how to fix this (other than switching my build environment 😄 ). Any ideas?

The binding is [here](https://github.com/mhilbush/openhab2-addons/tree/doorbird-binding-bnd/bundles/org.openhab.binding.doorbird).

```
[ERROR] C:\Users\mark\openhab2-addons\bundles\org.openhab.binding.doorbird\target\com.googlecode.addjars.mojo.AddJarsMojo\pom.xml [0:0]: Input file does not exist: C:Usersmarkopenhab2-addonsbundlesorg.openhab.binding.doorbird/lib/
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.984 s
[INFO] Finished at: 2019-03-22T07:56:43-04:00
[INFO] Final Memory: 22M/365M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal biz.aQute.bnd:bnd-maven-plugin:4.2.0:bnd-process (default) on project org.openhab.binding.doorbird: Input file does not exist: C:Usersmarkopenhab2-addonsbundlesorg.openhab.binding.doorbird/lib/ -> [Help 1]
```

**Comment by wborn** [comment]
I could reproduce the issue @mhilbush and made a fix for it in https://github.com/openhab/openhab2-addons/pull/5196.

**Comment by mhilbush** [comment]
@wborn Thanks! Confirming the fix resolved the issue for me.

**Comment by swamiller** [comment]
@mhilbush 
Sorry to hijack this merged issue, but any chance your Doorbird binding might become public at some point?

**Comment by mhilbush** [comment]
@swamiller I should have something for you to try out in a couple days. I need to write the README. The only thing I'm not sure about is whether the libsodium crypto library will run on a pi (this lib is needed to decrypt the event stream from the device). So, if you're running on a pi, I guess we'll find that out soon enough... If it's ok, I'll ping you on the forum.

**Comment by swamiller** [comment]
@mhilbush The forum is fine. I know there is a Doorbird thread there but you haven't been a participant so I didn't want to throw you in there if you didn't have intentions of sharing your binding.  The github venue is a bit off the beaten path.  And for the record,  I run OH on an Ubuntu VM, not a pi.  I kept having reliability/stability issues with OH on a pi.  My VM has proven extremely stable.

**Pull request merged**
