### PR TITLE
Resolve issues with MiLight bulbs (Fixes #1572)

### LINKED ISSUE #1572: [Milight] OH2 cannot change brightness for white bulbs
Setting the brightness for white bulbs doesn't seem to be working.

Decreasing the brightness from 100℅ results in the bulb turning off. Increasing the brightness from 0% doesn't result in the bulb turning on (unless it's to 100%).

Looking at the code for MilightCommunication the calls to increaseBrightness/decreaseBrightness are passing -1 for the oldPercent parameter which seems to be the cause of the problem.

### PR DESCRIPTION
**Pull request by MikeJMajor**
Fixed the ability to set the brightness for white bulbs. The brightness setting for white bulbs and RGBW bulbs has been aligned (previously a very low percentage would have resulted in a white bulb being off which seemed inconsistent with RGBW bulbs).

Fixed setting colour temperature for white bulbs.

Fixed disco mode for RGBW bulbs.

Fixed issue with wrong RGBW bulb changing brightness (due to missing sendOn commands)

### CODE REVIEW

**Comment by MikeJMajor** [comment]
Please wait with the review. There are still some issues with the wrong RGBW  bulbs changing brightness which I need to look into.

**Comment by MikeJMajor** [comment]
Ready for review.

**Comment by davidgraeff** [comment]
@MikeJMajor: The changes look good.
Some notes that came to my mind:

- You introduced a lot more sleep(100) commands. Is this really necessary? Even if the old bridges wouldn't be able to receive more than 10 commands a second, I'm not so sure about the newer variants.
- You removed the handling of DecimalType in favour of IncreaseDecreaseType and PercentType. This is fine, but you may break old setups with this. Can't you just handle DecimalType as well?

**Comment by MikeJMajor** [comment]
@davidgraeff : Thanks for the review.

The change from DecimalType to PercentType has been on the back of my mind so I'll make a change to support both.

Most of the additional sleep(100) calls are associated with an additional call to setOn. Looking at the milight API and various other implementations it looked like you should always send the on command and wait 100ms before sending another command, e.g. brightness.

For changing brightness I had bulbs from other channels changing brightness at the same time which the extra call to setOn resolved.  The setColor method previously only had a 50ms wait, but for me setting a bulb which was off to a colour didn't work 50% of the time  (turned on but didn't change colour) which now works 99% of the time with a 100ms wait.

I'm not sure if the 100ms wait is needed for the bridge or the actual bulb, but for me it works a lot more reliably with the extra calls to setOn and sleep(100). Are there any sleep(100) calls which you think can be removed?

Mike

**Comment by davidgraeff** [comment]
Hm, I think for now we just go with the sleeps. What bothers me is, that the main addon thread sleeps quite often now and if the user slides over a color fader, he will probably issue a lot of commands. Instead of just using the last command, the addon will now apply one command after the other in a 1/10s step even if the user released all buttons already. 

I will introduce a smarter way of handling the necessary wait between commands in a separate pull request later if time permits.

**Comment by MikeJMajor** [comment]
I've swapped the use of PercentType back to DecimalType to maintain backwards compatibility and also added back StringType support for setting disco mode.

**Comment by davidgraeff** [comment]
@kaikreuzer This pull request can be merged :)

**Pull request merged**
