### PR TITLE
[nibeuplink] Change airsupply to watersupply for the ground water bas…

### PR DESCRIPTION
**Pull request by uqs**
…ed heat pumps

Air supply makes little sense on the F1145 to F1255 heat pump models.
They are ground source heat pumps, so add the temperature for the brine
in/out instead.

Note: we could change AIRSUPPLY to a more generic SUPPLY instead, let me
know if this is desired instead.

Signed-off-by: Ulrich Spörlein <uspoerlein@gmail.com>

### CODE REVIEW

**Comment by uqs** [comment]
tagging @alexf2015

**Comment by alexf2015** [comment]
> 
> 
> tagging @alexf2015

I disagree, the mentioned channels exist but in general (also for VVM models) are only available if a ERS air ventilation unit is attached. So it does not make any sense to replace channels.
In addition the brine in/out channels are already added in my latest dev version. Please see here: https://community.openhab.org/t/nibe-uplink-binding/25756

**Comment by uqs** [comment]
I wasn't aware of the changes in the DEV version. As long as I can get the brine temp in degrees and not decidegrees, I'm happy.

Do you also have plans to support the brine pump frequency directly? The remaining custom channels that I have are for the speed of the pump for the heat medium, as well as the cold medium.

**Comment by alexf2015** [comment]
> Do you also have plans to support the brine pump frequency directly? The remaining custom channels that I have are for the speed of the pump for the heat medium, as well as the cold medium.

We should discuss that in the community thread.

**Comment by uqs** [comment]
Hey Alex, I've now finally updated to OH2.5, but I still don't see the BT10/BT11 items in the UI, only BT20/BT21

Did the new version not make it into OH2.5? Does compressor#40015 merely not show up in the UI?

**Comment by uqs** [comment]
Had to delete the Thing and re-add it, then the new values appeared.
Cheers.

**Pull request closed without merging**
