### PR TITLE
[knx] Extension of the KNX Binding with an ETS knxproj parser

### PR DESCRIPTION
**Pull request by kgoderis**
This PR extends the KNX Basic binding with new functionality to read and parse knxproj files that are generated by ETS5.

I tried to stick as close as possible to the Interfaces provided by the KNX Basic binding, however, some changes were necessary left and right. The extension introduces a new Type of Bridge and Thing as well, and I also tried to limit the changes to the Types already provided by the KNX Basic binding. 

Signed-off-by: Karel Goderis <karel.goderis@me.com>

### CODE REVIEW

**Comment by kgoderis** [comment]
> @kgoderis Thanks, but didn't we agree that the "extended KNX" functionality should come as a separate OSGi bundle, so that the code is cleanly separated? You should not touch the basic knx bundle at all - and if so, please do it as a separate PR, which explains the required changes to it.

That is not how I understood it, i.e. it would be refactored afterwards, after the impact on the basic binding was discussed and so forth. Just for the sake of the discussion, I would not split it up right now because it would make understanding the changes tot the basic binding IMO more difficult.

**Comment by sjka** [comment]
The idea of putting that into different bundles has a very good reason: We should strive for a clean "API" of what the basic binding offers for re-use and what should be kept internal. A high entanglement will lead to changing semantics and thereby to conflicting concepts and melting into a large, single, unmaintainable blob. One axample is already visible in #3500 wrt `ChannelConfiguration` & friends.

Don't get me wrong, I think it completely makes sense to make different assumptions about the way how channels are configured in this ETS extension. That's all fine! It's just that this should be kept clearly separate from the "basic" binding. 

Therefore I would like to second @kaikreuzer here and veto putting all the "ETS" related stuff into the same _bundle_. 
And just to be clear: of course this should be part of the KNX _binding_ and keep using the `knx` namespace prefix everywhere (like it is done in bluetooth, zigbee, etc...). My request relates to creating a separate _bundle_ for it.

**Comment by kgoderis** [comment]
@sjka I think the basic binding offers interesting stuff that is not exposed right now. KNXChannelType for example. If you guys think this is not worth it, then I will simply copy/paste them into that new binding without change, but then any future modifications to shared stuff (like the KNXCoreTypeMapper) will have to be duplicated (and that will also unmaintainable IMO)

I will refactor into a separate bundle once the dust has settled on the API stuff, but for debugging purposes I have not yet done that.

**Comment by kgoderis** [comment]
> A high entanglement will lead to changing semantics and thereby to conflicting concepts and melting into a large, single, unmaintainable blob. One axample is already visible in #3500 wrt ChannelConfiguration & friends.

You have a strange definition of "high" ;-) I mean, the changes proposed in https://github.com/openhab/openhab2-addons/pull/3500 are really not that extensive at all

**Comment by rklueber** [comment]
Hello, 

I try to find out whats the status of the "auto creation" of the things files from the ETS5 knxproj file. I was not able to find a conlusive statement. Is there a working solution? In the standard knx2 binding? on a seperate binding? Where?

Anyone adding some light here? Or hint me to the right seach terms. Sorry for bothering.

Regards
Ralf

**Comment by davidgraeff** [comment]
It is impossible to review 65k lines of code. It would make more sense to publish the parser as a library to maven central or jcentral and just use that library. That would also help because other people will start to contribute at some point and extend and squish bugs.

And feel disagreement from maintainers.

Can we close this PR?

**Comment by lewie** [comment]
I find it very sad when this project is finished. That would be a very good unique selling point for openHAB!

But I am well aware how much work it would take!!!

**Comment by davidgraeff** [comment]
Unique selling point yes. But it would also help if other projects would be able to use that code as java library and openHAB would profit because more people will start to find and fix bugs.

**Comment by J-N-K** [comment]
Closing due to inactivity. If someone wants to pick up this work, please open a new PR.

**Pull request closed without merging**
