### PR TITLE
[jeelink] Add units of measurement

### PR DESCRIPTION
**Pull request by vbier**
This adds unit of measurement to the LaCrosse Sensor temperature channel.

AFAICS on https://www.openhab.org/docs/concepts/units-of-measurement.html#quantitytype, this is the only channel for which I could add unit support, or have I missed something?

Signed-off-by: Volker Bier <volker.bier@web.de>

### CODE REVIEW

**Comment by wborn** [comment]
Thanks for the effort @vbier!

> AFAICS on https://www.openhab.org/docs/concepts/units-of-measurement.html#quantitytype, this is the only channel for which I could add unit support, or have I missed something?

I think there are a few more:

```
	<channel-type id="current-watt">
	<channel-type id="max-watt">
	<channel-type id="consumption-total">
	<channel-type id="appliance-time" advanced="true">
	<channel-type id="sensor-time" advanced="true">
	<channel-type id="humidity">
```

Recently also some new system channels were added you might want to reuse if possible. For the complete list see [Thing Definition](https://www.eclipse.org/smarthome/documentation/development/bindings/thing-definition.html#channels).

**Comment by wborn** [comment]
The [QuantityType](https://www.openhab.org/docs/concepts/units-of-measurement.html#quantitytype) section only lists the Metric/Imperial units that can be converted to each other.

All units from the [List of Units](https://www.openhab.org/docs/concepts/units-of-measurement.html#list-of-units) section are available. You can also use the prefixes like Milli/Mega with all those units.

So you could add a Power unit to the current-watt channel type with something like:

https://github.com/openhab/openhab2-addons/blob/832d81f1885e114551d79c2108d81ce44e1135a3/addons/binding/org.openhab.binding.avmfritz/ESH-INF/thing/channel-types.xml#L56-L62

It's also better to remove references to certain units (like "watt") from the channel type names and descriptions.

> So I can leave channel types as Number and use units nevertheless?

Only if you use units with a channel type you need to add the dimension to the Number.

**Comment by vbier** [comment]
I did not find humidity in the list of units, but added the other ones.

**Comment by wborn** [comment]
Great! You can use dimensionless for the humidity channel. See for instance the Netatmo Binding:

https://github.com/openhab/openhab2-addons/blob/832d81f1885e114551d79c2108d81ce44e1135a3/addons/binding/org.openhab.binding.netatmo/ESH-INF/thing/channels.xml#L225-L231

**Comment by vbier** [comment]
That should be it. Shall I remove the WIP from the title?

**Comment by wborn** [comment]
Yes I think most/all channels have the right unit now. If there's more to do it can always be addressed after reviews.

**Comment by vbier** [comment]
Done. Thanks for your help.

**Comment by wborn** [comment]
Thanks for adding the units to the channels @vbier!

Can you also create a PR to add some information regarding the renamed currentWatt and maxWatt channels to: https://github.com/openhab/openhab-distro/blob/master/distributions/openhab/src/main/resources/bin/update.lst

This file is used for generating release notes.

**Pull request merged**
