### PR TITLE
[miele, minecraft] fix import of MDNSDiscoveryParticipant

### PR DESCRIPTION
**Pull request by philomatic**
This adapts to the package move of MDNSDiscoveryParticipant in https://github.com/eclipse/smarthome/pull/4471

Signed-off-by: Patrick Gottschaemmer <mail@gottschaemmer.net>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Note: This must not be merged before the next ESH stable release.

**Comment by philomatic** [comment]
Yes, thanks for pointing that out!

General question about this:
Did OH2 always build against esh stable?
Did this change (or am I confused by all the esh/oh2 repos 😉 )

Nevertheless:
I've made a fresh IDE setup with the eclipse installer and ofc this compile failure raises up.
Is there a (simple) mechanism in eclipse to change if oh2-addons should be compiled against the esh bundles in workspace or the esh stable bundles in target platform (for all at once)?
Otherwise this is confusing, don't knowing when changes are already in stable :/

Best regards

**Comment by kaikreuzer** [comment]
Yes, it has always been like this - check https://github.com/eclipse/smarthome/wiki/ESH-used-in-openHAB#check-changes.

> I've made a fresh IDE setup with the eclipse installer and ofc this compile failure raises up.

Only if you have selected ESH bundles in this setup (which you should not do unless you want to do changes to them as well).

> Is there a (simple) mechanism in eclipse

Oh yes, a very simple one: Close the projects and they are taken from the (stable) target platform. Open them and the version that you have checked out will be used.

**Comment by philomatic** [comment]
> Yes, it has always been like this - check https://github.com/eclipse/smarthome/wiki/ESH-used-in-openHAB#check-changes.

Ah yes, makes sense for the distribution ofc 😆 

> Oh yes, a very simple one: Close the projects and they are taken from the (stable) target platform. Open them and the version that you have checked out will be used.

Didn't think of that. Sadly, closing / opening projects in eclipse takes huge time, but that's ok.

Thank you for pointing me to the esh wiki for developing, didn't notice that it was created :)
Any rule of thumb which developer informations shall be found on https://www.eclipse.org/smarthome/documentation/development/ide.html and which on the wiki? Should we cross-link them?

**Comment by kaikreuzer** [comment]
The fix for the compilation problem was actually simply to remove the invalid imports: https://github.com/openhab/openhab2-addons/pull/2832/files

You can update this PR to migrate from the deprecated to the new version of MDNSDiscoveryParticipant if you like.

**Comment by philomatic** [comment]
Yeah, I saw that invalid import...

> You can update this PR to migrate from the deprecated to the new version of MDNSDiscoveryParticipant if you like.

... and wanted to move to the new import at once; too excessive.

Rebased and updated.

**Pull request merged**
