### PR TITLE
[i18n] Adapted channel translation to changed ESH API

### PR DESCRIPTION
**Pull request by cweitkamp**
see https://github.com/eclipse/smarthome/pull/4411

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by lolodomo** [comment]
Please exclude netatmo from this PR as we decided to not update the netatmo binding in parallel to @clinique  current work to avoid a new conflict.

**Comment by cweitkamp** [comment]
The netatmo binding is the only source which is really affected by the changes in the ESH API. I am fine with waiting for other PRs to get merged in advance.

**Comment by kaikreuzer** [comment]
@lolodomo & @cweitkamp What is the status here? Should the netatmo changes be removed before this is merged?

**Comment by cweitkamp** [comment]
In general this PR is ready to get merged. But we decidedd to wait for #2682 to be merged in advance. Now it depends. If #2682 doesn't make it into the upcoming release, we maybe think about merging this one first.

**Comment by lolodomo** [comment]
#2682 is very big, hard to rebase and (almost) ready for merging. If we break it again with this PR, I am afraid that #2682 will never be merged... and we need it in the version 2.2.

**Comment by lolodomo** [comment]
@cweitkamp : PR #2682 was finally merged. Any chance that you can rebase quickly your PR so that it could be included in coming OH version 2.2 ?

**Comment by kaikreuzer** [comment]
@lolodomo As I don't know whether @cweitkamp is available on such a short notice, I have just done the rebase on behalf of him. Could you please quickly check if that looks ok?

**Comment by lolodomo** [comment]
LGTM

**Comment by cweitkamp** [comment]
Thank you very much.

**Pull request merged**
