### PR TITLE
[tankerkoenig] Migrate to bnd build

### PR DESCRIPTION
**Pull request by wborn**
Migrates the Tankerkoenig Binding to the bnd build

Are you OK with this @JueBag ?

### CODE REVIEW

**Comment by JueBag** [comment]
All I can say is: Thank you!

I should have done that (although it would have taken more time)!

And for completeness: LGTM

**Comment by cweitkamp** [comment]
@kaikreuzer Can you please add @JueBag to the team as we are not able to request a review from him? Thanks.

**Comment by wborn** [comment]
Thanks for reviewing the changes @JueBag! :+1: 

My first binding migration took me several hours but that was probably also due to the lack of documentation. But still I was struggling hours because of missing one tiny detail. :stuck_out_tongue_winking_eye:

**Comment by martinvw** [comment]
> @kaikreuzer Can you please add @JueBag to the team as we are not able to request a review from him? Thanks.

@cweitkamp as a consequence of @kaikreuzer recents role changes we can do that ourselves now.

**Pull request merged**
