### PR TITLE
Homematic: Removed thread in BridgeHander initialization because of timing issue…

### PR DESCRIPTION
**Pull request by gerrieg**
…s on slower computers

Signed-off-by: Gerhard Riegler <gerhard.riegler@gmail.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Doesn't this break the requirement that the ìnitialize()` method always has to return fast?

**Comment by gerrieg** [comment]
yes, i know. But some users have problems with a fast gateway (Homegear) and a slow computer like a raspi or an old laptop. It seems, that the ThingHandler is initialized to early so that the thing does not have all channels. I can not reproduce the behavior.
Removing the thread in the BridgeHandler fixes the problem.

See: https://community.openhab.org/t/homematic-binding-channel-not-found-for-datapoint-errors-for-definitely-existing-channels/26209

**Comment by kaikreuzer** [comment]
Especially for slow systems, initialization should be done in an asynchronous job, so this PR is definitely the wrong approach.

> It seems, that the ThingHandler is initialized too early

initialize() should not be called before the bridge handler sets its status to ONLINE/OFFLINE/UNKNOWN. So your issue might be that you set the status too early.

There is a known issue in the frameworks initialization handling (see https://github.com/eclipse/smarthome/issues/3351), but I am not sure if this is related to your issue here.

**Comment by gerrieg** [comment]
OK, then close this PR please, i have to find another solution.

**Comment by kaikreuzer** [comment]
Thanks for your understanding :-)

**Pull request closed without merging**
