### PR TITLE
[Seneye] Add disconnected, slideserial, outofwater, wrongslide channels - new pull

### PR DESCRIPTION
**Pull request by MickUrsell**
New Pull Request for [Seneye] Add disconnected, slideserial, outofwater, wrongslide channels #3961.
Due to problems cleaning up previous commits.
Signed-off-by: mickursell <bindings@mru-photography.co.uk>

### CODE REVIEW

**Comment by MickUrsell** [comment]
Closed Pull as same problems as previous pull.

**Comment by MickUrsell** [comment]
Hilbrand,
Hopeful I have added you correctly.
Thanks

**Comment by Hilbrand** [comment]
Ok. fixed. You can now remove me again.

**Note** I push forced your branch, so your local master is different from what is on github, so if you would continue working on that branch you first need to reset it. If you've not done a lot of work locally and are uncomfortable with this just remove your local openhab2-addons and clone it again. Maybe just wait after this pull request was merged.

**Comment by MickUrsell** [comment]
Many Thanks,

I was already planning to start a fresh already:)

**Pull request merged**
