### PR TITLE
[PioneerAVR Binding] Documentation update and small bugfixes

### PR DESCRIPTION
**Pull request by Stratehm**
I have checked the line endings and whitespaces of the files, but they still are displayed as fully modified, I do not know why. Any hints ?

### CODE REVIEW

**Comment by kaikreuzer** [comment]
It is all full of tabs instead of spaces, so that might be one issue.
Altogether it seems that you do not have the current formatter settings...
Can you run "Perform Setup Tasks" and also enable the tasks that appear when clicking "Show all triggered tasks"?

**Comment by Stratehm** [comment]
It is a git line endings problem. On master, files are using a CRLF line ending (for this binding only). Since the default configuration of Git in eclipse set core.autocrlf to true, the new commits convert them to LF line ending.
=> I will make a new PR to convert all the line endings of the binding and then rebase this PR.

Thanks for your help.

**Comment by kaikreuzer** [comment]
Thanks, so now please rebase this one :-)

**Comment by Stratehm** [comment]
Done

**Comment by kaikreuzer** [comment]
thanks, that looks much better :-)
Now you only have to squash your commits!

**Comment by Stratehm** [comment]
It should be good.

**Comment by kaikreuzer** [comment]
Wonderful :+1: 
Thanks!

**Pull request merged**
