### PR TITLE
[homekit] Fix dependency and feature

### PR DESCRIPTION
**Pull request by J-N-K**
Bundle couldn't run, reported here https://community.openhab.org/t/homekit-bundle-throwing-exceptions-on-installation/73940 due to missing classes. Introduced by #5538 (custom version of embedded `net.i2p.crypto/eddsa` library exported different classes than the published one).

This was probably wrong from the beginning, as `com.beowolfe.hap/hap/1.1.4` has a dependency to `net.vrallev.ecc/ecc-25519-java/1.0.1` not to `net.i2p.crypto/eddsa/0.0.1`. This was not discovered because these dependencies are not correctly set.

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by J-N-K** [comment]
I don't understand why Jenkins fails. It even works for me if I clean the whole m2 repository.

**Comment by martinvw** [comment]
Isn't it failing on the problems which you solved in the other PR?

**Comment by martinvw** [comment]
@beowulfe you'r vote would be appreciated on this one!

**Comment by J-N-K** [comment]
Jenkins fails because of the other problem, yes. The problem here is independent. Originally (before the migration) net.i2p.crypto/eddsa/0.0.1 was included as embedded library. This provides `net.i2p.crypto.eddsa.math`. The lowest version that is available in any repository is 0.1.0 which does not export this package. This was not discovered because the manifest in hap/1.1.4 is not declaring what it needs to import. The thread above shows a classdefnotfound-exception because of that.

I looked at the pom in the hap-package and found that another dependency is declared instead which provides that package. The reporter in the forum reported that it fixed the exception.

**Comment by J-N-K** [comment]
included in #5581

**Pull request closed without merging**
