### PR TITLE
correctly declare dependency to UPnP in Kodi binding

### LINKED ISSUE #3394: [Kodi] Unable to resolve root: missing requirement
OH 2.3.0 snapshot 1234
Kodi 2.3.0.201803212307

Removing Kodi from my /conf/services/addons.cfg will let OH start cleanly, but adding it back results in the error. This did not occur in 1232. This is also being reported in the community... https://community.openhab.org/t/after-oh2-3-upgrade-fail-to-install-any-features-error-core-karaf-internal-featureinstaller-failed-installing-openhab/41209/20?u=5iver.

`2018-03-22 17:33:10.744 [ERROR] [org.openhab.core.karaf.internal.FeatureInstaller  ] - Failed installing 'openhab-binding-kodi': Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-binding-kodi; type=karaf.feature; version="[2.3.0.SNAPSHOT,2.3.0.SNAPSHOT]"; filter:="(&(osgi.identity=openhab-binding-kodi)(type=karaf.feature)(version>=2.3.0.SNAPSHOT)(version<=2.3.0.SNAPSHOT))" [caused by: Unable to resolve openhab-binding-kodi/2.3.0.SNAPSHOT: missing requirement [openhab-binding-kodi/2.3.0.SNAPSHOT] osgi.identity; osgi.identity=org.openhab.binding.kodi; type=osgi.bundle; version="[2.3.0.201803212307,2.3.0.201803212307]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.binding.kodi/2.3.0.201803212307: missing requirement [org.openhab.binding.kodi/2.3.0.201803212307] osgi.wiring.package; filter:="(osgi.wiring.package=org.eclipse.smarthome.config.discovery.upnp)"]]`

### PR DESCRIPTION
**Pull request by kaikreuzer**
fixes #3394

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by cweitkamp** [comment]
Thank you. One question for my personal understanding: Is this related to or introduced by #3338?

**Comment by kaikreuzer** [comment]
@cweitkamp It was missing before already and the problem only surfaced through #3338, because it now requires another additional bundle to be available (config.upnp), which didn't exist before.

**Comment by cweitkamp** [comment]
@kaikreuzer Ok, thanks for explanation. May I ask you another question?

Do you have any ideas how to handle the following errors. I currently see them when I want to install the binding manually.
```
2018-03-25 13:22:37.455 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab2/addons/org.openhab.binding.kodi-2.3.0-SNAPSHOT.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.kodi [233]
  Unresolved requirement: Import-Package: org.eclipse.jdt.annotation; resolution:="optional"
  Unresolved requirement: Import-Package: org.eclipse.jetty.websocket.client

	at org.eclipse.osgi.container.Module.start(Module.java:444) [?:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) [?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [9:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [9:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) [9:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [9:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [9:org.apache.felix.fileinstall:3.6.4]
```

**Comment by kaikreuzer** [comment]
@cweitkamp I'd assume that you will need to install the feature "openhab-transport-http" to resolve this.
It is weird that the manual installation installs the websocket bundle automatically although the feature dependency is not declared - I have created #3401 to correctly declare it nonetheless.

**Pull request merged**
