### PR TITLE
Added OpenClosedType to ZWaveBasicConverter

### LINKED ISSUE #746: Zwave: Basic converter does not support open / closed type.
Fibaro Door / Window sensor reports it's updates as Basic. The ZWaveBasicConverter does not support OpenClosedType however. Hence the following message in the log:

`NODE: 21: No conversion in ZwaveBasicConverter to OpenClosedType.`

### PR DESCRIPTION
**Pull request by jspuij**
Fixes #746.

Signed-off-by: Jan-Willem Spuij jw@spuij.nl (github: jspuij)

### CODE REVIEW

**Comment by jspuij** [comment]
@cdjackson Hey Chris, as I'm only starting again. Anything wrong with this? ;-)

**Comment by cdjackson** [comment]
Sorry - I missed this... I thought I added this about 10 minutes after you raised the issue on #746 (it was my turn to be fast :) ) - but I'll check...

**Comment by jspuij** [comment]
Sorry, you did probably. I guess I missed your pull request. Close this one. ;-)

**Comment by cdjackson** [comment]
Yep - this commit https://github.com/cdjackson/openhab2-addons/commit/4c394fa344933eb3dc44b0dab67a2c4020f8e36a was merged a week ago - I think it's exactly the same as this PR unless I've missed something?

**Comment by cdjackson** [comment]
Cool - thanks :)

**Pull request closed without merging**
