### PR TITLE
Updated copyrights to 2018

### PR DESCRIPTION
**Pull request by martinvw**

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Can you explain why this PR removes 15 lines more than it adds?
The PR is too big for Github to figure this out myself...

**Comment by martinvw** [comment]
Pff, fair question, I scrolled through everything but did not note anything strange, let me go through it once more

**Comment by martinvw** [comment]
https://github.com/openhab/openhab2-addons/pull/3071/files#diff-86d346295a850f8f6d96720b29805e09

**Comment by kaikreuzer** [comment]
Ok, thanks, that should explain it!

**Pull request merged**
