### PR TITLE
[smartmeter] migrate to bnd

### PR DESCRIPTION
**Pull request by J-N-K**
Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by J-N-K** [comment]
Anyone any idea how to solve this?

The problem is: `org.openmuc/jsml` depends on `org.openmuc/jrxtx`. To use "our" `nrjavaserial` instead of `gnu.io` (which is used in `jrxtx`), a "hack" was used and our own version of was included as [3rdparty source](https://github.com/openhab/openhab2-addons/tree/master/addons/binding/org.openhab.binding.smartmeter/src/main/java-extern/org/openmuc/jrxtx).

The code compiles without problems, but the feature verification fails. It sees a missing dependency to `org.openmuc.jrxtx`. What I do not understand is why this happens even after I added exclusions to the project pom.

I also tried to export our own version (added `org.openmuc.jrxtx` to the exported packages for bnd) and this at gets me a .jar which has this package as `Export-Package` (with version 2.5.0). That however  is not fulfilling the requirement of `(osgi.wiring.package=org.openmuc.jrxtx)(version>=1.0.0)(!(version>=2.0.0)`.

The only solution I see right now is to go back to including the libs as binaries within our bundle.

**Comment by J-N-K** [comment]
I introduced a `bnd.exportpackage` property (like the `bnd.importpackage`) which can be used to export e.g. 3rd-party content which is not in the org.openhab-namespace.

@openhab/2-x-add-ons-maintainers, we should discuss if we move the add-sources for `src/3rdparty` to the base pom.

**Comment by wborn** [comment]
The extra property as workaround makes sense to me. If one day there are more bundles depending on `org.openmuc/jrxtx` we could also create a `jrxtx-over-nrjavaserial` bundle (or maybe even more generic using gnu.io or ohc.serial). I.e. similar to how slf4j has [bridges](https://www.slf4j.org/legacy.html) for various logging implementations.

**Comment by davidgraeff** [comment]
That additional buildsystem variable need to be documented

**Comment by J-N-K** [comment]
Where?

**Comment by davidgraeff** [comment]
I propose a docs/buildsystem.md file or similar. All the flags that we introduced for noSnapshots, bndResolve etc should be in such a file.

This is only relevant for this repository, so it does not make sense to keep the info outside of the repo.

**Comment by J-N-K** [comment]
Now that the documentation remarks are addressed with a PR, can we merge here?

**Comment by davidgraeff** [comment]
Thanks :)

**Pull request merged**
