### PR TITLE
[senseBox] Forgot to add binding to feature.xml

### PR DESCRIPTION
**Pull request by hakan42**
Somehow, the commit adding this binding to feature.xml must have got lost before starting the pull requests 😊

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Weird... Didn't you miss it in the distro then? Thanks for adding it now!

**Comment by martinvw** [comment]
Hmm, guys, I think it's worse 👎 

It's not in the pom.xml either.

**Comment by martinvw** [comment]
My excuse is that I was on the [IoT tech days](http://iottechday.nl/) while reviewing ;-)

**Comment by hakan42** [comment]
> Weird... Didn't you miss it in the distro then? Thanks for adding it now!

On my system, I was always using the self-compiled one... Actually, it's the first time I am checking the full distribution 😊 

> It's not in the pom.xml either.

Really? I'll check immediately and create a new PR... More things to check before I start a PR, I guess...

**Comment by hakan42** [comment]
Here it is: https://github.com/openhab/openhab2-addons/pull/2372

And this time, I ran a full build on my machine to make sure the binding is being picked up for compilation 😊

**Pull request merged**
