### PR TITLE
Systeminfo test various minor fixes

### PR DESCRIPTION
**Pull request by svilenvul**

### CODE REVIEW

**Comment by martinvw** [comment]
The `PlatformDependentTestsInterface.java` file in the groovy folder surprises me. All changes look like improvements.

**Comment by kaikreuzer** [comment]
trying to get the PR builder running, please ignore my closing/reopening...

**Comment by martinvw** [comment]
@svilenvul the build at Jenkins is failing hard:

> 13:51:11.659  |  [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:1.0.0:compile (default-compile) on project org.openhab.binding.systeminfo.test: Compilation failure: Compilation failure:
13:51:11.659  |  [ERROR] /scratch/jenkins/workspace/PR-openHAB2-Addons/addons/binding/org.openhab.binding.systeminfo.test/src/test/groovy/org/openhab/binding/systeminfo/test/SysteminfoOSGiTest.groovy:[51,39] 1. ERROR in /scratch/jenkins/workspace/PR-openHAB2-Addons/addons/binding/org.openhab.binding.systeminfo.test/src/test/groovy/org/openhab/binding/systeminfo/test/SysteminfoOSGiTest.groovy (at line 51)
13:51:11.659  |  [ERROR] import org.openhab.binding.systeminfo.SysteminfoBindingConstants
13:51:11.660  |  [ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^
13:51:11.660  |  [ERROR] Groovy:unable to resolve class org.openhab.binding.systeminfo.SysteminfoBindingConstants
13:51:11.660  |  [ERROR] 
13:51:11.660  |  [ERROR] /scratch/jenkins/workspace/PR-openHAB2-Addons/addons/binding/org.openhab.binding.systeminfo.test/src/test/groovy/org/openhab/binding/systeminfo/test/SysteminfoOSGiTest.groovy:[52,49] 2. ERROR in /scratch/jenkins/workspace/PR-openHAB2-Addons/addons/binding/org.openhab.binding.systeminfo.test/src/test/groovy/org/openhab/binding/systeminfo/test/SysteminfoOSGiTest.groovy (at line 52)
13:51:11.661  |  [ERROR] import org.openhab.binding.systeminfo.discovery.SysteminfoDiscoveryService
13:51:11.661  |  [ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^
13:51:11.661  |  [ERROR] Groovy:unable to resolve class org.openhab.binding.systeminfo.discovery.SysteminfoDiscoveryService
13:51:11.662  |  [ERROR] 
13:51:11.662  |  [ERROR] /scratch/jenkins/workspace/PR-openHAB2-Addons/addons/binding/org.openhab.binding.systeminfo.test/src/test/groovy/org/openhab/binding/systeminfo/test/SysteminfoOSGiTest.groovy:[53,47] 3. ERROR in /scratch/jenkins/workspace/PR-openHAB2-Addons/addons/binding/org.openhab.binding.systeminfo.test/src/test/groovy/org/openhab/binding/systeminfo/test/SysteminfoOSGiTest.groovy (at line 53)
13:51:11.662  |  [ERROR] import org.openhab.binding.systeminfo.handler.SysteminfoHandler
13:51:11.663  |  [ERROR] ^^^^^^^^^^^^^^^^^
13:51:11.663  |  [ERROR] Groovy:unable to resolve class org.openhab.binding.systeminfo.handler.SysteminfoHandler
13:51:11.663  |  [ERROR] 
13:51:11.663  |  [ERROR] /scratch/jenkins/workspace/PR-openHAB2-Addons/addons/binding/org.openhab.binding.systeminfo.test/src/test/groovy/org/openhab/binding/systeminfo/test/SysteminfoOSGiTest.groovy:[54,48] 4. ERROR in /scratch/jenkins/workspace/PR-openHAB2-Addons/addons/binding/org.openhab.binding.systeminfo.test/src/test/groovy/org/openhab/binding/systeminfo/test/SysteminfoOSGiTest.groovy (at line 54)
13:51:11.664  |  [ERROR] import org.openhab.binding.systeminfo.internal.SysteminfoHandlerFactory
13:51:11.664  |  [ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^
13:51:11.664  |  [ERROR] Groovy:unable to resolve class org.openhab.binding.systeminfo.internal.SysteminfoHandlerFactory
13:51:11.664  |  [ERROR] 
13:51:11.665  |  [ERROR] /scratch/jenkins/workspace/PR-openHAB2-Addons/addons/binding/org.openhab.binding.systeminfo.test/src/test/groovy/org/openhab/binding/systeminfo/test/SysteminfoOSGiTest.groovy:[664,2] 5. ERROR in /scratch/jenkins/workspace/PR-openHAB2-Addons/addons/binding/org.openhab.binding.systeminfo.test/src/test/groovy/org/openhab/binding/systeminfo/test/SysteminfoOSGiTest.groovy (at line 664)
13:51:11.665  |  [ERROR] @Override
13:51:11.665  |  [ERROR] ^^^^^^^^
13:51:11.665  |  [ERROR] Groovy:Method 'getHostName' from class 'org.openhab.binding.systeminfo.test.SysteminfoOSGiTest$SysteminfoDiscoveryServiceMock' does not override method from its superclass or interfaces but is annotated with @Override.
13:51:11.665  |  [ERROR] 
13:51:11.666  |  [ERROR] Found 5 errors and 0 warnings.
13:51:11.666  |  [ERROR] -> [Help 1]
13:51:11.666  |  [ERROR] 
13:51:11.666  |  [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
13:51:11.667  |  [ERROR] Re-run Maven using the -X switch to enable full debug logging.
13:51:11.667  |  [ERROR] 
13:51:11.667  |  [ERROR] For more information about the errors and possible solutions, please read the following articles:
13:51:11.667  |  [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by svilenvul** [comment]
Strange, the Travis build is green.

**Comment by martinvw** [comment]
It reports, this for the systeminfo tests:

> [INFO] --- tycho-compiler-plugin:1.0.0:compile (default-compile) @ org.openhab.binding.systeminfo.test ---
[WARNING] Parameter 'useProjectSettings' is set to true, but preferences file '/home/travis/build/openhab/openhab2-addons/addons/binding/org.openhab.binding.systeminfo.test/.settings/org.eclipse.jdt.core.prefs' could not be found!
[INFO] Nothing to compile - all classes are up to date

Especially the nothing to compile troubles me.

@kaikreuzer I think we need to do a `mvn clean install` instead of the current `mvn install`

**Comment by kaikreuzer** [comment]
I have deactivated the tests on Jenkins again as we are only doing an incremental build there.
The Travis build is the one to look at for the test results.

**Comment by martinvw** [comment]
> The Travis build is the one to look at for the test results.

```
mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
```

Uhm

**Comment by kaikreuzer** [comment]
Interesting - so Travis by default deactivates the test executions on Maven? Time to adapt https://github.com/openhab/openhab2-addons/blob/master/.travis.yml, I guess...

**Comment by martinvw** [comment]
Maybe it first does this and a `mvn test` later on?

**Comment by martinvw** [comment]
Really curious whether Jenkins will be fine one we merged it ... :-S

**Comment by svilenvul** [comment]
> martinvw commented 6 days ago
> 
>The PlatformDependentTestsInterface.java file in the groovy folder surprises me. 

Maybe the name is not precise - HardwareConfigurationDependentTests would be more accurate. Or it is not the name that is surprising you ?

**Comment by martinvw** [comment]
Nope its java file which lives there, I would expect that in a src/test/java folder

**Comment by svilenvul** [comment]
>Nope its java file which lives there, I would expect that in a src/test/java folder

Thanks, I have renamed the file, so it should be ok now.

**Comment by martinvw** [comment]
LGTM

**Pull request merged**
