### PR TITLE
[intellij] Ignore project metadata for IntelliJ Idea

### PR DESCRIPTION
**Pull request by hakan42**
We already ignore the "old" IntelliJ project files (*.iml). Ignore the new ones, too.

Signed-off-by: Hakan Tandogan <hakan@tandogan.com>

Signed-off-by: Hakan Tandogan <hakan@tandogan.com> (github: hakan42)

### CODE REVIEW

**Comment by davidgraeff** [comment]
Should we also ignore the eclipse ".project" file? It isn't of much when the project is imported as maven project and auto-generated / over-written.
@openhab/2-x-add-ons-maintainers

**Comment by hakan42** [comment]
I would leave ignoring .project (and .classpath) files to a seperate PR, though, and would, with the same PR, remove the files already committed to git. If we go pom-first, go all the way 😄

**Comment by wborn** [comment]
The issue with deleting .project files from Git is that you'll probably break everyone's Eclipse setup.

**Comment by davidgraeff** [comment]
@wborn How about removing them just from the migrated bundles/ path? Developers that are using the bnd/maven buildsystem without a proper guide at the moment are adventurous enough to solve any upcoming issues. 

For me nothing would change for example as I needed to switch of auto-build. Everytime I rebuild, the .project file is restored.

**Comment by wborn** [comment]
I'd rather see the same files consistently being used/ignored in all openHAB repositories without causing  any issues for contributors.

**Comment by davidgraeff** [comment]
How about adding ".project" to gitignore and not touching the currently existing files?

**Comment by wborn** [comment]
Adding it to ignore will also interfere with how contributors currently work. If you often remove ignored files using  `git clean ...` you'll need to reimport your Eclipse projects everytime.

**Pull request merged**
