### PR TITLE
[knx] Update README.md

### PR DESCRIPTION
**Pull request by udo1toni**
Clarify ipAddress default value.

Signed-off-by: Udo Hartmann udo1toni@gmail.com

### CODE REVIEW

**Comment by cweitkamp** [comment]
@sjka Wdyt?

**Comment by lsteelandt** [comment]
Is the Group Address Notation can be clarified ?
The used of '<' sign is not clear and the use of sign '+' is not described. 

Thanks 😉

**Comment by udo1toni** [comment]
@lsteelandt https://www.openhab.org/addons/bindings/knx/#group-address-notation what's missing here?

**Comment by AngelosF** [comment]
@udo1toni Since you are updating knx2 readme, can you also include a minor fix in your PR:

On https://www.openhab.org/addons/bindings/knx/#ip-gateway

Fix the Description of `localSourceAddr`

Instead of the current: 
```
The group address for identification of this KNX/IP gateway within the KNX bus
```

It should read:
```
The physical address (PA) for identification of this KNX/IP gateway within the KNX bus.
```

**Comment by lsteelandt** [comment]
> @lsteelandt https://www.openhab.org/addons/bindings/knx/#group-address-notation what's missing here?
@udo1toni the text doesn't clearly describe the role of '+' sign. 
Trough "<config>="[<dpt>:][<]<mainGA>[[+[<]<listeningGA>]+[<]<listeningGA>..]]", I understand that the '+' operator allow to list several Group address linked to one 'config' of the binding.  Useful in the case you have one Group Adresse to post commands and one to receive States.  Don't know if there is other uses of '+' sign.
Also the syntax show that + signs are always followed by a 'listeninGA'. So the '<' sign seems to overload the fact that what is following is a 'listeninGA'. 
Can we have several Group Adress separate by several '+' to tell that one config can influence several group Adress ?
Something like that : 
`        Type switch        : demoSwitch        "Light"       [ ga="1/0/1+1/0/2" ]`
To tell that the demoSwitch send a On/Off order to GA 1/0/1 and GA 1/0/2 ?

**Comment by NorbertHD** [comment]
@udo1toni Since you are updating knx2 readme, can you also include a minor fix in your PR.

In this expression there is one more closing square bracket than opening square brackets:
```
Group Address Notation
<config>="[<dpt>:][<]<mainGA>[[+[<]<listeningGA>]+[<]<listeningGA>..]]"
```
I assume an opening square bracket should be placed in front of the last plus:
```
<config>="[<dpt>:][<]<mainGA>[[+[<]<listeningGA>]   [   +[<]<listeningGA>..]]"
```

**Comment by AngelosF** [comment]
check also https://github.com/openhab/openhab2-addons/issues/3768 to close it
need to fix the "....basic Things are wrappers around an arbitrary physical addresses on the KNX bus"

**Comment by udo1toni** [comment]
> @lsteelandt 
> the text doesn't clearly describe the role of '+' sign.
> Trough "="[:][<][[+[<]]+[<]..]]", I understand that the '+' operator allow to list several Group address linked to one 'config' of the binding. Useful in the case you have one Group Adresse to post commands and one to receive States. Don't know if there is other uses of '+' sign.

Well, it's pretty clear to me. `:` is optional, if used, it may appear in front of the first GA. `<` is optional, it may appear at any GA. If using more than one GA, they are to be separated with a `+`.
If you are familiar with knx, you should know that there is always **exactly** one GA which is used to send messages (the MainGA), every other GA additionally set to a communication object is only to listen to. Of course you are able to forbit sending even for a MainGA by clearing the Write Flag, but beside this flag, always only the first GA is allowed to send something. Even if sending a read request to another GA, this will result in an answer through the MainGA (if Write Flag and Readable Flag are set).
openHAB may send read requests to more than one GA per communication object, but I can't see a real benefit for this option. In fact, I think that even the ´<´ symbol is to be used not more than once per communication object, as the status is only to follow the last received command or status update.

**Comment by udo1toni** [comment]
I have created a new pull request :) maybe someday I will understand the correct way to this... 

https://github.com/openhab/openhab2-addons/pull/4229

**Pull request closed without merging**
