### PR TITLE
Add periodic labeler as GitHub Action

### PR DESCRIPTION
**Pull request by mueller-ma**
Also add a helper script to generate the labeler config.

This action labels all open PRs based on the changed files.

### CODE REVIEW

**Comment by davidgraeff** [comment]
I think the confusion comes from the fact that some bindings are indeed labeled, ie "mqtt".
That is purely historical though, it dates back from when no codeowner file existed afaik.

Should we maybe give up on those labels? Or are labels actually useful for maintainers, because you can look for your own bindings by label?

**Comment by mueller-ma** [comment]
> some bindings are indeed labeled, ie "mqtt".

The existing labels could be renamed to match the new label pattern.

> I don't see what this helps.

Users can look for open PRs for a binding, e.g. to know if there is already a pending fix for something.

**Comment by wborn** [comment]
What will happen when a PR is made touching multiple bindings?

Editing labels manually will be less easy when there are hundreds of labels.

AFAIK we currently only use labels for the most popular add-ons that frequently have issues/PRs so it's easier to find duplicates or related issues. Though some contributors have also added labels for less popular add-ons.

Labels are better for tooling compared to the prefix convention we currently use. E.g. when generating release notes. It may require more human effort if we often need to correct the labeler when PRs touch many bindings.

The prefixes we currently use make it very easy to immediately see what add-on is involved when scanning the issue/PR lists. Issue/PR titles may be confusing when they no longer have the prefixes and only use labels.

Before @TravisBuddy was introduced you could also easily search issues using add-on names. It now returns many false positives because @TravisBuddy comments contain Maven reactor summaries with add-on names. It's still possible to limit your search to titles only by adding `in:title`.

**Comment by Confectrician** [comment]
I agree with wborn.

With [prefixes] and well choosen labels, we have two dimensions of sorting.
Those are more or less easy to handle.

With hundreds of labels there would be much more effort in choosing and setting labels, which maybe would cause people to not set important labels due to the needed effort.

I think this label bit is interesting for 'one purpose repos' like Android, vscode, Alexa or even docs. (Would like to try them in the docs definitely.)
But I don't think that it will make work easier here.

We could maybe think about a subset of labels like setting the documentation label here, when a markdown file is affected.

**Comment by mueller-ma** [comment]
> We could maybe think about a subset of labels like setting the documentation label here, when a markdown file is affected.

This subset could also contain the currently existing binding labels.

**Comment by davidgraeff** [comment]
Thanks for the work @mueller-ma. The decision was however not to label issues with addon specific tags anymore. Open an issue for discussion first, to avoid unnecessary work. Maybe you learned something though, which is always good.

Closing now.

**Pull request closed without merging**
