### PR TITLE
Inherit from openHAB Super POM

### PR DESCRIPTION
**Pull request by pfink**
This PR carves out repositories and the deploy plugin to the newly introduced openHAB Super POM. It cannot be merged before https://github.com/openhab/infrastructure/pull/4 is merged and the first release of the Super POM is done.

### CODE REVIEW

**Comment by davidgraeff** [comment]
I think I do not really understand the unleash plugin. Assuming that we switch to a versioning schema where each addon in here is versioned on its own, is unleash still required?

**Comment by pfink** [comment]
> Assuming that we switch to a versioning schema where each addon in here is versioned on its own, is unleash still required?

Yes, at least for the aggregation POM and tagging within this repository. Anyhow, in case every addon would have an own version, I'd like to insist that there would also be a seperate repository for each plugin and we would also have to think of how we can provide a compatibility matrix for each addon.

Just try to create a full release over all 7 openHAB repositories once manually, incuding version bumps, repository tagging, sanity checks, .. and you'll understand the value of the unleash plugin ;-)

**Comment by davidgraeff** [comment]
An aggregated repository like this doesn't need tags or automatic version bumps. There were some discussions in the past already, but only OH3 would allow to change versioning.

I'm all for different repositories with a central registry, but Kai doesn't want to. I can live with this current monolithic repo as we have solved almost all issues (CODEOWNERS file for notifying only relevant maintainers, travis-ci can soon check single directories on a push, karaf feature files are now in each directory). The last point on the agenda would be versioning. The major version is shared with the core and expresses compatibility, minor and revision version is up to an addon developer.

**Comment by pfink** [comment]
> I'm all for different repositories with a central registry

Me, too. But what we should not do by any means in my eyes is to mix up different versions within the same repository. One version per repository, please. But again, this PR is not the right place for this discussion as it . Feel free to add a link here as soon as you start the discussion somewhere else :)

> I'm just asking if that carving out would break that flow, because if it is I'd veto. The discussion how this is actually done might not belong here, that is correct.

The answer is no. As I said, this topic has nothing to do with this PR.

**Comment by kaikreuzer** [comment]
@pfink Can the WIP now be removed and the PR merged?

**Comment by pfink** [comment]
Yes, can be merged as soon as Super POM is available within Maven Central, I could successfully get a releasebuild green on this branch.

**Comment by J-N-K** [comment]
Can we either fix or revert this, @pfink @kaikreuzer? Jenkins always fails because it can‘t find the super-pom.

**Comment by kaikreuzer** [comment]
@J-N-K Yes, we should fix it, the question is how - the super pom is available in Maven Central (http://repo1.maven.org/maven2/org/openhab/openhab-super-pom/1.0.0/) as well as in JCenter (https://jcenter.bintray.com/org/openhab/openhab-super-pom/1.0.0/), so why isn't it found?

**Comment by martinvw** [comment]
@pfink / @kaikreuzer  It seems to be only looking in https://ci.openhab.org/artifactory/libs-release, because its configured like that? Or am I mistaken:

image

**Comment by kaikreuzer** [comment]
@martinvw But even there it is available since May 28: https://ci.openhab.org/artifactory/libs-release/org/openhab/openhab-super-pom/1.0.0/

**Comment by pfink** [comment]
I think the reason is an outdated Maven version that is embedded into Jenkins Core. Give me 2 more days to analyze & fix...

**Comment by wborn** [comment]
Shall we undo the parent version range for now? It seems to build without it:

https://ci.openhab.org/job/PR-openHAB2-Addons/14222/console

**Comment by pfink** [comment]
Would be an option. Anyhow, I think I can fix it within Jenkins. Just need a bit more time :)

**Comment by pfink** [comment]
I could fix it now like this:

1. versions plugin resolves version range and statically
1. Jenkins parses the POM structure with the old Maven version
1. versions plugin reverts the change
1. actual build starts

FTR here the Jenkins issue: https://issues.jenkins-ci.org/browse/JENKINS-23846

**Comment by wborn** [comment]
Another way to workaround it might be to replace these "Maven project" jobs with either a "Freestyle project" or an even better "Pipeline" job:

Selection_002


That should also get rid of the old embedded Jenkins Maven version. But it's probably more work. I no longer use such versioned ranges with Maven because I've had too many issues with them.

**Comment by pfink** [comment]
> I no longer use such versioned ranges with Maven because I've had too many issues with them.

I'm also not a fan of them. Here it's really an exception to have a last resort in case the infrastructure changes (e.g. repository location of artifacts). That's why it's also forbidden to have a dependency section within the Super POM.

**Pull request merged**
