### PR TITLE
Paper UI: add support for command options

### PR DESCRIPTION
**Pull request by htreu**
This is the follow up on https://github.com/openhab/openhab-core/pull/540.

Signed-off-by: Henning Treu <henning.treu@googlemail.com>

### CODE REVIEW

**Comment by martinvw** [comment]
Would it make sense to add yourself also to the codeowners file?

**Comment by cweitkamp** [comment]
@martinvw @htreu already is the codeowner for Paper UI:

https://github.com/openhab/openhab2-addons/blob/9460b1878f7001e6f5339c2f9a72e3cc1f84670d/CODEOWNERS#L228

**Comment by martinvw** [comment]
> already is the codeowner for Paper UI:

Great! All of you did so much great work the last month, I cannot keep up :-)

**Comment by martinvw** [comment]
@htreu should we wait merging till the core PR is merged?

**Comment by kaikreuzer** [comment]
Yes, please wait!

**Comment by htreu** [comment]
@openhab/2-x-add-ons-maintainers since https://github.com/openhab/openhab-core/pull/540 is merged this one is ready, too.

**Comment by kaikreuzer** [comment]
Ok, let's see what breaks ;-)

**Pull request merged**
