### PR TITLE
[homie] Decrease timeouts for Homie devices

### LINKED ISSUE #5958: [mqtt.homie] Decrease subscribeTimeout time for Homie devices
Hi guys! (@davidgraeff, @J-N-K)

Now that many MQTT and Homie problems are solved, I think that we should decrease the subscribeTimeout parameter for Homie devices, because 15 seconds seems to be a little bit high. What about 2-3 seconds? It is still plenty of time to retrieve retained topics from the broker, so there shouldn't be any problem with constrained devices. What do you think? Do you want me to make a pull request with the changes? It is just a one line change:

https://github.com/openhab/openhab2-addons/blob/e775b4d09278cb97170dd8c4844fc5bb43a62027/bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/generic/internal/MqttThingHandlerFactory.java#L93

Thank you for all your work and support!

### PR DESCRIPTION
**Pull request by bodiroga**
Closes #5958

Signed-off-by: Aitor Iturrioz <riturrioz@gmail.com>

### CODE REVIEW

**Comment by davidgraeff** [comment]
Why do you want to increase the overall timeout anyway? That huge timeout is for 500+ homie topics and I intentionally have chosen such a huge number because another reported that his big zigbee2mqtt device tree takes several seconds to be received.

**Comment by bodiroga** [comment]
> Why do you want to increase the overall timeout anyway? That huge timeout is for 500+ homie topics and I intentionally have chosen such a huge number because another user reported that his big zigbee2mqtt device tree takes several seconds to be received.

Hi @davidgraeff! (and @J-N-K)

The problem with the high timeouts (that I want to decrease, not increase) is that you have to wait 15 seconds from the moment you approve the discovery result until the channels are displayed inside the thing, which is very awkward, because at first you think that something is wrong with the device. The way the timeout is coded makes that, even if the client and broker communication is fast (200ms, for example), you always have to wait those 15 seconds :cry: The ideal solution would be to set a small timeout (0.5 - 1 second) and at the same time pospone the timeout everytime a new discovery (node, property or attribute) message is received, solving the problem of big trees. But I'm not sure if that can be easily coded without changing too many things.

Anyway, functional wise, the discovery process works great, I just wanted to improve the user experience a little bit :wink:

**Comment by davidgraeff** [comment]
Yeah you mentioned the correct fix ^^
A "no further message" timeout is the way to go. That was discussed in the homie repo as well to actually make it part of the spec. And no it's not that much work. There's a one-time thing handler timer right now that finalizes the OH channels. That would need to be replaced with a timer that resets its timeout on new messages.

**Comment by J-N-K** [comment]
@bodiroga, would you work on the solution proposed by you and confirmed by @davidgraeff? I think this would be much better and close here.

**Comment by J-N-K** [comment]
https://github.com/openhab/openhab2-addons/pull/5963#issuecomment-523614808 shows the way to go. Closing here, if someone wants to implement that, please open a new PR.

**Comment by davidgraeff** [comment]
@J-N-K The problem persists though and someone will reopen another ticket at some point probably. Maybe reopen this one and rename the title to "Wait for all Homie topics to arrive" or so instead?

**Comment by J-N-K** [comment]
The issue is still open. I only closed the PR.

**Pull request closed without merging**
