### PR TITLE
[dsmr] migrate to bnd

### PR DESCRIPTION
**Pull request by JueBag**
Note: Did this the first time!

Signed-off-by: Juergen Baginski opus42@gmx.de (github: JueBag)
Signed-off-by: JueBag <opus42@gmx.de>

### CODE REVIEW

**Comment by wborn** [comment]
Deja vu https://github.com/openhab/openhab2-addons/pull/5159 :wink:

**Comment by davidgraeff** [comment]
Very good for the first migration. You forget to remove the old test directory though. Keep an eye on the lines-changed. They should drop by about 50 lines or so with the migration but never increase.

**Comment by JueBag** [comment]
Mist!
While looking for a binding with a test variant which I could handle I missed to look through the open PRs.
.Me.stupid!
At least I learned something, will continue tomorrow. Any guidance on which binding to choose is welcome.

**Comment by davidgraeff** [comment]
Ask in the PR thread if it is still being worked on. Some old PRs are abandoned.

**Comment by wborn** [comment]
Even if you'd look for an open PR in this case you wouldn't find it @JueBag. So it's hard to know there is work in progress this way. :neutral_face:

**Comment by davidgraeff** [comment]
Don't close it. We leave it open so that nobody tries it again for the moment.

**Comment by Hilbrand** [comment]
Maybe we should compile a list of all non-migrated addons and their status? Than we can see better what needs to be done and what might be picked up, add if pr is pending, if someone has picked it up. Or something else is the case.

**Comment by JueBag** [comment]
Ups, that last commit went in here?
What I meant to do is just create a separate commit for the feed binding. It looks like working on/with github is above my knowledge.
Is there a way to get that corrected?

**Comment by J-N-K** [comment]
Yes. On a git command line (not sure which OS you are using), do a `git rebase -i HEAD~4`. An editor should open which shows the latest commits, all with a command in front. If you want to remove one, replace `pick` with a simple `d` (for drop). Be sure not to change anything else. Save and exit. All your changes from that commit are lost now, if you need them, make a copy before. Now use `git push origin +<branchname>`. Done.

Your branch seems to be master, which in general is not a good idea. Better branch before with `git branch foo` to create a new branch foo. Make new branches for each feature you develop.

**Comment by JueBag** [comment]
@J-N-K   Done (the first part), Thank you.  Let see how to do the create a seperate branch, however that branch needs to have the starting point point (or whatever is the correct term) before my commit for the dsmr binding (if I'm not mistaken).

**Comment by J-N-K** [comment]
Branch, you should be on the new branch then (check with `git branch`). Then drop your commits until the last that was on the upstream master. Then go in from there.

After the changes you made here are merged, drop the commits in your own master.

If you are unsure, wait until these changes have been merged. You could accidentally erase them.

**Comment by JueBag** [comment]
>If you are unsure, wait until these changes have been merged. You could accidentally erase them.

That's the reason why I'm asking that much (my blood-pressure is going through the roof). 
I did "branch" , but obviously without that:
> Then drop your commits until the last that was on the upstream master. Then go in from there.

Question, if I'm dropping my last commit (which would be the commit of this PR), wouldn't that affect this PR? (Not that it would do any harm, since it will never be merged.)

Will continue this evening.

**Comment by Hilbrand** [comment]
Once pr #5273 has been merged I'll migrate the dsmr binding to bnd and close this pr. I expect there will be more conflicts here as a result of the pr, and I have a script that migrates 95% of the process needed here. I guess that saves every bodies time and is much simpler that fixing the conflicts.

**Comment by JueBag** [comment]
Thanks.

**Comment by J-N-K** [comment]
@Hilbrand, can you prepare the migration PR?

**Comment by Hilbrand** [comment]
Replaced by #5436

**Pull request closed without merging**
