### PR TITLE
Netatmo: eliminate false precision

### PR DESCRIPTION
**Pull request by jongj**
Temperature and other values where reported with very large presision.
For example:

netatmo_NAMain_home_Temp changed from 22 to 22.1000003814697265625

Signed-off-by: Jorg de Jong <jorg@dejong.info> (github: jongj)

### CODE REVIEW

**Comment by watou** [comment]
Could the issue be addressed earlier in io.swagger.client.model.NA*, like when the JSON is being deserialized, so BigDecimal would be used instead of float or double from the start?  That way, the exact values reported from Netatmo are accurately represented.

**Comment by jongj** [comment]
The swagger client is black box for me :smile:, but your suggestion sounds reasonable.  
@clinique as moddule author, what's your take on this?  Can the precession issue be fixed in  the swagger lib? Maybe together with issues i#805 and #866 which are also swagger issues?

**Comment by clinique** [comment]
@jongi : taking a look wether it can be directly fixed in swagger client.

**Comment by kaikreuzer** [comment]
@clinique For the time being, I would be fine to merge this PR, do you agree?

**Comment by clinique** [comment]
@kaikreuzer : please wait just a bit - currently investigating it - will provide needed feed-back for opened netatmo related issues soon.

**Comment by clinique** [comment]
@jongj , @kaikreuzer.
I took a look at swagger client. Problem does not seem to come from there.
Swagger lib returns Temperature as a "Float" that correctly reflects the value furnished by Netatmo API. The false precision comes when Float is converted to BigDecimal so it's on binding or ESH library part.

Then, to answer Kai's question, I would say, yes, let's merge this for now.

**Comment by clinique** [comment]
Then, a complement : 
    new DecimalType(dashboard.getTemperature().toString());
should be enough to avoid false precision

**Comment by kaikreuzer** [comment]
Thanks for checking @clinique!

> should be enough to avoid false precision

I don't mind the specific setting of the scale within this PR - and it reduces the risk that the problem reoccurs because of some floating point operations somewhere...

**Pull request merged**
