### PR TITLE
[etapu] EtaPU Binding initial contribution

### PR DESCRIPTION
**Pull request by hubermi**
A Binding for the ETA PU Pelletsheating that uses the REST interface to read the most important status messages and sensor values.

Current code only supports ETA PU. I will change implementation so that any ETA product is supported. Until then, please consider this PR as WIP and do not review it.

### CODE REVIEW

**Comment by nottheedge** [comment]
Hello, I'm getting an error that my ETA PC20 (pellet compact) doesn't give back values. The webservice is active, because if I trigger the heating from console I'm getting the values.

Do you use port 8080 for communication (http://IP:8080/user/var/...)?

Regards
Joerg Martin

**Comment by hubermi** [comment]
Hi Joerg,
yes I use port 8080. Does the ETA PC20 need a different port for the communication. 
Also, could you send me the Rest API doc for the ETA PC20, I have only registered my ETA PU at meineta and thus am not sure, that they support the same REST commands.

**Comment by nottheedge** [comment]
Hi, I'm also using 8080. Can I somehow send you an email or PM? I don't want to share the Restful-API by ETA here.

**Comment by hubermi** [comment]
I sent you an email to the address in your github profile.

**Comment by hubermi** [comment]
With support of @nottheedge it turns out that the plugin currently only works for eta pu units, as other products of eta habe different REST urls for the same information.

I need to change the implementation to support any eta product. As long as this has not been finished, please do not review the PR

**Comment by nottheedge** [comment]
Are you gonna updating the addon?

**Comment by martinvw** [comment]
You can leave it open, but please keep us updated of the status now and then.

**Comment by martinvw** [comment]
@hubermi  Any updates on this PR? Thanks for you time!

**Comment by triller-telekom** [comment]
@hubermi Any update on the status of your PR?

**Comment by triller-telekom** [comment]
@hubermi: A friendly ping :) Did you see my last comment?

**Comment by davidgraeff** [comment]
Closing because original author disappeared

**Pull request closed without merging**
