### PR TITLE
Adds a new delayed polling option (needed for ZWaveApplicationStatusC…

### PR DESCRIPTION
**Pull request by digitaldan**
…lass.java)

Signed-off-by: Dan Cunningham <dan@digitaldan.com>

### CODE REVIEW

**Comment by digitaldan** [comment]
@cdjackson I moved a very important part of the binding (polling) around, I just read and re-read my changes to make sure I didn't screw something up, but who knows ;-)  I just put this on my home system to let bake, looks good so far, but i'll keep an eye on it.  let me know what you think.

**Comment by cdjackson** [comment]
Thanks Dan. I’ll take a look. The current polling scheme was really a bit of a ‘quick hack’ so if you’ve improved that as well, then great stuff :)

**Comment by cdjackson** [comment]
@digitaldan I think you forgot to commit the event class....

**Comment by digitaldan** [comment]
@cdjackson thanks, just re-pushed

**Comment by cdjackson** [comment]
Thanks Dan.

I think I'm generally happy with this. I guess just one question I have is that we should put a limit on the delayed poll - in the order of seconds, or tens of seconds. My concern is that currently, routine polling gets disabled while delayed polling is enabled, so if somehow a delayed poll gets set for a long time in future, then all polling is stopped...  I don't think there's a need to have anything longer than (say) 10 seconds - is there?

**Comment by digitaldan** [comment]
Funny, I was just thinking about that too, I was going down a much more complicated road, I like your suggestion better, 10 seconds sounds safe, my guess is most devices only need one or two seconds. Give me a few mins to modify this PR

**Comment by digitaldan** [comment]
@cdjackson how does that look?

**Comment by cdjackson** [comment]
Looks good. I’ll merge it tomorrow evening so I can test it in the evening (didn’t get a chance tonight).

Cheers
Chris

**Comment by cdjackson** [comment]
Hey Dan. FYI, due to implementing the manual refresh command tonight, I decided to consolidate all poll timers into a single timer. So, I removed the specific poll timer, and now the delayed poll simply calls 'startPolling', but I implement the initial delay.

So, any poll, either a manual REFRESH, or a delayed poll (or any other polling we ultimately need) will simply restart polling with the initial delay...  This just seemed easier than having another poll thread, or hijacking the original, or...

Cheers
Chris

**Comment by digitaldan** [comment]
Sounds good Chris, I was hesitant to mess with the polling code, but agree that is a better solution then two competing executors.

**Pull request merged**
