### PR TITLE
Corrected references to tycho

### PR DESCRIPTION
**Pull request by martinvw**
Maven really needs to use the placeholder consistently otherwise it will not resolve.

cc: @pfink

### CODE REVIEW

**Comment by wborn** [comment]
Can it also be replaced in `addons/io/org.openhab.io.transport.modbus.test/pom.xml` @martinvw?

Looks like the binding test archetype always creates POMs without the `${tycho-groupid}` variable. So unless that is addressed, we resort to manually replacing it with PRs similar to this one. :disappointed:

**Comment by martinvw** [comment]
> Can it also be replaced in addons/io/org.openhab.io.transport.modbus.test/pom.xml @martinvw?

Yes it was waiting for a force push :-D

**Comment by pfink** [comment]
Mhm, for what is this variable needed @martinvw?

**Comment by martinvw** [comment]
I vagualy remember that we once played with resolving a similar warning in a similar way, maybe I’m wrong😊

**Pull request merged**
