### PR TITLE
[openhabcloud] How to install the add-on

### PR DESCRIPTION
**Pull request by dougmcdorman**
It wasn't obvious where to find this in the pile of add-ons so adding a one liner to tell people (beginners) where to find it.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
I would want to avoid adding such a line in every single add-on documentation - especially as Paper UI is just one mechanism, while there are other options as well.
It makes much more sense to have it explained ONCE in the docs (like the top of https://docs.openhab.org/addons/index.html) for all add-ons.

I assume your problems to find it were due to the "Misc" category. Possibly the docs menu should be better aligned with the Paper UI categories - it is not obvious that https://docs.openhab.org/addons/io.html corresponds to "Misc" and not all entries there actually are add-ons. @ThomDietrich, wdyt?

**Comment by ThomDietrich** [comment]
Hello @dougmcdorman 👋 
thank you very much for your contribution.
This kind of addition to the README is imho not ideal. A user of openHAB should know how addons are managed and installed in openHAB. With that presumption in mind it is (a) counterintuitive and confusing to specifically go into those details in the add-on README and/or (b) make sure every/none other add-on READMEs contain the same details.

Long story short: I understand why you came here and are willing to add these details. How about a different approach! 😉 Could you rewrite your sentence to something along the line of

> The "openHAB Cloud Connector" is an optional add-on and can e.g. be found in the "Misc" add-ons section of Paper UI.

@kaikreuzer I was already typing when you posted your answer. As you can see I basically agree with you but also want to satisfy the problem @dougmcdorman was facing before going through the effort of creating the PR.

Regarding your question: Yes that is a fair point. There are quite a few other thing I currently dislike in the menu structure and I already thought of some improvement which I wanted to tackle as soon as https://github.com/eclipse/smarthome/issues/4503 was settled. This issue would go a long way in making a few things possible/easier in docs.openhab.org It's a shame it isn't attracting as much attention as I expected...

Creating a docs issue for what you said right now.

**Comment by kaikreuzer** [comment]
@ThomDietrich I understood your "Zaunpfahl" 😉

**Comment by wborn** [comment]
Shall we close this PR and create issues in the docs/website project if it still remains unclear for people how to install each and every addon?

It should be possible for the website to generate some information for each addon how it can be installed in various UIs or using text files. I.e. similar to how it already generates a link for creating a PR for editing documentation.

**Comment by Confectrician** [comment]
+1 @wborn 
, thi sis really nothing that should be handled for each binding individually. :)

**Comment by wborn** [comment]
I've created https://github.com/openhab/website/issues/152 for generating add-on installation instructions on the website.

**Pull request closed without merging**
