### PR TITLE
[MQTT Generic]Update documentation

### PR DESCRIPTION
**Pull request by crxporter**
Update documentation to show generic ".items" file item - for help figuring the channel structure of the items file.

Fixed issues with heatpump example.

### CODE REVIEW

**Comment by crxporter** [comment]
As for the proper order - no I am not sure. I’m waiting for confirmation from someone, I expected you’d know. One thing I am sure of is that the way I put it works. 

As for the heat pump example adding the /state is because this example is worded like it’s meant to teach users how to convert MQTT 1 items to MQTT 2 items. The /state is in the MQTT 1 item so if you take it as an exact example - it won’t work. 

Also I adjusted the channel order in the heat pump example, perhaps both ways work. I’d like to know the “proper way” or correct way. 

I started the topic on the community site at the same time I was making the pull request. I’ll update as I learn more - hopefully someone has answers about how this should look.

**Comment by hakan42** [comment]
> As for the proper order - no I am not sure. I’m waiting for confirmation from someone, I expected you’d know. One thing I am sure of is that the way I put it works.

I believe this really depends on whether you create the broker Thing via .things file or via the GUI. And also, whether you have the Bridge and generic Thing in one file or split up into multiple seperate ones.

I would test each of those setups in isolation to make really sure that the item structure is the same.

**Comment by crxporter** [comment]
> I believe this really depends on whether you create the broker Thing via .things file or via the GUI. And also, whether you have the Bridge and generic Thing in one file or split up into multiple seperate ones.
I'm working through this now. I have a working setup with one individual sonoff - no other items, mosquitto MQTT broker at localhost. 

Test 1 was to switch the channel structure to:
`mqtt:<Broker_Name>:topic:<Thing_Name>:<Channel_Name>`
This is how the heat pump example shows the setup - it **does not work** for me.

Test 2 was to change my setup to match the Thing structure of the heat pump example:
`Thing mqtt:topic:mything {......`
This **did not work** at all for me in any configuration - I believe it to be another error in the heat pump example that should be fixed.

If we reference the discussion [here](https://community.openhab.org/t/sonoff-tasmota-with-mqtt-binding-2-4-using-config-files/61494) then we would need some adjustments to the heat pump example so that line looks like:
`Thing topic mything "Heat Pump" {......`

Do you have an example of how the channel structure and thing file will work if the bridge is added via GUI? I don't see examples for that anywhere - it seems people are using ONLY GUI or ONLY config files.

I'm a config file guy so it's troubling to me to see non-functioning examples on the main binding page.

I'm off to work, I'll check this during lunch to see if anyone else has comments. As it stands I think the sub-heading "Converting and MQTT1 installation" should be worked on some more. If nobody disagrees I'll work on it and add it to this pull request.

Also about the channel example in line 265 - this does work and is correct (the "other way" is not correct) when using .things files to configure a broker as a bridge. I'll add a comment to that effect - explaining that this works when using .things files rather than have it appear as a universally correct example.

**Comment by davidgraeff** [comment]
>  see non-functioning examples

And I'm very grateful that you tackle these. I was kind of forced to put textual examples in, although I don't use text files at all. And I have patched out .thing/.item file support in my personal setup, so I can't test textual examples even if I wanted to.

**Comment by crxporter** [comment]
I dug more into the example in the community thread showing how to convert MQTT 1.x to 2.x items using things files and noticed others had tried the conversion similar to the heat pump example and it did not work. @davidgraeff  - your comment [here](https://community.openhab.org/t/sonoff-tasmota-with-mqtt-binding-2-4-using-config-files/61494/20?u=crxporter) is my reasoning for the new changes.

As for the topic structure - it works, I've tested myself and not seen any working example that doesn't start "mqtt:topic:" for the .items file. 

Finally I'm sticking with the addition of /state in the heat pump example because that section of documentation is meant to be a quick tutorial in changing from 1.x to 2.x.

**Comment by davidgraeff** [comment]
> Finally I'm sticking with the addition of /state 

No objections. We recently had a lot of users not familiar with MQTT and they assumed at some point that "/state" is required for MQTT to retrieve states. I wanted a counter example, but I guess those people should just read up on MQTT as a general rule.

**Comment by crxporter** [comment]
> No objections. We recently had a lot of users not familiar with MQTT and they assumed at some point that "/state" is required for MQTT to retrieve states. I wanted a counter example, but I guess those people should just read up on MQTT as a general rule.

If we want to "teach them" we can remove /state in both the 1.x and 2.x example?

**Comment by davidgraeff** [comment]
> If we want to "teach them" we can remove /state in both the 1.x and 2.x example?

Yup that would be sweet

**Comment by crxporter** [comment]
I think this should be ready now. If everyone could please review that'd be great!

**Comment by davidgraeff** [comment]
Could you please add the sign-off-by line to your commits or leave that line as a comment.

**Comment by crxporter** [comment]
> Could you please add the sign-off-by line to your commits or leave that line as a comment.

I'm going to be honest - I just spent like 10 minutes trying to figure out where I need to add a line and what it needs to look like but I have no idea.

How do I add this?

**Comment by davidgraeff** [comment]
Thanks

**Pull request merged**
