### PR TITLE
Don't cache data points of reconfigurable channels.

### LINKED ISSUE #2930: [Homematic] Data point enumeration potentially incorrect for HM-MOD-EM-8
## Bug description
When having two (or more) HM-MOD-EM-8 whose switches are configured to differing button modes (e.g. some are configured to button mode, others to sensor mode), the data points of the one discovered last are enumerated incorrectly: the data points of the channels of the first instance are inherited all other instances, even though switching modes causes different data points to appear

For sensor mode, result of getParamsetDescription for VALUES is this (fetched with https://github.com/hobbyquaker/binrpc)
```json
{
  "INSTALL_TEST": {
    "FLAGS": 3,
    "ID": "INSTALL_TEST",
    "MAX": true,
    "MIN": false,
    "OPERATIONS": 4,
    "TAB_ORDER": 0,
    "TYPE": "ACTION",
    "UNIT": ""
  },
  "LOWBAT": {
    "CONTROL": "NONE",
    "FLAGS": 1,
    "ID": "LOWBAT",
    "MAX": true,
    "MIN": false,
    "OPERATIONS": 5,
    "TAB_ORDER": 1,
    "TYPE": "BOOL",
    "UNIT": ""
  },
  "STATE": {
    "CONTROL": "DOOR_SENSOR.STATE",
    "FLAGS": 1,
    "ID": "STATE",
    "MAX": true,
    "MIN": false,
    "OPERATIONS": 5,
    "TAB_ORDER": 2,
    "TYPE": "BOOL",
    "UNIT": ""
  }
}
```

while in button mode, it's this:

```json
{
  "INSTALL_TEST": {
    "FLAGS": 3,
    "ID": "INSTALL_TEST",
    "MAX": true,
    "MIN": false,
    "OPERATIONS": 4,
    "TAB_ORDER": 0,
    "TYPE": "ACTION",
    "UNIT": ""
  },
  "PRESS_CONT": {
    "FLAGS": 3,
    "ID": "PRESS_CONT",
    "MAX": true,
    "MIN": false,
    "OPERATIONS": 4,
    "TAB_ORDER": 1,
    "TYPE": "ACTION",
    "UNIT": ""
  },
  "PRESS_LONG": {
    "CONTROL": "BUTTON.LONG",
    "FLAGS": 1,
    "ID": "PRESS_LONG",
    "MAX": true,
    "MIN": false,
    "OPERATIONS": 4,
    "TAB_ORDER": 2,
    "TYPE": "ACTION",
    "UNIT": ""
  },
  "PRESS_LONG_RELEASE": {
    "FLAGS": 3,
    "ID": "PRESS_LONG_RELEASE",
    "MAX": true,
    "MIN": false,
    "OPERATIONS": 4,
    "TAB_ORDER": 3,
    "TYPE": "ACTION",
    "UNIT": ""
  },
  "PRESS_SHORT": {
    "CONTROL": "BUTTON.SHORT",
    "FLAGS": 1,
    "ID": "PRESS_SHORT",
    "MAX": true,
    "MIN": false,
    "OPERATIONS": 4,
    "TAB_ORDER": 4,
    "TYPE": "ACTION",
    "UNIT": ""
  }
}
```

The caching done at https://github.com/openhab/openhab2-addons/blob/2.1.0/addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/AbstractHomematicGateway.java#L400 only takes device type, firmware version and channel number into account, which is the same for all devices.

## Possible Solution
Not sure whether there's a proper way to detect such channels with 'dynamic' data points. If not, caching should be disabled for HM-MOD-EM-8 devices.

## Your Environment
In my case, I have one device where 4 channels are configured to sensor mode and another one where all 8 channels are configured to button mode: in that scenario, the data points of the former device are also used for the latter device, which means I can't use the button events of the first 4 channels of the latter device.

### PR DESCRIPTION
**Pull request by maniac103**
Channels that allow changing their type (e.g. the KEY channels in
HM-MOD-EM-8) have different data point sets depending on the selected
function. If multiple of such devices are present and are configured to
have differing functions, caching the data points of those channels can
lead to us enumerating wrong data points, as the configuration of the
first device will be implied for all subsequent devices.

Closes #2930

### CODE REVIEW

**Comment by maniac103** [comment]
@gerrieg Does this make sense to you? I've only compile time tested so far - I seem to be unable to compile the 2.1 sources, which I'd need for producing a jar compatible with my 2.1 installation :-(

**Comment by maniac103** [comment]
OK, I've verified this works by running master on my PC (instead of 2.1 on my server). Data points are detected correctly now. An additional optimization would be re-fetching the data points if the value of CHANNEL_FUNCTION changes.

**Comment by kaikreuzer** [comment]
@gerrieg Could you quickly review this change?

**Comment by maniac103** [comment]
Presumably this is the actual fix for #1870 BTW.

**Comment by gerrieg** [comment]
@maniac103 
I don't have this device, so i can not verify. The CHANNEL_FUNCTION is a MASTER datapoint and not updated by the CCU if it changes. You have to send a REFRESH to any channel of the device to reload all values.
Can you please try it if it works with a REFRESH?

**Comment by maniac103** [comment]
@gerrieg This patch is *not* about dynamic redetection of a reconfiguration of the channel function. It's about getting multiple HM-MOD-EM-8 devices with differing (but static) configurations detected *at all*.

Scenario is this (for me):
- one HM-MOD-EM-8 configured as 4x window contact, 4x button ('device 1')
- another HM-MOD-EM-8 configured as 8x button ('device 2')
- when I add a device, all device descriptions are fetched [1], device 1 happens to be before device 2 in that list
- channels of device 1 are loaded, thus 4 window contact channels + 4 button channels are detected and cached under the key 'HM-MOD-EM-8:2.5:x' (with x being 1..8) [2]
- when channels of device 2 are loaded, the channel keys happen to match those of device 1, thus the previously cached data point set is used [3] _even if it doesn't match the actual data point set for channels 1-4_

That scenario is what I'm aiming at fixing here. I'm aware it's incomplete (because the dynamic reconfiguration detection is missing), but it allows using both devices in that scenario, which wasn't previously possible. As mentioned before, I'm not familiar enough with the code base to make dynamic reenumeration of the thing channels on device channel reconfiguration work, but I'm happy to do tests of any patches you might come up with. For starters, what exactly do you mean by 'works with a REFRESH'?

[1] https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/AbstractHomematicGateway.java#L343
[2] https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/AbstractHomematicGateway.java#L375
[3] https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/AbstractHomematicGateway.java#L370

**Comment by gerrieg** [comment]
OK, i got it, thanks for the clarification

**Comment by kaikreuzer** [comment]
Thank you both!

**Pull request merged**
