### PR TITLE
Astro: Added astro event offset channel property

### PR DESCRIPTION
**Pull request by gerrieg**
Signed-off-by: Gerhard Riegler <gerhard.riegler@gmail.com>

### CODE REVIEW

**Comment by jupe76** [comment]
Thank you very much @gerrieg for adding the long awaited events and the possibility to add an offset.
One question about setting offsets: can I do this also programatical in a rule, or is the only way to set an offset in an .item configfile?

**Comment by gerrieg** [comment]
You can do this via PaperUI, just open 'Configure Channel' for the event channel

**Comment by Ferryb** [comment]
Dear Gerhard,

Can you give an example of how to use the offset?
In paper UI, I get an error 409 when I try to fill in some.

thanks

**Comment by kaikreuzer** [comment]
> In paper UI, I get an error 409 when I try to fill in some.

Not, if you create the Thing through the Paper UI (and not through a *.things file)

**Comment by ThomDietrich** [comment]
> set an offset in an .item configfile?

@gerrieg I'd be interested in this information as well.

**Pull request merged**
