### PR TITLE
Hue emulation: Extend AbstractHueState

### PR DESCRIPTION
**Pull request by davidgraeff**
Add "mode" and "alert" for a better hue emulation.

Signed-off-by: davidgraeff <david.graeff@web.de>

### CODE REVIEW

**Comment by martinvw** [comment]
@davidgraeff so that is this one?

**Comment by martinvw** [comment]
@davidgraeff hmm, not easy ton track back your ways ;-)

**Comment by davidgraeff** [comment]
No, it is this one: https://github.com/openhab/openhab2-addons/pull/4216

**Comment by martinvw** [comment]
Great, thanks!

**Pull request merged**
