### PR TITLE
use consistent typo of 'add-ons' for working sets

### PR DESCRIPTION
**Pull request by maggu2810**

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Why typo? Add-ons is the correct spelling :-)

**Comment by maggu2810** [comment]
Currently there is used Addons AND Add-ons. So do you prefer to use Add-ons?

**Comment by maggu2810** [comment]
Working set names:
* OH1 Addons
* OH2 Add-ons

**Comment by maggu2810** [comment]
So, I will change "OH1 Addons" to "OH1 Add-ons"

**Comment by kaikreuzer** [comment]
Hm, but your PR changes "OH1 Add-ons" to "OH1 Addons" here: https://github.com/openhab/openhab2-addons/pull/607/files#diff-47e0fa0b5f44fde887971a99356c610aR2338

**Comment by kaikreuzer** [comment]
Ah, but not for the working set, I see.

**Comment by maggu2810** [comment]
That is the project label, not the working set name...

**Comment by maggu2810** [comment]
changed it

**Comment by kaikreuzer** [comment]
thx

**Pull request merged**
