### PR TITLE
[yamaha] netradio navigation fix

### PR DESCRIPTION
**Pull request by dfrommi**
There are Yamaha AVRs like the RX-V777 that are using input name  `NET RADIO` (space separated) and not `NET_RADIO` (underscore separated). Consequently navigation and playback control are not working.
This PR adds the space-separated spelling as alternative to the list of supported inputs.

Additionally, special zone status like playback, DAB, navigation status were only refreshed when the input has changed. It is now done periodically, if the input supports it.

### CODE REVIEW

**Comment by martinvw** [comment]
@davidgraeff can you take a look at this PR?

**Comment by davidgraeff** [comment]
lgtm. do we want to replace guava by java8 streams here?

**Comment by martinvw** [comment]
always :-)

**Comment by davidgraeff** [comment]
@dfrommi Can you use Stream.of(....).collect(Collectors.toSet()) instead of the Sets class from guava?

You can also squash the commits, and sign them with the "-s" git command line flag if possible :)

**Comment by dfrommi** [comment]
@davidgraeff Thanks for your feedback. 
I've changed the `Set` initialisation in the files I've touched and also signed the commits. But I would rather not like to squash them. They are doing entirely different things. So differnent that I've even considered opening 2 PRs.

Do you have any idea why the `code-review/pullapprove` is showing an error? My commits are both containing `Signed-off-by`.

**Comment by martinvw** [comment]
> Do you have any idea why the code-review/pullapprove is showing an error? My commits are both containing Signed-off-by.

Most common cause is committing with a different email than your sign-off

**Comment by martinvw** [comment]
Thanks to both of you!

**Pull request merged**
