### PR TITLE
[WIP] Material Icon Set - Initial contribution. Closes #2139

### LINKED ISSUE #2139: Material Design Icons
Following the [forum thread](https://community.openhab.org/t/material-design-icons/26259), I'm proposing an icon set that uses [material design icons](https://materialdesignicons.com). Depending on the license (IANAL) we can include it in openHAB or Eclipse SmartHome.

Classic icons can be browsed here: https://github.com/eclipse/smarthome/tree/6dd1df77136a70ec55da6746be05bf65b78ba15b/extensions/ui/iconset/org.eclipse.smarthome.ui.iconset.classic/icons
Material icons can be browsed here: https://github.com/Templarian/MaterialDesign/tree/master/icons/svg

### PR DESCRIPTION
**Pull request by kubawolanin**
This is a work in progress branch with an attempt to create a Material icon set - a superset of the [classic icon set](http://docs.openhab.org/addons/iconsets/classic/readme.html) with [Material Design Icons](https://materialdesignicons.com/) to be used within openHAB.

The set still needs to be remapped to reflect @kaikreuzer's [changes](https://github.com/openhab/openhab2-addons/issues/2139#issuecomment-331102810) observable on [this page](https://www.eclipse.org/smarthome/documentation/features/ui/iconset/classic/readme.html) .

Signed-off-by: Kuba Wolanin <hi@kubawolanin.com>

### CODE REVIEW

**Comment by martinvw** [comment]
@kubawolanin it has build failures, I did not check the cause

**Comment by kubawolanin** [comment]
Hey @martinvw thanks! I noticed that too. It's in a rough state now, I'll clean it up later on.

**Comment by kaikreuzer** [comment]
Hey @kubawolanin, good news: I received an answer from the Eclipse IP team that the license is fine for Eclipse projects - so please move your work to ESH and create the PR which adds the iconset to https://github.com/eclipse/smarthome/tree/master/extensions/ui/iconset - thanks!

**Comment by kaikreuzer** [comment]
@kubawolanin Once the ESH PR is created, please don't miss to link it here :-)

**Pull request closed without merging**
