### PR TITLE
[autelis] Removed Guava dependency

### PR DESCRIPTION
**Pull request by cweitkamp**
- Removed Guava dependency

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by cweitkamp** [comment]
Waiting for #2519 and #3922.

**Comment by digitaldan** [comment]
Thanks @cweitkamp I must have accidentally pulled that in with eclipse auto complete!  Would not have pulled in Guava on purpose for one little utility method!

**Comment by cweitkamp** [comment]
@wborn as the license updates created conflicts anyways should we think about merging this PR - and all other PRs which will remove Guava dependencies - too? wdyt?

**Comment by cweitkamp** [comment]
@wborn Rebase done.

**Pull request merged**
