### PR TITLE
[hue] Add support for TransitionTime

### PR DESCRIPTION
**Pull request by xLAva**
Implemented fade time config for light things.
Implemented fade time channel for dynamically changing the fade times of light things.

Bug: #1722
Signed-off-by: Jochen jochen.leopold@model-view.com

### CODE REVIEW

**Comment by wborn** [comment]
It's fixing https://github.com/eclipse/smarthome/issues/1722.

**Comment by xLAva** [comment]
The PR-openHAB2-Addons Jenkins build failed.
I checked the log and it looks like it was not related to my pull request.

**Comment by kaikreuzer** [comment]
Thanks for this PR! (I have re-run the PR build, now it is green)

It lgtm, my only concern is the new fade time channel: I do not think that we should add channels for adjusting configurations. This looks like a very ugly workaround and imho we should not create a precedence.

I'd therefore prefer to remove it and rather discuss how we could make it possible through rules to change channel configurations, which would be the proper solution to the problem.

**Comment by xLAva** [comment]
I can understand your concerns.
I can split it up and only PR the configuration part.

But I really would like a dynamic way of controlling the fade time.
In my private use cases, I change the fade time for a single light nearly on a command basis.

The channel implementation was of course a workaround. My favorite solution would be to have control over the fade time with each light command send to the light.

I’m just not familiar enough with the code-base to know a better solution to accomplish this. The usage of a channel seemed like an easy solution.

Maybe your suggestion about the rules could be a way. Can you tell me more about that approach?
Or do you have another idea how to pack an additional value into the existing commands?
A wrapper command maybe?

**Comment by t-8ch** [comment]
This discussion would also be relevant for the ZigBee binding (cc @cdjackson) .
See also eclipse/smarthome#6755

**Comment by kaikreuzer** [comment]
No, I don't think so. The new potential feature of changing channel configurations through rules is not specific to any binding, but would be applicable to all - so this would be a framework feature and nothing to be added to each and every binding.

**Comment by xLAva** [comment]
But I actually don't want to change the configuration. I want to send a Light command with a specific fadetime and just ignore the configuration for that one command.

**Comment by kaikreuzer** [comment]
Ok, yes, for parametrized commands, the ThingActions are the way to go.

**Comment by kaikreuzer** [comment]
Thanks, looks good to me!

Just one last request: Could you please also add the new features to the README.md?

**Comment by xLAva** [comment]
Sure thing. Will do it tomorrow.

**Comment by xLAva** [comment]
The README.md is updated in the new PR.

**Comment by xLAva** [comment]
The PR-openHAB2-Addons Jenkins build failed again. Doesn't look like an issue with my changes.

**Comment by kaikreuzer** [comment]
Thanks! The only thing you forgot is to also add the transitionTime configuration parameter to the README :-)

**Comment by xLAva** [comment]
You are right. Sorry about that. Added the configuration parameter documentation with the newest PR.

**Comment by xLAva** [comment]
Thank you for the fast feedback comments. :-)

**Pull request merged**
