### PR TITLE
Rework add-libraries profile for CLI and Eclipse

### PR DESCRIPTION
**Pull request by wborn**
There is an issue in the addjars-maven-plugin that it modifies the basepath:

https://code.google.com/archive/p/addjars-maven-plugin/issues/8

Because the lib dir is used with `${.}` it is relative to the base path
(required for Windows, see #5196). The addjars-maven-plugin doesn't run in Eclipse
because it has no m2e lifecycle mapping. bnd tools now has issues including the
resources in Eclipse. This generates error messages for such projects in Eclipse.

For now the best solution seems to disable this profile in Eclipse. :disappointed:

### CODE REVIEW

**Comment by davidgraeff** [comment]
That renders all addons unusable for editing in eclipse. But we could have a build.properties file to include the lib directory additionally for eclipse can't we?

**Comment by wborn** [comment]
An extra profile for Eclipse also seems to work. :-)

**Comment by davidgraeff** [comment]
@wborn Could you participate the in the @openhab/2-x-add-ons-maintainers team vote please? :)

**Comment by wborn** [comment]
I already did. Check the names in thumbs up :+1:

**Pull request merged**
