### PR TITLE
[Gardena] Ignore known gateway properties

### PR DESCRIPTION
**Pull request by gerrieg**
Signed-off-by: Gerhard Riegler <gerhard.riegler@gmail.com>

Gardena added some properties to the gateway, they can be ignored.

Closes https://github.com/openhab/openhab2-addons/issues/4265

### CODE REVIEW

**Comment by kaikreuzer** [comment]
What does "isConnected" do? At a first glance, it sounds valuable e.g. for deriving a Thing ONLINE/OFFLINE status, no?

**Comment by gerrieg** [comment]
It's the status of the ethernet/wifi connection of the gateway. The gateway is not used as a Thing so we can ignore it.

**Comment by kaikreuzer** [comment]
Well, if the gateway is not connected, we can for sure also set the mower etc. to OFFLINE. Or is this already the case now?

**Comment by gerrieg** [comment]
Good objection, I'll implement it.

**Comment by kaikreuzer** [comment]
Ok, makes sense.

**Comment by stefan-hoehn** [comment]
I am still seeing this while trace is on:

"[WARN ] [model.deser.PropertyValueDeserializer] - Unsupported json value object, returning empty value"

I didn't get that message before installing the gardena binding. 
The binding version is **2.4.0M4**

I am not sure if the following has something to do with the gateway properties though:

```javascript
{  
   "devices":[  
      {  
         "id":"12345678-e48b-47c8-a103-0513dee2bc16",
         "name":"Gardena Gateway",
         "description":"Gateway device",
         "category":"gateway",
         "configuration_synchronized":true,
         "abilities":[  
            {  
               "id":"12345678-b5e2-11e5-b6a5-32212aec0665",
               "name":"device_info",
               "properties":[  
                  {  
                     "id":"12345678-b5e2-11e5-b6a5-100000000000",
                     "name":"manufacturer",
                     "value":"Seluxit",
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"12345678-b5e2-11e5-b6a5-100000000001",
                     "name":"product",
                     "value":"1-GATEWAY",
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"12345678-b5e2-11e5-b6a5-100000000002",
                     "name":"serial_number",
                     "value":"N/A",
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"12345678-b5e2-11e5-b6a5-100000000003",
                     "name":"sgtin",
                     "value":"N/A",
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"12345678-b5e2-11e5-b6a5-100000000004",
                     "name":"connection_status",
                     "value":"unknown",
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"12345678-b5e2-11e5-b6a5-100000000005",
                     "name":"ethernet_status",
                     "value":{  
                        "mac":"94:BB:AE:17:21:0B",
                        "ip":"192.168.178.166",
                        "isconnected":"true"
                     },
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"12345678-b5e2-11e5-b6a5-100000000006",
                     "name":"wifi_status",
                     "value":{  
                        "ssid":{  

                        },
                        "mac":"94:BB:AE:17:21:6F",
                        "ip":{  

                        },
                        "isconnected":"false",
                        "signal":"0%"
                     },
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"12345678-b5e2-11e5-b6a5-100000000007",
                     "name":"version",
                     "value":"3.4.11",
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"12345678-b5e2-11e5-b6a5-100000000008",
                     "name":"category",
                     "value":"gateway",
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"12345678-b5e2-11e5-b6a5-100000000009",
                     "name":"last_time_online",
                     "value":"N/A",
                     "writeable":false,
                     "supported_values":[  

                     ]
                  }
               ],
               "type":"device_info"
            },
            {  
               "id":"87654321-b5e4-11e5-86c5-32212aec0665",
               "name":"gateway",
               "properties":[  
                  {  
                     "id":"87654321-b5e4-11e5-86c5-100000000000",
                     "name":"ip_address",
                     "value":"192.168.178.166",
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"87654321-b5e4-11e5-86c5-100000000001",
                     "name":"time_zone",
                     "value":"Europe/Zurich (CEST, +0200)",
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"87654321-b5e4-11e5-86c5-100000000002",
                     "name":"homekit_setup_payload",
                     "value":"",
                     "writeable":false,
                     "supported_values":[  

                     ]
                  }
               ],
               "type":"gateway"
            }
         ],
         "configuration_synchronized_v2":{  
            "value":true,
            "timestamp":"2019-08-03T11:39:06.662Z"
         },
         "configuration_update":{  
            "status":"synchronized",
            "timestamp":"2019-08-03T11:39:06.662Z"
         },
         "constraints":[  

         ],
         "device_state":"ok",
         "property_constraints":[  

         ],
         "scheduled_events":[  

         ],
         "scheduling_wizard_mowing":null,
         "settings":[  

         ],
         "status_report_history":[  

         ],
         "zones":[  

         ]
      },
      {  
         "id":"abcdef12-64e4-487f-9bde-4a9f69c5d4a4",
         "name":"Water Control vorne",
         "category":"watering_computer",
         "configuration_synchronized":true,
         "abilities":[  
            {  
               "id":"abcdef13-0cfa-385b-a0e7-21f2ec2a4a0d",
               "name":"device_info",
               "properties":[  
                  {  
                     "id":"abcdef14-1029-3d6a-89fa-fa0de976f320",
                     "name":"manufacturer",
                     "value":"Gardena",
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"abcdef15-cd98-349e-86f8-3b2d90cf31c9",
                     "name":"product",
                     "value":"1-DEVICE",
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"abcdef16-ead4-3f13-bd12-69f586c79c80",
                     "name":"serial_number",
                     "value":"00055925",
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"abcdef17-0e45-3170-992a-7c913b901df2",
                     "name":"version",
                     "value":"0.3.5-2.5.2-1.2.5-1.1.2",
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"abc8ef12-0a81-36a4-8845-7291c8d17a05",
                     "name":"category",
                     "value":"watering_computer",
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"abcdef19-c36a-30e9-8f07-9abf43c50461",
                     "name":"last_time_online",
                     "value":"2019-08-03T14:02:02.476Z",
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"abcdef1a-9158-34e5-bc26-ca6e2974ef5a",
                     "name":"sgtin",
                     "value":"3034F8EE90126D400000DA75",
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"abcdef1b-f5e8-3212-9d2e-d44571a29b4c",
                     "name":"connection_status",
                     "value":"online",
                     "writeable":false,
                     "supported_values":[  

                     ]
                  }
               ],
               "type":"device_info"
            },
            {  
               "id":"abcdef21-7ab7-3ec1-be69-a1cf2471c190",
               "name":"battery",
               "properties":[  
                  {  
                     "id":"abcdef22-1261-3efa-a4de-cef609aaf153",
                     "name":"level",
                     "timestamp":"2019-08-03T13:58:08.229Z",
                     "unit":"%",
                     "value":91,
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"abcdef23-8162-3feb-a249-a839a941fac9",
                     "name":"disposable_battery_status",
                     "timestamp":"2019-08-03T13:31:22.250Z",
                     "value":"ok",
                     "writeable":false,
                     "supported_values":[  
                        "out_of_operation",
                        "replace_now",
                        "low",
                        "ok",
                        "undefined"
                     ]
                  }
               ],
               "type":"battery_power"
            },
            {  
               "id":"abcdef31-106a-3cb8-853c-0e3c7120e742",
               "name":"radio",
               "properties":[  
                  {  
                     "id":"abcdef32-50db-33e3-b393-672fcfd0bab5",
                     "name":"quality",
                     "timestamp":"2019-08-03T13:31:22.275Z",
                     "unit":"%",
                     "value":60,
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"abcdef32-3475-3c52-88f5-e61f7d6e6cdd",
                     "name":"connection_status",
                     "timestamp":"2019-08-03T14:14:07.341Z",
                     "value":"unknown",
                     "writeable":false,
                     "supported_values":[  
                        "unknown",
                        "status_device_unreachable",
                        "status_device_alive"
                     ]
                  },
                  {  
                     "id":"abcdef33-b15a-3d53-8459-863808142b83",
                     "name":"state",
                     "timestamp":"2019-08-03T13:31:22.285Z",
                     "value":"good",
                     "writeable":false,
                     "supported_values":[  
                        "bad",
                        "poor",
                        "good",
                        "undefined"
                     ]
                  }
               ],
               "type":"radio_link"
            },
            {  
               "id":"abcdef41-57b6-3b6c-a7b0-a1805920120e",
               "name":"outlet",
               "properties":[  
                  {  
                     "id":"abcdef42-6f85-3137-bce5-fdd6b8bcc148",
                     "name":"valve_open",
                     "timestamp":"2019-08-03T14:02:02.476Z",
                     "value":false,
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"abcdef43-b945-3126-aad4-1307dcc68107",
                     "name":"manual_override",
                     "timestamp":"2019-08-03T14:02:02.490Z",
                     "value":"inactive",
                     "writeable":true,
                     "supported_values":[  
                        "inactive",
                        "open",
                        "undefined"
                     ]
                  },
                  {  
                     "id":"abcdef44-b64a-379b-87ca-28add0d770ec",
                     "name":"button_manual_override_time",
                     "timestamp":"2019-08-03T13:58:08.455Z",
                     "unit":"minutes",
                     "value":1,
                     "writeable":true,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"abcdef45-3a1e-33bb-bcf9-da87d2bb5686",
                     "name":"last_manual_override_time",
                     "timestamp":"2019-08-03T14:01:57.227Z",
                     "unit":"minutes",
                     "value":1,
                     "writeable":false,
                     "supported_values":[  

                     ]
                  }
               ],
               "type":"watering_outlet"
            },
            {  
               "id":"abcdef51-b7e7-3a90-b85f-b0742e0f4ddb",
               "name":"ambient_temperature",
               "properties":[  
                  {  
                     "id":"abcdef52-71cd-368f-8ed9-c963dceb7790",
                     "name":"temperature",
                     "timestamp":"2019-08-03T13:31:22.295Z",
                     "unit":"C",
                     "value":34,
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"abcdef53-2b1b-37d3-8282-5d6ae7696240",
                     "name":"frost_warning",
                     "timestamp":"2019-08-03T13:31:22.305Z",
                     "value":"no_frost",
                     "writeable":false,
                     "supported_values":[  
                        "no_frost",
                        "frost",
                        "undefined"
                     ]
                  }
               ],
               "type":"ambient_temperature_sensor"
            },
            {  
               "id":"abcdef61-a19a-3e1f-963a-f2d133120ee1",
               "name":"identification",
               "properties":[  

               ],
               "type":"identification"
            },
            {  
               "id":"abcdef62-247c-3a92-9e67-15deb5fbbb4d",
               "name":"scheduling",
               "properties":[  
                  {  
                     "id":"e16bd5b2-4d12-3ca9-9fbd-fe6ef010bdc1",
                     "name":"scheduled_watering_next_start",
                     "timestamp":"2019-08-03T14:14:07.342Z",
                     "value":null,
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"abcdef63-f786-38f6-ab1f-4ad642a02210",
                     "name":"scheduled_watering_end",
                     "timestamp":"2019-08-03T14:14:07.342Z",
                     "value":null,
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"abcdef64-7a3b-3dde-a1e8-58bf74764b8b",
                     "name":"adaptive_scheduling_last_decision",
                     "timestamp":"2019-08-03T14:14:07.342Z",
                     "value":"undefined",
                     "writeable":false,
                     "supported_values":[  
                        "undefined",
                        "watered_sensor_timeout",
                        "skipped",
                        "watered"
                     ]
                  }
               ],
               "type":"scheduling"
            },
            {  
               "id":"abcdef71-66d1-36ba-acf3-115904022b71",
               "name":"firmware",
               "properties":[  
                  {  
                     "id":"784f5731-b72c-397c-ab44-753ac0922c11",
                     "name":"firmware_status",
                     "value":"up_to_date",
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"abcdef72-b488-389c-9a77-d8091dd3852b",
                     "name":"firmware_upload_progress",
                     "value":0,
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"abcdef73-765a-3a59-8d8c-bfd019a16dd4",
                     "name":"firmware_available_version",
                     "value":"",
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"abcdef74-7fd5-3810-9472-c6c76c53b4d8",
                     "name":"inclusion_status",
                     "value":"included",
                     "writeable":false,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"abcdef75-7deb-33c5-863e-08304d144ec2",
                     "name":"firmware_update_start",
                     "value":true,
                     "writeable":true,
                     "supported_values":[  

                     ]
                  },
                  {  
                     "id":"abcdef76-1f9b-3a8b-bbf2-8b62ed62c66e",
                     "name":"firmware_command",
                     "value":"idle",
                     "writeable":true,
                     "supported_values":[  
                        "idle",
                        "firmware_cancel",
                        "firmware_flash",
                        "firmware_upload",
                        "unsupported"
                     ]
                  }
               ],
               "type":"firmware"
            }
         ],
         "configuration_synchronized_v2":{  
            "value":true,
            "timestamp":"2019-08-03T12:14:19.580Z"
         },
         "configuration_update":{  
            "status":"synchronized",
            "timestamp":"2019-08-03T12:14:19.580Z"
         },
         "constraints":[  
            {  
               "resource_name":"scheduled_events",
               "values":[  
                  {  
                     "name":"is_supported",
                     "unit":"",
                     "value":true
                  },
                  {  
                     "name":"supported_smart_features",
                     "unit":"",
                     "value":{  
                        "adaptive_scheduling_sensor_legacy":true,
                        "adaptive_scheduling_suntimings":true
                     }
                  },
                  {  
                     "name":"events_week_max",
                     "unit":"",
                     "value":18
                  },
                  {  
                     "name":"duration_max",
                     "unit":"minutes",
                     "value":600
                  },
                  {  
                     "name":"is_pausable",
                     "unit":"",
                     "value":true
                  }
               ]
            },
            {  
               "resource_name":"scheduling_wizard_watering",
               "values":[  
                  {  
                     "name":"is_supported",
                     "unit":"",
                     "value":true
                  }
               ]
            }
         ],
         "device_state":"ok",
         "property_constraints":[  
            {  
               "name":"outlet",
               "values":[  
                  {  
                     "name":"manual_override",
                     "values":[  
                        {  
                           "name":"manual_watering_range",
                           "unit":"minutes",
                           "value":{  
                              "min":0,
                              "max":59
                           }
                        }
                     ]
                  },
                  {  
                     "name":"button_manual_override_time",
                     "values":[  
                        {  
                           "name":"manual_watering_range",
                           "unit":"minutes",
                           "value":{  
                              "min":0,
                              "max":59
                           }
                        }
                     ]
                  }
               ]
            }
         ],
         "scheduled_events":[  

         ],
         "scheduling_wizard_mowing":null,
         "settings":[  
            {  
               "name":"schedules_paused_until",
               "id":"d038dca4-bf5f-4419-8d8f-37df17bad6ea",
               "value":""
            }
         ],
         "status_report_history":[  
            {  
               "level":"info",
               "message":"UP_TO_DATE",
               "raw_message":"UP_TO_DATE",
               "source":"gateway",
               "timestamp":"2019-08-03T14:08:14.888Z"
            },
            {  
               "level":"important",
               "message":"ok",
               "raw_message":"code ID: 0",
               "source":"device",
               "timestamp":"2019-08-03T13:31:22.123Z"
            },
            {  
               "level":"info",
               "message":"UP_TO_DATE",
               "raw_message":"UP_TO_DATE",
               "source":"gateway",
               "timestamp":"2019-08-03T13:30:29.376Z"
            },
            {  
               "level":"info",
               "message":"UP_TO_DATE",
               "raw_message":"UP_TO_DATE",
               "source":"gateway",
               "timestamp":"2019-08-03T13:26:10.330Z"
            },
            {  
               "level":"important",
               "message":"ok",
               "raw_message":"code ID: 0",
               "source":"device",
               "timestamp":"2019-08-03T12:55:21.226Z"
            },
            {  
               "level":"important",
               "message":"ok",
               "raw_message":"code ID: 0",
               "source":"device",
               "timestamp":"2019-08-03T12:42:53.573Z"
            },
            {  
               "level":"important",
               "message":"ok",
               "raw_message":"code ID: 0",
               "source":"device",
               "timestamp":"2019-08-03T12:34:49.708Z"
            },
            {  
               "level":"important",
               "message":"ok",
               "raw_message":"code ID: 0",
               "source":"device",
               "timestamp":"2019-08-03T12:25:23.185Z"
            },
            {  
               "level":"error",
               "message":"sleep-mode-timeout",
               "raw_message":"code ID: 7",
               "source":"device",
               "timestamp":"2019-08-03T12:20:18.189Z"
            },
            {  
               "level":"info",
               "message":"UPLOAD_COMPLETE",
               "raw_message":"UPLOAD_COMPLETE",
               "source":"gateway",
               "timestamp":"2019-08-03T12:19:46.934Z"
            },
            {  
               "level":"info",
               "message":"UPLOADING",
               "raw_message":"UPLOADING",
               "source":"gateway",
               "timestamp":"2019-08-03T12:15:18.746Z"
            },
            {  
               "level":"important",
               "message":"ok",
               "raw_message":"code ID: 0",
               "source":"device",
               "timestamp":"2019-08-03T12:14:33.361Z"
            },
            {  
               "level":"info",
               "message":"UPDATE_AVAILABLE",
               "raw_message":"UPDATE_AVAILABLE",
               "source":"gateway",
               "timestamp":"2019-08-03T12:14:17.230Z"
            },
            {  
               "level":"info",
               "message":"INCLUDED",
               "raw_message":"INCLUDED",
               "source":"gateway",
               "timestamp":"2019-08-03T12:14:17.188Z"
            },
            {  
               "level":"info",
               "message":"STATUS_DEVICE_REPORT_SUCCESS",
               "raw_message":"STATUS_DEVICE_REPORT_SUCCESS",
               "source":"gateway",
               "timestamp":"2019-08-03T12:14:17.164Z"
            },
            {  
               "level":"important",
               "message":"ok",
               "raw_message":"code ID: 0",
               "source":"device",
               "timestamp":"2019-08-03T12:14:02.350Z"
            },
            {  
               "level":"info",
               "message":"STATUS_DEVICE_REPORTING",
               "raw_message":"STATUS_DEVICE_REPORTING",
               "source":"gateway",
               "timestamp":"2019-08-03T12:14:02.165Z"
            },
            {  
               "level":"info",
               "message":"STATUS_DEVICE_INCLUSION_SUCCESS",
               "raw_message":"STATUS_DEVICE_INCLUSION_SUCCESS",
               "source":"gateway",
               "timestamp":"2019-08-03T12:14:02.149Z"
            }
         ],
         "zones":[  

         ]
      }
   ]
}
```

Note: for privacy reasons I changed all ids.

Does the JSON help you?
**Do you like me to open a new issue for that?** 

TIA
Stefan

**Pull request merged**
