### PR TITLE
[loxone] Burglar Alarm Implementation

### LINKED ISSUE #5031: [loxone] Add support for Burglar Alarm Controller
Provide the possibility to turn on/off the Burglar Alarm Controller of Loxone

### PR DESCRIPTION
**Pull request by mmattan**
[loxone] Burglar Alarm Implementation (#5031)

* [loxone] provide support for the burglar alarm of Loxone

Signed-off-by: Michael Mattan <github@mattan.be>

Resolves #5031

### CODE REVIEW

**Comment by wborn** [comment]
Thanks for your PR @mmattan! Can you review this @ppieczul?

**Comment by ppieczul** [comment]
Thanks @mmattan for the feature. I'd like to start with a discussion about the way the openHAB submits commands to this block. It looks like it is a free text over String channel replicating some of the Loxone commands. I think it may miss the ability to model the behavior of these commands using the openHAB channels and their types. Could you see how these commands could be modeled that way and design what channels this block should expose to allow for commanding it and what states they could have to represent the states in the API. I think not all Loxone commands and states have to be covered if this is not suitable to the openHAB model, but there is a good chance most of them could. Thanks.

**Comment by mmattan** [comment]
Hi @ppieczul I agree.  However, I could not find a component in OH that is able to handle those different commands.
I could not find an existing component in Loxone that does this, so I decided at the moment to implement the StringType commands so that they can be addressed from within the rules.

I will look into other bindings that have this type of setup. If you have recommendations yourself, I am all ears :)

**Comment by mmattan** [comment]
Hi @ppieczul I updated the code so that most of the StringType commands are replaced by LxControlBurglarAlarmCommand controls that are linked to a Switch Item.
This is the best I could come up with at the moment.  In case you have other suggestions, it can always be discussed.

**Comment by ppieczul** [comment]
Do you know how in practice "with/without movement" feature works? And how do we specify the value of the delay when arming the alarm? These are not entirely clear to me. 
Anyway I think we could model the channels in the following way, here is my first attempt:
Switch - alarm armed - on command arms alarm, state shows current armed state
Switch - movement - allows to configure if with or without movement. It will send dismv command to the miniserver but also change the arming commands by adding 1/0 to them (it depends if I understand how movement works right). Changes to disableMove state update state of this channel.
Number - delay - if we can configure the delay which is not clear to me from the API
Number - current alarm level. Sending zero to this channel could acknowledge the alarm (quit command)
Plus maybe some read only channels that would show other parameters described by various stages.
As for the implementation please do not create multiple LxControl objects for different channels. You can add more than one channel to the control, look at timed switch for an example.

**Comment by mmattan** [comment]
Hi @ppieczul , the with/without movement is something that is available on the alarm controller of Loxone.  When you look at the mobile app, you see 2 buttons:
- Arm
- Arm with delay

Below the button,  you see 1 checkbox: with/without movement.
When the checkbox is checked, all the movement sensors that are linked to the alarm controller are also used to detect a burglary.

I will check the TimedSwitch and see how I can map this onto the alarm controller.

**Comment by ppieczul** [comment]
Ok, so it looks like it should be possible to model it the same way with a switch for the with without movement

**Comment by mmattan** [comment]
Hi @ppieczul I revisited the code.
I just don't see how the TimedSwitch is similar to the alarm.

The TimedSwitch accepts only 1 single command: on/off, it can perfectly be mapped on a switch in OH.
The only other channel that is exposed is a Read-only number to show the delay of the switch.

The one that comes closer to the Alarm is the Jalousie.  However, for that one, there is a frontend component that is able to generate the Loxone commands (up/down/stop/...).

For the Loxone alarm, there is no single control that is able to map all the commands on 1 single frontend component.  

So what is not clear to me is: how can I create a different channel that performs another command on the alarm, without creating a different LxControl?  I must be missing something extremely obvious here...

**Comment by ppieczul** [comment]
You can create another channel exactly like in the timed switch example. There can be more than one channel of the same type. Then if you receive a command (and this is not present in timed switch as not needed there) you need to compare the channel UID against the particular channel for the control. You can get these channel IDs calling getChannelIdForControl(control, index), index will be 1,2,3,...

**Comment by ppieczul** [comment]
...and why creating another LxControl is not a good idea is that the states will get broken - the updates of the states will not get dispatched correctly. Unfortunately the code of the handler gets less and less clean with more and more control types. I am doing a refactoring in commit #2905 where all the channel creation and command processing will be delegated to the control classes. I will port your changes over as soon as possible.

**Comment by mmattan** [comment]
> You can create another channel exactly like in the timed switch example. There can be more than one channel of the same type. Then if you receive a command (and this is not present in timed switch as not needed there) you need to compare the channel UID against the particular channel for the control. You can get these channel IDs calling getChannelIdForControl(control, index), index will be 1,2,3,...

OK, so I sort of need to do some string comparison on the UUID of the channel.  From a coding point of view, that's what I'm struggling with.  I need to parse the string and link an index to a specific type of action, which feels like hacking to me.

I understand that the second LxControl is not optimal, so I will change my code accordingly.  But the other approach is far from optimal either.

I will wait for the refactoring of your code to be merged into the master.  I will also review it and give my comments on it.

**Comment by ppieczul** [comment]
Unfortunately channels are distinguished by the channel ID which in fact is a string. We could add better support to the LxControl for that so that no string comparison is needed. This was marginal use case until now and now we have Alarm, TimedSwitch, Jalousie (not in current commited version) and one more I forgot. I will think how to do it and please provide your ideas too. Please take a look at the refactoring PR and provide feedback too, if you can find some time. Thanks.

**Comment by ppieczul** [comment]
Hi @mmattan can you please take a look at #2905 and see some LxControl* files and comment if this way of defining multiple channels is better. There is no need to specify ID and servicing the commands and state updates is done via lambda functions. Thanks.

**Comment by davidgraeff** [comment]
If we are going for #2905, is it a huge refactoring for this PR? Or should this go in first?

**Comment by mmattan** [comment]
Hi @davidgraeff if we go for #2905 this Pull Request will be obsolete.
This code can easily be ported to the 2905 branch.  I am already doing that and will discuss this with @ppieczul to include it.  It will be a single-file change with the refactored code.

**Pull request closed without merging**
