### PR TITLE
This PR aims to solve issue #1517

### PR DESCRIPTION
**Pull request by clinique**
Other modifications, concerning Thermostat, are :
* address refresh of parent device when module channel updated via OH
* Now, if not in manual mode, the end of current scheduled program is retrieved instead of null value previously grabbed for CHANNEL_SETPOINT_END_TIME

Signed-off-by: Gaël L'hopital <glhopital@gmail.com>

### CODE REVIEW

**Comment by clinique** [comment]
@lolodomo : can you please try this update when you've got a bit of time ahead to review code ? It may solve the nullHandle pb.

**Comment by lolodomo** [comment]
I will try to test your PR during the week-end.

**Comment by lolodomo** [comment]
@clinique: I tested your PR and after 2 restarts I can't see anymore the NPE.
My station values look good after the startup.

**Comment by lolodomo** [comment]
@clinique : can we conclude ? If you don't want to consider my comment, that's OK for me as it was fully minor. In this case, let me know and I will give a LGTM.

**Comment by mcarlosro** [comment]
If this is tested and it seems that it works, why does it take so much to be included in the daily snapshot? I've been waiting more that a week.

**Comment by clinique** [comment]
So, If there is now new bug, I'd like this to be my christmas gift to you log files :)

**Comment by lolodomo** [comment]
LGTM

**Pull request merged**
