### PR TITLE
[mihome] Added Aqara Switch

### PR DESCRIPTION
**Pull request by nekenk1**
Signed-off-by: Alexandre Vautier <alex@vautier.biz>

Added Aqara Switch in Mi Home Binding

### CODE REVIEW

**Comment by kubawolanin** [comment]
Hey @nekenk1 that looks awesome!
Could you also edit the README.md file so it contains the square wireless switch as well?
Thanks

**Comment by nekenk1** [comment]
Done, I also added the other Aqara sensors there were missing from the previous change.

**Comment by martinvw** [comment]
@dimalo can you check? Thanks!

**Comment by kubawolanin** [comment]
LGTM

**Comment by dimalo** [comment]
Just checked the code, looks good to me. If it’s working with the new switch, which I assume it is. Then go for it gentlemen. Thanks @nekenk1!

**Comment by wardwygaerts** [comment]
I received the Aqara switch today and tested it immediately :) Is it possible that long press & release are not supported by de device? So it has not exactly the same functionallity as the original round switch?

https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.mihome/ESH-INF/thing/sensor_switch_aq2.xml

**Pull request merged**
