### PR TITLE
Improve iCloud binding example

### PR DESCRIPTION
**Pull request by metbril**
This PR improves the full example included with the iCloud binding.
It adds a sitemap with a pushbutton and a map view. A simple rule is included to use the binding for presence detection.

### CODE REVIEW

**Comment by metbril** [comment]
It looks like something is wrong with my signing off. If you explain what's wrong and how to fix it, I will.
(I'm a rookie git user) 😄

**Comment by martinvw** [comment]
@pgfeller / @ThomDietrich  can you take a quick look, I think it looks fine.

**Comment by martinvw** [comment]
@metbril thanks for your contribution

For the sign-off we want the real email address and full name, see http://docs.openhab.org/developers/contributing/contributing.html#sign-your-work

**Comment by hmerk** [comment]
Do we really want to have rule examples in the Binding docs? Don't think this to be a good idea, especially as it is not really iCloud Binding specific.

**Comment by metbril** [comment]
This wouldn’t be the first binding with a simple rule example. The AQI binding has one. 

https://docs.openhab.org/addons/bindings/airquality/readme.html

**Comment by metbril** [comment]
Would my sign-off be ok if i add Some empty commit to the branch and PR?

**Comment by kaikreuzer** [comment]
@metbril Yes, if you cannot amend the previous commit, add a new one with the proper sign-off and we will squash when merging.

**Comment by metbril** [comment]
I read in the binding documentation that you can send a REFRESH command to any channel to force an update. This should be included in the example as well. I will add a commit for this.

**Comment by metbril** [comment]
I think I made a mess of it. Commit https://github.com/openhab/openhab2-addons/pull/3226/commits/ee9c7c0590cc45b3167caf0c6eb1820ed675b18f shouldn't have been there. :blush:

Before I mess up more stuff, I guess someone could fix this for me or I can create a new PR with 1 single commit that has the proper sign-off.

**Comment by metbril** [comment]
Closed it myself to prevent harm to the repo.

**Pull request closed without merging**
