### PR TITLE
[cometvisu] Fix config error and rest 500 errors

### LINKED ISSUE #3167: cometvisu cannot be installed: The activate method has thrown an exception
Running openhabianpi, latest version 2.2.0-1.
When I try to install the cometvisu, the activation does not work, an exception is raised:

```
2018-01-24 19:16:25.638 [ERROR] [org.openhab.ui.cometvisu            ] - [org.openhab.cometvisu(272)] The activate method has thrown an exception
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at org.openhab.ui.cometvisu.internal.servlet.CometVisuApp.readConfiguration(CometVisuApp.java:193) ~[?:?]
	at org.openhab.ui.cometvisu.internal.servlet.CometVisuApp.activate(CometVisuApp.java:228) ~[?:?]

```
then

```
2018-01-24 19:16:25.844 [WARN ] [org.openhab.ui.cometvisu            ] - FrameworkEvent WARNING - org.openhab.ui.cometvisu
org.osgi.framework.ServiceException: org.apache.felix.scr.impl.manager.SingleComponentManager.getService() returned a null service object
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:232) ~[?:?] 
```

then again 

```
2018-01-24 19:16:25.851 [ERROR] [org.openhab.ui.cometvisu            ] - [org.openhab.cometvisu(272)] The activate method has thrown an exception
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at org.openhab.ui.cometvisu.internal.servlet.CometVisuApp.readConfiguration(CometVisuApp.java:193) ~[?:?]
	at org.openhab.ui.cometvisu.internal.servlet.CometVisuApp.activate(CometVisuApp.java:228) ~[?:?] 

```

then it is uninstalled again, at least if I install it from the CLI via

`feature:install openhab-ui-cometvisu/2.2.0
`
Installing from the UI seems to create a bigger mess, at least the automatic uninstall does not work, and I had to restart openhab.
I have also deleted the existing cometvisu.cfg, but that did not help.

Any ideas what's going wrong?
Thanks
Thomas

### PR DESCRIPTION
**Pull request by peuter**
- fix string->boolean conversion for config setting
- fix rest path annotation

fixes #3167

Signed-off-by: Tobias Bräutigam <tbraeutigam@gmail.com>

### CODE REVIEW

**Comment by martinvw** [comment]
Thanks for the quick action!!!

**Comment by orificer** [comment]
Thank You very much for the fast response!

I wanted to test if everything is working as expexted now, but I think I'm still not using the fixed version of the binding. I've updated my openhab2-installation to 2.3.0~20180131125512-1. Is there any additional step needed to make sure the new binding is used if I want to install cometvisu through PaperUI?

**Comment by GOsa3** [comment]
I don't know where you got your update from, but if its the last Build from here: https://openhab.ci.cloudbees.com/job/openHAB-Distribution/lastBuild/
then the fix is not part of that build yet. You have to wait for the next one.

**Comment by peuter** [comment]
I don't know where you got your update from, but if its the last Build from here: https://openhab.ci.cloudbees.com/job/openHAB-Distribution/lastBuild/
then the fix is not part of that build yet. You have to wait for the next one.

**Comment by orificer** [comment]
Ok, thank You for the update. Yes, the version which is installed in my environment is build #1202. I will give it another try tomorrow and check if there is a new build which includes the fix.

**Comment by orificer** [comment]
A new build (#1203) has been generated last night and I've tried to install cometvisu again. The http-500 error is gone, but the installation is still showing an exception:

`2018-02-02 09:55:11.499 [ERROR] [org.openhab.ui.cometvisu            ] - [org.openhab.cometvisu(233)] The activate method has                                                                                                                 thrown an exception
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
        at org.openhab.ui.cometvisu.internal.servlet.CometVisuApp.readConfiguration(CometVisuApp.java:193) ~[?:?]
        at org.openhab.ui.cometvisu.internal.servlet.CometVisuApp.activate(CometVisuApp.java:228) ~[?:?]
........`

`2018-02-02 09:55:11.906 [WARN ] [org.openhab.ui.cometvisu            ] - FrameworkEvent WARNING - org.openhab.ui.cometvisu
org.osgi.framework.ServiceException: org.apache.felix.scr.impl.manager.SingleComponentManager.getService() returned a null se                                                                                                                rvice object
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:232) ~[?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:111) ~[?:?]
........`

**Comment by martinvw** [comment]
@peuter it seems that in (some) cases it is already a boolean

**Comment by peuter** [comment]
I don't know how to reproduce the error, but I added a type check to handle both types (String and Boolean) in PR #3204. Hopefully this will finally fix the problem.

**Pull request merged**
